# -*- coding: utf-8 -*-
"""
dedupe_b1_data.py — 450 nieuwe B1-woorden die de gaten opvullen na de deduplicatie (v1.44).
Gekozen op basis van een frequentie-analyse (OpenSubtitles it_50k, gelemmatiseerd met
simplemma): woorden binnen de ~3000 meest voorkomende Italiaanse lemma's die nog niet in
vocabulary.json stonden, thematisch toegewezen aan de les waar een gat viel.
Formaat: (lesson, it, nl, ph, ex, exNl, cat)
"""

GAP_WORDS = [
    # ── Blok 1: imperfetto, verhalen, weer, emoties ─────────────────────────
    (121, 'lavorare', 'werken', 'la-vo-RA-re', 'Da giovane lavoravo in un bar.', 'Als jongere werkte ik in een bar.', 'verbo'),
    (123, 'sentire', 'horen, voelen', 'sen-TI-re', 'Ho sentito un rumore mentre dormivo.', 'Ik hoorde een geluid terwijl ik sliep.', 'verbo'),
    (123, 'tornare', 'terugkeren', 'tor-NA-re', 'Sono tornato a casa mentre pioveva.', 'Ik kwam thuis terwijl het regende.', 'verbo'),
    (123, 'finire', 'eindigen, afmaken', 'fi-NI-re', 'Ho finito il libro ieri sera.', 'Ik heb het boek gisteravond uitgelezen.', 'verbo'),
    (125, 'studiare', 'studeren, leren', 'stu-DJA-re', 'Da bambino studiavo ogni pomeriggio.', 'Als kind studeerde ik elke middag.', 'verbo'),
    (125, 'usare', 'gebruiken', 'u-ZA-re', 'Usavamo sempre la bicicletta.', 'We gebruikten altijd de fiets.', 'verbo'),
    (125, 'spesso', 'vaak', 'SPES-so', 'Andavamo spesso al mare.', 'We gingen vaak naar zee.', 'avverbio'),
    (126, 'dire', 'zeggen', 'DI-re', 'Mia nonna diceva sempre la verità.', 'Mijn oma zei altijd de waarheid.', 'verbo'),
    (126, 'allora', 'toen, dus', 'al-LO-ra', 'Allora non avevamo il telefono.', 'Toen hadden we geen telefoon.', 'avverbio'),
    (127, 'entrare', 'binnenkomen', 'en-TRA-re', 'È entrato senza bussare.', 'Hij kwam binnen zonder te kloppen.', 'verbo'),
    (127, 'il ragazzo', 'de jongen', 'ra-GAT-tso', 'Il ragazzo è entrato di corsa.', 'De jongen kwam rennend binnen.', 'sostantivo'),
    (127, 'il momento', 'het moment', 'mo-MEN-to', 'In quel momento è squillato il telefono.', 'Op dat moment ging de telefoon.', 'sostantivo'),
    (128, 'la tempesta', 'de storm', 'tem-PES-ta', 'La tempesta è durata tutta la notte.', 'De storm duurde de hele nacht.', 'meteo'),
    (128, 'il ghiaccio', 'het ijs', 'GJAT-tsjo', "C'era ghiaccio sulla strada.", 'Er lag ijs op de weg.', 'meteo'),
    (128, 'la temperatura', 'de temperatuur', 'tem-pe-ra-TU-ra', 'La temperatura scendeva ogni giorno.', 'De temperatuur daalde elke dag.', 'meteo'),
    (129, 'la paura', 'de angst', 'pa-U-ra', 'Avevo paura del buio.', 'Ik was bang voor het donker.', 'emozione'),
    (129, 'la rabbia', 'de woede', 'RAB-bja', 'Ha reagito con rabbia.', 'Hij reageerde met woede.', 'emozione'),
    (129, 'la gioia', 'de vreugde', 'DJO-ja', 'Che gioia rivederti!', 'Wat een vreugde om je weer te zien!', 'emozione'),
    (129, 'la speranza', 'de hoop', 'spe-RAN-tsa', 'Non perdevamo mai la speranza.', 'We verloren nooit de hoop.', 'emozione'),
    (129, 'piangere', 'huilen', 'PJAN-dje-re', 'Piangeva di gioia.', 'Ze huilde van blijdschap.', 'verbo'),
    (129, 'ridere', 'lachen', 'RI-de-re', 'Ridevamo tutta la sera.', 'We lachten de hele avond.', 'verbo'),
    (130, 'ancora', 'nog, nog steeds', 'an-KO-ra', 'Sei ancora qui?', 'Ben je er nog?', 'avverbio'),
    # ── Blok 2: condizionale, restaurant, reizen, vervoer ───────────────────
    (132, 'potere', 'kunnen, mogen', 'po-TE-re', 'Potresti aiutarmi un attimo?', 'Zou je me even kunnen helpen?', 'verbo'),
    (133, 'permettere', 'toestaan', 'per-MET-te-re', 'Mi permetta di presentarmi.', 'Sta mij toe mezelf voor te stellen.', 'verbo'),
    (134, 'il destino', 'het lot', 'des-TI-no', 'Il destino ci ha fatto incontrare.', 'Het lot heeft ons samengebracht.', 'sostantivo'),
    (134, 'la fortuna', 'het geluk, de fortuin', 'for-TU-na', 'Vorrei avere più fortuna.', 'Ik zou graag meer geluk hebben.', 'sostantivo'),
    (134, 'diventare', 'worden', 'di-ven-TA-re', 'Vorrei diventare medico.', 'Ik zou dokter willen worden.', 'verbo'),
    (134, 'il mondo', 'de wereld', 'MON-do', 'Vorrei girare il mondo.', 'Ik zou de wereld rond willen reizen.', 'sostantivo'),
    (134, 'la vita', 'het leven', 'VI-ta', 'La vita è bella.', 'Het leven is mooi.', 'sostantivo'),
    (134, "l'amore", 'de liefde', 'a-MO-re', "L'amore cambia tutto.", 'De liefde verandert alles.', 'sostantivo'),
    (134, 'qualcosa', 'iets', 'kwal-KO-za', 'Vorrei fare qualcosa di speciale.', 'Ik zou iets bijzonders willen doen.', 'avverbio'),
    (135, 'considerare', 'overwegen', 'kon-si-de-RA-re', 'Dovresti considerare un altro lavoro.', 'Je zou een andere baan moeten overwegen.', 'verbo'),
    (136, 'la cena', 'het avondeten', 'TSJE-na', 'La cena è alle otto.', 'Het avondeten is om acht uur.', 'ristorante'),
    (136, 'il pranzo', 'de lunch', 'PRAN-dzo', 'Il pranzo è incluso nel prezzo.', 'De lunch is bij de prijs inbegrepen.', 'ristorante'),
    (136, 'il cibo', 'het eten', 'TSJI-bo', 'Il cibo qui è ottimo.', 'Het eten hier is uitstekend.', 'ristorante'),
    (136, 'il ristorante', 'het restaurant', 'ris-to-RAN-te', 'Conosci un buon ristorante qui vicino?', 'Ken je een goed restaurant hier in de buurt?', 'ristorante'),
    (136, 'la bottiglia', 'de fles', 'bot-TI-lja', "Una bottiglia d'acqua, per favore.", 'Een fles water, alstublieft.', 'ristorante'),
    (137, 'la vacanza', 'de vakantie', 'va-KAN-tsa', 'Dove vai in vacanza?', 'Waar ga je op vakantie?', 'viaggio'),
    (137, 'la nave', 'het schip', 'NA-ve', 'La nave parte alle sei.', 'Het schip vertrekt om zes uur.', 'viaggio'),
    (137, 'il minuto', 'de minuut', 'mi-NU-to', 'Il treno parte tra cinque minuti.', 'De trein vertrekt over vijf minuten.', 'tempo'),
    (137, 'la mappa', 'de kaart, de plattegrond', 'MAP-pa', 'Ho scaricato la mappa della città.', 'Ik heb de plattegrond van de stad gedownload.', 'viaggio'),
    (137, 'il paese', 'het land, het dorp', 'pa-E-ze', 'Quale paese vuoi visitare?', 'Welk land wil je bezoeken?', 'viaggio'),
    (137, 'il giro', 'de rondrit, het rondje', 'DJI-ro', 'Facciamo un giro in barca?', 'Zullen we een boottochtje maken?', 'viaggio'),
    (138, 'la stanza', 'de kamer', 'STAN-tsa', 'La stanza ha vista sul mare.', 'De kamer heeft uitzicht op zee.', 'alloggio'),
    (138, 'la sala', 'de zaal', 'SA-la', 'La colazione è nella sala grande.', 'Het ontbijt is in de grote zaal.', 'alloggio'),
    (138, 'la doccia', 'de douche', 'DOT-tsja', 'La doccia non funziona.', 'De douche werkt niet.', 'alloggio'),
    (138, 'interno', 'binnen-, intern', 'in-TER-no', 'La camera ha un bagno interno.', 'De kamer heeft een eigen badkamer.', 'aggettivo'),
    (139, 'la sinistra', 'links, de linkerkant', 'si-NIS-tra', 'Gira a sinistra al semaforo.', 'Sla linksaf bij het stoplicht.', 'direzione'),
    (139, 'la destra', 'rechts, de rechterkant', 'DES-tra', 'La stazione è sulla destra.', 'Het station is aan de rechterkant.', 'direzione'),
    (139, 'avanti', 'vooruit, verder', 'a-VAN-ti', 'Vai sempre avanti fino alla piazza.', 'Ga steeds rechtdoor tot het plein.', 'avverbio'),
    (139, 'fermare', 'stoppen, tegenhouden', 'fer-MA-re', 'Ferma la macchina qui.', 'Stop de auto hier.', 'verbo'),
    (139, 'piano', 'langzaam, zachtjes', 'PJA-no', 'Guida piano, la strada è bagnata.', 'Rijd langzaam, de weg is nat.', 'avverbio'),
    (139, "l'autista", 'de chauffeur', 'au-TIS-ta', "L'autista dell'autobus è gentile.", 'De buschauffeur is vriendelijk.', 'trasporto'),
    (140, 'aspettare', 'wachten', 'as-pet-TA-re', 'Aspetto il treno da mezz\'ora.', 'Ik wacht al een half uur op de trein.', 'verbo'),
    (140, 'restare', 'blijven', 'res-TA-re', 'Restiamo a casa stasera?', 'Blijven we vanavond thuis?', 'verbo'),
    (140, 'proprio', 'echt, precies', 'PRO-prjo', 'È proprio quello che volevo.', 'Dat is precies wat ik wilde.', 'avverbio'),
    # ── Blok 3: congiuntivo, werk, gevoelens ────────────────────────────────
    (141, 'pensare', 'denken', 'pen-SA-re', 'Penso che tu abbia ragione.', 'Ik denk dat je gelijk hebt.', 'verbo'),
    (141, 'credere', 'geloven', 'KRE-de-re', 'Credo che sia troppo tardi.', 'Ik geloof dat het te laat is.', 'verbo'),
    (143, 'vero', 'waar, echt', 'VE-ro', 'Non è vero che costa tanto.', 'Het is niet waar dat het veel kost.', 'aggettivo'),
    (144, 'strano', 'vreemd', 'STRA-no', 'È strano che non risponda.', 'Het is vreemd dat hij niet antwoordt.', 'aggettivo'),
    (144, 'la sensazione', 'het gevoel, de gewaarwording', 'sen-sa-TSJO-ne', 'Ho la sensazione che qualcosa non vada.', 'Ik heb het gevoel dat er iets niet klopt.', 'emozione'),
    (145, 'la carriera', 'de carrière', 'kar-RJE-ra', 'Vuole fare carriera in banca.', 'Hij wil carrière maken bij een bank.', 'lavoro'),
    (145, "l'assistente", 'de assistent', 'as-sis-TEN-te', "Cerchiamo un'assistente per il direttore.", 'We zoeken een assistent voor de directeur.', 'lavoro'),
    (145, 'il socio', 'de partner, de vennoot', 'SO-tsjo', 'Il mio socio gestisce le vendite.', 'Mijn vennoot beheert de verkoop.', 'lavoro'),
    (145, 'la paga', 'het loon', 'PA-ga', 'La paga è ogni fine mese.', 'Het loon komt aan het eind van de maand.', 'lavoro'),
    (145, 'il signore', 'de meneer, de heer', 'si-NJO-re', 'Il signore Rossi è il direttore.', 'Meneer Rossi is de directeur.', 'sostantivo'),
    (146, 'la scrivania', 'het bureau', 'skri-va-NI-a', 'La mia scrivania è vicino alla finestra.', 'Mijn bureau staat bij het raam.', 'ufficio'),
    (146, 'il programma', 'het programma', 'pro-GRAM-ma', 'Il programma della riunione è cambiato.', 'Het programma van de vergadering is veranderd.', 'ufficio'),
    (146, 'la lista', 'de lijst', 'LIS-ta', 'Ho fatto una lista delle cose da fare.', 'Ik heb een lijst gemaakt van wat er moet gebeuren.', 'ufficio'),
    (146, 'la telefonata', 'het telefoongesprek', 'te-le-fo-NA-ta', 'Ho ricevuto una telefonata importante.', 'Ik kreeg een belangrijk telefoontje.', 'ufficio'),
    (146, 'il numero', 'het nummer, het getal', 'NU-me-ro', 'Qual è il numero dell\'ufficio?', 'Wat is het nummer van het kantoor?', 'sostantivo'),
    (147, 'il personale', 'het personeel', 'per-so-NA-le', 'Il personale è molto gentile.', 'Het personeel is heel vriendelijk.', 'lavoro'),
    (147, 'il dottore', 'de dokter, de doctor', 'dot-TO-re', 'Il dottore riceve dalle nove.', 'De dokter ontvangt vanaf negen uur.', 'professione'),
    (147, "l'esperto", 'de expert', 'es-PER-to', 'È un esperto di informatica.', 'Hij is een IT-expert.', 'professione'),
    (149, "l'umore", 'de stemming, het humeur', 'u-MO-re', 'Oggi sono di buon umore.', 'Vandaag ben ik in een goede stemming.', 'emozione'),
    (149, "l'emozione", 'de emotie', 'e-mo-TSJO-ne', 'Non riesco a nascondere le emozioni.', 'Ik kan mijn emoties niet verbergen.', 'emozione'),
    # ── Blok 4: pronomi, passief, gezondheid, sport, voeding, milieu ────────
    (152, 'mandare', 'sturen', 'man-DA-re', 'Te lo mando domani.', 'Ik stuur het je morgen.', 'verbo'),
    (153, 'creare', 'creëren, maken', 'kre-A-re', 'Il sito è stato creato nel 2020.', 'De website is in 2020 gemaakt.', 'verbo'),
    (153, 'ricevere', 'ontvangen', 'ri-TSJE-ve-re', 'La lettera è stata ricevuta ieri.', 'De brief is gisteren ontvangen.', 'verbo'),
    (154, 'la malattia', 'de ziekte', 'ma-lat-TI-a', 'È una malattia rara.', 'Het is een zeldzame ziekte.', 'salute'),
    (154, 'malato', 'ziek', 'ma-LA-to', 'Sono malato da tre giorni.', 'Ik ben al drie dagen ziek.', 'aggettivo'),
    (154, 'il corpo', 'het lichaam', 'KOR-po', 'Il corpo ha bisogno di riposo.', 'Het lichaam heeft rust nodig.', 'corpo'),
    (154, 'la dottoressa', 'de dokter (vrouw)', 'dot-to-RES-sa', 'La dottoressa mi ha visitato.', 'De dokter heeft me onderzocht.', 'salute'),
    (154, 'grave', 'ernstig', 'GRA-ve', 'Non è niente di grave.', 'Het is niets ernstigs.', 'aggettivo'),
    (155, 'il sonno', 'de slaap', 'SON-no', 'Ho bisogno di più sonno.', 'Ik heb meer slaap nodig.', 'salute'),
    (155, 'la calma', 'de rust, de kalmte', 'KAL-ma', 'Mantieni la calma!', 'Blijf kalm!', 'salute'),
    (155, 'il peso', 'het gewicht', 'PE-zo', 'Devo controllare il peso.', 'Ik moet op mijn gewicht letten.', 'salute'),
    (155, 'debole', 'zwak', 'DE-bo-le', 'Mi sento ancora debole.', 'Ik voel me nog zwak.', 'aggettivo'),
    (155, 'forte', 'sterk', 'FOR-te', 'Lo sport ti rende forte.', 'Sport maakt je sterk.', 'aggettivo'),
    (156, 'la pelle', 'de huid', 'PEL-le', 'Ho la pelle secca.', 'Ik heb een droge huid.', 'corpo'),
    (156, 'la gamba', 'het been', 'GAM-ba', 'Mi fa male la gamba destra.', 'Mijn rechterbeen doet pijn.', 'corpo'),
    (157, 'la palla', 'de bal', 'PAL-la', 'Passami la palla!', 'Geef me de bal!', 'sport'),
    (157, 'il campione', 'de kampioen', 'kam-PJO-ne', 'È il campione del mondo.', 'Hij is de wereldkampioen.', 'sport'),
    (157, 'il giocatore', 'de speler', 'djo-ka-TO-re', 'Il giocatore è stato espulso.', 'De speler kreeg een rode kaart.', 'sport'),
    (157, "l'esercizio", 'de oefening', 'e-zer-TSJI-tsjo', 'Faccio esercizio ogni mattina.', 'Ik doe elke ochtend oefeningen.', 'sport'),
    (157, 'il gioco', 'het spel', 'DJO-ko', 'Il calcio è un gioco di squadra.', 'Voetbal is een teamsport.', 'sport'),
    (157, 'saltare', 'springen', 'sal-TA-re', 'Riesce a saltare due metri.', 'Hij kan twee meter springen.', 'verbo'),
    (158, "l'uovo", 'het ei', 'WO-vo', 'Mangio due uova a colazione.', 'Ik eet twee eieren bij het ontbijt.', 'cucina'),
    (158, 'il latte', 'de melk', 'LAT-te', 'Il latte è in frigo.', 'De melk staat in de koelkast.', 'cucina'),
    (158, 'la patata', 'de aardappel', 'pa-TA-ta', 'Le patate al forno sono pronte.', 'De aardappels uit de oven zijn klaar.', 'cucina'),
    (158, 'il pezzo', 'het stuk', 'PET-tso', 'Vuoi un pezzo di torta?', 'Wil je een stuk taart?', 'cucina'),
    (158, 'il cioccolato', 'de chocolade', 'tsjok-ko-LA-to', 'Adoro il cioccolato fondente.', 'Ik ben dol op pure chocolade.', 'cucina'),
    (158, 'la fame', 'de honger', 'FA-me', 'Ho una fame da lupi.', 'Ik heb honger als een paard.', 'cucina'),
    (158, 'il pasto', 'de maaltijd', 'PAS-to', 'Tre pasti al giorno bastano.', 'Drie maaltijden per dag zijn genoeg.', 'cucina'),
    (159, 'la natura', 'de natuur', 'na-TU-ra', 'Amo passeggiare nella natura.', 'Ik hou van wandelen in de natuur.', 'ambiente'),
    (159, "l'albero", 'de boom', 'AL-be-ro', 'Hanno piantato cento alberi.', 'Ze hebben honderd bomen geplant.', 'ambiente'),
    (159, "l'aria", 'de lucht', 'A-rja', "L'aria in città è inquinata.", 'De lucht in de stad is vervuild.', 'ambiente'),
    (159, 'la terra', 'de aarde, de grond', 'TER-ra', 'Dobbiamo proteggere la Terra.', 'We moeten de aarde beschermen.', 'ambiente'),
    (159, "l'uccello", 'de vogel', 'ut-TSJEL-lo', 'Gli uccelli cantano al mattino.', "De vogels zingen 's ochtends.", 'ambiente'),
    (160, 'conoscere', 'kennen, leren kennen', 'ko-NO-sje-re', 'Conosci Marco?', 'Ken je Marco?', 'verbo'),
    (160, 'servire', 'dienen, nodig zijn', 'ser-VI-re', 'Mi serve una penna.', 'Ik heb een pen nodig.', 'verbo'),
    # ── Blok 5: bijzinnen, indirecte rede, technologie, media ───────────────
    (163, 'nemmeno', 'zelfs niet, ook niet', 'nem-ME-no', 'Non ho nemmeno un euro.', 'Ik heb zelfs geen euro.', 'avverbio'),
    (163, 'oppure', 'of anders', 'op-PU-re', 'Vieni con noi oppure resti qui?', 'Ga je met ons mee of blijf je hier?', 'congiunzione'),
    (163, 'solo', 'alleen, slechts', 'SO-lo', 'Ho solo cinque euro, ma vengo lo stesso.', 'Ik heb maar vijf euro, maar ik kom toch.', 'avverbio'),
    (165, 'ripetere', 'herhalen', 'ri-PE-te-re', 'Puoi ripetere, per favore?', 'Kun je dat herhalen, alsjeblieft?', 'verbo'),
    (165, 'notare', 'opmerken', 'no-TA-re', 'Ha notato che ero stanco.', 'Hij merkte dat ik moe was.', 'verbo'),
    (165, 'la conversazione', 'het gesprek', 'kon-ver-sa-TSJO-ne', 'Abbiamo avuto una lunga conversazione.', 'We hadden een lang gesprek.', 'sostantivo'),
    (165, 'qualcuno', 'iemand', 'kwal-KU-no', 'Ha detto che qualcuno lo aveva chiamato.', 'Hij zei dat iemand hem gebeld had.', 'avverbio'),
    (165, 'la parola', 'het woord', 'pa-RO-la', 'Ha detto che non aveva parole.', 'Hij zei dat hij geen woorden had.', 'sostantivo'),
    (167, 'il cellulare', 'de mobiele telefoon', 'tsjel-lu-LA-re', 'Il mio cellulare è scarico.', 'Mijn mobiel is leeg.', 'tecnologia'),
    (167, 'lo schermo', 'het scherm', 'SKER-mo', 'Lo schermo è rotto.', 'Het scherm is kapot.', 'tecnologia'),
    (167, 'il codice', 'de code', 'KO-di-tsje', 'Inserisci il codice di sicurezza.', 'Voer de beveiligingscode in.', 'tecnologia'),
    (167, 'il telefono', 'de telefoon', 'te-LE-fo-no', 'Il telefono squilla in continuazione.', 'De telefoon gaat voortdurend.', 'tecnologia'),
    (167, 'collegare', 'verbinden, aansluiten', 'kol-le-GA-re', 'Collega il computer alla rete.', 'Sluit de computer aan op het netwerk.', 'verbo'),
    (168, 'il video', 'de video', 'VI-de-o', 'Il video ha un milione di visualizzazioni.', 'De video heeft een miljoen weergaven.', 'social'),
    (168, 'il commento', 'de reactie, het commentaar', 'kom-MEN-to', 'Ho lasciato un commento sotto il post.', 'Ik heb een reactie onder de post achtergelaten.', 'social'),
    (168, 'la versione', 'de versie', 'ver-SJO-ne', "C'è una nuova versione dell'app.", 'Er is een nieuwe versie van de app.', 'tecnologia'),
    (168, 'cancellare', 'wissen, verwijderen', 'kan-tsjel-LA-re', 'Ho cancellato il mio profilo.', 'Ik heb mijn profiel verwijderd.', 'verbo'),
    (168, 'registrare', 'opnemen, registreren', 're-djis-TRA-re', 'Registro un video per il canale.', 'Ik neem een video op voor het kanaal.', 'verbo'),
    (168, 'il contatto', 'het contact', 'kon-TAT-to', 'Ho aggiunto un nuovo contatto.', 'Ik heb een nieuw contact toegevoegd.', 'social'),
    (169, "l'episodio", 'de aflevering', 'e-pi-ZO-djo', "L'ultimo episodio era bellissimo.", 'De laatste aflevering was prachtig.', 'sostantivo'),
    (169, 'interessante', 'interessant', 'in-te-res-SAN-te', 'Il film era davvero interessante.', 'De film was echt interessant.', 'aggettivo'),
    (169, 'lo scrittore', 'de schrijver', 'skrit-TO-re', 'È il mio scrittore preferito.', 'Hij is mijn favoriete schrijver.', 'sostantivo'),
    (169, 'il libro', 'het boek', 'LI-bro', 'Sto leggendo un libro di Elena Ferrante.', 'Ik lees een boek van Elena Ferrante.', 'sostantivo'),
    (169, "l'eroe", 'de held', 'e-RO-e', "L'eroe del romanzo è un ragazzo.", 'De held van de roman is een jongen.', 'sostantivo'),
    (170, 'iniziare', 'beginnen', 'i-ni-TSJA-re', 'Il film inizia alle nove.', 'De film begint om negen uur.', 'verbo'),
    (170, 'cominciare', 'beginnen', 'ko-min-TSJA-re', 'Cominciamo a mangiare?', 'Beginnen we met eten?', 'verbo'),
    (170, 'quasi', 'bijna', 'KWA-zi', 'Ho quasi finito.', 'Ik ben bijna klaar.', 'avverbio'),
    (170, 'circa', 'ongeveer', 'TSJIR-ka', 'Ci vogliono circa due ore.', 'Het duurt ongeveer twee uur.', 'avverbio'),
    # ── Blok 6: hypothese, regio's, keuken, cultuur, toekomst ───────────────
    (174, 'possibile', 'mogelijk', 'pos-SI-bi-le', 'Se fosse possibile, partirei domani.', 'Als het mogelijk was, zou ik morgen vertrekken.', 'aggettivo'),
    (176, 'il villaggio', 'het dorp', 'vil-LAD-djo', 'È un villaggio di pescatori.', 'Het is een vissersdorp.', 'geografia'),
    (176, 'la zona', 'de zone, het gebied', 'DZO-na', 'Questa zona è famosa per il vino.', 'Dit gebied is beroemd om zijn wijn.', 'geografia'),
    (176, 'il confine', 'de grens', 'kon-FI-ne', 'Il confine con la Francia è vicino.', 'De grens met Frankrijk is dichtbij.', 'geografia'),
    (176, 'il luogo', 'de plaats, de plek', 'LWO-go', 'È un luogo pieno di storia.', 'Het is een plek vol geschiedenis.', 'geografia'),
    (176, 'il monte', 'de berg', 'MON-te', 'Il Monte Bianco è il più alto.', 'De Mont Blanc is de hoogste.', 'geografia'),
    (177, 'la salsa', 'de saus', 'SAL-sa', 'La salsa di pomodoro è fatta in casa.', 'De tomatensaus is zelfgemaakt.', 'cucina'),
    (177, 'il panino', 'het broodje', 'pa-NI-no', 'Prendo un panino con il prosciutto.', 'Ik neem een broodje ham.', 'cucina'),
    (177, 'delizioso', 'heerlijk', 'de-li-TSJO-zo', 'Questo risotto è delizioso.', 'Deze risotto is heerlijk.', 'aggettivo'),
    (177, 'il gusto', 'de smaak', 'GUS-to', 'Che gusto di gelato vuoi?', 'Welke smaak ijs wil je?', 'cucina'),
    (178, 'benvenuto', 'welkom', 'ben-ve-NU-to', 'Benvenuti a casa nostra!', 'Welkom in ons huis!', 'espressione'),
    (179, 'lo scopo', 'het doel', 'SKO-po', 'Il mio scopo è imparare bene l\'italiano.', 'Mijn doel is goed Italiaans leren.', 'sostantivo'),
    (179, 'la decisione', 'de beslissing', 'de-tsji-ZJO-ne', 'Ho preso una decisione importante.', 'Ik heb een belangrijke beslissing genomen.', 'sostantivo'),
    # ── Blok 7: passato remoto, geschiedenis, kunst, tradities ──────────────
    (181, 'amare', 'houden van', 'a-MA-re', 'Dante amò Beatrice tutta la vita.', 'Dante hield zijn hele leven van Beatrice.', 'verbo'),
    (181, 'cantare', 'zingen', 'kan-TA-re', 'Cantò per la prima volta a Milano.', 'Hij zong voor het eerst in Milaan.', 'verbo'),
    (181, 'ritornare', 'terugkeren', 'ri-tor-NA-re', 'Ritornò in Italia nel 1950.', 'Hij keerde in 1950 terug naar Italië.', 'verbo'),
    (181, 'durare', 'duren', 'du-RA-re', 'La guerra durò dieci anni.', 'De oorlog duurde tien jaar.', 'verbo'),
    (182, 'scegliere', 'kiezen', 'SJE-lje-re', 'Scelse di restare in Italia.', 'Hij koos ervoor in Italië te blijven.', 'verbo'),
    (182, 'scendere', 'afdalen, uitstappen', 'SJEN-de-re', 'Scese dal treno e sparì.', 'Hij stapte uit de trein en verdween.', 'verbo'),
    (182, 'apparire', 'verschijnen', 'ap-pa-RI-re', 'Apparve improvvisamente alla porta.', 'Hij verscheen plotseling aan de deur.', 'verbo'),
    (184, 'il disegno', 'de tekening', 'di-ZE-njo', 'I disegni di Leonardo sono famosi.', 'De tekeningen van Leonardo zijn beroemd.', 'sostantivo'),
    (184, 'la figura', 'de figuur, de gestalte', 'fi-GU-ra', 'La figura centrale è una donna.', 'De centrale figuur is een vrouw.', 'sostantivo'),
    (184, 'lo stile', 'de stijl', 'STI-le', 'Lo stile barocco è ricco di dettagli.', 'De barokstijl is rijk aan details.', 'sostantivo'),
    (184, 'la torre', 'de toren', 'TOR-re', 'La torre di Pisa pende.', 'De toren van Pisa staat scheef.', 'sostantivo'),
    (184, 'il castello', 'het kasteel', 'kas-TEL-lo', 'Il castello domina la città.', 'Het kasteel torent boven de stad uit.', 'sostantivo'),
    (184, "l'edificio", 'het gebouw', 'e-di-FI-tsjo', "L'edificio risale al Cinquecento.", 'Het gebouw dateert uit de zestiende eeuw.', 'sostantivo'),
    (185, 'il maestro', 'de meester', 'ma-ES-tro', 'Leonardo fu un grande maestro.', 'Leonardo was een groot meester.', 'sostantivo'),
    (188, "l'augurio", 'de wens, de gelukwens', 'au-GU-rjo', 'Tanti auguri di buon Natale!', 'Prettige kerstdagen gewenst!', 'cultura'),
    (188, 'il dono', 'het geschenk', 'DO-no', 'I bambini aprono i doni la mattina.', "De kinderen openen 's ochtends de geschenken.", 'cultura'),
    (188, 'la nonna', 'de oma', 'NON-na', 'A Natale andiamo dalla nonna.', 'Met Kerst gaan we naar oma.', 'cultura'),
    (188, 'la messa', 'de mis', 'MES-sa', 'A mezzanotte c\'è la messa.', 'Om middernacht is er een mis.', 'cultura'),
    (188, 'la tavola', 'de (gedekte) tafel', 'TA-vo-la', 'A Natale la tavola è piena.', 'Met Kerst staat de tafel vol.', 'cultura'),
    (189, 'il canto', 'het gezang, het lied', 'KAN-to', 'Il canto napoletano è famoso.', 'Het Napolitaanse lied is beroemd.', 'sostantivo'),
    (190, 'la parte', 'het deel', 'PAR-te', 'La prima parte del film è lenta.', 'Het eerste deel van de film is traag.', 'sostantivo'),
    (190, 'il posto', 'de plaats, de plek', 'POS-to', 'Questo posto è magnifico.', 'Deze plek is prachtig.', 'sostantivo'),
    # ── Blok 8: condizionale passato, financiën, wonen ──────────────────────
    (191, 'salvare', 'redden, opslaan', 'sal-VA-re', 'Avrei potuto salvare il file.', 'Ik had het bestand kunnen opslaan.', 'verbo'),
    (191, 'sbagliato', 'verkeerd, fout', 'zba-LJA-to', 'Avrei preso la strada sbagliata.', 'Ik zou de verkeerde weg hebben genomen.', 'aggettivo'),
    (192, 'addio', 'vaarwel', 'ad-DI-o', 'Avrei dovuto dirti addio di persona.', 'Ik had je persoonlijk vaarwel moeten zeggen.', 'espressione'),
    (192, 'la bugia', 'de leugen', 'bu-DJI-a', 'Non avrei dovuto dire una bugia.', 'Ik had geen leugen moeten vertellen.', 'sostantivo'),
    (192, 'mentire', 'liegen', 'men-TI-re', 'Mi dispiace di aver mentito.', 'Het spijt me dat ik gelogen heb.', 'verbo'),
    (193, 'ottenere', 'verkrijgen', 'ot-te-NE-re', 'Avrei voluto ottenere quel lavoro.', 'Ik had die baan graag gekregen.', 'verbo'),
    (193, 'la promessa', 'de belofte', 'pro-MES-sa', 'Ha mantenuto la promessa.', 'Hij heeft zijn belofte gehouden.', 'sostantivo'),
    (193, 'il tentativo', 'de poging', 'ten-ta-TI-vo', 'Al secondo tentativo ha vinto.', 'Bij de tweede poging won hij.', 'sostantivo'),
    (193, 'perfetto', 'perfect', 'per-FET-to', 'Sarebbe stato perfetto.', 'Het zou perfect zijn geweest.', 'aggettivo'),
    (193, 'mancare', 'missen, ontbreken', 'man-KA-re', 'Mi manchi tanto.', 'Ik mis je heel erg.', 'verbo'),
    (194, 'il denaro', 'het geld', 'de-NA-ro', 'Il denaro non fa la felicità.', 'Geld maakt niet gelukkig.', 'sostantivo'),
    (194, 'il contante', 'het contant geld', 'kon-TAN-te', 'Pago in contanti.', 'Ik betaal contant.', 'sostantivo'),
    (194, 'i soldi', 'het geld', 'SOL-di', 'Non ho abbastanza soldi.', 'Ik heb niet genoeg geld.', 'sostantivo'),
    (194, 'il credito', 'het krediet', 'KRE-di-to', 'La banca ha concesso il credito.', 'De bank heeft het krediet verleend.', 'sostantivo'),
    (195, 'il milione', 'het miljoen', 'mi-LJO-ne', 'La città ha due milioni di abitanti.', 'De stad heeft twee miljoen inwoners.', 'sostantivo'),
    (195, 'il costo', 'de kosten, de prijs', 'KOS-to', 'Il costo della vita è alto.', 'De kosten van levensonderhoud zijn hoog.', 'sostantivo'),
    (195, 'povero', 'arm', 'PO-ve-ro', 'Molte famiglie sono diventate povere.', 'Veel gezinnen zijn arm geworden.', 'aggettivo'),
    (197, 'il pavimento', 'de vloer', 'pa-vi-MEN-to', 'Il pavimento è di legno.', 'De vloer is van hout.', 'sostantivo'),
    (197, 'dentro', 'binnen', 'DEN-tro', 'Dentro casa fa caldo.', 'Binnen in huis is het warm.', 'avverbio'),
    (197, 'il corridoio', 'de gang', 'kor-ri-DO-jo', 'Il bagno è in fondo al corridoio.', 'De badkamer is aan het eind van de gang.', 'sostantivo'),
    (198, 'la scatola', 'de doos', 'SKA-to-la', 'Metti i libri nella scatola.', 'Doe de boeken in de doos.', 'sostantivo'),
    (199, "l'angolo", 'de hoek', 'AN-go-lo', 'Il bar è all\'angolo della strada.', 'Het café is op de hoek van de straat.', 'sostantivo'),
    (199, 'davanti', 'voor, aan de voorkant', 'da-VAN-ti', 'Davanti a casa c\'è un parco.', 'Voor het huis ligt een park.', 'avverbio'),
    (199, 'fuori', 'buiten', 'FWO-ri', 'I bambini giocano fuori.', 'De kinderen spelen buiten.', 'avverbio'),
    (199, 'la distanza', 'de afstand', 'dis-TAN-tsa', 'La distanza dal centro è breve.', 'De afstand tot het centrum is klein.', 'sostantivo'),
    (200, 'unico', 'enig, uniek', 'U-ni-ko', 'È l\'unico modo per riuscire.', 'Het is de enige manier om te slagen.', 'aggettivo'),
    # ── Blok 9: congiuntivo imperfetto, twijfel, onderwijs, taal ────────────
    (201, 'bastare', 'genoeg zijn', 'bas-TA-re', 'Pensavo che bastasse un giorno.', 'Ik dacht dat één dag genoeg was.', 'verbo'),
    (201, 'capitare', 'gebeuren, voorkomen', 'ka-pi-TA-re', 'Non credevo che capitasse a me.', 'Ik geloofde niet dat het mij zou overkomen.', 'verbo'),
    (201, 'significare', 'betekenen', 'si-nji-fi-KA-re', 'Non sapevo cosa significasse.', 'Ik wist niet wat het betekende.', 'verbo'),
    (202, 'trattare', 'behandelen', 'trat-TA-re', 'Volevo che lo trattassero bene.', 'Ik wilde dat ze hem goed behandelden.', 'verbo'),
    (202, 'rendere', 'maken, teruggeven', 'REN-de-re', 'Speravo che la notizia lo rendesse felice.', 'Ik hoopte dat het nieuws hem blij zou maken.', 'verbo'),
    (202, 'togliere', 'wegnemen, verwijderen', 'TO-lje-re', 'Volevo che togliessero il cartello.', 'Ik wilde dat ze het bord weghaalden.', 'verbo'),
    (202, 'muovere', 'bewegen', 'MWO-ve-re', 'Temevo che si muovesse.', 'Ik was bang dat het zou bewegen.', 'verbo'),
    (202, 'esistere', 'bestaan', 'e-ZIS-te-re', 'Non credevo che esistesse un posto così.', 'Ik geloofde niet dat zo\'n plek bestond.', 'verbo'),
    (203, 'sicuro', 'zeker, veilig', 'si-KU-ro', 'Non sono sicuro che venga.', 'Ik weet niet zeker of hij komt.', 'aggettivo'),
    (203, 'certo', 'zeker, natuurlijk', 'TSJER-to', 'Certo che vengo!', 'Natuurlijk kom ik!', 'aggettivo'),
    (203, 'qualche', 'enkele, een paar', 'KWAL-ke', 'Forse ci sono qualche dubbio.', 'Misschien zijn er enkele twijfels.', 'avverbio'),
    (203, 'esatto', 'precies, juist', 'e-ZAT-to', 'Non so l\'ora esatta.', 'Ik weet niet precies hoe laat.', 'aggettivo'),
    (203, 'preciso', 'precies, nauwkeurig', 'pre-TSJI-zo', 'Non ho un\'idea precisa.', 'Ik heb geen precies idee.', 'aggettivo'),
    (204, 'cioè', 'dat wil zeggen', 'tsjo-E', 'Parto presto, cioè alle sei.', 'Ik vertrek vroeg, dat wil zeggen om zes uur.', 'congiunzione'),
    (204, 'intanto', 'intussen', 'in-TAN-to', 'Intanto io preparo la cena.', 'Intussen maak ik het avondeten klaar.', 'avverbio'),
    (204, 'anzi', 'integendeel, sterker nog', 'AN-tsi', 'Non è male, anzi è ottimo.', 'Het is niet slecht, integendeel, het is uitstekend.', 'congiunzione'),
    (204, 'così', 'zo, op die manier', 'ko-ZI', 'Non è così semplice.', 'Zo eenvoudig is het niet.', 'avverbio'),
    (205, 'il genitore', 'de ouder', 'dje-ni-TO-re', 'I genitori parlano con l\'insegnante.', 'De ouders praten met de leraar.', 'sostantivo'),
    (205, 'lo studente', 'de student, de leerling', 'stu-DEN-te', 'Gli studenti hanno un esame domani.', 'De studenten hebben morgen een examen.', 'sostantivo'),
    (206, 'lo studio', 'de studie', 'STU-djo', 'Ha dedicato anni allo studio.', 'Hij heeft jaren aan zijn studie gewijd.', 'sostantivo'),
    (206, 'il corso', 'de cursus', 'KOR-so', 'Seguo un corso di storia.', 'Ik volg een cursus geschiedenis.', 'sostantivo'),
    (206, 'il termine', 'de term, de termijn', 'TER-mi-ne', 'È un termine tecnico.', 'Het is een technische term.', 'sostantivo'),
    (207, 'la penna', 'de pen', 'PEN-na', 'Mi presti una penna?', 'Kun je me een pen lenen?', 'sostantivo'),
    (207, 'il diario', 'het dagboek', 'di-A-rjo', 'Scrivo un diario ogni sera.', 'Ik schrijf elke avond in mijn dagboek.', 'sostantivo'),
    (207, 'la biblioteca', 'de bibliotheek', 'bi-bljo-TE-ka', 'Studio in biblioteca.', 'Ik studeer in de bibliotheek.', 'sostantivo'),
    (207, 'il titolo', 'de titel', 'TI-to-lo', 'Qual è il titolo del libro?', 'Wat is de titel van het boek?', 'sostantivo'),
    (207, 'semplice', 'eenvoudig', 'SEM-pli-tsje', 'Il testo è scritto in modo semplice.', 'De tekst is eenvoudig geschreven.', 'aggettivo'),
    (207, "l'esempio", 'het voorbeeld', 'e-ZEM-pjo', 'Fammi un esempio.', 'Geef me een voorbeeld.', 'sostantivo'),
    (208, 'correggere', 'verbeteren, corrigeren', 'kor-RED-dje-re', 'Il professore corregge i compiti.', 'De leraar kijkt het huiswerk na.', 'verbo'),
    (208, 'la prova', 'de test, het bewijs', 'PRO-va', 'La prova scritta è venerdì.', 'De schriftelijke toets is vrijdag.', 'sostantivo'),
    (208, 'qualsiasi', 'welke dan ook, om het even welke', 'kwal-SI-a-zi', 'Puoi scegliere qualsiasi argomento.', 'Je mag om het even welk onderwerp kiezen.', 'aggettivo'),
    (208, 'ultimo', 'laatste', 'UL-ti-mo', 'L\'ultimo esame è a giugno.', 'Het laatste examen is in juni.', 'aggettivo'),
    (209, 'il senso', 'de betekenis, de zin', 'SEN-so', 'Questa frase non ha senso.', 'Deze zin slaat nergens op.', 'sostantivo'),
    (209, 'il cognome', 'de achternaam', 'ko-NJO-me', 'Come si scrive il tuo cognome?', 'Hoe schrijf je je achternaam?', 'sostantivo'),
    (209, 'il nome', 'de naam', 'NO-me', 'Il mio nome è Giulia.', 'Mijn naam is Giulia.', 'sostantivo'),
    (209, 'la maniera', 'de manier', 'ma-NJE-ra', 'Parla in maniera formale.', 'Hij spreekt op een formele manier.', 'sostantivo'),
    (209, 'la traduzione', 'de vertaling', 'tra-du-TSJO-ne', 'La traduzione non è letterale.', 'De vertaling is niet letterlijk.', 'sostantivo'),
    (210, 'il problema', 'het probleem', 'pro-BLE-ma', 'Non c\'è nessun problema.', 'Er is geen enkel probleem.', 'sostantivo'),
    (210, "l'idea", 'het idee', 'i-DE-a', 'Che bella idea!', 'Wat een goed idee!', 'sostantivo'),
    (210, 'la situazione', 'de situatie', 'si-tu-a-TSJO-ne', 'La situazione è complicata.', 'De situatie is ingewikkeld.', 'sostantivo'),
    (210, 'la questione', 'de kwestie', 'kwes-TJO-ne', 'È una questione di tempo.', 'Het is een kwestie van tijd.', 'sostantivo'),
    (210, 'il caso', 'het geval, het toeval', 'KA-zo', 'In ogni caso ti chiamo.', 'In ieder geval bel ik je.', 'sostantivo'),
    (210, 'la causa', 'de oorzaak', 'KAU-za', 'Qual è la causa del problema?', 'Wat is de oorzaak van het probleem?', 'sostantivo'),
    (210, 'il gruppo', 'de groep', 'GRUP-po', 'Lavoriamo in gruppo.', 'We werken in een groep.', 'sostantivo'),
    # ── Blok 10: relaties, karakter, ambities, welzijn ──────────────────────
    (211, "l'amico", 'de vriend', 'a-MI-ko', 'Marco è il mio migliore amico.', 'Marco is mijn beste vriend.', 'sostantivo'),
    (211, 'la persona', 'de persoon', 'per-SO-na', 'È una persona molto simpatica.', 'Het is een heel sympathiek persoon.', 'sostantivo'),
    (211, 'la gente', 'de mensen', 'DJEN-te', 'La gente qui è gentile.', 'De mensen hier zijn vriendelijk.', 'sostantivo'),
    (212, 'sposato', 'getrouwd', 'spo-ZA-to', 'Sono sposati da dieci anni.', 'Ze zijn tien jaar getrouwd.', 'aggettivo'),
    (212, 'la donna', 'de vrouw', 'DON-na', 'La donna dei miei sogni.', 'De vrouw van mijn dromen.', 'sostantivo'),
    (212, 'l\'uomo', 'de man', 'WO-mo', 'È un uomo onesto.', 'Hij is een eerlijke man.', 'sostantivo'),
    (213, 'la scusa', 'het excuus, de verontschuldiging', 'SKU-za', 'Ti chiedo scusa per ieri.', 'Ik bied mijn excuses aan voor gisteren.', 'sostantivo'),
    (213, 'il nemico', 'de vijand', 'ne-MI-ko', 'Non voglio farmi dei nemici.', 'Ik wil geen vijanden maken.', 'sostantivo'),
    (213, 'la ragazza', 'het meisje', 'ra-GAT-tsa', 'La ragazza non gli parla più.', 'Het meisje praat niet meer met hem.', 'sostantivo'),
    (214, 'giovane', 'jong', 'DJO-va-ne', 'È giovane ma molto maturo.', 'Hij is jong maar heel volwassen.', 'aggettivo'),
    (214, 'serio', 'serieus', 'SE-rjo', 'È una persona seria e affidabile.', 'Het is een serieus en betrouwbaar persoon.', 'aggettivo'),
    (214, 'cattivo', 'slecht, gemeen', 'kat-TI-vo', 'Non è cattivo, è solo timido.', 'Hij is niet gemeen, alleen verlegen.', 'aggettivo'),
    (216, 'l\'inizio', 'het begin', 'i-NI-tsjo', 'Ogni sogno ha un inizio.', 'Elke droom heeft een begin.', 'sostantivo'),
    (216, 'la fantasia', 'de fantasie', 'fan-ta-ZI-a', 'Ha una grande fantasia.', 'Ze heeft veel fantasie.', 'sostantivo'),
    (216, 'il bisogno', 'de behoefte', 'bi-ZO-njo', 'Ho bisogno di una sfida nuova.', 'Ik heb behoefte aan een nieuwe uitdaging.', 'sostantivo'),
    (216, 'il vantaggio', 'het voordeel', 'van-TAD-djo', 'Parlare due lingue è un vantaggio.', 'Twee talen spreken is een voordeel.', 'sostantivo'),
    (216, "l'impegno", 'de inzet, de verplichting', 'im-PE-njo', 'Con impegno si arriva lontano.', 'Met inzet kom je ver.', 'sostantivo'),
    (217, 'il merito', 'de verdienste', 'ME-ri-to', 'Il merito è tutto suo.', 'De verdienste is helemaal van hem.', 'sostantivo'),
    (217, 'duro', 'hard, zwaar', 'DU-ro', 'È stato un anno duro.', 'Het was een zwaar jaar.', 'aggettivo'),
    (217, 'inutile', 'nutteloos', 'i-NU-ti-le', 'È inutile insistere.', 'Het heeft geen zin om aan te dringen.', 'aggettivo'),
    (218, 'la giornata', 'de dag (als geheel)', 'djor-NA-ta', 'Che bella giornata!', 'Wat een mooie dag!', 'sostantivo'),
    (218, 'il bambino', 'het kind', 'bam-BI-no', 'I bambini sono felici con poco.', 'Kinderen zijn blij met weinig.', 'sostantivo'),
    (219, 'il panico', 'de paniek', 'PA-ni-ko', 'Niente panico, va tutto bene.', 'Geen paniek, alles gaat goed.', 'emozione'),
    (219, 'il silenzio', 'de stilte', 'si-LEN-tsjo', 'Ho bisogno di un po\' di silenzio.', 'Ik heb wat stilte nodig.', 'sostantivo'),
    (219, 'calmare', 'kalmeren', 'kal-MA-re', 'Cerca di calmarti.', 'Probeer te kalmeren.', 'verbo'),
    (220, 'la forza', 'de kracht', 'FOR-tsa', 'Non ho più la forza di continuare.', 'Ik heb de kracht niet meer om door te gaan.', 'sostantivo'),
    # ── Blok 11: natuur, landschap, klimaat, duurzaamheid ───────────────────
    (223, "l'erba", 'het gras', 'ER-ba', "L'erba è bagnata.", 'Het gras is nat.', 'ambiente'),
    (224, 'la pietra', 'de steen', 'PJE-tra', 'Il muro è fatto di pietra.', 'De muur is van steen.', 'geografia'),
    (224, 'la roccia', 'de rots', 'ROT-tsja', 'La casa è costruita sulla roccia.', 'Het huis is op de rots gebouwd.', 'geografia'),
    (224, "l'oceano", 'de oceaan', 'o-TSJE-a-no', "L'oceano Atlantico è immenso.", 'De Atlantische Oceaan is immens.', 'geografia'),
    (224, 'alto', 'hoog', 'AL-to', 'Le montagne sono molto alte.', 'De bergen zijn heel hoog.', 'aggettivo'),
    (224, 'la cima', 'de top', 'TSJI-ma', 'Dalla cima si vede il mare.', 'Vanaf de top zie je de zee.', 'geografia'),
    (224, "l'alba", 'de dageraad', 'AL-ba', 'Partiamo all\'alba.', 'We vertrekken bij zonsopgang.', 'tempo'),
    (226, "l'altezza", 'de hoogte', 'al-TET-tsa', 'Siamo a duemila metri di altezza.', 'We zijn op tweeduizend meter hoogte.', 'geografia'),
    (226, 'il passo', 'de stap, de bergpas', 'PAS-so', 'Un passo alla volta si arriva in cima.', 'Stap voor stap kom je op de top.', 'sostantivo'),
    (227, 'il fuoco', 'het vuur', 'FWO-ko', 'Il fuoco ha distrutto il bosco.', 'Het vuur heeft het bos verwoest.', 'ambiente'),
    (227, 'distruggere', 'vernietigen', 'dis-TRUD-dje-re', 'La siccità distrugge i raccolti.', 'De droogte vernietigt de oogsten.', 'verbo'),
    (227, 'continuo', 'voortdurend', 'kon-TI-nu-o', 'Il clima è in continuo cambiamento.', 'Het klimaat verandert voortdurend.', 'aggettivo'),
    (228, 'la spazzatura', 'het afval', 'spat-tsa-TU-ra', 'Porta fuori la spazzatura.', 'Zet het afval buiten.', 'ambiente'),
    (228, 'il materiale', 'het materiaal', 'ma-te-RJA-le', 'È un materiale riciclabile.', 'Het is een recyclebaar materiaal.', 'ambiente'),
    (228, 'il vetro', 'het glas (materiaal)', 'VE-tro', 'Il vetro va nel contenitore verde.', 'Glas gaat in de groene container.', 'ambiente'),
    (228, 'buttare', 'weggooien', 'but-TA-re', 'Non buttare la plastica nel bosco.', 'Gooi geen plastic in het bos.', 'verbo'),
    (230, 'il cane', 'de hond', 'KA-ne', 'Il cane corre nel parco.', 'De hond rent in het park.', 'ambiente'),
    (230, 'il cavallo', 'het paard', 'ka-VAL-lo', 'Il cavallo mangia l\'erba.', 'Het paard eet gras.', 'ambiente'),
    # ── Blok 12: film, theater, kunst, media, mode, evenementen ─────────────
    (231, 'il finale', 'het einde, de finale', 'fi-NA-le', 'Il finale del film mi ha sorpreso.', 'Het einde van de film verraste me.', 'sostantivo'),
    (231, 'classico', 'klassiek', 'KLAS-si-ko', 'È un film classico degli anni Sessanta.', 'Het is een klassieke film uit de jaren zestig.', 'aggettivo'),
    (231, 'romantico', 'romantisch', 'ro-MAN-ti-ko', 'Preferisco i film romantici.', 'Ik geef de voorkeur aan romantische films.', 'aggettivo'),
    (231, 'famoso', 'beroemd', 'fa-MO-zo', 'L\'attore è famoso in tutto il mondo.', 'De acteur is wereldberoemd.', 'aggettivo'),
    (231, 'divertente', 'grappig, leuk', 'di-ver-TEN-te', 'È una commedia molto divertente.', 'Het is een heel grappige komedie.', 'aggettivo'),
    (232, 'il palco', 'het podium', 'PAL-ko', 'Gli attori salgono sul palco.', 'De acteurs gaan het podium op.', 'sostantivo'),
    (233, 'il segno', 'het teken', 'SE-njo', 'Il pittore lascia un segno in ogni opera.', 'De schilder laat in elk werk een teken achter.', 'sostantivo'),
    (233, "l'ombra", 'de schaduw', 'OM-bra', 'Il pittore gioca con luce e ombra.', 'De schilder speelt met licht en schaduw.', 'sostantivo'),
    (233, 'il colore', 'de kleur', 'ko-LO-re', 'I colori del quadro sono vivaci.', 'De kleuren van het schilderij zijn levendig.', 'sostantivo'),
    (233, 'l\'aspetto', 'het uiterlijk, het aspect', 'as-PET-to', 'L\'aspetto del quadro è moderno.', 'Het uiterlijk van het schilderij is modern.', 'sostantivo'),
    (233, 'simile', 'gelijkend, vergelijkbaar', 'SI-mi-le', 'I due quadri sono molto simili.', 'De twee schilderijen lijken sterk op elkaar.', 'aggettivo'),
    (234, 'il modello', 'het model', 'mo-DEL-lo', 'È un modello di design italiano.', 'Het is een model van Italiaans design.', 'sostantivo'),
    (235, 'la stampa', 'de pers', 'STAM-pa', 'La stampa ha criticato il governo.', 'De pers heeft de regering bekritiseerd.', 'sostantivo'),
    (235, 'la fonte', 'de bron', 'FON-te', 'Il giornalista protegge le sue fonti.', 'De journalist beschermt zijn bronnen.', 'sostantivo'),
    (235, "l'informazione", 'de informatie', 'in-for-ma-TSJO-ne', 'Cerco informazioni sul treno.', 'Ik zoek informatie over de trein.', 'sostantivo'),
    (236, 'la radio', 'de radio', 'RA-djo', 'Ascolto la radio in macchina.', 'Ik luister naar de radio in de auto.', 'sostantivo'),
    (236, 'la voce', 'de stem', 'VO-tsje', 'La voce del conduttore è calda.', 'De stem van de presentator is warm.', 'sostantivo'),
    (236, 'il suono', 'het geluid', 'SWO-no', 'Il suono della radio è basso.', 'Het geluid van de radio staat zacht.', 'sostantivo'),
    (237, 'popolare', 'populair', 'po-po-LA-re', 'È un prodotto molto popolare.', 'Het is een heel populair product.', 'aggettivo'),
    (237, 'speciale', 'speciaal, bijzonder', 'spe-TSJA-le', 'Un\'offerta speciale solo per oggi.', 'Een speciale aanbieding alleen vandaag.', 'aggettivo'),
    (237, 'il cartello', 'het bord, de poster', 'kar-TEL-lo', 'Il cartello pubblicitario è enorme.', 'Het reclamebord is enorm.', 'sostantivo'),
    (239, "l'evento", 'het evenement', 'e-VEN-to', "L'evento si tiene in piazza.", 'Het evenement vindt plaats op het plein.', 'sostantivo'),
    (239, 'la banda', 'de band, de fanfare', 'BAN-da', 'La banda suona in piazza.', 'De fanfare speelt op het plein.', 'sostantivo'),
    (239, 'l\'incontro', 'de ontmoeting, de bijeenkomst', 'in-KON-tro', 'Il festival è un incontro tra culture.', 'Het festival is een ontmoeting tussen culturen.', 'sostantivo'),
    (239, 'il costume', 'het kostuum', 'kos-TU-me', 'Tutti portano un costume tradizionale.', 'Iedereen draagt een traditioneel kostuum.', 'sostantivo'),
    (239, 'la serata', 'de avond (als geheel)', 'se-RA-ta', 'La serata finisce con i fuochi d\'artificio.', 'De avond eindigt met vuurwerk.', 'sostantivo'),
    (240, 'il ballo', 'het bal, de dans', 'BAL-lo', 'Il ballo finisce a mezzanotte.', 'Het bal eindigt om middernacht.', 'sostantivo'),
    (240, 'indossare', 'dragen (kleding)', 'in-dos-SA-re', 'Indossa sempre vestiti eleganti.', 'Ze draagt altijd elegante kleding.', 'verbo'),
    # ── Blok 13: politiek, recht, maatschappij ──────────────────────────────
    (241, 'il politico', 'de politicus', 'po-LI-ti-ko', 'I politici promettono molto.', 'Politici beloven veel.', 'sostantivo'),
    (241, 'il sindaco', 'de burgemeester', 'SIN-da-ko', 'Il sindaco ha inaugurato il parco.', 'De burgemeester heeft het park geopend.', 'sostantivo'),
    (241, 'la posizione', 'de positie, het standpunt', 'po-zi-TSJO-ne', 'Qual è la posizione del partito?', 'Wat is het standpunt van de partij?', 'sostantivo'),
    (241, 'il membro', 'het lid', 'MEM-bro', 'È membro del consiglio.', 'Hij is lid van de raad.', 'sostantivo'),
    (242, 'la base', 'de basis', 'BA-ze', 'La democrazia è la base dello Stato.', 'Democratie is de basis van de staat.', 'sostantivo'),
    (242, 'nazionale', 'nationaal', 'na-tsjo-NA-le', 'Le elezioni nazionali sono a marzo.', 'De nationale verkiezingen zijn in maart.', 'aggettivo'),
    (242, 'sociale', 'sociaal', 'so-TSJA-le', 'La politica sociale è importante.', 'Het sociale beleid is belangrijk.', 'aggettivo'),
    (243, 'la sicurezza', 'de veiligheid', 'si-ku-RET-tsa', 'Lo Stato garantisce la sicurezza.', 'De staat garandeert de veiligheid.', 'sostantivo'),
    (243, 'la protezione', 'de bescherming', 'pro-te-TSJO-ne', 'La legge garantisce protezione.', 'De wet garandeert bescherming.', 'sostantivo'),
    (243, 'legale', 'wettelijk, legaal', 'le-GA-le', 'È il suo diritto legale.', 'Het is zijn wettelijk recht.', 'aggettivo'),
    (244, 'innocente', 'onschuldig', 'in-no-TSJEN-te', 'Il tribunale lo ha dichiarato innocente.', 'De rechtbank heeft hem onschuldig verklaard.', 'aggettivo'),
    (245, "l'origine", 'de afkomst, de oorsprong', 'o-RI-dji-ne', 'È di origine marocchina.', 'Hij is van Marokkaanse afkomst.', 'sostantivo'),
    (245, 'la nazione', 'de natie', 'na-TSJO-ne', 'Vengono da molte nazioni diverse.', 'Ze komen uit veel verschillende landen.', 'sostantivo'),
    (245, 'sconosciuto', 'onbekend', 'sko-no-SJU-to', 'Arrivò in un paese sconosciuto.', 'Hij kwam aan in een onbekend land.', 'aggettivo'),
    (246, "l'aiuto", 'de hulp', 'a-JU-to', 'Grazie per il tuo aiuto.', 'Bedankt voor je hulp.', 'sostantivo'),
    (246, 'offrire', 'aanbieden', 'of-FRI-re', 'Offriamo cibo ai senzatetto.', 'We bieden eten aan daklozen.', 'verbo'),
    (247, "l'anima", 'de ziel', 'A-ni-ma', 'La musica tocca l\'anima.', 'Muziek raakt de ziel.', 'sostantivo'),
    (247, 'lo spirito', 'de geest', 'SPI-ri-to', 'Ha uno spirito libero.', 'Zij heeft een vrije geest.', 'sostantivo'),
    (249, 'il soldato', 'de soldaat', 'sol-DA-to', 'Il soldato torna a casa.', 'De soldaat keert naar huis terug.', 'sostantivo'),
    (250, 'la violenza', 'het geweld', 'vjo-LEN-tsa', 'La violenza non è mai la soluzione.', 'Geweld is nooit de oplossing.', 'sostantivo'),
    (250, 'la difesa', 'de verdediging', 'di-FE-za', "L'avvocato prepara la difesa.", 'De advocaat bereidt de verdediging voor.', 'sostantivo'),
    # ── Blok 14: werk verdieping, zakelijk ──────────────────────────────────
    (251, 'contare', 'tellen, rekenen op', 'kon-TA-re', 'Puoi contare su di me.', 'Je kunt op me rekenen.', 'verbo'),
    (251, 'il ruolo', 'de rol, de functie', 'RWO-lo', 'Il ruolo richiede esperienza.', 'De functie vereist ervaring.', 'lavoro'),
    (251, 'richiedere', 'vereisen, aanvragen', 'ri-KJE-de-re', 'Il lavoro richiede molta pazienza.', 'Het werk vereist veel geduld.', 'verbo'),
    (251, 'disponibile', 'beschikbaar', 'dis-po-NI-bi-le', 'Sono disponibile da subito.', 'Ik ben per direct beschikbaar.', 'aggettivo'),
    (252, "l'impressione", 'de indruk', 'im-pres-SJO-ne', 'Ha fatto un\'ottima impressione.', 'Hij heeft een uitstekende indruk gemaakt.', 'sostantivo'),
    (253, "l'opzione", 'de optie', 'op-TSJO-ne', 'Abbiamo due opzioni sul tavolo.', 'We hebben twee opties op tafel.', 'ufficio'),
    (253, 'l\'attenzione', 'de aandacht', 'at-ten-TSJO-ne', 'Grazie per l\'attenzione.', 'Bedankt voor uw aandacht.', 'ufficio'),
    (253, 'la conferma', 'de bevestiging', 'kon-FER-ma', 'Aspetto la conferma via e-mail.', 'Ik wacht op de bevestiging per e-mail.', 'ufficio'),
    (253, 'concludere', 'afsluiten, concluderen', 'kon-KLU-de-re', 'Concludiamo la riunione alle cinque.', 'We sluiten de vergadering om vijf uur af.', 'verbo'),
    (253, 'stabilire', 'vaststellen', 'sta-bi-LI-re', 'Dobbiamo stabilire una data.', 'We moeten een datum vaststellen.', 'verbo'),
    (254, 'presentare', 'presenteren, voorstellen', 'pre-zen-TA-re', 'Presento i risultati del trimestre.', 'Ik presenteer de kwartaalresultaten.', 'verbo'),
    (254, 'il dettaglio', 'het detail', 'det-TA-ljo', 'Vediamo i dettagli nella prossima slide.', 'De details zien we op de volgende slide.', 'ufficio'),
    (255, "l'indirizzo", 'het adres', 'in-di-RIT-tso', 'Qual è il suo indirizzo e-mail?', 'Wat is uw e-mailadres?', 'ufficio'),
    (256, 'il patto', 'het pact, de afspraak', 'PAT-to', 'Facciamo un patto.', 'Laten we een afspraak maken.', 'sostantivo'),
    (256, 'convenire', 'gunstig zijn, overeenkomen', 'kon-ve-NI-re', 'Ci conviene accettare l\'offerta.', 'Het is gunstig voor ons het aanbod te accepteren.', 'verbo'),
    (256, 'entrambi', 'beide, allebei', 'en-TRAM-bi', 'Entrambe le parti sono soddisfatte.', 'Beide partijen zijn tevreden.', 'aggettivo'),
    (256, 'insistere', 'aandringen', 'in-SIS-te-re', 'Insisto su questo punto.', 'Ik dring aan op dit punt.', 'verbo'),
    (257, 'la regola', 'de regel', 'RE-go-la', 'In azienda ci sono regole chiare.', 'In het bedrijf zijn er duidelijke regels.', 'sostantivo'),
    (258, 'il trasporto', 'het transport', 'tras-POR-to', 'Il trasporto è a carico del cliente.', 'Het transport is voor rekening van de klant.', 'sostantivo'),
    (259, 'assicurare', 'verzekeren, garanderen', 'as-si-ku-RA-re', 'Le assicuro che risolveremo tutto.', 'Ik verzeker u dat we alles oplossen.', 'verbo'),
    (259, 'attento', 'oplettend, voorzichtig', 'at-TEN-to', 'Stia attento alla data di scadenza.', 'Let op de vervaldatum.', 'aggettivo'),
    (259, 'l\'attimo', 'het ogenblik', 'AT-ti-mo', 'Un attimo, la metto in contatto.', 'Een ogenblik, ik verbind u door.', 'sostantivo'),
    (259, 'spiacente', 'het spijt me', 'spja-TSJEN-te', 'Spiacente, il prodotto è esaurito.', 'Het spijt me, het product is uitverkocht.', 'espressione'),
    (260, 'funzionare', 'werken, functioneren', 'fun-tsjo-NA-re', 'La stampante non funziona.', 'De printer werkt niet.', 'verbo'),
    (260, 'controllare', 'controleren', 'kon-trol-LA-re', 'Controlla la posta ogni giorno.', 'Controleer elke dag je mail.', 'verbo'),
    # ── Blok 15: ziekenhuis, apotheek, wetenschap ───────────────────────────
    (261, "l'infermiera", 'de verpleegkundige (vrouw)', 'in-fer-MJE-ra', "L'infermiera misura la febbre.", 'De verpleegkundige meet de koorts.', 'salute'),
    (261, "l'intervento", 'de operatie, de ingreep', 'in-ter-VEN-to', "L'intervento è durato tre ore.", 'De operatie duurde drie uur.', 'salute'),
    (261, 'ferito', 'gewond', 'fe-RI-to', 'Ci sono tre feriti gravi.', 'Er zijn drie zwaargewonden.', 'aggettivo'),
    (261, 'il sangue', 'het bloed', 'SAN-gwe', 'Devo fare un esame del sangue.', 'Ik moet een bloedonderzoek laten doen.', 'corpo'),
    (261, 'la morte', 'de dood', 'MOR-te', 'La morte del paziente è stata improvvisa.', 'De dood van de patiënt kwam plotseling.', 'sostantivo'),
    (261, 'il cancro', 'de kanker', 'KAN-kro', 'Ha sconfitto il cancro.', 'Ze heeft de kanker overwonnen.', 'salute'),
    (262, 'la dose', 'de dosis', 'DO-ze', 'Non superare la dose indicata.', 'Overschrijd de aangegeven dosis niet.', 'salute'),
    (262, 'pericoloso', 'gevaarlijk', 'pe-ri-ko-LO-zo', 'Questo farmaco è pericoloso per i bambini.', 'Dit medicijn is gevaarlijk voor kinderen.', 'aggettivo'),
    (262, 'il trattamento', 'de behandeling', 'trat-ta-MEN-to', 'Il trattamento dura due settimane.', 'De behandeling duurt twee weken.', 'salute'),
    (262, 'utile', 'nuttig', 'U-ti-le', 'Questo sciroppo è utile contro la tosse.', 'Deze siroop is nuttig tegen hoest.', 'aggettivo'),
    (262, 'il paio', 'het paar', 'PA-jo', 'Prendi un paio di pastiglie.', 'Neem een paar tabletten.', 'sostantivo'),
    (263, 'il trauma', 'het trauma', 'TRAU-ma', 'Ha superato il trauma con la terapia.', 'Hij heeft het trauma met therapie verwerkt.', 'salute'),
    (263, 'la mente', 'de geest', 'MEN-te', 'Una mente sana in un corpo sano.', 'Een gezonde geest in een gezond lichaam.', 'sostantivo'),
    (264, 'vivo', 'levend', 'VI-vo', 'Il ferito è ancora vivo.', 'De gewonde leeft nog.', 'aggettivo'),
    (265, 'scientifico', 'wetenschappelijk', 'sjen-TI-fi-ko', 'Il metodo scientifico si basa su prove.', 'De wetenschappelijke methode berust op bewijs.', 'aggettivo'),
    (265, 'la sostanza', 'de stof, de substantie', 'sos-TAN-tsa', 'Questa sostanza è pericolosa.', 'Deze stof is gevaarlijk.', 'sostantivo'),
    (265, 'umano', 'menselijk', 'u-MA-no', 'Il corpo umano è complesso.', 'Het menselijk lichaam is complex.', 'aggettivo'),
    (266, 'il gene', 'het gen', 'DJE-ne', 'Alcune malattie dipendono dai geni.', 'Sommige ziektes hangen af van de genen.', 'sostantivo'),
    (268, 'l\'uso', 'het gebruik', 'U-zo', 'L\'uso della radio cambiò il mondo.', 'Het gebruik van de radio veranderde de wereld.', 'sostantivo'),
    (268, 'la tecnica', 'de techniek', 'TEK-ni-ka', 'La tecnica di stampa è antica.', 'De druktechniek is oud.', 'sostantivo'),
    (268, 'lo strumento', 'het instrument, het gereedschap', 'stru-MEN-to', 'Il telescopio è uno strumento potente.', 'De telescoop is een krachtig instrument.', 'sostantivo'),
    (269, 'spaziale', 'ruimte-, ruimtelijk', 'spa-TSJA-le', 'La stazione spaziale gira intorno alla Terra.', 'Het ruimtestation draait om de aarde.', 'aggettivo'),
    (270, 'il cervello', 'de hersenen', 'tsjer-VEL-lo', 'Il cervello controlla tutto il corpo.', 'De hersenen sturen het hele lichaam aan.', 'corpo'),
    (270, 'il grado', 'de graad', 'GRA-do', 'La febbre è a trentanove gradi.', 'De koorts staat op negenendertig graden.', 'sostantivo'),
    (270, 'la struttura', 'de structuur', 'strut-TU-ra', 'La struttura della cellula è complessa.', 'De structuur van de cel is complex.', 'sostantivo'),
    (270, 'il limite', 'de grens, de limiet', 'LI-mi-te', 'Ogni cosa ha un limite.', 'Alles heeft een grens.', 'sostantivo'),
    # ── Blok 16: dagelijks leven ────────────────────────────────────────────
    (271, 'la faccia', 'het gezicht', 'FAT-tsja', 'Lavati la faccia con acqua fredda.', 'Was je gezicht met koud water.', 'corpo'),
    (271, 'il capello', 'het haar (één haar)', 'ka-PEL-lo', 'Ho i capelli lunghi.', 'Ik heb lang haar.', 'corpo'),
    (272, 'l\'incidente', 'het ongeluk', 'in-tsji-DEN-te', 'C\'è stato un incidente in autostrada.', 'Er was een ongeluk op de snelweg.', 'sostantivo'),
    (274, 'la spesa', 'de uitgave, de boodschappen', 'SPE-za', 'Le spese mediche sono coperte.', 'De medische kosten worden gedekt.', 'sostantivo'),
    (275, 'la tazza', 'de kop, de mok', 'TAT-tsa', 'Aggiungi una tazza di farina.', 'Voeg een kop bloem toe.', 'cucina'),
    (275, 'cenare', 'dineren, avondeten', 'tsje-NA-re', 'Ceniamo alle otto.', 'We eten om acht uur.', 'verbo'),
    (275, 'intero', 'heel, geheel', 'in-TE-ro', 'Cuoci il pollo intero.', 'Braad de hele kip.', 'aggettivo'),
    (275, 'il chilo', 'de kilo', 'KI-lo', 'Un chilo di pomodori, per favore.', 'Een kilo tomaten, alstublieft.', 'cucina'),
    (275, 'riempire', 'vullen', 'rjem-PI-re', 'Riempi la pentola d\'acqua.', 'Vul de pan met water.', 'verbo'),
    (276, 'pulito', 'schoon', 'pu-LI-to', 'La cucina è finalmente pulita.', 'De keuken is eindelijk schoon.', 'aggettivo'),
    (278, 'piantare', 'planten', 'pjan-TA-re', 'Piantiamo i pomodori in aprile.', 'We planten de tomaten in april.', 'verbo'),
    (280, 'la fila', 'de rij', 'FI-la', 'C\'è una lunga fila alla cassa.', 'Er staat een lange rij bij de kassa.', 'sostantivo'),
    # ── Blok 17: uitdrukkingen, communicatie ────────────────────────────────
    (282, 'la fretta', 'de haast', 'FRET-ta', 'Ho fretta, ci vediamo dopo.', 'Ik heb haast, tot straks.', 'sostantivo'),
    (284, 'abituarsi a', 'wennen aan', 'a-bi-tu-AR-si a', 'Mi sono abituato al freddo.', 'Ik ben gewend geraakt aan de kou.', 'espressione'),
    (285, 'fornire', 'leveren, verstrekken', 'for-NI-re', 'Vi forniremo tutti i documenti.', 'Wij zullen u alle documenten verstrekken.', 'verbo'),
    (287, 'telefonare', 'bellen', 'te-le-fo-NA-re', 'Ti telefono domani mattina.', 'Ik bel je morgenochtend.', 'verbo'),
    (288, 'rotto', 'kapot', 'ROT-to', 'Il riscaldamento è rotto.', 'De verwarming is kapot.', 'aggettivo'),
    (288, 'sporco', 'vies', 'SPOR-ko', 'La camera era sporca.', 'De kamer was vies.', 'aggettivo'),
    (288, 'aperto', 'open', 'a-PER-to', 'Il negozio non era aperto.', 'De winkel was niet open.', 'aggettivo'),
    (289, 'congratulazioni', 'gefeliciteerd', 'kon-gra-tu-la-TSJO-ni', 'Congratulazioni per la laurea!', 'Gefeliciteerd met je diploma!', 'espressione'),
    (289, 'carino', 'lief, aardig, leuk', 'ka-RI-no', 'Sei stato molto carino con me.', 'Je bent heel lief voor me geweest.', 'aggettivo'),
    (290, 'la differenza', 'het verschil', 'dif-fe-REN-tsa', 'Che differenza c\'è tra i due?', 'Wat is het verschil tussen de twee?', 'sostantivo'),
    (290, 'il periodo', 'de periode', 'pe-RI-o-do', 'È stato un periodo difficile.', 'Het was een moeilijke periode.', 'sostantivo'),
    (290, 'ora', 'nu', 'O-ra', 'Ora capisco tutto.', 'Nu begrijp ik alles.', 'avverbio'),
    # ── Blok 18: herhaling ──────────────────────────────────────────────────
    (291, 'accompagnare', 'begeleiden, meegaan', 'ak-kom-pa-NJA-re', 'Ti ho accompagnato alla stazione.', 'Ik heb je naar het station gebracht.', 'verbo'),
    (291, 'incontrare', 'ontmoeten', 'in-kon-TRA-re', 'Ho incontrato Luca al mercato.', 'Ik kwam Luca tegen op de markt.', 'verbo'),
    (291, 'dimenticare', 'vergeten', 'di-men-ti-KA-re', 'Avevo dimenticato le chiavi.', 'Ik was de sleutels vergeten.', 'verbo'),
    (291, 'salire', 'stijgen, instappen, omhooggaan', 'sa-LI-re', 'Siamo saliti sul treno alle otto.', 'We stapten om acht uur op de trein.', 'verbo'),
    (291, 'mai', 'nooit', 'MAI', 'Non ero mai stato a Roma.', 'Ik was nog nooit in Rome geweest.', 'avverbio'),
    (291, 'sorprendere', 'verrassen', 'sor-PREN-de-re', 'La notizia mi ha sorpreso.', 'Het nieuws heeft me verrast.', 'verbo'),
    (292, 'preoccuparsi', 'zich zorgen maken', 'pre-ok-ku-PAR-si', 'Non voglio che ti preoccupi.', 'Ik wil niet dat je je zorgen maakt.', 'verbo'),
    (292, 'interessare', 'interesseren', 'in-te-res-SA-re', 'Spero che il corso ti interessi.', 'Ik hoop dat de cursus je interesseert.', 'verbo'),
    (292, 'impedire', 'verhinderen', 'im-pe-DI-re', 'Nulla impedisce che tu venga.', 'Niets verhindert dat je komt.', 'verbo'),
    (292, 'osare', 'durven', 'o-ZA-re', 'Non credo che osi chiederlo.', 'Ik denk niet dat hij het durft te vragen.', 'verbo'),
    (292, 'ritenere', 'menen, van mening zijn', 'ri-te-NE-re', 'Ritengo che sia giusto.', 'Ik meen dat het juist is.', 'verbo'),
    (292, 'l\'odio', 'de haat', 'O-djo', 'Non credo che ci sia odio tra loro.', 'Ik geloof niet dat er haat tussen hen is.', 'emozione'),
    (293, 'guidare', 'rijden, besturen', 'gwi-DA-re', 'Guiderei io, ma sono stanco.', 'Ik zou wel rijden, maar ik ben moe.', 'verbo'),
    (293, 'vendere', 'verkopen', 'VEN-de-re', 'Venderei la macchina, se potessi.', 'Ik zou de auto verkopen, als ik kon.', 'verbo'),
    (293, 'tirare', 'trekken', 'ti-RA-re', 'Tirerei la corda, se servisse.', 'Ik zou aan het touw trekken, als het nodig was.', 'verbo'),
    (294, 'rischiare', 'riskeren', 'ris-KJA-re', 'Se non studi, rischi di essere bocciato.', 'Als je niet studeert, riskeer je te zakken.', 'verbo'),
    (294, 'dipendere', 'afhangen', 'di-PEN-de-re', 'Dipende da quanto costa.', 'Het hangt ervan af hoeveel het kost.', 'verbo'),
    (294, 'causare', 'veroorzaken', 'kau-ZA-re', 'Se piove, causerà ritardi.', 'Als het regent, veroorzaakt het vertragingen.', 'verbo'),
    (294, 'sopravvivere', 'overleven', 'so-prav-VI-ve-re', 'Se fosse rimasto, non sarebbe sopravvissuto.', 'Als hij was gebleven, had hij het niet overleefd.', 'verbo'),
    (295, 'confessare', 'bekennen', 'kon-fes-SA-re', 'Ha confessato che aveva paura.', 'Hij bekende dat hij bang was.', 'verbo'),
    (295, 'avvisare', 'waarschuwen, laten weten', 'av-vi-ZA-re', 'Mi ha avvisato che sarebbe arrivato tardi.', 'Hij liet me weten dat hij laat zou komen.', 'verbo'),
    (295, 'giurare', 'zweren', 'dju-RA-re', 'Ha giurato che non lo sapeva.', 'Hij zwoer dat hij het niet wist.', 'verbo'),
    (296, 'attraverso', 'door, via', 'at-tra-VER-so', 'Ci siamo conosciuti attraverso amici.', 'We hebben elkaar via vrienden leren kennen.', 'congiunzione'),
    (296, 'oltre', 'voorbij, behalve', 'OL-tre', 'Oltre a questo, non so niente.', 'Behalve dit weet ik niets.', 'congiunzione'),
    (296, 'entro', 'binnen (tijd), uiterlijk', 'EN-tro', 'Rispondi entro venerdì.', 'Antwoord uiterlijk vrijdag.', 'congiunzione'),
    (297, 'la nascita', 'de geboorte', 'NA-sji-ta', 'La data di nascita è sul passaporto.', 'De geboortedatum staat in het paspoort.', 'sostantivo'),
    (297, 'durante', 'tijdens', 'du-RAN-te', 'Durante la lezione ho preso appunti.', 'Tijdens de les heb ik aantekeningen gemaakt.', 'congiunzione'),
    (297, "l'importanza", 'het belang', 'im-por-TAN-tsa', 'Non capisco l\'importanza di questa regola.', 'Ik begrijp het belang van deze regel niet.', 'sostantivo'),
    (298, 'la fattoria', 'de boerderij (niet: fabriek)', 'fat-to-RI-a', 'Mio zio ha una fattoria in Toscana.', 'Mijn oom heeft een boerderij in Toscane.', 'sostantivo'),
    (298, 'il parente', 'het familielid (niet: ouder)', 'pa-REN-te', 'A Natale vengono tutti i parenti.', 'Met Kerst komt de hele familie.', 'sostantivo'),
    (298, 'attuale', 'huidig (niet: actueel)', 'at-tu-A-le', 'La situazione attuale è difficile.', 'De huidige situatie is moeilijk.', 'aggettivo'),
    (298, 'il magazzino', 'het magazijn (niet: tijdschrift)', 'ma-gad-DZI-no', 'La merce è nel magazzino.', 'De goederen liggen in het magazijn.', 'sostantivo'),
    (298, 'la conferenza', 'de lezing, het congres', 'kon-fe-REN-tsa', 'Tiene una conferenza sull\'arte.', 'Zij geeft een lezing over kunst.', 'sostantivo'),
    (300, 'straordinario', 'buitengewoon', 'stra-or-di-NA-rjo', 'Hai fatto un lavoro straordinario.', 'Je hebt buitengewoon werk geleverd.', 'aggettivo'),
    (300, 'eccellente', 'uitstekend', 'et-tsjel-LEN-te', 'Il tuo italiano è eccellente.', 'Je Italiaans is uitstekend.', 'aggettivo'),
    (300, 'magnifico', 'prachtig', 'ma-NJI-fi-ko', 'Che risultato magnifico!', 'Wat een prachtig resultaat!', 'aggettivo'),
    (300, 'l\'onore', 'de eer', 'o-NO-re', 'È stato un onore imparare con te.', 'Het was een eer om met jou te leren.', 'sostantivo'),
    (300, "l'orgoglio", 'de trots', 'or-GO-ljo', 'Guardo con orgoglio a quanto ho imparato.', 'Ik kijk met trots naar wat ik geleerd heb.', 'sostantivo'),
]
