#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_es_a1.py — Spaans A1 (v1.48): 60 lessen × 8 woorden, zelfde thema-opbouw als Italiaans A1
zodat plaatsingstoets (5 groepen van 12 lessen) en toetslessen (elke 10 lessen) direct werken.
Woord-IDs: e001… Draai opnieuw na bewerken: python3 scripts/generate_es_a1.py
Formaat per les: L(id, emoji, title, description, grammar_title, grammar_body, [ (es, nl, ph, ex, exNl, cat) × 8 ])
"""
import json
from pathlib import Path

OUT = Path(__file__).parent.parent / 'www' / 'data' / 'es'

def L(id, emoji, title, desc, gt, gb, words):
    return dict(id=id, emoji=emoji, title=title, description=desc, grammar=dict(title=gt, body=gb), words=words)

LESSONS = [
L(1, '👋', 'Begroetingen', 'De eerste woorden om iemand te begroeten en te bedanken.',
  'Tú of usted — informeel of formeel?', 'In het Spaans zeg je "tú" tegen vrienden en familie en "usted" tegen onbekenden en ouderen. Bij usted gebruik je de werkwoordsvorm van hij/zij: ¿Cómo está usted?',
  [('hola', 'hallo', 'OH-la', '¡Hola! ¿Qué tal?', 'Hallo! Hoe gaat het?', 'begroeting'),
   ('buenos días', 'goedemorgen', 'BWEH-nos DEE-as', 'Buenos días, señora.', 'Goedemorgen, mevrouw.', 'begroeting'),
   ('buenas tardes', 'goedemiddag / goedenavond', 'BWEH-nas TAR-des', 'Buenas tardes a todos.', 'Goedemiddag allemaal.', 'begroeting'),
   ('buenas noches', 'goedenacht', 'BWEH-nas NO-tsjes', 'Buenas noches, hasta mañana.', 'Goedenacht, tot morgen.', 'begroeting'),
   ('adiós', 'tot ziens', 'a-DJOS', 'Adiós, hasta luego.', 'Tot ziens, tot straks.', 'begroeting'),
   ('gracias', 'dank je', 'GRA-sjas', 'Muchas gracias por todo.', 'Hartelijk dank voor alles.', 'begroeting'),
   ('de nada', 'graag gedaan', 'de NA-da', 'Gracias. — De nada.', 'Bedankt. — Graag gedaan.', 'begroeting'),
   ('perdón', 'pardon / sorry', 'per-DON', 'Perdón, ¿puedo pasar?', 'Pardon, mag ik erlangs?', 'begroeting')]),
L(2, '🤝', 'Stel je voor', 'Zeg wie je bent en vraag hoe het gaat.',
  'Ser en estar — twee keer "zijn"', 'Het Spaans heeft twee werkwoorden voor zijn. "Ser" voor wie of wat iets is (soy holandés), "estar" voor hoe of waar iets is (estoy bien, estoy en Madrid).',
  [('sí', 'ja', 'sie', 'Sí, claro.', 'Ja, natuurlijk.', 'basis'),
   ('no', 'nee', 'no', 'No, gracias.', 'Nee, dank je.', 'basis'),
   ('¿cómo estás?', 'hoe gaat het?', 'KO-mo es-TAS', '¡Hola, Ana! ¿Cómo estás?', 'Hallo Ana! Hoe gaat het?', 'basis'),
   ('bien', 'goed', 'bjen', 'Estoy bien, gracias.', 'Het gaat goed, dank je.', 'basis'),
   ('mal', 'slecht', 'mal', 'Hoy estoy un poco mal.', 'Vandaag gaat het een beetje slecht.', 'basis'),
   ('me llamo', 'ik heet', 'me JA-mo', 'Me llamo Carlos.', 'Ik heet Carlos.', 'basis'),
   ('mucho gusto', 'aangenaam', 'MOE-tsjo GOES-to', 'Mucho gusto, Elena.', 'Aangenaam, Elena.', 'basis'),
   ('por favor', 'alsjeblieft', 'por fa-VOR', 'Un café, por favor.', 'Een koffie, alstublieft.', 'basis')]),
L(3, '🔢', 'Cijfers 1-10', 'Tellen tot tien.',
  'Getallen gebruiken', 'Getallen veranderen niet, behalve "uno": vóór een mannelijk woord wordt het "un" (un libro) en vóór een vrouwelijk woord "una" (una casa).',
  [('uno', 'één', 'OE-no', 'Tengo un hermano.', 'Ik heb één broer.', 'cijfers'),
   ('dos', 'twee', 'dos', 'Dos cafés, por favor.', 'Twee koffie, alstublieft.', 'cijfers'),
   ('tres', 'drie', 'tres', 'Son las tres.', 'Het is drie uur.', 'cijfers'),
   ('cuatro', 'vier', 'KWA-tro', 'Somos cuatro personas.', 'We zijn met vier personen.', 'cijfers'),
   ('cinco', 'vijf', 'SIN-ko', 'Cinco euros, por favor.', 'Vijf euro, alstublieft.', 'cijfers'),
   ('seis', 'zes', 'seis', 'Mi hija tiene seis años.', 'Mijn dochter is zes jaar.', 'cijfers'),
   ('siete', 'zeven', 'SJEH-te', 'La semana tiene siete días.', 'De week heeft zeven dagen.', 'cijfers'),
   ('ocho', 'acht', 'O-tsjo', 'Cenamos a las ocho.', 'We eten om acht uur.', 'cijfers'),
   ('nueve', 'negen', 'NWEH-ve', 'El tren sale a las nueve.', 'De trein vertrekt om negen uur.', 'cijfers'),
   ('diez', 'tien', 'djeth', 'Diez minutos más.', 'Nog tien minuten.', 'cijfers')]),
L(4, '💶', 'Hogere cijfers & prijzen', 'Grotere getallen en vragen wat iets kost.',
  'Samengestelde getallen', 'Van 16 tot 29 schrijf je getallen aan elkaar: dieciséis, veintiuno. Vanaf 31 gebruik je "y": treinta y uno, cuarenta y dos.',
  [('once', 'elf', 'ON-se', 'Son las once.', 'Het is elf uur.', 'cijfers'),
   ('doce', 'twaalf', 'DO-se', 'Doce meses.', 'Twaalf maanden.', 'cijfers'),
   ('quince', 'vijftien', 'KIN-se', 'Cuesta quince euros.', 'Het kost vijftien euro.', 'cijfers'),
   ('veinte', 'twintig', 'VEIN-te', 'Tengo veinte años.', 'Ik ben twintig jaar.', 'cijfers'),
   ('treinta', 'dertig', 'TREIN-ta', 'Treinta grados hoy.', 'Dertig graden vandaag.', 'cijfers'),
   ('cincuenta', 'vijftig', 'sin-KWEN-ta', 'Cincuenta euros es mucho.', 'Vijftig euro is veel.', 'cijfers'),
   ('cien', 'honderd', 'sjen', 'Cien gramos de jamón.', 'Honderd gram ham.', 'cijfers'),
   ('¿cuánto cuesta?', 'hoeveel kost het?', 'KWAN-to KWES-ta', '¿Cuánto cuesta esta camisa?', 'Hoeveel kost dit overhemd?', 'winkelen')]),
L(5, '🎨', 'Kleuren', 'De basiskleuren.',
  'Bijvoeglijke naamwoorden passen zich aan', 'Kleuren op -o veranderen mee met het woord: el coche rojo, la casa roja, los coches rojos. Kleuren op -e of een medeklinker (verde, azul, gris) veranderen alleen in het meervoud.',
  [('rojo', 'rood', 'RO-cho', 'El coche es rojo.', 'De auto is rood.', 'kleuren'),
   ('azul', 'blauw', 'a-SOEL', 'El cielo es azul.', 'De lucht is blauw.', 'kleuren'),
   ('verde', 'groen', 'VER-de', 'La manzana es verde.', 'De appel is groen.', 'kleuren'),
   ('amarillo', 'geel', 'a-ma-RIE-jo', 'El sol es amarillo.', 'De zon is geel.', 'kleuren'),
   ('blanco', 'wit', 'BLAN-ko', 'Una camisa blanca.', 'Een wit overhemd.', 'kleuren'),
   ('negro', 'zwart', 'NE-gro', 'Un café negro, por favor.', 'Een zwarte koffie, alstublieft.', 'kleuren'),
   ('naranja', 'oranje', 'na-RAN-cha', 'Me gusta el color naranja.', 'Ik hou van de kleur oranje.', 'kleuren'),
   ('rosa', 'roze', 'RO-sa', 'Una flor rosa.', 'Een roze bloem.', 'kleuren')]),
L(6, '👨‍👩‍👧‍👦', 'Familie', 'Je naaste familie benoemen.',
  'Bezittelijke voornaamwoorden', 'mi (mijn), tu (jouw), su (zijn/haar/uw), nuestro (ons). In het meervoud krijgen ze een -s: mis padres, tus hermanos.',
  [('la madre', 'moeder', 'la MA-dre', 'Mi madre se llama Rosa.', 'Mijn moeder heet Rosa.', 'familie'),
   ('el padre', 'vader', 'el PA-dre', 'Mi padre trabaja en Sevilla.', 'Mijn vader werkt in Sevilla.', 'familie'),
   ('el hermano', 'broer', 'el er-MA-no', 'Tengo un hermano mayor.', 'Ik heb een oudere broer.', 'familie'),
   ('la hermana', 'zus', 'la er-MA-na', 'Mi hermana vive en Madrid.', 'Mijn zus woont in Madrid.', 'familie'),
   ('el hijo', 'zoon', 'el IE-cho', 'Su hijo tiene diez años.', 'Zijn zoon is tien jaar.', 'familie'),
   ('la hija', 'dochter', 'la IE-cha', 'Nuestra hija estudia.', 'Onze dochter studeert.', 'familie'),
   ('el marido', 'echtgenoot', 'el ma-RIE-do', 'Mi marido es cocinero.', 'Mijn man is kok.', 'familie'),
   ('la mujer', 'echtgenote / vrouw', 'la moe-CHER', 'Mi mujer se llama Laura.', 'Mijn vrouw heet Laura.', 'familie')]),
L(7, '🫀', 'Het lichaam', 'Lichaamsdelen — handig bij de dokter en in noodgevallen.',
  'Lidwoorden: el, la, los, las', '"El" voor mannelijke woorden (el pie), "la" voor vrouwelijke (la mano). Meervoud: los, las. Let op: la mano is vrouwelijk, el día is mannelijk.',
  [('la cabeza', 'hoofd', 'la ka-BE-sa', 'Me duele la cabeza.', 'Ik heb hoofdpijn.', 'lichaam'),
   ('la mano', 'hand', 'la MA-no', 'Lávate las manos.', 'Was je handen.', 'lichaam'),
   ('el pie', 'voet', 'el pje', 'Me duele el pie derecho.', 'Mijn rechtervoet doet pijn.', 'lichaam'),
   ('el ojo', 'oog', 'el O-cho', 'Tiene los ojos verdes.', 'Zij heeft groene ogen.', 'lichaam'),
   ('la pierna', 'het been', 'la PJER-na', 'Tengo las piernas cansadas.', 'Mijn benen zijn moe.', 'lichaam'),
   ('la nariz', 'neus', 'la na-RIS', 'Tengo la nariz fría.', 'Mijn neus is koud.', 'lichaam'),
   ('la boca', 'mond', 'la BO-ka', 'Abre la boca, por favor.', 'Doe je mond open, alsjeblieft.', 'lichaam'),
   ('la espalda', 'rug', 'la es-PAL-da', 'Me duele la espalda.', 'Mijn rug doet pijn.', 'lichaam')]),
L(8, '🏠', 'Thuis', 'De kamers en delen van een huis.',
  'Er is / er zijn — hay', 'Het woord "hay" betekent zowel "er is" als "er zijn": Hay una cocina grande. Hay dos dormitorios. Het verandert nooit.',
  [('la casa', 'huis', 'la KA-sa', 'Mi casa es pequeña.', 'Mijn huis is klein.', 'thuis'),
   ('la cocina', 'keuken', 'la ko-SIE-na', 'La cocina está limpia.', 'De keuken is schoon.', 'thuis'),
   ('el dormitorio', 'slaapkamer', 'el dor-mi-TO-rjo', 'Hay dos dormitorios.', 'Er zijn twee slaapkamers.', 'thuis'),
   ('el baño', 'badkamer', 'el BA-njo', '¿Dónde está el baño?', 'Waar is de badkamer?', 'thuis'),
   ('la habitación', 'de kamer', 'la a-bi-ta-SJON', 'Mi habitación tiene una ventana grande.', 'Mijn kamer heeft een groot raam.', 'thuis'),
   ('la puerta', 'deur', 'la PWER-ta', 'Cierra la puerta, por favor.', 'Doe de deur dicht, alsjeblieft.', 'thuis'),
   ('la ventana', 'raam', 'la ven-TA-na', 'Abro la ventana.', 'Ik doe het raam open.', 'thuis'),
   ('la cama', 'bed', 'la KA-ma', 'La cama es muy cómoda.', 'Het bed is heel comfortabel.', 'thuis')]),
L(9, '🍝', 'Eten & drinken', 'De basis van eten en drinken.',
  'Onbepaald lidwoord: un, una', '"Un" voor mannelijke woorden (un café), "una" voor vrouwelijke (una cerveza). Meervoud: unos, unas (een paar).',
  [('el agua', 'water', 'el A-gwa', 'Un vaso de agua, por favor.', 'Een glas water, alstublieft.', 'eten'),
   ('el vino', 'wijn', 'el VIE-no', 'Un vino tinto, por favor.', 'Een rode wijn, alstublieft.', 'eten'),
   ('el café', 'koffie', 'el ka-FE', 'Tomo un café con leche.', 'Ik neem een koffie met melk.', 'eten'),
   ('el pan', 'brood', 'el pan', 'El pan está fresco.', 'Het brood is vers.', 'eten'),
   ('la tortilla', 'tortilla (aardappelomelet)', 'la tor-TIE-ja', 'La tortilla de patatas es mi plato favorito.', 'De aardappelomelet is mijn favoriete gerecht.', 'eten'),
   ('la paella', 'paella', 'la pa-E-ja', 'La paella es de Valencia.', 'Paella komt uit Valencia.', 'eten'),
   ('la fruta', 'fruit', 'la FROE-ta', 'Como fruta cada día.', 'Ik eet elke dag fruit.', 'eten'),
   ('la verdura', 'groente', 'la ver-DOE-ra', 'La verdura es sana.', 'Groente is gezond.', 'eten')]),
L(10, '🍽️', 'In het restaurant', 'Bestellen en betalen in een restaurant.',
  'Voorkeuren uitdrukken met "quisiera"', '"Quisiera" (ik zou graag willen) is de beleefde vorm van "quiero" (ik wil): Quisiera una mesa para dos. Ook heel gebruikelijk: "¿Me pone...?" (Geeft u mij...?).',
  [('la carta', 'menukaart', 'la KAR-ta', 'La carta, por favor.', 'De menukaart, alstublieft.', 'restaurant'),
   ('la cuenta', 'rekening', 'la KWEN-ta', 'La cuenta, por favor.', 'De rekening, alstublieft.', 'restaurant'),
   ('la mesa', 'tafel', 'la ME-sa', 'Una mesa para dos, por favor.', 'Een tafel voor twee, alstublieft.', 'restaurant'),
   ('el camarero', 'ober', 'el ka-ma-RE-ro', 'El camarero es muy amable.', 'De ober is heel vriendelijk.', 'restaurant'),
   ('pedir', 'bestellen', 'pe-DIER', '¿Qué vas a pedir?', 'Wat ga je bestellen?', 'restaurant'),
   ('el primer plato', 'voorgerecht', 'el pri-MER PLA-to', 'De primer plato, una sopa.', 'Als voorgerecht een soep.', 'restaurant'),
   ('el segundo plato', 'hoofdgerecht', 'el se-GOEN-do PLA-to', 'De segundo plato, pescado.', 'Als hoofdgerecht vis.', 'restaurant'),
   ('el postre', 'dessert', 'el POS-tre', 'De postre, flan.', 'Als dessert flan.', 'restaurant')]),
L(11, '🛍️', 'Winkelen', 'Woorden voor in de winkel en op de markt.',
  'Aanwijzende voornaamwoorden: este / ese / aquel', '"Este" is dit (dichtbij), "ese" is dat (bij de ander), "aquel" is dat daar (ver weg). Ze passen zich aan: esta camisa, estos zapatos.',
  [('la tienda', 'winkel', 'la TJEN-da', 'La tienda abre a las diez.', 'De winkel gaat om tien uur open.', 'winkelen'),
   ('el precio', 'prijs', 'el PRE-sjo', 'El precio es bueno.', 'De prijs is goed.', 'winkelen'),
   ('algo', 'iets', 'AL-go', 'Busco algo para mi madre.', 'Ik zoek iets voor mijn moeder.', 'winkelen'),
   ('caro', 'duur', 'KA-ro', 'Es demasiado caro.', 'Het is te duur.', 'winkelen'),
   ('el descuento', 'korting', 'el des-KWEN-to', '¿Hay descuento?', 'Is er korting?', 'winkelen'),
   ('comprar', 'kopen', 'kom-PRAR', 'Quiero comprar un regalo.', 'Ik wil een cadeau kopen.', 'winkelen'),
   ('pagar', 'betalen', 'pa-GAR', '¿Puedo pagar con tarjeta?', 'Kan ik met kaart betalen?', 'winkelen'),
   ('el mercado', 'markt', 'el mer-KA-do', 'El mercado es los sábados.', 'De markt is op zaterdag.', 'winkelen')]),
L(12, '👗', 'Kleding', 'Kledingstukken en maten.',
  'Meervoud van zelfstandige naamwoorden', 'Eindigt een woord op een klinker, dan krijgt het -s (camisa → camisas). Eindigt het op een medeklinker, dan -es (pantalón → pantalones).',
  [('el vestido', 'jurk', 'el ves-TIE-do', 'Un vestido azul.', 'Een blauwe jurk.', 'kleding'),
   ('la camisa', 'overhemd', 'la ka-MIE-sa', 'Una camisa blanca.', 'Een wit overhemd.', 'kleding'),
   ('los pantalones', 'broek', 'los pan-ta-LO-nes', 'Estos pantalones son cómodos.', 'Deze broek zit lekker.', 'kleding'),
   ('los zapatos', 'schoenen', 'los sa-PA-tos', 'Busco zapatos negros.', 'Ik zoek zwarte schoenen.', 'kleding'),
   ('el abrigo', 'jas', 'el a-BRIE-go', 'Hace frío, ponte el abrigo.', 'Het is koud, doe je jas aan.', 'kleding'),
   ('el sombrero', 'hoed', 'el som-BRE-ro', 'Un sombrero para el sol.', 'Een hoed tegen de zon.', 'kleding'),
   ('la talla', 'maat', 'la TA-ja', '¿Qué talla tiene?', 'Welke maat heeft u?', 'kleding'),
   ('el bolso', 'tas', 'el BOL-so', 'Un bolso de piel.', 'Een leren tas.', 'kleding')]),
L(13, '🚌', 'Transport', 'Vervoermiddelen en het station.',
  'Voorzetsels: en, con, a', '"En" = in/met (en tren, en Madrid), "con" = met (con mi amigo), "a" = naar (voy a Barcelona). Let op: a + el = al (voy al aeropuerto).',
  [('el tren', 'trein', 'el tren', 'El tren a Sevilla sale a las nueve.', 'De trein naar Sevilla vertrekt om negen uur.', 'transport'),
   ('el autobús', 'bus', 'el au-to-BOES', 'Tomo el autobús cada día.', 'Ik neem elke dag de bus.', 'transport'),
   ('el taxi', 'taxi', 'el TAK-si', 'Un taxi al hotel, por favor.', 'Een taxi naar het hotel, alstublieft.', 'transport'),
   ('el avión', 'vliegtuig', 'el a-VJON', 'El avión sale a las seis.', 'Het vliegtuig vertrekt om zes uur.', 'transport'),
   ('el coche', 'auto', 'el KO-tsje', 'Vamos en coche.', 'We gaan met de auto.', 'transport'),
   ('esperar', 'wachten', 'es-pe-RAR', 'Espero el tren.', 'Ik wacht op de trein.', 'transport'),
   ('la estación', 'station', 'la es-ta-SJON', 'La estación está cerca.', 'Het station is dichtbij.', 'transport'),
   ('el aeropuerto', 'vliegveld', 'el a-e-ro-PWER-to', 'Voy al aeropuerto en taxi.', 'Ik ga met de taxi naar het vliegveld.', 'transport')]),
L(14, '🏛️', 'In de stad', 'Belangrijke plekken in de stad.',
  'Waar is...? — ¿Dónde está?', 'Voor plaatsen gebruik je altijd "estar": ¿Dónde está la farmacia? Meervoud: ¿Dónde están los baños?',
  [('la plaza', 'plein', 'la PLA-sa', 'La Plaza Mayor es famosa.', 'De Plaza Mayor is beroemd.', 'stad'),
   ('la iglesia', 'kerk', 'la i-GLE-sja', 'La iglesia es antigua.', 'De kerk is oud.', 'stad'),
   ('el museo', 'museum', 'el moe-SE-o', 'El museo abre a las diez.', 'Het museum gaat om tien uur open.', 'stad'),
   ('el banco', 'bank', 'el BAN-ko', 'El banco cierra a las dos.', 'De bank sluit om twee uur.', 'stad'),
   ('la farmacia', 'apotheek', 'la far-MA-sja', '¿Dónde está la farmacia?', 'Waar is de apotheek?', 'stad'),
   ('el hospital', 'ziekenhuis', 'el os-pi-TAL', 'El hospital está lejos.', 'Het ziekenhuis is ver.', 'stad'),
   ('entrar', 'binnenkomen', 'en-TRAR', '¿Entramos en el museo?', 'Gaan we het museum binnen?', 'stad'),
   ('la gente', 'de mensen', 'la CHEN-te', 'Hay mucha gente en la plaza.', 'Er zijn veel mensen op het plein.', 'stad')]),
L(15, '⛅', 'Het weer', 'Over het weer praten.',
  'Weer uitdrukken met "hace" en "hay"', 'Voor het weer gebruik je vaak "hace": hace calor, hace frío, hace sol. Met "hay" zeg je dat iets er is: hay viento, hay nubes. Regenen is een werkwoord: llueve.',
  [('el sol', 'zon', 'el sol', 'Hoy hace sol.', 'Vandaag schijnt de zon.', 'weer'),
   ('la lluvia', 'regen', 'la JOE-vja', 'No me gusta la lluvia.', 'Ik hou niet van regen.', 'weer'),
   ('el viento', 'wind', 'el VJEN-to', 'Hay mucho viento.', 'Er is veel wind.', 'weer'),
   ('la nieve', 'sneeuw', 'la NJE-ve', 'La nieve es blanca.', 'De sneeuw is wit.', 'weer'),
   ('el calor', 'warmte / hitte', 'el ka-LOR', 'Hace mucho calor.', 'Het is heel warm.', 'weer'),
   ('el frío', 'koude', 'el FRIE-o', 'Hace frío en enero.', 'Het is koud in januari.', 'weer'),
   ('fuera', 'buiten', 'FWE-ra', 'Fuera llueve.', 'Buiten regent het.', 'weer'),
   ('la tormenta', 'onweer', 'la tor-MEN-ta', 'Esta noche hay tormenta.', 'Vannacht is er onweer.', 'weer')]),
L(16, '⏰', 'Tijdsaanduidingen', 'Delen van de dag en "nu".',
  'Hoe laat is het? — ¿Qué hora es?', 'Es la una (één uur), son las dos (twee uur). Halve uren: son las tres y media. Kwart: y cuarto / menos cuarto.',
  [('la mañana', 'ochtend', 'la ma-NJA-na', 'Por la mañana tomo café.', "'s Ochtends drink ik koffie.", 'tijd'),
   ('la tarde', 'middag', 'la TAR-de', 'Por la tarde trabajo.', "'s Middags werk ik.", 'tijd'),
   ('la noche', 'avond / nacht', 'la NO-tsje', 'Por la noche vemos la tele.', "'s Avonds kijken we tv.", 'tijd'),
   ('hoy', 'vandaag', 'oi', 'Hoy es lunes.', 'Vandaag is het maandag.', 'tijd'),
   ('mañana', 'morgen', 'ma-NJA-na', 'Mañana voy a Madrid.', 'Morgen ga ik naar Madrid.', 'tijd'),
   ('ahora', 'nu', 'a-O-ra', 'Ahora tengo tiempo.', 'Nu heb ik tijd.', 'tijd'),
   ('el mediodía', 'middag (twaalf uur)', 'el me-djo-DIE-a', 'Comemos al mediodía.', 'We eten om twaalf uur.', 'tijd'),
   ('la hora', 'het uur / de tijd', 'la O-ra', '¿Qué hora es?', 'Hoe laat is het?', 'tijd')]),
L(17, '📅', 'Dagen van de week', 'De zeven dagen.',
  'Dagen met lidwoord', 'Dagen zijn mannelijk en krijgen "el" als je "op" bedoelt: el lunes = op maandag. Meervoud "los lunes" = elke maandag. Geen hoofdletter.',
  [('el lunes', 'maandag', 'el LOE-nes', 'El lunes trabajo.', 'Op maandag werk ik.', 'tijd'),
   ('el martes', 'dinsdag', 'el MAR-tes', 'El martes tengo clase.', 'Op dinsdag heb ik les.', 'tijd'),
   ('el miércoles', 'woensdag', 'el MJER-ko-les', 'El miércoles voy al gimnasio.', 'Op woensdag ga ik naar de sportschool.', 'tijd'),
   ('el jueves', 'donderdag', 'el CHWE-ves', 'El jueves hay mercado.', 'Op donderdag is er markt.', 'tijd'),
   ('el viernes', 'vrijdag', 'el VJER-nes', 'El viernes salimos.', 'Op vrijdag gaan we uit.', 'tijd'),
   ('el sábado', 'zaterdag', 'el SA-ba-do', 'El sábado descanso.', 'Op zaterdag rust ik uit.', 'tijd'),
   ('el domingo', 'zondag', 'el do-MIN-go', 'El domingo comemos en familia.', 'Op zondag eten we met de familie.', 'tijd'),
   ('la semana', 'week', 'la se-MA-na', 'La semana que viene.', 'Volgende week.', 'tijd')]),
L(18, '🌸', 'Maanden & seizoenen', 'Maanden en seizoenen benoemen.',
  'En + maand / seizoen', '"En enero" (in januari), "en verano" (in de zomer). Maanden hebben geen hoofdletter en geen lidwoord.',
  [('enero', 'januari', 'e-NE-ro', 'En enero hace frío.', 'In januari is het koud.', 'tijd'),
   ('febrero', 'februari', 'fe-BRE-ro', 'Febrero es corto.', 'Februari is kort.', 'tijd'),
   ('marzo', 'maart', 'MAR-so', 'En marzo empieza la primavera.', 'In maart begint de lente.', 'tijd'),
   ('junio', 'juni', 'CHOE-njo', 'En junio termina la escuela.', 'In juni eindigt de school.', 'tijd'),
   ('agosto', 'augustus', 'a-GOS-to', 'En agosto vamos a la playa.', 'In augustus gaan we naar het strand.', 'tijd'),
   ('el verano', 'zomer', 'el ve-RA-no', 'Me encanta el verano.', 'Ik ben dol op de zomer.', 'tijd'),
   ('el invierno', 'winter', 'el in-VJER-no', 'En invierno nieva.', 'In de winter sneeuwt het.', 'tijd'),
   ('la primavera', 'lente', 'la pri-ma-VE-ra', 'La primavera es bonita.', 'De lente is mooi.', 'tijd')]),
L(19, '🎭', 'Vrije tijd & hobby\'s', 'Vertellen wat je leuk vindt.',
  'Me gusta — ik vind het leuk', '"Me gusta" + enkelvoud of werkwoord (me gusta leer), "me gustan" + meervoud (me gustan los libros). Letterlijk: het bevalt mij.',
  [('leer', 'lezen', 'le-ER', 'Me gusta leer por la noche.', "Ik lees graag 's avonds.", 'vrije tijd'),
   ('la música', 'muziek', 'la MOE-si-ka', 'Escucho música española.', 'Ik luister naar Spaanse muziek.', 'vrije tijd'),
   ('el cine', 'bioscoop', 'el SIE-ne', 'Vamos al cine el sábado.', 'We gaan zaterdag naar de bioscoop.', 'vrije tijd'),
   ('viajar', 'reizen', 'vja-CHAR', 'Me encanta viajar.', 'Ik ben dol op reizen.', 'vrije tijd'),
   ('cocinar', 'koken', 'ko-si-NAR', 'Cocino los domingos.', 'Ik kook op zondag.', 'vrije tijd'),
   ('bailar', 'dansen', 'bai-LAR', '¿Te gusta bailar?', 'Dans je graag?', 'vrije tijd'),
   ('el libro', 'het boek', 'el LIE-bro', 'Leo un libro.', 'Ik lees een boek.', 'vrije tijd'),
   ('el deporte', 'sport', 'el de-POR-te', 'El deporte es sano.', 'Sport is gezond.', 'vrije tijd')]),
L(20, '⛵', 'Sport & natuur', 'Sport en de natuur om je heen.',
  'Hacer deporte — sport doen', '"Hacer deporte" is sporten. Voor een balsport gebruik je "jugar a": juego al fútbol. Let op de klinkerwisseling: jugar → juego.',
  [('el fútbol', 'voetbal', 'el FOET-bol', 'Juego al fútbol los sábados.', 'Ik voetbal op zaterdag.', 'sport'),
   ('nadar', 'zwemmen', 'na-DAR', 'Nado en el mar.', 'Ik zwem in zee.', 'sport'),
   ('correr', 'hardlopen', 'ko-RRER', 'Corro por la mañana.', "Ik loop 's ochtends hard.", 'sport'),
   ('fuerte', 'sterk', 'FWER-te', '¡Eres muy fuerte!', 'Je bent heel sterk!', 'sport'),
   ('el mar', 'zee', 'el mar', 'El mar está tranquilo.', 'De zee is rustig.', 'natuur'),
   ('la montaña', 'berg', 'la mon-TA-nja', 'Vamos a la montaña.', 'We gaan naar de bergen.', 'natuur'),
   ('el lago', 'meer', 'el LA-go', 'El lago es muy bonito.', 'Het meer is heel mooi.', 'natuur'),
   ('la playa', 'strand', 'la PLA-ja', 'La playa está llena.', 'Het strand is vol.', 'natuur')]),
L(21, '🛒', 'De markt', 'Boodschappen doen op de markt.',
  'Hoeveelheden: un kilo de, medio kilo de', 'Op de markt vraag je met "de": un kilo de tomates, medio kilo de queso, un litro de leche. "¿Algo más?" (Nog iets?) — "No, nada más."',
  [('el tomate', 'tomaat', 'el to-MA-te', 'Un kilo de tomates, por favor.', 'Een kilo tomaten, alstublieft.', 'eten'),
   ('la manzana', 'appel', 'la man-SA-na', 'Las manzanas están dulces.', 'De appels zijn zoet.', 'eten'),
   ('la leche', 'de melk', 'la LE-tsje', 'Un litro de leche.', 'Een liter melk.', 'eten'),
   ('el queso', 'kaas', 'el KE-so', 'El queso manchego es famoso.', 'Manchego-kaas is beroemd.', 'eten'),
   ('el jamón', 'ham', 'el cha-MON', 'Cien gramos de jamón serrano.', 'Honderd gram serranoham.', 'eten'),
   ('el huevo', 'ei', 'el WE-vo', 'Una docena de huevos.', 'Een dozijn eieren.', 'eten'),
   ('fresco', 'vers', 'FRES-ko', 'El pescado está fresco.', 'De vis is vers.', 'eten'),
   ('la bolsa', 'tas / zak', 'la BOL-sa', '¿Quiere una bolsa?', 'Wilt u een tas?', 'winkelen')]),
L(22, '🎨', 'Meer kleuren', 'Extra kleuren en beschrijvingen.',
  'Kleuren die nooit veranderen', 'Kleuren die van een voorwerp komen (naranja, rosa, violeta) veranderen niet mee: los coches naranja. "Claro" en "oscuro" blijven ook gelijk: azul claro, verde oscuro.',
  [('gris', 'grijs', 'gris', 'El cielo está gris.', 'De lucht is grijs.', 'kleuren'),
   ('marrón', 'bruin', 'ma-RRON', 'Unos zapatos marrones.', 'Bruine schoenen.', 'kleuren'),
   ('claro', 'licht (van kleur)', 'KLA-ro', 'Un azul claro.', 'Een lichtblauw.', 'kleuren'),
   ('oscuro', 'donker', 'os-KOE-ro', 'Un verde oscuro.', 'Een donkergroen.', 'kleuren'),
   ('morado', 'paars', 'mo-RA-do', 'Una flor morada.', 'Een paarse bloem.', 'kleuren'),
   ('de rayas', 'gestreept', 'de RA-jas', 'Una camiseta de rayas.', 'Een gestreept T-shirt.', 'kleuren'),
   ('de lunares', 'gestippeld', 'de loe-NA-res', 'Un vestido de lunares.', 'Een gestippelde jurk.', 'kleuren'),
   ('brillante', 'helder / glanzend', 'bri-JAN-te', 'Un color brillante.', 'Een heldere kleur.', 'kleuren')]),
L(23, '👗', 'Kleding 2', 'Meer kleding en je aankleden.',
  'Wederkerende werkwoorden: vestirse, ponerse', 'Me visto (ik kleed me aan), te vistes, se viste. "Ponerse" is aantrekken: me pongo el abrigo. Het voornaamwoord staat vóór het werkwoord.',
  [('la chaqueta', 'jasje / colbert', 'la tsja-KE-ta', 'Una chaqueta elegante.', 'Een elegant jasje.', 'kleding'),
   ('la falda', 'rok', 'la FAL-da', 'Una falda larga.', 'Een lange rok.', 'kleding'),
   ('la camiseta', 'T-shirt', 'la ka-mi-SE-ta', 'Una camiseta de algodón.', 'Een katoenen T-shirt.', 'kleding'),
   ('los calcetines', 'sokken', 'los kal-se-TIE-nes', 'Calcetines de lana.', 'Wollen sokken.', 'kleding'),
   ('la gorra', 'pet', 'la GO-rra', 'Una gorra para el sol.', 'Een pet tegen de zon.', 'kleding'),
   ('las gafas', 'bril', 'las GA-fas', 'Llevo gafas de sol.', 'Ik draag een zonnebril.', 'kleding'),
   ('ponerse', 'aantrekken', 'po-NER-se', 'Me pongo el abrigo.', 'Ik trek mijn jas aan.', 'kleding'),
   ('vestirse', 'zich aankleden', 'ves-TIER-se', 'Me visto rápido.', 'Ik kleed me snel aan.', 'kleding')]),
L(24, '🫁', 'Het lichaam 2', 'Meer lichaamsdelen en pijn.',
  'Pijn uitdrukken: me duele / me duelen', '"Me duele la cabeza" (mijn hoofd doet pijn), "me duelen los pies" (mijn voeten doen pijn). Het werkwoord past zich aan het lichaamsdeel aan, niet aan de persoon.',
  [('el brazo', 'arm', 'el BRA-so', 'Me duele el brazo.', 'Mijn arm doet pijn.', 'lichaam'),
   ('la rodilla', 'knie', 'la ro-DIE-ja', 'Me duele la rodilla.', 'Mijn knie doet pijn.', 'lichaam'),
   ('la garganta', 'keel', 'la gar-GAN-ta', 'Me duele la garganta.', 'Mijn keel doet pijn.', 'lichaam'),
   ('el estómago', 'maag / buik', 'el es-TO-ma-go', 'Me duele el estómago.', 'Ik heb buikpijn.', 'lichaam'),
   ('la cara', 'het gezicht', 'la KA-ra', 'Me lavo la cara.', 'Ik was mijn gezicht.', 'lichaam'),
   ('oír', 'horen', 'o-IER', 'No oigo bien.', 'Ik hoor niet goed.', 'lichaam'),
   ('el diente', 'tand', 'el DJEN-te', 'Me duele un diente.', 'Een tand doet pijn.', 'lichaam'),
   ('cansado', 'moe', 'kan-SA-do', 'Estoy muy cansado.', 'Ik ben heel moe.', 'lichaam')]),
L(25, '🌤️', 'Het weer 2', 'Weersvoorspelling en seizoenen.',
  'Onpersoonlijke werkwoorden voor het weer', 'Llueve (het regent), nieva (het sneeuwt), hace viento (het waait). Deze werkwoorden staan altijd in de derde persoon.',
  [('la nube', 'wolk', 'la NOE-be', 'Hay muchas nubes.', 'Er zijn veel wolken.', 'weer'),
   ('llover', 'regenen', 'jo-VER', 'Mañana va a llover.', 'Morgen gaat het regenen.', 'weer'),
   ('la niebla', 'mist', 'la NJE-bla', 'Hay niebla en la carretera.', 'Er is mist op de weg.', 'weer'),
   ('nevar', 'sneeuwen', 'ne-VAR', 'En la sierra nieva.', 'In de bergen sneeuwt het.', 'weer'),
   ('despejado', 'helder / onbewolkt', 'des-pe-CHA-do', 'El cielo está despejado.', 'De lucht is onbewolkt.', 'weer'),
   ('húmedo', 'vochtig', 'OE-me-do', 'El aire está húmedo.', 'De lucht is vochtig.', 'weer'),
   ('el pronóstico', 'weersvoorspelling', 'el pro-NOS-ti-ko', 'El pronóstico es bueno.', 'De weersvoorspelling is goed.', 'weer'),
   ('la temperatura', 'temperatuur', 'la tem-pe-ra-TOE-ra', 'La temperatura baja por la noche.', "'s Nachts daalt de temperatuur.", 'weer')]),
L(26, '🎵', "Hobby's 2", 'Meer vrijetijdsactiviteiten.',
  'Me gusta + infinitief of zelfstandig naamwoord', '"Me gusta pintar" (ik schilder graag), "me gusta el jardín". Om sterker te zeggen: "me encanta". Vragen: ¿Qué te gusta hacer?',
  [('la fotografía', 'fotografie', 'la fo-to-gra-FIE-a', 'La fotografía es mi hobby.', 'Fotografie is mijn hobby.', 'vrije tijd'),
   ('pintar', 'schilderen', 'pin-TAR', 'Pinto los fines de semana.', 'Ik schilder in het weekend.', 'vrije tijd'),
   ('interesante', 'interessant', 'in-te-re-SAN-te', 'El libro es interesante.', 'Het boek is interessant.', 'vrije tijd'),
   ('dibujar', 'tekenen', 'di-boe-CHAR', 'Me gusta dibujar.', 'Ik teken graag.', 'vrije tijd'),
   ('divertido', 'grappig / leuk', 'di-ver-TIE-do', 'La película es divertida.', 'De film is grappig.', 'vrije tijd'),
   ('jugar a las cartas', 'kaarten spelen', 'choe-GAR a las KAR-tas', 'Jugamos a las cartas.', 'We spelen kaarten.', 'vrije tijd'),
   ('el jardín', 'tuin', 'el char-DIEN', 'Trabajo en el jardín.', 'Ik werk in de tuin.', 'vrije tijd'),
   ('descansar', 'rusten', 'des-kan-SAR', 'Los domingos descanso.', 'Op zondag rust ik uit.', 'vrije tijd')]),
L(27, '🚌', 'Vervoer 2', 'Reizen met trein en metro.',
  'Ir a / ir en', '"Ir a" + bestemming: voy a Madrid. "Ir en" + vervoermiddel: voy en tren. Uitzondering: a pie (te voet).',
  [('el billete', 'kaartje / ticket', 'el bi-JE-te', 'Un billete de ida y vuelta.', 'Een retourtje.', 'transport'),
   ('la parada', 'halte', 'la pa-RA-da', 'La parada está aquí.', 'De halte is hier.', 'transport'),
   ('el andén', 'perron', 'el an-DEN', 'El tren sale del andén dos.', 'De trein vertrekt van perron twee.', 'transport'),
   ('el horario', 'dienstregeling', 'el o-RA-rjo', '¿Tiene el horario?', 'Heeft u de dienstregeling?', 'transport'),
   ('el retraso', 'vertraging', 'el re-TRA-so', 'El tren lleva retraso.', 'De trein heeft vertraging.', 'transport'),
   ('el metro', 'metro', 'el ME-tro', 'Vamos en metro.', 'We gaan met de metro.', 'transport'),
   ('salir', 'vertrekken', 'sa-LIER', 'El autobús sale ahora.', 'De bus vertrekt nu.', 'transport'),
   ('llegar', 'aankomen', 'je-GAR', 'Llegamos a las tres.', 'We komen om drie uur aan.', 'transport')]),
L(28, '🏠', 'Huis & meubels', 'Meubels en waar ze staan.',
  'Voorzetsels van plaats: en, sobre, debajo de, delante de', 'El libro está en la mesa (op/in), sobre la mesa (op), debajo de la cama (onder), delante de la puerta (voor), detrás de (achter).',
  [('dentro', 'binnen', 'DEN-tro', 'Dentro hace calor.', 'Binnen is het warm.', 'thuis'),
   ('el sofá', 'bank (meubel)', 'el so-FA', 'El sofá es cómodo.', 'De bank is comfortabel.', 'thuis'),
   ('la silla', 'stoel', 'la SIE-ja', 'Siéntate en la silla.', 'Ga op de stoel zitten.', 'thuis'),
   ('el armario', 'kast', 'el ar-MA-rjo', 'La ropa está en el armario.', 'De kleren liggen in de kast.', 'thuis'),
   ('la lámpara', 'lamp', 'la LAM-pa-ra', 'Enciende la lámpara.', 'Doe de lamp aan.', 'thuis'),
   ('el espejo', 'spiegel', 'el es-PE-cho', 'Hay un espejo en el baño.', 'Er hangt een spiegel in de badkamer.', 'thuis'),
   ('el salón', 'woonkamer', 'el sa-LON', 'Vemos la tele en el salón.', 'We kijken tv in de woonkamer.', 'thuis'),
   ('la nevera', 'koelkast', 'la ne-VE-ra', 'La leche está en la nevera.', 'De melk staat in de koelkast.', 'thuis')]),
L(29, '📅', 'Kalender & afspraken', 'Data en afspraken maken.',
  'Data uitdrukken: el + getal + de + maand', 'Hoy es el quince de marzo. De eerste dag: el uno (of el primero) de mayo. Vragen: ¿Qué día es hoy?',
  [('ayer', 'gisteren', 'a-JER', 'Ayer fue domingo.', 'Gisteren was het zondag.', 'tijd'),
   ('el mes', 'maand', 'el mes', 'El mes que viene.', 'Volgende maand.', 'tijd'),
   ('el año', 'jaar', 'el A-njo', 'Este año viajo a España.', 'Dit jaar reis ik naar Spanje.', 'tijd'),
   ('el cumpleaños', 'verjaardag', 'el koem-ple-A-njos', 'Mi cumpleaños es en mayo.', 'Mijn verjaardag is in mei.', 'tijd'),
   ('la fecha', 'datum', 'la FE-tsja', '¿Qué fecha es hoy?', 'Welke datum is het vandaag?', 'tijd'),
   ('el fin de semana', 'het weekend', 'el fin de se-MA-na', 'El fin de semana vamos al mar.', 'In het weekend gaan we naar zee.', 'tijd'),
   ('la cita', 'de afspraak', 'la SIE-ta', 'Tengo una cita a las tres.', 'Ik heb om drie uur een afspraak.', 'tijd'),
   ('pronto', 'binnenkort / snel', 'PRON-to', '¡Hasta pronto!', 'Tot gauw!', 'tijd')]),
L(30, '😊', 'Gevoelens', 'Zeggen hoe je je voelt.',
  'Estar + bijvoeglijk naamwoord voor gemoedstoestand', 'Voor tijdelijke gevoelens gebruik je "estar": estoy contento, estás triste, está enfadada. Het bijvoeglijk naamwoord past zich aan: contento/contenta.',
  [('feliz', 'gelukkig', 'fe-LIS', 'Soy muy feliz aquí.', 'Ik ben hier heel gelukkig.', 'gevoelens'),
   ('triste', 'verdrietig', 'TRIS-te', 'Hoy estoy triste.', 'Vandaag ben ik verdrietig.', 'gevoelens'),
   ('enfadado', 'boos', 'en-fa-DA-do', '¿Por qué estás enfadado?', 'Waarom ben je boos?', 'gevoelens'),
   ('sorprendido', 'verrast', 'sor-pren-DIE-do', 'Estoy sorprendida.', 'Ik ben verrast.', 'gevoelens'),
   ('tranquilo', 'rustig', 'tran-KIE-lo', 'Tranquilo, no pasa nada.', 'Rustig maar, er is niets aan de hand.', 'gevoelens'),
   ('reír', 'lachen', 're-IER', 'Me río mucho contigo.', 'Ik lach veel met jou.', 'gevoelens'),
   ('preocupado', 'bezorgd', 'pre-o-koe-PA-do', 'Estoy preocupado por ti.', 'Ik maak me zorgen om je.', 'gevoelens'),
   ('llorar', 'huilen', 'jo-RAR', 'El niño llora.', 'Het kind huilt.', 'gevoelens')]),
L(31, '🏨', 'Hotel & verblijf', 'Inchecken en vragen stellen in het hotel.',
  'Poder — kunnen / mogen', '"¿Puedo...?" (mag ik) en "¿Puede...?" (kunt u) zijn de beleefde manier om iets te vragen: ¿Puede ayudarme? Let op: poder → puedo, puedes, puede.',
  [('el hotel', 'hotel', 'el o-TEL', 'El hotel está en el centro.', 'Het hotel ligt in het centrum.', 'hotel'),
   ('la reserva', 'reservering', 'la re-SER-va', 'Tengo una reserva.', 'Ik heb een reservering.', 'hotel'),
   ('la llave', 'sleutel', 'la JA-ve', 'La llave de la habitación.', 'De sleutel van de kamer.', 'hotel'),
   ('el ascensor', 'lift', 'el as-sen-SOR', 'El ascensor no funciona.', 'De lift werkt niet.', 'hotel'),
   ('el desayuno', 'ontbijt', 'el de-sa-JOE-no', '¿A qué hora es el desayuno?', 'Hoe laat is het ontbijt?', 'hotel'),
   ('la piscina', 'zwembad', 'la pis-SIE-na', 'La piscina abre a las nueve.', 'Het zwembad gaat om negen uur open.', 'hotel'),
   ('la recepción', 'receptie', 'la re-sep-SJON', 'Pregunte en recepción.', 'Vraag het bij de receptie.', 'hotel'),
   ('el equipaje', 'bagage', 'el e-ki-PA-che', 'Mi equipaje está en el taxi.', 'Mijn bagage staat in de taxi.', 'hotel')]),
L(32, '🚨', 'Noodgevallen', 'Hulp vragen in een noodsituatie.',
  'De gebiedende wijs in noodgevallen', '¡Llame a la policía! (Belt u de politie!) ¡Ayúdeme! (Help me!) Het noodnummer in Spanje is 112.',
  [('¡socorro!', 'help!', 'so-KO-rro', '¡Socorro! ¡Ayuda!', 'Help! Hulp!', 'nood'),
   ('la policía', 'politie', 'la po-li-SIE-a', 'Llame a la policía.', 'Bel de politie.', 'nood'),
   ('la ambulancia', 'ambulance', 'la am-boe-LAN-sja', 'Necesitamos una ambulancia.', 'We hebben een ambulance nodig.', 'nood'),
   ('el médico', 'dokter', 'el ME-di-ko', 'Necesito un médico.', 'Ik heb een dokter nodig.', 'nood'),
   ('la emergencia', 'noodgeval', 'la e-mer-CHEN-sja', 'Es una emergencia.', 'Het is een noodgeval.', 'nood'),
   ('alguien', 'iemand', 'AL-gjen', '¡Que alguien llame a un médico!', 'Iemand moet een dokter bellen!', 'nood'),
   ('estoy perdido', 'ik ben verdwaald', 'es-TOI per-DIE-do', 'Perdón, estoy perdido.', 'Sorry, ik ben verdwaald.', 'nood'),
   ('urgencias', 'spoedeisende hulp', 'oer-CHEN-sjas', 'Vamos a urgencias.', 'We gaan naar de spoedeisende hulp.', 'nood')]),
L(33, '🏥', 'Gezondheid', 'Klachten uitleggen bij de dokter.',
  'Tener + klacht', 'Tengo fiebre (ik heb koorts), tengo dolor de cabeza (ik heb hoofdpijn), tengo frío. Zich voelen: me siento mal / bien.',
  [('el dolor', 'pijn', 'el do-LOR', 'Tengo dolor de espalda.', 'Ik heb rugpijn.', 'gezondheid'),
   ('la fiebre', 'koorts', 'la FJE-bre', 'Tengo fiebre.', 'Ik heb koorts.', 'gezondheid'),
   ('el dolor de cabeza', 'hoofdpijn', 'el do-LOR de ka-BE-sa', 'Tengo dolor de cabeza.', 'Ik heb hoofdpijn.', 'gezondheid'),
   ('las náuseas', 'misselijkheid', 'las NAU-se-as', 'Tengo náuseas.', 'Ik ben misselijk.', 'gezondheid'),
   ('la medicina', 'medicijn', 'la me-di-SIE-na', 'Tomo la medicina por la mañana.', "Ik neem het medicijn 's ochtends.", 'gezondheid'),
   ('el doctor', 'de dokter, de arts', 'el dok-TOR', 'El doctor llega a las diez.', 'De dokter komt om tien uur.', 'gezondheid'),
   ('el dentista', 'tandarts', 'el den-TIS-ta', 'Voy al dentista mañana.', 'Ik ga morgen naar de tandarts.', 'gezondheid'),
   ('me siento mal', 'ik voel me ziek', 'me SJEN-to mal', 'Hoy me siento mal.', 'Vandaag voel ik me ziek.', 'gezondheid')]),
L(34, '✨', 'Beschrijvingen', 'Dingen en mensen beschrijven.',
  'Bijvoeglijk naamwoord na het zelfstandig naamwoord', 'In het Spaans staat het bijvoeglijk naamwoord meestal achter het woord: una casa grande, un coche nuevo. "Bueno" en "malo" kunnen ervoor: un buen día.',
  [('grande', 'groot', 'GRAN-de', 'Una ciudad grande.', 'Een grote stad.', 'beschrijvingen'),
   ('pequeño', 'klein', 'pe-KE-njo', 'Un pueblo pequeño.', 'Een klein dorp.', 'beschrijvingen'),
   ('bonito', 'mooi', 'bo-NIE-to', 'Una plaza bonita.', 'Een mooi plein.', 'beschrijvingen'),
   ('feo', 'lelijk', 'FE-o', 'Un edificio feo.', 'Een lelijk gebouw.', 'beschrijvingen'),
   ('nuevo', 'nieuw', 'NWE-vo', 'Un coche nuevo.', 'Een nieuwe auto.', 'beschrijvingen'),
   ('viejo', 'oud', 'VJE-cho', 'Un libro viejo.', 'Een oud boek.', 'beschrijvingen'),
   ('largo', 'lang', 'LAR-go', 'Un viaje largo.', 'Een lange reis.', 'beschrijvingen'),
   ('alto', 'hoog / lang (persoon)', 'AL-to', 'Mi hermano es muy alto.', 'Mijn broer is heel lang.', 'beschrijvingen')]),
L(35, '😊', 'Gevoelens 2', 'Diepere gevoelens uitdrukken.',
  'Me siento vs. Estoy', '"Me siento" (ik voel me) + bijvoeglijk naamwoord: me siento nervioso. "Estoy" werkt ook: estoy nervioso. "Tener miedo" is bang zijn.',
  [('el miedo', 'de angst', 'el MJE-do', 'Tengo miedo de la oscuridad.', 'Ik ben bang in het donker.', 'gevoelens'),
   ('enamorado', 'verliefd', 'e-na-mo-RA-do', 'Estoy enamorado de ella.', 'Ik ben verliefd op haar.', 'gevoelens'),
   ('nervioso', 'nerveus', 'ner-VJO-so', 'Estoy nervioso por el examen.', 'Ik ben nerveus voor het examen.', 'gevoelens'),
   ('contento', 'tevreden / blij', 'kon-TEN-to', 'Estoy muy contenta.', 'Ik ben heel blij.', 'gevoelens'),
   ('asustado', 'bang / geschrokken', 'a-soes-TA-do', 'El perro está asustado.', 'De hond is bang.', 'gevoelens'),
   ('preocuparse', 'zich zorgen maken', 'pre-o-koe-PAR-se', '¡No te preocupes!', 'Maak je geen zorgen!', 'gevoelens'),
   ('celoso', 'jaloers', 'se-LO-so', 'Está celoso de su hermano.', 'Hij is jaloers op zijn broer.', 'gevoelens'),
   ('confundido', 'verward', 'kon-foen-DIE-do', 'Estoy un poco confundido.', 'Ik ben een beetje in de war.', 'gevoelens')]),
L(36, '⚡', 'Werkwoorden in actie', 'De belangrijkste werkwoorden.',
  'Regelmatige werkwoorden: -ar, -er, -ir', 'Hablar: hablo, hablas, habla, hablamos, habláis, hablan. Comer: como, comes, come, comemos, coméis, comen. Vivir: vivo, vives, vive, vivimos, vivís, viven.',
  [('ir', 'gaan', 'ier', 'Voy a la playa.', 'Ik ga naar het strand.', 'werkwoorden'),
   ('venir', 'komen', 've-NIER', '¿Vienes a la fiesta?', 'Kom je naar het feest?', 'werkwoorden'),
   ('comer', 'eten', 'ko-MER', 'Comemos a las dos.', 'We eten om twee uur.', 'werkwoorden'),
   ('beber', 'drinken', 'be-BER', 'Bebo mucha agua.', 'Ik drink veel water.', 'werkwoorden'),
   ('dormir', 'slapen', 'dor-MIER', 'Duermo ocho horas.', 'Ik slaap acht uur.', 'werkwoorden'),
   ('hablar', 'praten / spreken', 'a-BLAR', 'Hablo un poco de español.', 'Ik spreek een beetje Spaans.', 'werkwoorden'),
   ('entender', 'begrijpen', 'en-ten-DER', 'No entiendo.', 'Ik begrijp het niet.', 'werkwoorden'),
   ('ayudar', 'helpen', 'a-joe-DAR', '¿Me puedes ayudar?', 'Kun je me helpen?', 'werkwoorden')]),
L(37, '💬', 'Nuttige uitdrukkingen', 'Korte zinnen die je elke dag gebruikt.',
  'Modale werkwoorden: querer, poder, tener que', 'Quiero (ik wil), puedo (ik kan), tengo que (ik moet) + infinitief: Tengo que trabajar. Quiero comer. ¿Puedo entrar?',
  [('quiero', 'ik wil', 'KJE-ro', 'Quiero un café.', 'Ik wil een koffie.', 'uitdrukkingen'),
   ('puedo', 'ik kan / mag ik', 'PWE-do', '¿Puedo pasar?', 'Mag ik erlangs?', 'uitdrukkingen'),
   ('tengo que', 'ik moet', 'TEN-go ke', 'Tengo que irme.', 'Ik moet gaan.', 'uitdrukkingen'),
   ('me gusta', 'ik vind het leuk', 'me GOES-ta', 'Me gusta mucho.', 'Ik vind het heel leuk.', 'uitdrukkingen'),
   ('necesito', 'ik heb nodig', 'ne-se-SIE-to', 'Necesito ayuda.', 'Ik heb hulp nodig.', 'uitdrukkingen'),
   ('decir', 'zeggen', 'de-SIER', '¿Cómo se dice "kaas" en español?', 'Hoe zeg je "kaas" in het Spaans?', 'uitdrukkingen'),
   ('¿dónde está?', 'waar is?', 'DON-de es-TA', '¿Dónde está el baño?', 'Waar is het toilet?', 'uitdrukkingen'),
   ('quisiera', 'ik zou graag willen', 'ki-SJE-ra', 'Quisiera una mesa para dos.', 'Ik zou graag een tafel voor twee willen.', 'uitdrukkingen')]),
L(38, '🗺️', 'Richting wijzen', 'De weg vragen en uitleggen.',
  'De weg uitleggen — werkwoorden', 'Siga todo recto (ga rechtdoor), gire a la izquierda (sla linksaf), cruce la plaza (steek het plein over). Beleefde gebiedende wijs op -a/-e.',
  [('a la izquierda', 'naar links', 'a la is-KJER-da', 'Gire a la izquierda.', 'Sla linksaf.', 'richting'),
   ('a la derecha', 'naar rechts', 'a la de-RE-tsja', 'El banco está a la derecha.', 'De bank is rechts.', 'richting'),
   ('todo recto', 'rechtdoor', 'TO-do REK-to', 'Siga todo recto.', 'Ga rechtdoor.', 'richting'),
   ('cerca', 'dichtbij', 'SER-ka', 'La estación está cerca.', 'Het station is dichtbij.', 'richting'),
   ('lejos', 'ver weg', 'LE-chos', '¿Está lejos el museo?', 'Is het museum ver?', 'richting'),
   ('aquí', 'hier', 'a-KIE', 'Estamos aquí.', 'We zijn hier.', 'richting'),
   ('allí', 'daar', 'a-JIE', 'La farmacia está allí.', 'De apotheek is daar.', 'richting'),
   ('detrás de', 'achter', 'de-TRAS de', 'Detrás de la iglesia.', 'Achter de kerk.', 'richting')]),
L(39, '🌿', 'De natuur', 'Landschap en natuur.',
  'Uitroepen met ¡Qué...!', '¡Qué bonito! (Wat mooi!), ¡Qué calor! (Wat een hitte!), ¡Qué paisaje! Let op de omgekeerde uitroeptekens aan het begin.',
  [('la puesta de sol', 'zonsondergang', 'la PWES-ta de sol', '¡Qué puesta de sol!', 'Wat een zonsondergang!', 'natuur'),
   ('el río', 'rivier', 'el RIE-o', 'El río pasa por la ciudad.', 'De rivier stroomt door de stad.', 'natuur'),
   ('la isla', 'eiland', 'la IS-la', 'Mallorca es una isla.', 'Mallorca is een eiland.', 'natuur'),
   ('el bosque', 'bos', 'el BOS-ke', 'Paseamos por el bosque.', 'We wandelen door het bos.', 'natuur'),
   ('el caballo', 'het paard', 'el ka-BA-jo', 'El caballo come hierba.', 'Het paard eet gras.', 'natuur'),
   ('el campo', 'platteland', 'el KAM-po', 'Vivo en el campo.', 'Ik woon op het platteland.', 'natuur'),
   ('la estrella', 'ster', 'la es-TRE-ja', 'Hay muchas estrellas.', 'Er zijn veel sterren.', 'natuur'),
   ('la flor', 'bloem', 'la flor', 'Una flor roja.', 'Een rode bloem.', 'natuur')]),
L(40, '✈️', 'Klaar voor vertrek! 🇪🇸', 'Vaste uitdrukkingen voor onderweg — je bent op de helft!',
  'Op de helft — goed bezig!', 'Je kent nu ruim 300 woorden. Deze uitdrukkingen hoor je overal in Spanje. ¡Buen viaje!',
  [('¡buen viaje!', 'goede reis!', 'bwen VJA-che', '¡Buen viaje y hasta pronto!', 'Goede reis en tot gauw!', 'uitdrukkingen'),
   ('¡qué bonito!', 'wat mooi!', 'ke bo-NIE-to', '¡Qué bonito es este pueblo!', 'Wat is dit dorp mooi!', 'uitdrukkingen'),
   ('echar de menos', 'missen', 'e-TSJAR de ME-nos', 'Te echo de menos.', 'Ik mis je.', 'uitdrukkingen'),
   ('tengo hambre', 'ik heb honger', 'TEN-go AM-bre', 'Tengo hambre, ¿comemos?', 'Ik heb honger, zullen we eten?', 'uitdrukkingen'),
   ('tengo sed', 'ik heb dorst', 'TEN-go sed', 'Tengo sed, un agua por favor.', 'Ik heb dorst, een water alstublieft.', 'uitdrukkingen'),
   ('¡mucha suerte!', 'veel succes!', 'MOE-tsja SWER-te', '¡Mucha suerte con el examen!', 'Veel succes met het examen!', 'uitdrukkingen'),
   ('¡hasta luego!', 'tot straks / tot ziens!', 'AS-ta LWE-go', '¡Hasta luego, nos vemos!', 'Tot straks, we zien elkaar!', 'uitdrukkingen'),
   ('la suerte', 'het geluk', 'la SWER-te', '¡Qué suerte tienes!', 'Wat heb jij een geluk!', 'uitdrukkingen')]),
L(41, '☕', 'In het café', 'Bestellen in een Spaanse bar.',
  'Bestellen — ¿Me pone...?', 'In een bar zeg je "¿Me pone un café?" of "Un café, por favor". Koffiesoorten: café solo (espresso), café con leche, cortado (met een beetje melk).',
  [('el té', 'thee', 'el te', 'Un té con limón.', 'Een thee met citroen.', 'eten'),
   ('el zumo', 'sap', 'el SOE-mo', 'Un zumo de naranja natural.', 'Een vers sinaasappelsap.', 'eten'),
   ('la cerveza', 'bier', 'la ser-VE-sa', 'Una cerveza fría, por favor.', 'Een koud biertje, alstublieft.', 'eten'),
   ('el café con leche', 'koffie met melk', 'el ka-FE kon LE-tsje', 'Un café con leche, por favor.', 'Een koffie met melk, alstublieft.', 'eten'),
   ('el churro', 'churro', 'el TSJOE-rro', 'Churros con chocolate.', 'Churros met chocolade.', 'eten'),
   ('el agua mineral', 'mineraalwater', 'el A-gwa mi-ne-RAL', 'Agua mineral sin gas.', 'Mineraalwater zonder prik.', 'eten'),
   ('la tapa', 'tapa (hapje)', 'la TA-pa', 'Una tapa de aceitunas.', 'Een hapje olijven.', 'eten'),
   ('la barra', 'de bar (toog)', 'la BA-rra', 'Tomamos algo en la barra.', 'We drinken iets aan de bar.', 'eten')]),
L(42, '🍝', 'En el restaurante', 'Een volledige maaltijd in Spanje.',
  'De maaltijdstructuur in Spanje', 'Spanjaarden lunchen laat (14–15 uur) en dineren rond 21–22 uur. Een "menú del día" is een vast dagmenu met primer plato, segundo plato en postre.',
  [('el menú del día', 'dagmenu', 'el me-NOE del DIE-a', 'El menú del día cuesta doce euros.', 'Het dagmenu kost twaalf euro.', 'restaurant'),
   ('rico', 'lekker', 'RIE-ko', '¡Qué rico está!', 'Wat is dit lekker!', 'restaurant'),
   ('la sopa', 'soep', 'la SO-pa', 'De primero, sopa.', 'Als eerste soep.', 'restaurant'),
   ('el pescado', 'vis', 'el pes-KA-do', 'Prefiero el pescado.', 'Ik heb liever vis.', 'restaurant'),
   ('la carne', 'vlees', 'la KAR-ne', 'No como carne.', 'Ik eet geen vlees.', 'restaurant'),
   ('el tenedor', 'de vork', 'el te-ne-DOR', 'Falta un tenedor.', 'Er ontbreekt een vork.', 'restaurant'),
   ('el plato', 'het bord / gerecht', 'el PLA-to', 'Este plato es típico de aquí.', 'Dit gerecht is typisch voor hier.', 'restaurant'),
   ('la cena', 'het avondeten', 'la SE-na', 'La cena es a las nueve.', 'Het avondeten is om negen uur.', 'restaurant')]),
L(43, '🚆', 'Vervoer', 'Treinen en vliegen in Spanje.',
  'Treinen in Spanje — Renfe & AVE', 'De hogesnelheidstrein heet AVE. Een kaartje koop je "de ida" (enkel) of "de ida y vuelta" (retour). Reserveren is vaak verplicht.',
  [('el billete de ida y vuelta', 'retourtje', 'el bi-JE-te de IE-da i VWEL-ta', 'Un billete de ida y vuelta a Sevilla.', 'Een retourtje naar Sevilla.', 'transport'),
   ('el minuto', 'de minuut', 'el mi-NOE-to', 'El tren sale en cinco minutos.', 'De trein vertrekt over vijf minuten.', 'tijd'),
   ('la vía', 'het spoor', 'la VIE-a', 'El tren sale de la vía tres.', 'De trein vertrekt van spoor drie.', 'transport'),
   ('el vuelo', 'vlucht', 'el VWE-lo', 'Mi vuelo es a las siete.', 'Mijn vlucht is om zeven uur.', 'transport'),
   ('la maleta', 'koffer', 'la ma-LE-ta', 'Mi maleta es azul.', 'Mijn koffer is blauw.', 'transport'),
   ('el asiento', 'stoel / zitplaats', 'el a-SJEN-to', 'Un asiento de ventana, por favor.', 'Een plaats bij het raam, alstublieft.', 'transport'),
   ('conducir', 'rijden, besturen', 'kon-doe-SIER', 'No sé conducir.', 'Ik kan niet autorijden.', 'transport'),
   ('el conductor', 'chauffeur / bestuurder', 'el kon-doek-TOR', 'El conductor es amable.', 'De chauffeur is vriendelijk.', 'transport')]),
L(44, '🏨', 'Hotel & verblijf 2', 'Beleefd vragen in het hotel.',
  'Formele verzoeken in het hotel', 'Met "usted" ben je beleefd: ¿Podría darme la llave? (Zou u mij de sleutel kunnen geven?) ¿Tiene una habitación libre?',
  [('reservar', 'reserveren', 're-ser-VAR', 'Quiero reservar una habitación.', 'Ik wil een kamer reserveren.', 'hotel'),
   ('la habitación doble', 'tweepersoonskamer', 'la a-bi-ta-SJON DO-ble', 'Una habitación doble, por favor.', 'Een tweepersoonskamer, alstublieft.', 'hotel'),
   ('la habitación individual', 'eenpersoonskamer', 'la a-bi-ta-SJON in-di-vi-DWAL', 'Una habitación individual para tres noches.', 'Een eenpersoonskamer voor drie nachten.', 'hotel'),
   ('la almohada', 'kussen', 'la al-mo-A-da', 'Necesito otra almohada.', 'Ik heb nog een kussen nodig.', 'hotel'),
   ('quedarse', 'blijven / verblijven', 'ke-DAR-se', 'Me quedo tres noches.', 'Ik blijf drie nachten.', 'hotel'),
   ('la toalla', 'handdoek', 'la to-A-ja', 'Necesito una toalla más.', 'Ik heb nog een handdoek nodig.', 'hotel'),
   ('el aire acondicionado', 'airconditioning', 'el AI-re a-kon-di-sjo-NA-do', 'El aire acondicionado no funciona.', 'De airconditioning werkt niet.', 'hotel'),
   ('el aparcamiento', 'de parkeerplaats', 'el a-par-ka-MJEN-to', '¿Hay aparcamiento?', 'Is er een parkeerplaats?', 'hotel')]),
L(45, '👨‍👩‍👧‍👦', 'Familie 2', 'De bredere familie.',
  'Bezittelijk voornaamwoord + familie', 'Mi abuelo, mis abuelos, tu tía, sus primos. "Los padres" betekent de ouders, "los hijos" de kinderen (zonen én dochters).',
  [('la familia', 'familie', 'la fa-MIE-lja', 'Mi familia es grande.', 'Mijn familie is groot.', 'familie'),
   ('el abuelo', 'opa', 'el a-BWE-lo', 'Mi abuelo tiene ochenta años.', 'Mijn opa is tachtig.', 'familie'),
   ('la abuela', 'oma', 'la a-BWE-la', 'Mi abuela cocina muy bien.', 'Mijn oma kookt heel goed.', 'familie'),
   ('los padres', 'de ouders', 'los PA-dres', 'Mis padres viven en Málaga.', 'Mijn ouders wonen in Málaga.', 'familie'),
   ('el tío', 'de oom', 'el TIE-o', 'Mi tío vive en Argentina.', 'Mijn oom woont in Argentinië.', 'familie'),
   ('la tía', 'de tante', 'la TIE-a', 'Mi tía es profesora.', 'Mijn tante is lerares.', 'familie'),
   ('el primo', 'de neef (kind van oom of tante)', 'el PRIE-mo', 'Mi primo estudia en Madrid.', 'Mijn neef studeert in Madrid.', 'familie'),
   ('el niño', 'het kind / de jongen', 'el NIE-njo', 'Los niños juegan en el parque.', 'De kinderen spelen in het park.', 'familie')]),
L(46, '🗺️', 'De weg vragen', 'De weg vragen aan een voorbijganger.',
  'Beleefde gebiedende wijs', 'Tegen onbekenden: siga (ga door), gire (sla af), cruce (steek over), tome (neem). Perdone, ¿cómo llego a la estación?',
  [('adelante', 'vooruit / verder', 'a-de-LAN-te', 'Siga adelante hasta la plaza.', 'Ga verder tot het plein.', 'richting'),
   ('parar', 'stoppen', 'pa-RAR', '¿Puede parar aquí?', 'Kunt u hier stoppen?', 'richting'),
   ('la calle', 'straat', 'la KA-je', 'Vivo en la calle Mayor.', 'Ik woon in de Calle Mayor.', 'richting'),
   ('la esquina', 'hoek', 'la es-KIE-na', 'El bar está en la esquina.', 'Het café is op de hoek.', 'richting'),
   ('girar', 'afslaan', 'chi-RAR', 'Gire a la derecha.', 'Sla rechtsaf.', 'richting'),
   ('cruzar', 'oversteken', 'kroe-SAR', 'Cruce la plaza.', 'Steek het plein over.', 'richting'),
   ('el puente', 'brug', 'el PWEN-te', 'Cruce el puente.', 'Steek de brug over.', 'richting'),
   ('enfrente de', 'tegenover', 'en-FREN-te de', 'Enfrente de la iglesia.', 'Tegenover de kerk.', 'richting')]),
L(47, '☀️', 'Het weer 3', 'Praten over het weer van vandaag.',
  'Weersuitdrukkingen met "hacer" en "estar"', 'Hace buen tiempo / mal tiempo. Está nublado (het is bewolkt), está lloviendo (het regent nu). ¿Qué tiempo hace?',
  [('el tiempo', 'weer', 'el TJEM-po', '¿Qué tiempo hace hoy?', 'Wat voor weer is het vandaag?', 'weer'),
   ('nublado', 'bewolkt', 'noe-BLA-do', 'Está nublado.', 'Het is bewolkt.', 'weer'),
   ('soleado', 'zonnig', 'so-le-A-do', 'Un día soleado.', 'Een zonnige dag.', 'weer'),
   ('el grado', 'graad', 'el GRA-do', 'Hace treinta grados.', 'Het is dertig graden.', 'weer'),
   ('el paraguas', 'paraplu', 'el pa-RA-gwas', 'Lleva el paraguas.', 'Neem de paraplu mee.', 'weer'),
   ('el día', 'de dag', 'el DIE-a', '¡Qué día tan bonito!', 'Wat een mooie dag!', 'tijd'),
   ('la sombra', 'schaduw', 'la SOM-bra', 'Nos sentamos a la sombra.', 'We gaan in de schaduw zitten.', 'weer'),
   ('el otoño', 'herfst', 'el o-TO-njo', 'En otoño llueve más.', 'In de herfst regent het meer.', 'weer')]),
L(48, '🏥', 'Gezondheid 2', 'Bij de apotheek.',
  'Pijn en klachten uitdrukken', 'Estoy resfriado (ik ben verkouden), tengo tos (ik hoest), soy alérgico a... (ik ben allergisch voor). Bij de apotheek: ¿Tiene algo para el dolor de cabeza?',
  [('el medicamento', 'medicijn', 'el me-di-ka-MEN-to', 'Un medicamento para la tos.', 'Een medicijn tegen hoest.', 'gezondheid'),
   ('la alergia', 'allergie', 'la a-LER-chja', 'Tengo alergia al polen.', 'Ik heb een pollenallergie.', 'gezondheid'),
   ('la tos', 'de hoest', 'la tos', 'Tengo tos desde ayer.', 'Ik hoest sinds gisteren.', 'gezondheid'),
   ('el resfriado', 'de verkoudheid', 'el res-FRJA-do', 'Tengo un resfriado.', 'Ik ben verkouden.', 'gezondheid'),
   ('la pastilla', 'pil / tablet', 'la pas-TIE-ja', 'Una pastilla cada ocho horas.', 'Elke acht uur een tablet.', 'gezondheid'),
   ('la receta', 'recept (medisch)', 'la re-SE-ta', 'Necesita receta.', 'Daar is een recept voor nodig.', 'gezondheid'),
   ('la salud', 'de gezondheid', 'la sa-LOED', '¡Salud!', 'Gezondheid! / Proost!', 'gezondheid'),
   ('sano', 'gezond', 'SA-no', 'Como sano.', 'Ik eet gezond.', 'gezondheid')]),
L(49, '🎭', "Activiteiten & hobby's", 'Hoe vaak doe je iets?',
  'Frequentie: siempre, a menudo, nunca', 'Siempre (altijd), a menudo (vaak), a veces (soms), nunca (nooit). "Nunca" met dubbele ontkenning: no voy nunca.',
  [('caminar', 'wandelen', 'ka-mi-NAR', 'Camino por el parque.', 'Ik wandel door het park.', 'activiteiten'),
   ('escuchar', 'luisteren', 'es-koe-TSJAR', 'Escucho música.', 'Ik luister naar muziek.', 'activiteiten'),
   ('ver', 'kijken / zien', 'ver', 'Veo la tele.', 'Ik kijk tv.', 'activiteiten'),
   ('hacer deporte', 'sporten', 'a-SER de-POR-te', 'Hago deporte tres veces por semana.', 'Ik sport drie keer per week.', 'activiteiten'),
   ('a menudo', 'vaak', 'a me-NOE-do', 'Voy a menudo a la piscina.', 'Ik ga vaak naar het zwembad.', 'activiteiten'),
   ('nunca', 'nooit', 'NOEN-ka', 'Nunca voy al gimnasio.', 'Ik ga nooit naar de sportschool.', 'activiteiten'),
   ('tocar', 'een instrument bespelen', 'to-KAR', 'Toco la guitarra.', 'Ik speel gitaar.', 'activiteiten'),
   ('estudiar', 'studeren, leren', 'es-toe-DJAR', 'Estudio español cada día.', 'Ik studeer elke dag Spaans.', 'activiteiten')]),
L(50, '📅', 'Plannen maken', 'Over de nabije toekomst praten.',
  'De nabije toekomst — ir a + infinitief', 'Voy a comer (ik ga eten), vamos a viajar (we gaan reizen). Zo praat je over plannen zonder de toekomende tijd te kennen.',
  [('empezar', 'beginnen', 'em-pe-SAR', 'El curso empieza el lunes.', 'De cursus begint maandag.', 'plannen'),
   ('próximo', 'volgende', 'PROK-si-mo', 'La próxima semana.', 'Volgende week.', 'plannen'),
   ('pasado', 'vorig', 'pa-SA-do', 'El año pasado.', 'Vorig jaar.', 'plannen'),
   ('temprano', 'vroeg', 'tem-PRA-no', 'Me levanto temprano.', 'Ik sta vroeg op.', 'plannen'),
   ('tarde', 'laat', 'TAR-de', 'Llegamos tarde.', 'We komen laat aan.', 'plannen'),
   ('juntos', 'samen', 'CHOEN-tos', 'Vamos juntos al cine.', 'We gaan samen naar de bioscoop.', 'plannen'),
   ('la idea', 'het idee', 'la i-DE-a', '¡Qué buena idea!', 'Wat een goed idee!', 'plannen'),
   ('por fin', 'eindelijk', 'por fin', '¡Por fin es viernes!', 'Eindelijk is het vrijdag!', 'plannen')]),
L(51, '✈️', 'De luchthaven', 'Op het vliegveld.',
  'Tener que + infinitief — verplichting', 'Tengo que facturar la maleta (ik moet de koffer inchecken). Tienes que enseñar el pasaporte. "Hay que" is onpersoonlijk: hay que esperar.',
  [('el pasaporte', 'paspoort', 'el pa-sa-POR-te', 'El pasaporte, por favor.', 'Uw paspoort, alstublieft.', 'reizen'),
   ('el equipaje de mano', 'handbagage', 'el e-ki-PA-che de MA-no', 'Solo llevo equipaje de mano.', 'Ik heb alleen handbagage.', 'reizen'),
   ('la puerta de embarque', 'gate', 'la PWER-ta de em-BAR-ke', 'La puerta de embarque es la B12.', 'De gate is B12.', 'reizen'),
   ('el control de pasaportes', 'paspoortcontrole', 'el kon-TROL de pa-sa-POR-tes', 'Hay cola en el control de pasaportes.', 'Er staat een rij bij de paspoortcontrole.', 'reizen'),
   ('embarcar', 'instappen / boarden', 'em-bar-KAR', 'Embarcamos a las ocho.', 'We boarden om acht uur.', 'reizen'),
   ('aterrizar', 'landen', 'a-te-rri-SAR', 'El avión aterriza a las diez.', 'Het vliegtuig landt om tien uur.', 'reizen'),
   ('despegar', 'opstijgen', 'des-pe-GAR', 'El avión despega ahora.', 'Het vliegtuig stijgt nu op.', 'reizen'),
   ('facturar', 'inchecken (bagage)', 'fak-toe-RAR', 'Tengo que facturar la maleta.', 'Ik moet mijn koffer inchecken.', 'reizen')]),
L(52, '🤒', 'Bij de dokter', 'Een gesprek bij de dokter.',
  'Desde hace + tijdsduur — hoe lang al?', 'Tengo fiebre desde hace dos días (ik heb al twee dagen koorts). ¿Desde cuándo? (Sinds wanneer?)',
  [('el síntoma', 'symptoom', 'el SIN-to-ma', '¿Qué síntomas tiene?', 'Welke klachten heeft u?', 'gezondheid'),
   ('la gripe', 'griep', 'la GRIE-pe', 'Tengo la gripe.', 'Ik heb griep.', 'gezondheid'),
   ('la farmacia de guardia', 'dienstapotheek', 'la far-MA-sja de GWAR-dja', '¿Dónde está la farmacia de guardia?', 'Waar is de dienstapotheek?', 'gezondheid'),
   ('el seguro', 'verzekering', 'el se-GOE-ro', 'Tengo seguro médico.', 'Ik heb een ziektekostenverzekering.', 'gezondheid'),
   ('la herida', 'wond', 'la e-RIE-da', 'La herida es pequeña.', 'De wond is klein.', 'gezondheid'),
   ('la vacuna', 'vaccin / inenting', 'la va-KOE-na', 'Necesito una vacuna.', 'Ik heb een vaccin nodig.', 'gezondheid'),
   ('curarse', 'genezen / herstellen', 'koe-RAR-se', 'Me curo rápido.', 'Ik herstel snel.', 'gezondheid'),
   ('la tirita', 'pleister', 'la ti-RIE-ta', 'Ponte una tirita.', 'Doe een pleister op.', 'gezondheid')]),
L(53, '💼', 'Beroepen', 'Vertellen wat je doet.',
  'Beroepen zonder lidwoord', 'Soy médico, es profesora (zonder "un/una"). Vrouwelijke vormen: el profesor / la profesora, el camarero / la camarera.',
  [('el trabajo', 'werk / baan', 'el tra-BA-cho', 'Me gusta mi trabajo.', 'Ik hou van mijn werk.', 'beroepen'),
   ('el profesor', 'leraar', 'el pro-fe-SOR', 'Mi padre es profesor.', 'Mijn vader is leraar.', 'beroepen'),
   ('el ingeniero', 'ingenieur', 'el in-che-NJE-ro', 'Soy ingeniero.', 'Ik ben ingenieur.', 'beroepen'),
   ('el cocinero', 'kok', 'el ko-si-NE-ro', 'Mi hermana es cocinera.', 'Mijn zus is kok.', 'beroepen'),
   ('el abogado', 'advocaat', 'el a-bo-GA-do', 'Es abogada en Barcelona.', 'Ze is advocaat in Barcelona.', 'beroepen'),
   ('el señor', 'de meneer, de heer', 'el se-NJOR', 'El señor García es mi jefe.', 'Meneer García is mijn baas.', 'beroepen'),
   ('el periodista', 'journalist', 'el pe-rjo-DIS-ta', 'Trabaja como periodista.', 'Ze werkt als journalist.', 'beroepen'),
   ('el sueldo', 'salaris', 'el SWEL-do', 'El sueldo es bueno.', 'Het salaris is goed.', 'beroepen')]),
L(54, '🌿', 'De natuur 2', 'Dieren en landschap.',
  'Vergelijkingen: más… que en -ísimo', 'El río es más largo que el lago (langer dan). Overtreffend: el más largo. Versterking met -ísimo: grandísimo, bellísimo.',
  [('el árbol', 'boom', 'el AR-bol', 'Un árbol muy alto.', 'Een heel hoge boom.', 'natuur'),
   ('el animal', 'dier', 'el a-ni-MAL', 'Me gustan los animales.', 'Ik hou van dieren.', 'natuur'),
   ('el perro', 'de hond', 'el PE-rro', 'El perro corre en el parque.', 'De hond rent in het park.', 'natuur'),
   ('el gato', 'de kat', 'el GA-to', 'El gato duerme al sol.', 'De kat slaapt in de zon.', 'natuur'),
   ('el pájaro', 'vogel', 'el PA-cha-ro', 'Los pájaros cantan.', 'De vogels zingen.', 'natuur'),
   ('el parque', 'park', 'el PAR-ke', 'Paseo por el parque.', 'Ik wandel door het park.', 'natuur'),
   ('la hierba', 'gras', 'la JER-ba', 'La hierba está verde.', 'Het gras is groen.', 'natuur'),
   ('el paisaje', 'landschap', 'el pai-SA-che', '¡Qué paisaje tan bonito!', 'Wat een mooi landschap!', 'natuur')]),
L(55, '💻', 'Technologie', 'Telefoon en internet.',
  'Beleefd vragen met podría', '¿Podría darme la contraseña del wifi? (Zou u mij het wifi-wachtwoord kunnen geven?) "Podría" is de beleefde vorm van "puede".',
  [('el ordenador', 'computer', 'el or-de-na-DOR', 'Trabajo con el ordenador.', 'Ik werk met de computer.', 'technologie'),
   ('la conexión', 'verbinding', 'la ko-nek-SJON', 'La conexión es lenta.', 'De verbinding is traag.', 'technologie'),
   ('el teléfono', 'de telefoon', 'el te-LE-fo-no', '¿Dónde está mi teléfono?', 'Waar is mijn telefoon?', 'technologie'),
   ('el móvil', 'mobiele telefoon', 'el MO-vil', 'Mi móvil no tiene batería.', 'Mijn mobiel is leeg.', 'technologie'),
   ('la contraseña', 'wachtwoord', 'la kon-tra-SE-nja', '¿Cuál es la contraseña del wifi?', 'Wat is het wifi-wachtwoord?', 'technologie'),
   ('enviar', 'versturen', 'en-VJAR', 'Te envío un mensaje.', 'Ik stuur je een bericht.', 'technologie'),
   ('el número', 'het nummer / getal', 'el NOE-me-ro', '¿Cuál es tu número?', 'Wat is jouw nummer?', 'technologie'),
   ('usar', 'gebruiken', 'oe-SAR', 'Uso el móvil para todo.', 'Ik gebruik mijn mobiel voor alles.', 'technologie')]),
L(56, '🎶', 'Muziek & cultuur', 'Uitgaan en cultuur.',
  'Verbindingswoorden: pero, también, entonces', 'Pero (maar), también (ook), entonces (dus/dan), porque (omdat). Me gusta el flamenco, pero también el rock.',
  [('el concierto', 'concert', 'el kon-SJER-to', 'Vamos a un concierto.', 'We gaan naar een concert.', 'cultuur'),
   ('el cantante', 'zanger', 'el kan-TAN-te', 'La cantante es famosa.', 'De zangeres is beroemd.', 'cultuur'),
   ('la canción', 'lied', 'la kan-SJON', 'Me encanta esta canción.', 'Ik ben dol op dit lied.', 'cultuur'),
   ('la fiesta', 'feest', 'la FJES-ta', 'La fiesta es el sábado.', 'Het feest is zaterdag.', 'cultuur'),
   ('el flamenco', 'flamenco', 'el fla-MEN-ko', 'El flamenco es de Andalucía.', 'Flamenco komt uit Andalusië.', 'cultuur'),
   ('el teatro', 'theater', 'el te-A-tro', 'El teatro está en el centro.', 'Het theater staat in het centrum.', 'cultuur'),
   ('la guitarra', 'gitaar', 'la gi-TA-rra', 'Toca la guitarra muy bien.', 'Hij speelt heel goed gitaar.', 'cultuur'),
   ('el ritmo', 'het ritme', 'el RIT-mo', 'Me gusta el ritmo.', 'Ik hou van het ritme.', 'cultuur')]),
L(57, '⚽', 'Sport gevorderd', 'Voetbal en wedstrijden.',
  'Dagelijkse routine: wederkerende werkwoorden', 'Me levanto (ik sta op), me ducho (ik douche), me acuesto (ik ga naar bed). Vóór het werkwoord: me, te, se, nos, os, se.',
  [('el equipo', 'team', 'el e-KIE-po', 'Mi equipo favorito es el Betis.', 'Mijn favoriete team is Betis.', 'sport'),
   ('el partido', 'wedstrijd', 'el par-TIE-do', 'El partido es el domingo.', 'De wedstrijd is zondag.', 'sport'),
   ('el juego', 'het spel', 'el CHWE-go', 'El fútbol es un juego de equipo.', 'Voetbal is een teamspel.', 'sport'),
   ('ganar', 'winnen', 'ga-NAR', 'Queremos ganar.', 'We willen winnen.', 'sport'),
   ('perder', 'verliezen', 'per-DER', 'Perdimos dos a uno.', 'We verloren met twee tegen één.', 'sport'),
   ('la pelota', 'de bal', 'la pe-LO-ta', '¡Pásame la pelota!', 'Geef me de bal!', 'sport'),
   ('el resultado', 'uitslag', 'el re-soel-TA-do', '¿Cuál es el resultado?', 'Wat is de uitslag?', 'sport'),
   ('el gol', 'doelpunt', 'el gol', '¡Gol!', 'Doelpunt!', 'sport')]),
L(58, '🌍', 'Reizen gevorderd', 'Op reis in Spanje en Latijns-Amerika.',
  'Voorkeur uitdrukken: preferir', 'Prefiero el tren (ik heb liever de trein). Prefiero viajar en verano. Let op: preferir → prefiero, prefieres, prefiere.',
  [('el país', 'het land', 'el pa-IES', '¿Qué país quieres visitar?', 'Welk land wil je bezoeken?', 'reizen'),
   ('el pueblo', 'het dorp', 'el PWE-blo', 'Un pueblo blanco de Andalucía.', 'Een wit dorp in Andalusië.', 'reizen'),
   ('el turista', 'toerist', 'el toe-RIS-ta', 'Hay muchos turistas.', 'Er zijn veel toeristen.', 'reizen'),
   ('el guía', 'gids', 'el GIE-a', 'El guía habla holandés.', 'De gids spreekt Nederlands.', 'reizen'),
   ('el mapa', 'kaart / plattegrond', 'el MA-pa', 'Tengo un mapa de la ciudad.', 'Ik heb een plattegrond van de stad.', 'reizen'),
   ('el recuerdo', 'souvenir / herinnering', 'el re-KWER-do', 'Un recuerdo para mi madre.', 'Een souvenir voor mijn moeder.', 'reizen'),
   ('la excursión', 'excursie / uitstapje', 'la eks-koer-SJON', 'Hacemos una excursión en barco.', 'We maken een boottocht.', 'reizen'),
   ('la aventura', 'avontuur', 'la a-ven-TOE-ra', '¡Qué aventura!', 'Wat een avontuur!', 'reizen')]),
L(59, '🛍️', 'Winkelen gevorderd', 'Passen, ruilen en betalen.',
  'Objectspronomen: lo, la, los, las', '¿La camisa? La quiero (ik wil hem). ¿Los zapatos? Los compro. Het voornaamwoord staat vóór het werkwoord.',
  [('el probador', 'paskamer', 'el pro-ba-DOR', '¿Dónde está el probador?', 'Waar is de paskamer?', 'winkelen'),
   ('el recibo', 'kassabon', 'el re-SIE-bo', 'Aquí tiene el recibo.', 'Hier is uw bon.', 'winkelen'),
   ('vender', 'verkopen', 'ven-DER', 'Venden fruta fresca.', 'Ze verkopen vers fruit.', 'winkelen'),
   ('ir de compras', 'winkelen', 'ier de KOM-pras', 'Vamos de compras el sábado.', 'We gaan zaterdag winkelen.', 'winkelen'),
   ('las rebajas', 'uitverkoop', 'las re-BA-chas', 'Las rebajas empiezan en enero.', 'De uitverkoop begint in januari.', 'winkelen'),
   ('probarse', 'passen (kleding)', 'pro-BAR-se', '¿Puedo probarme esto?', 'Mag ik dit passen?', 'winkelen'),
   ('la tarjeta', 'kaart (pinpas)', 'la tar-CHE-ta', 'Pago con tarjeta.', 'Ik betaal met kaart.', 'winkelen'),
   ('en efectivo', 'contant', 'en e-fek-TIE-vo', 'Pago en efectivo.', 'Ik betaal contant.', 'winkelen')]),
L(60, '🏛️', 'Stad & toerisme', 'Bezienswaardigheden en A1 afgerond!',
  'Handige vaste uitdrukkingen', 'Je hebt A1 afgerond: 60 lessen en 480 woorden. Onthoud: ¡Enhorabuena! (gefeliciteerd), ¡Vale! (oké), ¡No pasa nada! (geeft niet).',
  [('el lugar', 'de plaats, de plek', 'el loe-GAR', 'Es un lugar precioso.', 'Het is een prachtige plek.', 'stad'),
   ('la fuente', 'fontein', 'la FWEN-te', 'La fuente está en la plaza.', 'De fontein staat op het plein.', 'stad'),
   ('el palacio', 'paleis', 'el pa-LA-sjo', 'Visitamos el palacio real.', 'We bezoeken het koninklijk paleis.', 'stad'),
   ('la catedral', 'kathedraal', 'la ka-te-DRAL', 'La catedral es enorme.', 'De kathedraal is enorm.', 'stad'),
   ('el castillo', 'kasteel', 'el kas-TIE-jo', 'El castillo está en la colina.', 'Het kasteel ligt op de heuvel.', 'stad'),
   ('la vista', 'uitzicht', 'la VIS-ta', '¡Qué vista tan bonita!', 'Wat een mooi uitzicht!', 'stad'),
   ('el paseo', 'wandeling', 'el pa-SE-o', 'Damos un paseo por el centro.', 'We maken een wandeling door het centrum.', 'stad'),
   ('¡enhorabuena!', 'gefeliciteerd!', 'e-no-ra-BWE-na', '¡Enhorabuena, has terminado A1!', 'Gefeliciteerd, je hebt A1 afgerond!', 'uitdrukkingen')]),
]

# ── Validatie + schrijven ────────────────────────────────────────────────────
from collections import Counter
assert [l['id'] for l in LESSONS] == list(range(1, 61)), 'les-IDs'
vocab, curriculum = [], []
seen = Counter()
n = 1
for l in LESSONS:
    assert len(l['words']) == 8 or (l['id'] == 3 and len(l['words']) == 10), f"les {l['id']}: {len(l['words'])} woorden"
    ids = []
    for es, nl, ph, ex, exNl, cat in l['words']:
        seen[es.lower()] += 1
        wid = f'e{n:03d}'; n += 1
        vocab.append({'id': wid, 'it': es, 'nl': nl, 'ph': ph, 'ex': ex, 'exNl': exNl, 'lesson': l['id'], 'level': 'A1', 'cat': cat})
        ids.append(wid)
    curriculum.append({'id': l['id'], 'title': l['title'], 'emoji': l['emoji'], 'level': 'A1', 'description': l['description'],
                       'grammar': l['grammar'], 'words': ids})
dups = [k for k, c in seen.items() if c > 1]
assert not dups, f'dubbele woorden: {dups}'
OUT.mkdir(parents=True, exist_ok=True)
json.dump(vocab, open(OUT / 'vocabulary.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'vocabulary.json', 'a').write('\n')
json.dump(curriculum, open(OUT / 'curriculum.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'curriculum.json', 'a').write('\n')
print(f'Spaans A1: {len(curriculum)} lessen, {len(vocab)} woorden → {OUT}')
