"""B1-lessen 211–240 (blokken 10–12) voor Vocado.

Blok 10: Relaties & emoties verdieping (211–220)
Blok 11: Natuur, dieren & milieu (221–230)
Blok 12: Kunst, media & entertainment (231–240)

Bevat twee variabelen: LESSONS en WORDS.
Word-IDs: w1931–w2170 (240 woorden).
"""

# ── LESSEN ────────────────────────────────────────────────────────────────────

LESSONS = [
    # ═══ BLOK 10: RELATIES & EMOTIES VERDIEPING (211–220) ═════════════════════
    {
        "id": 211, "title": "Relaties & vriendschap", "emoji": "🤝", "level": "B1",
        "description": "Praat over vriendschappen en relaties.",
        "grammar": {
            "title": "Reflexieve werkwoorden in relaties",
            "body": "Veel werkwoorden over relaties zijn wederkerend (reflexief):\n\n• incontrarsi — elkaar ontmoeten: Ci incontriamo al bar.\n• conoscersi — elkaar kennen: Ci conosciamo da anni.\n• abbracciarsi — elkaar omhelzen: Si abbracciano sempre.\n• fidarsi di — vertrouwen op: Mi fido di te.\n• volersi bene — van elkaar houden: Ci vogliamo bene.\n\nLet op: bij wederkerige acties gebruik je de meervoudsvorm (ci/vi/si)."
        },
        "words": ["w1931","w1932","w1933","w1934","w1935","w1936","w1937","w1938"]
    },
    {
        "id": 212, "title": "Liefde & romantiek", "emoji": "❤️", "level": "B1",
        "description": "Woorden en uitdrukkingen over liefde en romantische relaties.",
        "words": ["w1939","w1940","w1941","w1942","w1943","w1944","w1945","w1946"]
    },
    {
        "id": 213, "title": "Conflicten & verzoening", "emoji": "🕊️", "level": "B1",
        "description": "Leer praten over ruzies, conflicten en verzoening.",
        "words": ["w1947","w1948","w1949","w1950","w1951","w1952","w1953","w1954"]
    },
    {
        "id": 214, "title": "Karakter & persoonlijkheid", "emoji": "🎭", "level": "B1",
        "description": "Beschrijf karaktereigenschappen en persoonlijkheid.",
        "words": ["w1955","w1956","w1957","w1958","w1959","w1960","w1961","w1962"]
    },
    {
        "id": 215, "title": "Psychologie & gevoelens", "emoji": "🧠", "level": "B1",
        "description": "Praat over gevoelens, emoties en psychologisch welzijn.",
        "words": ["w1963","w1964","w1965","w1966","w1967","w1968","w1969","w1970"]
    },
    {
        "id": 216, "title": "Dromen & ambities", "emoji": "🌟", "level": "B1",
        "description": "Vertel over je dromen, ambities en toekomstplannen.",
        "words": ["w1971","w1972","w1973","w1974","w1975","w1976","w1977","w1978"]
    },
    {
        "id": 217, "title": "Succes & falen", "emoji": "🏆", "level": "B1",
        "description": "Woorden over succes, mislukking en doorzettingsvermogen.",
        "words": ["w1979","w1980","w1981","w1982","w1983","w1984","w1985","w1986"]
    },
    {
        "id": 218, "title": "Geluk & tevredenheid", "emoji": "😊", "level": "B1",
        "description": "Praat over geluk, tevredenheid en wat je blij maakt.",
        "words": ["w1987","w1988","w1989","w1990","w1991","w1992","w1993","w1994"]
    },
    {
        "id": 219, "title": "Stress & ontspanning", "emoji": "🧘", "level": "B1",
        "description": "Leer woorden over stress, ontspanning en balans.",
        "words": ["w1995","w1996","w1997","w1998","w1999","w2000","w2001","w2002"]
    },
    {
        "id": 220, "title": "Toetsles B1 — Blok 10 (les 211–220)", "emoji": "📝", "level": "B1",
        "description": "Test je kennis van blok 10: relaties, emoties en persoonlijkheid.",
        "words": ["w2003","w2004","w2005","w2006","w2007","w2008","w2009","w2010"]
    },

    # ═══ BLOK 11: NATUUR, DIEREN & MILIEU (221–230) ═══════════════════════════
    {
        "id": 221, "title": "Huisdieren", "emoji": "🐾", "level": "B1",
        "description": "Praat over huisdieren en dierenverzorging.",
        "grammar": {
            "title": "Verkleinwoorden: -ino/-ina/-etto/-etta",
            "body": "Het Italiaans gebruikt verkleinachtervoegsels om iets kleins of liefs aan te duiden:\n\n• -ino/-ina: gatto → gattino (katje), casa → casina (huisje)\n• -etto/-etta: giardino → giardinetto (tuintje), camera → cameretta (kamertje)\n• -uccio/-uccia: casa → casuccia (klein huisje, ook liefkozend)\n\nVuistregel: -ino is het meest gebruikelijk. Let op geslachtsverandering: il gatto → il gattino, la gatta → la gattina."
        },
        "words": ["w2011","w2012","w2013","w2014","w2015","w2016","w2017","w2018"]
    },
    {
        "id": 222, "title": "Wilde dieren", "emoji": "🦁", "level": "B1",
        "description": "Leer de namen van wilde dieren en waar ze leven.",
        "words": ["w2019","w2020","w2021","w2022","w2023","w2024","w2025","w2026"]
    },
    {
        "id": 223, "title": "Planten & tuinieren", "emoji": "🌱", "level": "B1",
        "description": "Woorden over planten, bloemen en tuinieren.",
        "words": ["w2027","w2028","w2029","w2030","w2031","w2032","w2033","w2034"]
    },
    {
        "id": 224, "title": "Landschappen & geografie", "emoji": "🏔️", "level": "B1",
        "description": "Beschrijf landschappen, natuur en geografie.",
        "words": ["w2035","w2036","w2037","w2038","w2039","w2040","w2041","w2042"]
    },
    {
        "id": 225, "title": "De zee & het strand", "emoji": "🏖️", "level": "B1",
        "description": "Woorden over de zee, het strand en watersport.",
        "words": ["w2043","w2044","w2045","w2046","w2047","w2048","w2049","w2050"]
    },
    {
        "id": 226, "title": "Bergen & wandelen", "emoji": "⛰️", "level": "B1",
        "description": "Praat over bergen, wandelen en bergsport.",
        "words": ["w2051","w2052","w2053","w2054","w2055","w2056","w2057","w2058"]
    },
    {
        "id": 227, "title": "Klimaat & klimaatverandering", "emoji": "🌍", "level": "B1",
        "description": "Bespreek het klimaat en klimaatverandering.",
        "words": ["w2059","w2060","w2061","w2062","w2063","w2064","w2065","w2066"]
    },
    {
        "id": 228, "title": "Duurzaamheid & recycling", "emoji": "♻️", "level": "B1",
        "description": "Leer woorden over duurzaamheid en afvalverwerking.",
        "words": ["w2067","w2068","w2069","w2070","w2071","w2072","w2073","w2074"]
    },
    {
        "id": 229, "title": "Energie & grondstoffen", "emoji": "⚡", "level": "B1",
        "description": "Praat over energiebronnen en grondstoffen.",
        "words": ["w2075","w2076","w2077","w2078","w2079","w2080","w2081","w2082"]
    },
    {
        "id": 230, "title": "Toetsles B1 — Blok 11 (les 221–230)", "emoji": "📝", "level": "B1",
        "description": "Test je kennis van blok 11: natuur, dieren en milieu.",
        "words": ["w2083","w2084","w2085","w2086","w2087","w2088","w2089","w2090"]
    },

    # ═══ BLOK 12: KUNST, MEDIA & ENTERTAINMENT (231–240) ══════════════════════
    {
        "id": 231, "title": "Film & bioscoop", "emoji": "🎬", "level": "B1",
        "description": "Praat over films, de bioscoop en genres.",
        "grammar": {
            "title": "Meningen uiten met de congiuntivo (herhaling)",
            "body": "Gebruik de congiuntivo na werkwoorden van mening en gevoel:\n\n• Penso che… (ik denk dat…): Penso che sia un bel film.\n• Credo che… (ik geloof dat…): Credo che abbia ragione.\n• Mi sembra che… (het lijkt me dat…): Mi sembra che piova.\n• È importante che… (het is belangrijk dat…): È importante che tu venga.\n\nVuistregel: na penso/credo/spero/temo + che → congiuntivo.\nBij zekerheid (sono sicuro che) → indicativo."
        },
        "words": ["w2091","w2092","w2093","w2094","w2095","w2096","w2097","w2098"]
    },
    {
        "id": 232, "title": "Theater & opera", "emoji": "🎭", "level": "B1",
        "description": "Woorden over theater, opera en podiumkunsten.",
        "words": ["w2099","w2100","w2101","w2102","w2103","w2104","w2105","w2106"]
    },
    {
        "id": 233, "title": "Schilderkunst & musea", "emoji": "🖼️", "level": "B1",
        "description": "Leer praten over schilderijen, musea en kunstwerken.",
        "words": ["w2107","w2108","w2109","w2110","w2111","w2112","w2113","w2114"]
    },
    {
        "id": 234, "title": "Fotografie & design", "emoji": "📸", "level": "B1",
        "description": "Woorden over fotografie, design en visuele kunst.",
        "words": ["w2115","w2116","w2117","w2118","w2119","w2120","w2121","w2122"]
    },
    {
        "id": 235, "title": "Kranten & journalistiek", "emoji": "📰", "level": "B1",
        "description": "Praat over kranten, nieuws en journalistiek.",
        "words": ["w2123","w2124","w2125","w2126","w2127","w2128","w2129","w2130"]
    },
    {
        "id": 236, "title": "Radio & televisie", "emoji": "📺", "level": "B1",
        "description": "Woorden over radio, televisie en uitzendingen.",
        "words": ["w2131","w2132","w2133","w2134","w2135","w2136","w2137","w2138"]
    },
    {
        "id": 237, "title": "Reclame & marketing", "emoji": "📢", "level": "B1",
        "description": "Leer woorden over reclame, marketing en merken.",
        "words": ["w2139","w2140","w2141","w2142","w2143","w2144","w2145","w2146"]
    },
    {
        "id": 238, "title": "Mode & trends", "emoji": "👗", "level": "B1",
        "description": "Praat over mode, trends en stijl.",
        "words": ["w2147","w2148","w2149","w2150","w2151","w2152","w2153","w2154"]
    },
    {
        "id": 239, "title": "Evenementen & festivals", "emoji": "🎉", "level": "B1",
        "description": "Woorden over evenementen, festivals en vieringen.",
        "words": ["w2155","w2156","w2157","w2158","w2159","w2160","w2161","w2162"]
    },
    {
        "id": 240, "title": "Toetsles B1 — Blok 12 (les 231–240)", "emoji": "📝", "level": "B1",
        "description": "Test je kennis van blok 12: kunst, media en entertainment.",
        "words": ["w2163","w2164","w2165","w2166","w2167","w2168","w2169","w2170"]
    },
]

# ── WOORDEN ───────────────────────────────────────────────────────────────────

WORDS = [
    # ═══ LES 211: Relaties & vriendschap ══════════════════════════════════════
    {"id": "w1931", "it": "l'amicizia", "nl": "de vriendschap", "ph": "a-mi-TSJI-tsia",
     "ex": "L'amicizia è importante nella vita.", "exNl": "Vriendschap is belangrijk in het leven.",
     "lesson": 211, "level": "B1", "cat": "sostantivo"},
    {"id": "w1932", "it": "fidarsi", "nl": "vertrouwen op", "ph": "fi-DAR-si",
     "ex": "Mi fido completamente di lei.", "exNl": "Ik vertrouw volledig op haar.",
     "lesson": 211, "level": "B1", "cat": "verbo"},
    {"id": "w1933", "it": "il legame", "nl": "de band", "ph": "le-GA-me",
     "ex": "Abbiamo un legame molto forte.", "exNl": "We hebben een heel sterke band.",
     "lesson": 211, "level": "B1", "cat": "sostantivo"},
    {"id": "w1934", "it": "confidarsi", "nl": "zich toevertrouwen", "ph": "kon-fi-DAR-si",
     "ex": "Mi confido sempre con la mia amica.", "exNl": "Ik vertrouw me altijd toe aan mijn vriendin.",
     "lesson": 211, "level": "B1", "cat": "verbo"},
    {"id": "w1935", "it": "il compagno", "nl": "de metgezel", "ph": "kom-PA-njo",
     "ex": "È il mio compagno di avventure.", "exNl": "Hij is mijn metgezel in avonturen.",
     "lesson": 211, "level": "B1", "cat": "sostantivo"},
    {"id": "w1936", "it": "sostenere", "nl": "steunen", "ph": "sos-te-NE-re",
     "ex": "Gli amici veri ti sostengono sempre.", "exNl": "Echte vrienden steunen je altijd.",
     "lesson": 211, "level": "B1", "cat": "verbo"},
    {"id": "w1937", "it": "la complicità", "nl": "de verstandhouding", "ph": "kom-pli-tsji-TA",
     "ex": "Tra noi c'è una grande complicità.", "exNl": "Tussen ons is er een grote verstandhouding.",
     "lesson": 211, "level": "B1", "cat": "sostantivo"},
    {"id": "w1938", "it": "incontrarsi", "nl": "elkaar ontmoeten", "ph": "in-kon-TRAR-si",
     "ex": "Ci incontriamo ogni venerdì.", "exNl": "We ontmoeten elkaar elke vrijdag.",
     "lesson": 211, "level": "B1", "cat": "verbo"},

    # ═══ LES 212: Liefde & romantiek ═════════════════════════════════════════
    {"id": "w1939", "it": "innamorarsi", "nl": "verliefd worden", "ph": "in-na-mo-RAR-si",
     "ex": "Mi sono innamorato di lei al primo sguardo.", "exNl": "Ik werd op het eerste gezicht verliefd op haar.",
     "lesson": 212, "level": "B1", "cat": "verbo"},
    {"id": "w1940", "it": "la coppia", "nl": "het koppel", "ph": "KOP-pja",
     "ex": "Sono una coppia molto felice.", "exNl": "Ze zijn een heel gelukkig koppel.",
     "lesson": 212, "level": "B1", "cat": "sostantivo"},
    {"id": "w1941", "it": "il bacio", "nl": "de kus", "ph": "BA-tsjo",
     "ex": "Le ha dato un bacio sulla guancia.", "exNl": "Hij gaf haar een kus op de wang.",
     "lesson": 212, "level": "B1", "cat": "sostantivo"},
    {"id": "w1942", "it": "l'abbraccio", "nl": "de omhelzing", "ph": "ab-BRA-tsjo",
     "ex": "Mi ha dato un abbraccio caloroso.", "exNl": "Ze gaf me een warme omhelzing.",
     "lesson": 212, "level": "B1", "cat": "sostantivo"},
    {"id": "w1943", "it": "il fidanzato", "nl": "de verloofde (m)", "ph": "fi-dan-TSA-to",
     "ex": "Il mio fidanzato si chiama Marco.", "exNl": "Mijn verloofde heet Marco.",
     "lesson": 212, "level": "B1", "cat": "sostantivo"},
    {"id": "w1944", "it": "sposarsi", "nl": "trouwen", "ph": "spo-ZAR-si",
     "ex": "Si sposeranno a giugno.", "exNl": "Ze gaan in juni trouwen.",
     "lesson": 212, "level": "B1", "cat": "verbo"},
    {"id": "w1945", "it": "romantico", "nl": "romantisch", "ph": "ro-MAN-ti-ko",
     "ex": "Ha organizzato una cena romantica.", "exNl": "Hij heeft een romantisch diner georganiseerd.",
     "lesson": 212, "level": "B1", "cat": "aggettivo"},
    {"id": "w1946", "it": "la tenerezza", "nl": "de tederheid", "ph": "te-ne-RE-tsa",
     "ex": "Mi guarda con tenerezza.", "exNl": "Ze kijkt me aan met tederheid.",
     "lesson": 212, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 213: Conflicten & verzoening ════════════════════════════════════
    {"id": "w1947", "it": "il conflitto", "nl": "het conflict", "ph": "kon-FLIT-to",
     "ex": "Bisogna risolvere il conflitto.", "exNl": "We moeten het conflict oplossen.",
     "lesson": 213, "level": "B1", "cat": "sostantivo"},
    {"id": "w1948", "it": "litigare", "nl": "ruziemaken", "ph": "li-ti-GA-re",
     "ex": "Non mi piace litigare con te.", "exNl": "Ik maak niet graag ruzie met jou.",
     "lesson": 213, "level": "B1", "cat": "verbo"},
    {"id": "w1949", "it": "la riconciliazione", "nl": "de verzoening", "ph": "ri-kon-tsji-lja-TSJO-ne",
     "ex": "La riconciliazione è stata difficile.", "exNl": "De verzoening was moeilijk.",
     "lesson": 213, "level": "B1", "cat": "sostantivo"},
    {"id": "w1950", "it": "scusarsi", "nl": "zich verontschuldigen", "ph": "sku-ZAR-si",
     "ex": "Si è scusato per il suo comportamento.", "exNl": "Hij heeft zich verontschuldigd voor zijn gedrag.",
     "lesson": 213, "level": "B1", "cat": "verbo"},
    {"id": "w1951", "it": "il malinteso", "nl": "het misverstand", "ph": "ma-lin-TE-zo",
     "ex": "È stato solo un malinteso.", "exNl": "Het was slechts een misverstand.",
     "lesson": 213, "level": "B1", "cat": "sostantivo"},
    {"id": "w1952", "it": "perdonare", "nl": "vergeven", "ph": "per-do-NA-re",
     "ex": "Ti perdono, non preoccuparti.", "exNl": "Ik vergeef je, maak je geen zorgen.",
     "lesson": 213, "level": "B1", "cat": "verbo"},
    {"id": "w1953", "it": "la colpa", "nl": "de schuld", "ph": "KOL-pa",
     "ex": "Non è colpa tua.", "exNl": "Het is niet jouw schuld.",
     "lesson": 213, "level": "B1", "cat": "sostantivo"},
    {"id": "w1954", "it": "risolvere", "nl": "oplossen", "ph": "ri-ZOL-ve-re",
     "ex": "Dobbiamo risolvere questo problema insieme.", "exNl": "We moeten dit probleem samen oplossen.",
     "lesson": 213, "level": "B1", "cat": "verbo"},

    # ═══ LES 214: Karakter & persoonlijkheid ═════════════════════════════════
    {"id": "w1955", "it": "il carattere", "nl": "het karakter", "ph": "ka-RAT-te-re",
     "ex": "Ha un carattere forte.", "exNl": "Ze heeft een sterk karakter.",
     "lesson": 214, "level": "B1", "cat": "sostantivo"},
    {"id": "w1956", "it": "coraggioso", "nl": "moedig", "ph": "ko-ra-DJO-zo",
     "ex": "È una persona molto coraggiosa.", "exNl": "Het is een heel moedig persoon.",
     "lesson": 214, "level": "B1", "cat": "aggettivo"},
    {"id": "w1957", "it": "sensibile", "nl": "gevoelig", "ph": "sen-SI-bi-le",
     "ex": "È un ragazzo molto sensibile.", "exNl": "Het is een heel gevoelige jongen.",
     "lesson": 214, "level": "B1", "cat": "aggettivo"},
    {"id": "w1958", "it": "testardo", "nl": "koppig", "ph": "tes-TAR-do",
     "ex": "Mio fratello è molto testardo.", "exNl": "Mijn broer is heel koppig.",
     "lesson": 214, "level": "B1", "cat": "aggettivo"},
    {"id": "w1959", "it": "generoso", "nl": "gul", "ph": "dje-ne-RO-zo",
     "ex": "È sempre molto generoso con tutti.", "exNl": "Hij is altijd heel gul met iedereen.",
     "lesson": 214, "level": "B1", "cat": "aggettivo"},
    {"id": "w1960", "it": "la personalità", "nl": "de persoonlijkheid", "ph": "per-so-na-li-TA",
     "ex": "Ha una personalità affascinante.", "exNl": "Ze heeft een fascinerende persoonlijkheid.",
     "lesson": 214, "level": "B1", "cat": "sostantivo"},
    {"id": "w1961", "it": "orgoglioso", "nl": "trots", "ph": "or-go-LJO-zo",
     "ex": "Sono orgoglioso di te.", "exNl": "Ik ben trots op je.",
     "lesson": 214, "level": "B1", "cat": "aggettivo"},
    {"id": "w1962", "it": "umile", "nl": "bescheiden", "ph": "U-mi-le",
     "ex": "Nonostante il successo, è rimasto umile.", "exNl": "Ondanks het succes is hij bescheiden gebleven.",
     "lesson": 214, "level": "B1", "cat": "aggettivo"},

    # ═══ LES 215: Psychologie & gevoelens ════════════════════════════════════
    {"id": "w1963", "it": "l'ansia", "nl": "de angst", "ph": "AN-sja",
     "ex": "L'ansia prima dell'esame è normale.", "exNl": "Angst voor het examen is normaal.",
     "lesson": 215, "level": "B1", "cat": "sostantivo"},
    {"id": "w1964", "it": "la depressione", "nl": "de depressie", "ph": "de-pres-SJO-ne",
     "ex": "La depressione è una malattia seria.", "exNl": "Depressie is een serieuze ziekte.",
     "lesson": 215, "level": "B1", "cat": "sostantivo"},
    {"id": "w1965", "it": "il benessere", "nl": "het welzijn", "ph": "be-NES-se-re",
     "ex": "Il benessere mentale è fondamentale.", "exNl": "Mentaal welzijn is fundamenteel.",
     "lesson": 215, "level": "B1", "cat": "sostantivo"},
    {"id": "w1966", "it": "provare", "nl": "voelen / ervaren", "ph": "pro-VA-re",
     "ex": "Cosa provi in questo momento?", "exNl": "Wat voel je op dit moment?",
     "lesson": 215, "level": "B1", "cat": "verbo"},
    {"id": "w1967", "it": "la vergogna", "nl": "de schaamte", "ph": "ver-GO-nja",
     "ex": "Ha provato una grande vergogna.", "exNl": "Hij voelde een grote schaamte.",
     "lesson": 215, "level": "B1", "cat": "sostantivo"},
    {"id": "w1968", "it": "la gelosia", "nl": "de jaloezie", "ph": "dje-lo-ZI-a",
     "ex": "La gelosia può distruggere una relazione.", "exNl": "Jaloezie kan een relatie verwoesten.",
     "lesson": 215, "level": "B1", "cat": "sostantivo"},
    {"id": "w1969", "it": "emozionante", "nl": "ontroerend", "ph": "e-mo-tsjo-NAN-te",
     "ex": "Il film era molto emozionante.", "exNl": "De film was heel ontroerend.",
     "lesson": 215, "level": "B1", "cat": "aggettivo"},
    {"id": "w1970", "it": "soffrire", "nl": "lijden", "ph": "sof-FRI-re",
     "ex": "Non voglio vederti soffrire.", "exNl": "Ik wil je niet zien lijden.",
     "lesson": 215, "level": "B1", "cat": "verbo"},

    # ═══ LES 216: Dromen & ambities ══════════════════════════════════════════
    {"id": "w1971", "it": "il sogno", "nl": "de droom", "ph": "SO-njo",
     "ex": "Il mio sogno è viaggiare per il mondo.", "exNl": "Mijn droom is om de wereld rond te reizen.",
     "lesson": 216, "level": "B1", "cat": "sostantivo"},
    {"id": "w1972", "it": "l'ambizione", "nl": "de ambitie", "ph": "am-bi-TSJO-ne",
     "ex": "Ha molta ambizione nella carriera.", "exNl": "Ze heeft veel ambitie in haar carrière.",
     "lesson": 216, "level": "B1", "cat": "sostantivo"},
    {"id": "w1973", "it": "realizzare", "nl": "verwezenlijken", "ph": "re-a-li-DZA-re",
     "ex": "Voglio realizzare i miei sogni.", "exNl": "Ik wil mijn dromen verwezenlijken.",
     "lesson": 216, "level": "B1", "cat": "verbo"},
    {"id": "w1974", "it": "l'obiettivo", "nl": "het doel", "ph": "o-bjet-TI-vo",
     "ex": "Il mio obiettivo è imparare l'italiano.", "exNl": "Mijn doel is om Italiaans te leren.",
     "lesson": 216, "level": "B1", "cat": "sostantivo"},
    {"id": "w1975", "it": "sperare", "nl": "hopen", "ph": "spe-RA-re",
     "ex": "Spero di riuscire a farcela.", "exNl": "Ik hoop dat het me lukt.",
     "lesson": 216, "level": "B1", "cat": "verbo"},
    {"id": "w1976", "it": "la motivazione", "nl": "de motivatie", "ph": "mo-ti-va-TSJO-ne",
     "ex": "La motivazione è la chiave del successo.", "exNl": "Motivatie is de sleutel tot succes.",
     "lesson": 216, "level": "B1", "cat": "sostantivo"},
    {"id": "w1977", "it": "determinato", "nl": "vastbesloten", "ph": "de-ter-mi-NA-to",
     "ex": "È determinato a finire il progetto.", "exNl": "Hij is vastbesloten om het project af te ronden.",
     "lesson": 216, "level": "B1", "cat": "aggettivo"},
    {"id": "w1978", "it": "la passione", "nl": "de passie", "ph": "pas-SJO-ne",
     "ex": "La sua passione è la musica.", "exNl": "Zijn passie is de muziek.",
     "lesson": 216, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 217: Succes & falen ═════════════════════════════════════════════
    {"id": "w1979", "it": "il successo", "nl": "het succes", "ph": "su-TSJES-so",
     "ex": "Il successo richiede impegno.", "exNl": "Succes vereist inzet.",
     "lesson": 217, "level": "B1", "cat": "sostantivo"},
    {"id": "w1980", "it": "il fallimento", "nl": "het falen", "ph": "fal-li-MEN-to",
     "ex": "Il fallimento fa parte della vita.", "exNl": "Falen hoort bij het leven.",
     "lesson": 217, "level": "B1", "cat": "sostantivo"},
    {"id": "w1981", "it": "riuscire", "nl": "slagen / lukken", "ph": "rju-SJI-re",
     "ex": "Sono riuscito a superare l'esame.", "exNl": "Het is me gelukt om het examen te halen.",
     "lesson": 217, "level": "B1", "cat": "verbo"},
    {"id": "w1982", "it": "la sconfitta", "nl": "de nederlaag", "ph": "skon-FIT-ta",
     "ex": "La sconfitta ci ha insegnato molto.", "exNl": "De nederlaag heeft ons veel geleerd.",
     "lesson": 217, "level": "B1", "cat": "sostantivo"},
    {"id": "w1983", "it": "raggiungere", "nl": "bereiken", "ph": "ra-DJUN-dje-re",
     "ex": "Ha raggiunto il suo obiettivo.", "exNl": "Ze heeft haar doel bereikt.",
     "lesson": 217, "level": "B1", "cat": "verbo"},
    {"id": "w1984", "it": "l'impegno", "nl": "de inzet", "ph": "im-PE-njo",
     "ex": "Con impegno tutto è possibile.", "exNl": "Met inzet is alles mogelijk.",
     "lesson": 217, "level": "B1", "cat": "sostantivo"},
    {"id": "w1985", "it": "arrendersi", "nl": "zich overgeven / opgeven", "ph": "ar-REN-der-si",
     "ex": "Non mi arrendo mai.", "exNl": "Ik geef nooit op.",
     "lesson": 217, "level": "B1", "cat": "verbo"},
    {"id": "w1986", "it": "la vittoria", "nl": "de overwinning", "ph": "vit-TO-rja",
     "ex": "La vittoria è stata meritata.", "exNl": "De overwinning was verdiend.",
     "lesson": 217, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 218: Geluk & tevredenheid ═══════════════════════════════════════
    {"id": "w1987", "it": "la felicità", "nl": "het geluk", "ph": "fe-li-tsji-TA",
     "ex": "La felicità è nelle piccole cose.", "exNl": "Geluk zit in de kleine dingen.",
     "lesson": 218, "level": "B1", "cat": "sostantivo"},
    {"id": "w1988", "it": "soddisfatto", "nl": "tevreden", "ph": "sod-dis-FAT-to",
     "ex": "Sono soddisfatto del mio lavoro.", "exNl": "Ik ben tevreden over mijn werk.",
     "lesson": 218, "level": "B1", "cat": "aggettivo"},
    {"id": "w1989", "it": "la gioia", "nl": "de vreugde", "ph": "DJO-ja",
     "ex": "Che gioia rivederti!", "exNl": "Wat een vreugde om je weer te zien!",
     "lesson": 218, "level": "B1", "cat": "sostantivo"},
    {"id": "w1990", "it": "apprezzare", "nl": "waarderen", "ph": "ap-pre-TSA-re",
     "ex": "Apprezzo molto il tuo aiuto.", "exNl": "Ik waardeer je hulp heel erg.",
     "lesson": 218, "level": "B1", "cat": "verbo"},
    {"id": "w1991", "it": "grato", "nl": "dankbaar", "ph": "GRA-to",
     "ex": "Ti sono molto grato.", "exNl": "Ik ben je heel dankbaar.",
     "lesson": 218, "level": "B1", "cat": "aggettivo"},
    {"id": "w1992", "it": "la serenità", "nl": "de sereniteit", "ph": "se-re-ni-TA",
     "ex": "Cerco la serenità nella natura.", "exNl": "Ik zoek sereniteit in de natuur.",
     "lesson": 218, "level": "B1", "cat": "sostantivo"},
    {"id": "w1993", "it": "godere", "nl": "genieten", "ph": "go-DE-re",
     "ex": "Bisogna godere ogni momento.", "exNl": "Je moet van elk moment genieten.",
     "lesson": 218, "level": "B1", "cat": "verbo"},
    {"id": "w1994", "it": "entusiasta", "nl": "enthousiast", "ph": "en-tu-ZJAS-ta",
     "ex": "Sono entusiasta del nuovo progetto.", "exNl": "Ik ben enthousiast over het nieuwe project.",
     "lesson": 218, "level": "B1", "cat": "aggettivo"},

    # ═══ LES 219: Stress & ontspanning ═══════════════════════════════════════
    {"id": "w1995", "it": "lo stress", "nl": "de stress", "ph": "STRESS",
     "ex": "Lo stress del lavoro mi stanca.", "exNl": "De stress van het werk maakt me moe.",
     "lesson": 219, "level": "B1", "cat": "sostantivo"},
    {"id": "w1996", "it": "rilassarsi", "nl": "zich ontspannen", "ph": "ri-las-SAR-si",
     "ex": "Mi rilasso leggendo un libro.", "exNl": "Ik ontspan me door een boek te lezen.",
     "lesson": 219, "level": "B1", "cat": "verbo"},
    {"id": "w1997", "it": "la pressione", "nl": "de druk", "ph": "pres-SJO-ne",
     "ex": "C'è molta pressione al lavoro.", "exNl": "Er is veel druk op het werk.",
     "lesson": 219, "level": "B1", "cat": "sostantivo"},
    {"id": "w1998", "it": "meditare", "nl": "mediteren", "ph": "me-di-TA-re",
     "ex": "Medito ogni mattina per venti minuti.", "exNl": "Ik mediteer elke ochtend twintig minuten.",
     "lesson": 219, "level": "B1", "cat": "verbo"},
    {"id": "w1999", "it": "esausto", "nl": "uitgeput", "ph": "e-ZAUS-to",
     "ex": "Dopo la giornata sono esausto.", "exNl": "Na de dag ben ik uitgeput.",
     "lesson": 219, "level": "B1", "cat": "aggettivo"},
    {"id": "w2000", "it": "l'equilibrio", "nl": "het evenwicht", "ph": "e-kwi-LI-brjo",
     "ex": "Cerco un equilibrio tra lavoro e vita.", "exNl": "Ik zoek een evenwicht tussen werk en leven.",
     "lesson": 219, "level": "B1", "cat": "sostantivo"},
    {"id": "w2001", "it": "la tranquillità", "nl": "de rust", "ph": "tran-kwil-li-TA",
     "ex": "Qui c'è una grande tranquillità.", "exNl": "Hier is een grote rust.",
     "lesson": 219, "level": "B1", "cat": "sostantivo"},
    {"id": "w2002", "it": "affrontare", "nl": "het hoofd bieden", "ph": "af-fron-TA-re",
     "ex": "Bisogna affrontare i problemi con calma.", "exNl": "Je moet problemen kalm het hoofd bieden.",
     "lesson": 219, "level": "B1", "cat": "verbo"},

    # ═══ LES 220: Toetsles B1 — Blok 10 (les 211–220) ═══════════════════════
    {"id": "w2003", "it": "la relazione", "nl": "de relatie", "ph": "re-la-TSJO-ne",
     "ex": "La nostra relazione è molto bella.", "exNl": "Onze relatie is heel mooi.",
     "lesson": 220, "level": "B1", "cat": "sostantivo"},
    {"id": "w2004", "it": "affettuoso", "nl": "aanhankelijk", "ph": "af-fet-TUO-zo",
     "ex": "È un bambino molto affettuoso.", "exNl": "Het is een heel aanhankelijk kind.",
     "lesson": 220, "level": "B1", "cat": "aggettivo"},
    {"id": "w2005", "it": "la pazienza", "nl": "het geduld", "ph": "pa-TSJEN-tsa",
     "ex": "Ci vuole molta pazienza.", "exNl": "Er is veel geduld nodig.",
     "lesson": 220, "level": "B1", "cat": "sostantivo"},
    {"id": "w2006", "it": "ammirare", "nl": "bewonderen", "ph": "am-mi-RA-re",
     "ex": "Ammiro il tuo coraggio.", "exNl": "Ik bewonder je moed.",
     "lesson": 220, "level": "B1", "cat": "verbo"},
    {"id": "w2007", "it": "la nostalgia", "nl": "het heimwee", "ph": "nos-tal-DJI-a",
     "ex": "Ho nostalgia di casa.", "exNl": "Ik heb heimwee naar huis.",
     "lesson": 220, "level": "B1", "cat": "sostantivo"},
    {"id": "w2008", "it": "sincero", "nl": "oprecht", "ph": "sin-TSJE-ro",
     "ex": "È una persona sincera.", "exNl": "Ze is een oprecht persoon.",
     "lesson": 220, "level": "B1", "cat": "aggettivo"},
    {"id": "w2009", "it": "il rispetto", "nl": "het respect", "ph": "ris-PET-to",
     "ex": "Il rispetto reciproco è importante.", "exNl": "Wederzijds respect is belangrijk.",
     "lesson": 220, "level": "B1", "cat": "sostantivo"},
    {"id": "w2010", "it": "preoccuparsi", "nl": "zich zorgen maken", "ph": "pre-ok-ku-PAR-si",
     "ex": "Non preoccuparti, andrà tutto bene.", "exNl": "Maak je geen zorgen, het komt allemaal goed.",
     "lesson": 220, "level": "B1", "cat": "verbo"},

    # ═══ LES 221: Huisdieren ═════════════════════════════════════════════════
    {"id": "w2011", "it": "l'animale domestico", "nl": "het huisdier", "ph": "a-ni-MA-le do-MES-ti-ko",
     "ex": "Hai un animale domestico?", "exNl": "Heb je een huisdier?",
     "lesson": 221, "level": "B1", "cat": "sostantivo"},
    {"id": "w2012", "it": "il gattino", "nl": "het katje", "ph": "gat-TI-no",
     "ex": "Il gattino gioca con la palla.", "exNl": "Het katje speelt met de bal.",
     "lesson": 221, "level": "B1", "cat": "sostantivo"},
    {"id": "w2013", "it": "il cucciolo", "nl": "het puppy / jong dier", "ph": "KU-tsjo-lo",
     "ex": "Il cucciolo abbaia tutto il giorno.", "exNl": "Het puppy blaft de hele dag.",
     "lesson": 221, "level": "B1", "cat": "sostantivo"},
    {"id": "w2014", "it": "il veterinario", "nl": "de dierenarts", "ph": "ve-te-ri-NA-rjo",
     "ex": "Devo portare il cane dal veterinario.", "exNl": "Ik moet de hond naar de dierenarts brengen.",
     "lesson": 221, "level": "B1", "cat": "sostantivo"},
    {"id": "w2015", "it": "la gabbia", "nl": "de kooi", "ph": "GAB-bja",
     "ex": "L'uccello è nella gabbia.", "exNl": "De vogel zit in de kooi.",
     "lesson": 221, "level": "B1", "cat": "sostantivo"},
    {"id": "w2016", "it": "il guinzaglio", "nl": "de riem (hond)", "ph": "gwin-TSA-ljo",
     "ex": "Porta il cane al guinzaglio.", "exNl": "Doe de hond aan de riem.",
     "lesson": 221, "level": "B1", "cat": "sostantivo"},
    {"id": "w2017", "it": "accarezzare", "nl": "aaien", "ph": "ak-ka-re-TSA-re",
     "ex": "Al gatto piace essere accarezzato.", "exNl": "De kat vindt het fijn om geaaid te worden.",
     "lesson": 221, "level": "B1", "cat": "verbo"},
    {"id": "w2018", "it": "il pesciolino", "nl": "het visje", "ph": "pe-sjo-LI-no",
     "ex": "Ho comprato un pesciolino rosso.", "exNl": "Ik heb een rood visje gekocht.",
     "lesson": 221, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 222: Wilde dieren ═══════════════════════════════════════════════
    {"id": "w2019", "it": "il lupo", "nl": "de wolf", "ph": "LU-po",
     "ex": "Il lupo vive nei boschi.", "exNl": "De wolf leeft in de bossen.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},
    {"id": "w2020", "it": "l'orso", "nl": "de beer", "ph": "OR-so",
     "ex": "L'orso bruno vive sulle Alpi.", "exNl": "De bruine beer leeft in de Alpen.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},
    {"id": "w2021", "it": "la volpe", "nl": "de vos", "ph": "VOL-pe",
     "ex": "La volpe è un animale furbo.", "exNl": "De vos is een slim dier.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},
    {"id": "w2022", "it": "il cervo", "nl": "het hert", "ph": "TSJER-vo",
     "ex": "Ho visto un cervo nel bosco.", "exNl": "Ik heb een hert gezien in het bos.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},
    {"id": "w2023", "it": "l'aquila", "nl": "de arend", "ph": "A-kwi-la",
     "ex": "L'aquila vola sopra le montagne.", "exNl": "De arend vliegt boven de bergen.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},
    {"id": "w2024", "it": "il serpente", "nl": "de slang", "ph": "ser-PEN-te",
     "ex": "Il serpente si nasconde tra le rocce.", "exNl": "De slang verstopt zich tussen de rotsen.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},
    {"id": "w2025", "it": "la scimmia", "nl": "de aap", "ph": "SJIM-mja",
     "ex": "La scimmia mangia le banane.", "exNl": "De aap eet bananen.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},
    {"id": "w2026", "it": "il delfino", "nl": "de dolfijn", "ph": "del-FI-no",
     "ex": "Il delfino nuota velocemente.", "exNl": "De dolfijn zwemt snel.",
     "lesson": 222, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 223: Planten & tuinieren ════════════════════════════════════════
    {"id": "w2027", "it": "la pianta", "nl": "de plant", "ph": "PJAN-ta",
     "ex": "Questa pianta ha bisogno di sole.", "exNl": "Deze plant heeft zon nodig.",
     "lesson": 223, "level": "B1", "cat": "sostantivo"},
    {"id": "w2028", "it": "il fiore", "nl": "de bloem", "ph": "FJO-re",
     "ex": "I fiori sbocciano in primavera.", "exNl": "De bloemen bloeien in de lente.",
     "lesson": 223, "level": "B1", "cat": "sostantivo"},
    {"id": "w2029", "it": "l'albero", "nl": "de boom", "ph": "AL-be-ro",
     "ex": "L'albero è molto vecchio.", "exNl": "De boom is heel oud.",
     "lesson": 223, "level": "B1", "cat": "sostantivo"},
    {"id": "w2030", "it": "seminare", "nl": "zaaien", "ph": "se-mi-NA-re",
     "ex": "In primavera seminiamo i pomodori.", "exNl": "In de lente zaaien we de tomaten.",
     "lesson": 223, "level": "B1", "cat": "verbo"},
    {"id": "w2031", "it": "innaffiare", "nl": "water geven", "ph": "in-naf-FJA-re",
     "ex": "Devo innaffiare le piante ogni giorno.", "exNl": "Ik moet de planten elke dag water geven.",
     "lesson": 223, "level": "B1", "cat": "verbo"},
    {"id": "w2032", "it": "il seme", "nl": "het zaad", "ph": "SE-me",
     "ex": "Ho piantato i semi di basilico.", "exNl": "Ik heb basilicumzaadjes geplant.",
     "lesson": 223, "level": "B1", "cat": "sostantivo"},
    {"id": "w2033", "it": "la radice", "nl": "de wortel", "ph": "ra-DI-tsje",
     "ex": "Le radici dell'albero sono profonde.", "exNl": "De wortels van de boom zijn diep.",
     "lesson": 223, "level": "B1", "cat": "sostantivo"},
    {"id": "w2034", "it": "il raccolto", "nl": "de oogst", "ph": "rak-KOL-to",
     "ex": "Il raccolto di quest'anno è abbondante.", "exNl": "De oogst van dit jaar is overvloedig.",
     "lesson": 223, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 224: Landschappen & geografie ═══════════════════════════════════
    {"id": "w2035", "it": "il paesaggio", "nl": "het landschap", "ph": "pa-e-ZA-djo",
     "ex": "Il paesaggio toscano è bellissimo.", "exNl": "Het Toscaanse landschap is prachtig.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},
    {"id": "w2036", "it": "la collina", "nl": "de heuvel", "ph": "kol-LI-na",
     "ex": "La casa si trova sulla collina.", "exNl": "Het huis staat op de heuvel.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},
    {"id": "w2037", "it": "la pianura", "nl": "de vlakte", "ph": "pja-NU-ra",
     "ex": "La Pianura Padana è molto fertile.", "exNl": "De Povlakte is heel vruchtbaar.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},
    {"id": "w2038", "it": "la valle", "nl": "het dal", "ph": "VAL-le",
     "ex": "La valle è circondata da montagne.", "exNl": "Het dal is omringd door bergen.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},
    {"id": "w2039", "it": "il vulcano", "nl": "de vulkaan", "ph": "vul-KA-no",
     "ex": "L'Etna è un vulcano attivo.", "exNl": "De Etna is een actieve vulkaan.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},
    {"id": "w2040", "it": "il deserto", "nl": "de woestijn", "ph": "de-ZER-to",
     "ex": "Il Sahara è il deserto più grande.", "exNl": "De Sahara is de grootste woestijn.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},
    {"id": "w2041", "it": "la foresta", "nl": "het bos / het woud", "ph": "fo-RES-ta",
     "ex": "La foresta amazzonica è enorme.", "exNl": "Het Amazonewoud is enorm.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},
    {"id": "w2042", "it": "la penisola", "nl": "het schiereiland", "ph": "pe-NI-zo-la",
     "ex": "L'Italia è una penisola.", "exNl": "Italië is een schiereiland.",
     "lesson": 224, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 225: De zee & het strand ════════════════════════════════════════
    {"id": "w2043", "it": "la spiaggia", "nl": "het strand", "ph": "SPJA-dja",
     "ex": "Andiamo in spiaggia domani.", "exNl": "We gaan morgen naar het strand.",
     "lesson": 225, "level": "B1", "cat": "sostantivo"},
    {"id": "w2044", "it": "l'onda", "nl": "de golf", "ph": "ON-da",
     "ex": "Le onde sono molto alte oggi.", "exNl": "De golven zijn vandaag heel hoog.",
     "lesson": 225, "level": "B1", "cat": "sostantivo"},
    {"id": "w2045", "it": "la sabbia", "nl": "het zand", "ph": "SAB-bja",
     "ex": "I bambini giocano nella sabbia.", "exNl": "De kinderen spelen in het zand.",
     "lesson": 225, "level": "B1", "cat": "sostantivo"},
    {"id": "w2046", "it": "tuffarsi", "nl": "duiken", "ph": "tuf-FAR-si",
     "ex": "Mi piace tuffarmi nel mare.", "exNl": "Ik duik graag in de zee.",
     "lesson": 225, "level": "B1", "cat": "verbo"},
    {"id": "w2047", "it": "la costa", "nl": "de kust", "ph": "KOS-ta",
     "ex": "La costa amalfitana è famosa.", "exNl": "De Amalfikust is beroemd.",
     "lesson": 225, "level": "B1", "cat": "sostantivo"},
    {"id": "w2048", "it": "il porto", "nl": "de haven", "ph": "POR-to",
     "ex": "Le barche sono nel porto.", "exNl": "De boten liggen in de haven.",
     "lesson": 225, "level": "B1", "cat": "sostantivo"},
    {"id": "w2049", "it": "la conchiglia", "nl": "de schelp", "ph": "kon-KI-lja",
     "ex": "Ho trovato una bella conchiglia.", "exNl": "Ik heb een mooie schelp gevonden.",
     "lesson": 225, "level": "B1", "cat": "sostantivo"},
    {"id": "w2050", "it": "l'ombrellone", "nl": "de parasol (strand)", "ph": "om-brel-LO-ne",
     "ex": "Abbiamo affittato un ombrellone.", "exNl": "We hebben een parasol gehuurd.",
     "lesson": 225, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 226: Bergen & wandelen ══════════════════════════════════════════
    {"id": "w2051", "it": "la montagna", "nl": "de berg", "ph": "mon-TA-nja",
     "ex": "D'inverno andiamo in montagna.", "exNl": "In de winter gaan we naar de bergen.",
     "lesson": 226, "level": "B1", "cat": "sostantivo"},
    {"id": "w2052", "it": "il sentiero", "nl": "het pad", "ph": "sen-TJE-ro",
     "ex": "Il sentiero è ben segnalato.", "exNl": "Het pad is goed aangegeven.",
     "lesson": 226, "level": "B1", "cat": "sostantivo"},
    {"id": "w2053", "it": "la vetta", "nl": "de top (berg)", "ph": "VET-ta",
     "ex": "Abbiamo raggiunto la vetta!", "exNl": "We hebben de top bereikt!",
     "lesson": 226, "level": "B1", "cat": "sostantivo"},
    {"id": "w2054", "it": "arrampicarsi", "nl": "klimmen", "ph": "ar-ram-pi-KAR-si",
     "ex": "Mi piace arrampicarmi sulle rocce.", "exNl": "Ik klim graag op de rotsen.",
     "lesson": 226, "level": "B1", "cat": "verbo"},
    {"id": "w2055", "it": "il rifugio", "nl": "de berghut", "ph": "ri-FU-djo",
     "ex": "Dormiamo al rifugio questa notte.", "exNl": "We slapen vanavond in de berghut.",
     "lesson": 226, "level": "B1", "cat": "sostantivo"},
    {"id": "w2056", "it": "lo zaino", "nl": "de rugzak", "ph": "DZAI-no",
     "ex": "Ho messo tutto nello zaino.", "exNl": "Ik heb alles in de rugzak gedaan.",
     "lesson": 226, "level": "B1", "cat": "sostantivo"},
    {"id": "w2057", "it": "il ghiacciaio", "nl": "de gletsjer", "ph": "gjat-TJA-jo",
     "ex": "Il ghiacciaio si sta sciogliendo.", "exNl": "De gletsjer smelt.",
     "lesson": 226, "level": "B1", "cat": "sostantivo"},
    {"id": "w2058", "it": "l'escursione", "nl": "de wandeltocht", "ph": "es-kur-SJO-ne",
     "ex": "Facciamo un'escursione di tre ore.", "exNl": "We maken een wandeltocht van drie uur.",
     "lesson": 226, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 227: Klimaat & klimaatverandering ═══════════════════════════════
    {"id": "w2059", "it": "il clima", "nl": "het klimaat", "ph": "KLI-ma",
     "ex": "Il clima in Italia è mediterraneo.", "exNl": "Het klimaat in Italië is mediterraan.",
     "lesson": 227, "level": "B1", "cat": "sostantivo"},
    {"id": "w2060", "it": "il riscaldamento globale", "nl": "de opwarming van de aarde", "ph": "ris-kal-da-MEN-to glo-BA-le",
     "ex": "Il riscaldamento globale è un problema serio.", "exNl": "De opwarming van de aarde is een serieus probleem.",
     "lesson": 227, "level": "B1", "cat": "sostantivo"},
    {"id": "w2061", "it": "l'inquinamento", "nl": "de vervuiling", "ph": "in-kwi-na-MEN-to",
     "ex": "L'inquinamento dell'aria è grave.", "exNl": "De luchtvervuiling is ernstig.",
     "lesson": 227, "level": "B1", "cat": "sostantivo"},
    {"id": "w2062", "it": "la siccità", "nl": "de droogte", "ph": "sit-tsji-TA",
     "ex": "La siccità colpisce molte regioni.", "exNl": "De droogte treft veel regio's.",
     "lesson": 227, "level": "B1", "cat": "sostantivo"},
    {"id": "w2063", "it": "l'alluvione", "nl": "de overstroming", "ph": "al-lu-VJO-ne",
     "ex": "L'alluvione ha causato molti danni.", "exNl": "De overstroming heeft veel schade veroorzaakt.",
     "lesson": 227, "level": "B1", "cat": "sostantivo"},
    {"id": "w2064", "it": "l'effetto serra", "nl": "het broeikaseffect", "ph": "ef-FET-to SER-ra",
     "ex": "L'effetto serra aumenta le temperature.", "exNl": "Het broeikaseffect verhoogt de temperaturen.",
     "lesson": 227, "level": "B1", "cat": "sostantivo"},
    {"id": "w2065", "it": "sciogliersi", "nl": "smelten", "ph": "SJOL-jer-si",
     "ex": "I ghiacciai si stanno sciogliendo.", "exNl": "De gletsjers zijn aan het smelten.",
     "lesson": 227, "level": "B1", "cat": "verbo"},
    {"id": "w2066", "it": "la temperatura", "nl": "de temperatuur", "ph": "tem-pe-ra-TU-ra",
     "ex": "La temperatura è aumentata di due gradi.", "exNl": "De temperatuur is twee graden gestegen.",
     "lesson": 227, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 228: Duurzaamheid & recycling ═══════════════════════════════════
    {"id": "w2067", "it": "riciclare", "nl": "recyclen", "ph": "ri-tsji-KLA-re",
     "ex": "È importante riciclare la plastica.", "exNl": "Het is belangrijk om plastic te recyclen.",
     "lesson": 228, "level": "B1", "cat": "verbo"},
    {"id": "w2068", "it": "i rifiuti", "nl": "het afval", "ph": "ri-FJU-ti",
     "ex": "Non gettare i rifiuti per terra.", "exNl": "Gooi geen afval op de grond.",
     "lesson": 228, "level": "B1", "cat": "sostantivo"},
    {"id": "w2069", "it": "la sostenibilità", "nl": "de duurzaamheid", "ph": "sos-te-ni-bi-li-TA",
     "ex": "La sostenibilità è il futuro.", "exNl": "Duurzaamheid is de toekomst.",
     "lesson": 228, "level": "B1", "cat": "sostantivo"},
    {"id": "w2070", "it": "la raccolta differenziata", "nl": "het gescheiden inzamelen", "ph": "rak-KOL-ta dif-fe-ren-TSJA-ta",
     "ex": "Fai la raccolta differenziata?", "exNl": "Scheid jij je afval?",
     "lesson": 228, "level": "B1", "cat": "sostantivo"},
    {"id": "w2071", "it": "ridurre", "nl": "verminderen", "ph": "ri-DUR-re",
     "ex": "Dobbiamo ridurre i consumi.", "exNl": "We moeten het verbruik verminderen.",
     "lesson": 228, "level": "B1", "cat": "verbo"},
    {"id": "w2072", "it": "riutilizzare", "nl": "hergebruiken", "ph": "ri-u-ti-li-DZA-re",
     "ex": "Cerco di riutilizzare le borse.", "exNl": "Ik probeer de tassen te hergebruiken.",
     "lesson": 228, "level": "B1", "cat": "verbo"},
    {"id": "w2073", "it": "lo spreco", "nl": "de verspilling", "ph": "SPRE-ko",
     "ex": "Lo spreco alimentare è un problema.", "exNl": "Voedselverspilling is een probleem.",
     "lesson": 228, "level": "B1", "cat": "sostantivo"},
    {"id": "w2074", "it": "ecologico", "nl": "ecologisch", "ph": "e-ko-LO-dji-ko",
     "ex": "Questo prodotto è ecologico.", "exNl": "Dit product is ecologisch.",
     "lesson": 228, "level": "B1", "cat": "aggettivo"},

    # ═══ LES 229: Energie & grondstoffen ═════════════════════════════════════
    {"id": "w2075", "it": "l'energia", "nl": "de energie", "ph": "e-ner-DJI-a",
     "ex": "L'energia solare è rinnovabile.", "exNl": "Zonne-energie is hernieuwbaar.",
     "lesson": 229, "level": "B1", "cat": "sostantivo"},
    {"id": "w2076", "it": "il petrolio", "nl": "de aardolie", "ph": "pe-TRO-ljo",
     "ex": "Il petrolio è una risorsa limitata.", "exNl": "Aardolie is een beperkte grondstof.",
     "lesson": 229, "level": "B1", "cat": "sostantivo"},
    {"id": "w2077", "it": "il pannello solare", "nl": "het zonnepaneel", "ph": "pan-NEL-lo so-LA-re",
     "ex": "Abbiamo installato i pannelli solari.", "exNl": "We hebben zonnepanelen geïnstalleerd.",
     "lesson": 229, "level": "B1", "cat": "sostantivo"},
    {"id": "w2078", "it": "rinnovabile", "nl": "hernieuwbaar", "ph": "rin-no-VA-bi-le",
     "ex": "Le fonti rinnovabili sono il futuro.", "exNl": "Hernieuwbare bronnen zijn de toekomst.",
     "lesson": 229, "level": "B1", "cat": "aggettivo"},
    {"id": "w2079", "it": "il carbone", "nl": "de steenkool", "ph": "kar-BO-ne",
     "ex": "Il carbone inquina molto.", "exNl": "Steenkool vervuilt veel.",
     "lesson": 229, "level": "B1", "cat": "sostantivo"},
    {"id": "w2080", "it": "la risorsa", "nl": "de grondstof", "ph": "ri-ZOR-sa",
     "ex": "Le risorse naturali sono preziose.", "exNl": "Natuurlijke grondstoffen zijn waardevol.",
     "lesson": 229, "level": "B1", "cat": "sostantivo"},
    {"id": "w2081", "it": "consumare", "nl": "verbruiken", "ph": "kon-su-MA-re",
     "ex": "Questa auto consuma poca benzina.", "exNl": "Deze auto verbruikt weinig benzine.",
     "lesson": 229, "level": "B1", "cat": "verbo"},
    {"id": "w2082", "it": "la centrale nucleare", "nl": "de kerncentrale", "ph": "tsjen-TRA-le nu-kle-A-re",
     "ex": "L'Italia non ha centrali nucleari.", "exNl": "Italië heeft geen kerncentrales.",
     "lesson": 229, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 230: Toetsles B1 — Blok 11 (les 221–230) ═══════════════════════
    {"id": "w2083", "it": "la natura", "nl": "de natuur", "ph": "na-TU-ra",
     "ex": "Amo stare nella natura.", "exNl": "Ik hou ervan om in de natuur te zijn.",
     "lesson": 230, "level": "B1", "cat": "sostantivo"},
    {"id": "w2084", "it": "l'ambiente", "nl": "het milieu", "ph": "am-BJEN-te",
     "ex": "Dobbiamo proteggere l'ambiente.", "exNl": "We moeten het milieu beschermen.",
     "lesson": 230, "level": "B1", "cat": "sostantivo"},
    {"id": "w2085", "it": "la specie", "nl": "de diersoort", "ph": "SPE-tsje",
     "ex": "Molte specie sono in pericolo.", "exNl": "Veel diersoorten zijn in gevaar.",
     "lesson": 230, "level": "B1", "cat": "sostantivo"},
    {"id": "w2086", "it": "proteggere", "nl": "beschermen", "ph": "pro-TED-dje-re",
     "ex": "Bisogna proteggere gli animali.", "exNl": "We moeten de dieren beschermen.",
     "lesson": 230, "level": "B1", "cat": "verbo"},
    {"id": "w2087", "it": "il ghiaccio", "nl": "het ijs", "ph": "GJAT-tsjo",
     "ex": "Il ghiaccio si scioglie al sole.", "exNl": "Het ijs smelt in de zon.",
     "lesson": 230, "level": "B1", "cat": "sostantivo"},
    {"id": "w2088", "it": "la cascata", "nl": "de waterval", "ph": "kas-KA-ta",
     "ex": "La cascata è spettacolare.", "exNl": "De waterval is spectaculair.",
     "lesson": 230, "level": "B1", "cat": "sostantivo"},
    {"id": "w2089", "it": "inquinare", "nl": "vervuilen", "ph": "in-kwi-NA-re",
     "ex": "Le fabbriche inquinano l'aria.", "exNl": "De fabrieken vervuilen de lucht.",
     "lesson": 230, "level": "B1", "cat": "verbo"},
    {"id": "w2090", "it": "selvaggio", "nl": "wild", "ph": "sel-VA-djo",
     "ex": "Questo è un paesaggio selvaggio.", "exNl": "Dit is een wild landschap.",
     "lesson": 230, "level": "B1", "cat": "aggettivo"},

    # ═══ LES 231: Film & bioscoop ════════════════════════════════════════════
    {"id": "w2091", "it": "il regista", "nl": "de regisseur", "ph": "re-DJIS-ta",
     "ex": "Il regista ha vinto un premio.", "exNl": "De regisseur heeft een prijs gewonnen.",
     "lesson": 231, "level": "B1", "cat": "sostantivo"},
    {"id": "w2092", "it": "la scena", "nl": "de scène", "ph": "SJE-na",
     "ex": "Quella scena era molto emozionante.", "exNl": "Die scène was heel ontroerend.",
     "lesson": 231, "level": "B1", "cat": "sostantivo"},
    {"id": "w2093", "it": "la trama", "nl": "het plot", "ph": "TRA-ma",
     "ex": "La trama del film è avvincente.", "exNl": "Het plot van de film is meeslepend.",
     "lesson": 231, "level": "B1", "cat": "sostantivo"},
    {"id": "w2094", "it": "il sottotitolo", "nl": "de ondertitel", "ph": "sot-to-TI-to-lo",
     "ex": "Guardo i film con i sottotitoli.", "exNl": "Ik kijk films met ondertitels.",
     "lesson": 231, "level": "B1", "cat": "sostantivo"},
    {"id": "w2095", "it": "girare", "nl": "filmen / draaien", "ph": "dji-RA-re",
     "ex": "Hanno girato il film a Roma.", "exNl": "Ze hebben de film in Rome gedraaid.",
     "lesson": 231, "level": "B1", "cat": "verbo"},
    {"id": "w2096", "it": "il documentario", "nl": "de documentaire", "ph": "do-ku-men-TA-rjo",
     "ex": "Ho visto un documentario sulla natura.", "exNl": "Ik heb een documentaire over de natuur gezien.",
     "lesson": 231, "level": "B1", "cat": "sostantivo"},
    {"id": "w2097", "it": "il personaggio", "nl": "het personage", "ph": "per-so-NA-djo",
     "ex": "Il personaggio principale è molto forte.", "exNl": "Het hoofdpersonage is heel sterk.",
     "lesson": 231, "level": "B1", "cat": "sostantivo"},
    {"id": "w2098", "it": "la colonna sonora", "nl": "de filmmuziek", "ph": "ko-LON-na so-NO-ra",
     "ex": "La colonna sonora è bellissima.", "exNl": "De filmmuziek is prachtig.",
     "lesson": 231, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 232: Theater & opera ════════════════════════════════════════════
    {"id": "w2099", "it": "il palcoscenico", "nl": "het podium", "ph": "pal-ko-SJE-ni-ko",
     "ex": "Gli attori sono sul palcoscenico.", "exNl": "De acteurs staan op het podium.",
     "lesson": 232, "level": "B1", "cat": "sostantivo"},
    {"id": "w2100", "it": "la rappresentazione", "nl": "de voorstelling", "ph": "rap-pre-zen-ta-TSJO-ne",
     "ex": "La rappresentazione inizia alle otto.", "exNl": "De voorstelling begint om acht uur.",
     "lesson": 232, "level": "B1", "cat": "sostantivo"},
    {"id": "w2101", "it": "l'atto", "nl": "het bedrijf (theater)", "ph": "AT-to",
     "ex": "L'opera ha tre atti.", "exNl": "De opera heeft drie bedrijven.",
     "lesson": 232, "level": "B1", "cat": "sostantivo"},
    {"id": "w2102", "it": "il sipario", "nl": "het gordijn (toneel)", "ph": "si-PA-rjo",
     "ex": "Il sipario si alza lentamente.", "exNl": "Het gordijn gaat langzaam omhoog.",
     "lesson": 232, "level": "B1", "cat": "sostantivo"},
    {"id": "w2103", "it": "applaudire", "nl": "applaudisseren", "ph": "ap-plau-DI-re",
     "ex": "Il pubblico ha applaudito a lungo.", "exNl": "Het publiek heeft lang geapplaudisseerd.",
     "lesson": 232, "level": "B1", "cat": "verbo"},
    {"id": "w2104", "it": "il soprano", "nl": "de sopraan", "ph": "so-PRA-no",
     "ex": "Il soprano ha una voce straordinaria.", "exNl": "De sopraan heeft een buitengewone stem.",
     "lesson": 232, "level": "B1", "cat": "sostantivo"},
    {"id": "w2105", "it": "la regia", "nl": "de regie", "ph": "re-DJI-a",
     "ex": "La regia dello spettacolo è eccellente.", "exNl": "De regie van de voorstelling is uitstekend.",
     "lesson": 232, "level": "B1", "cat": "sostantivo"},
    {"id": "w2106", "it": "recitare", "nl": "acteren / toneelspelen", "ph": "re-tsji-TA-re",
     "ex": "Da bambina sognava di recitare.", "exNl": "Als kind droomde ze ervan om te acteren.",
     "lesson": 232, "level": "B1", "cat": "verbo"},

    # ═══ LES 233: Schilderkunst & musea ══════════════════════════════════════
    {"id": "w2107", "it": "il quadro", "nl": "het schilderij", "ph": "KWA-dro",
     "ex": "Questo quadro è un capolavoro.", "exNl": "Dit schilderij is een meesterwerk.",
     "lesson": 233, "level": "B1", "cat": "sostantivo"},
    {"id": "w2108", "it": "la mostra", "nl": "de tentoonstelling", "ph": "MOS-tra",
     "ex": "La mostra chiude a fine mese.", "exNl": "De tentoonstelling sluit eind deze maand.",
     "lesson": 233, "level": "B1", "cat": "sostantivo"},
    {"id": "w2109", "it": "il capolavoro", "nl": "het meesterwerk", "ph": "ka-po-la-VO-ro",
     "ex": "La Gioconda è un capolavoro.", "exNl": "De Mona Lisa is een meesterwerk.",
     "lesson": 233, "level": "B1", "cat": "sostantivo"},
    {"id": "w2110", "it": "la scultura", "nl": "het beeldhouwwerk", "ph": "skul-TU-ra",
     "ex": "La scultura è fatta di marmo.", "exNl": "Het beeldhouwwerk is van marmer gemaakt.",
     "lesson": 233, "level": "B1", "cat": "sostantivo"},
    {"id": "w2111", "it": "dipingere", "nl": "schilderen", "ph": "di-PIN-dje-re",
     "ex": "Leonardo dipingeva con grande maestria.", "exNl": "Leonardo schilderde met groot meesterschap.",
     "lesson": 233, "level": "B1", "cat": "verbo"},
    {"id": "w2112", "it": "il pennello", "nl": "het penseel", "ph": "pen-NEL-lo",
     "ex": "L'artista usa un pennello sottile.", "exNl": "De kunstenaar gebruikt een dun penseel.",
     "lesson": 233, "level": "B1", "cat": "sostantivo"},
    {"id": "w2113", "it": "l'affresco", "nl": "het fresco", "ph": "af-FRES-ko",
     "ex": "Gli affreschi della Cappella Sistina sono famosi.", "exNl": "De fresco's van de Sixtijnse Kapel zijn beroemd.",
     "lesson": 233, "level": "B1", "cat": "sostantivo"},
    {"id": "w2114", "it": "il ritratto", "nl": "het portret", "ph": "ri-TRAT-to",
     "ex": "Ha dipinto il ritratto di sua madre.", "exNl": "Hij heeft het portret van zijn moeder geschilderd.",
     "lesson": 233, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 234: Fotografie & design ════════════════════════════════════════
    {"id": "w2115", "it": "la fotografia", "nl": "de fotografie", "ph": "fo-to-gra-FI-a",
     "ex": "La fotografia è la mia passione.", "exNl": "Fotografie is mijn passie.",
     "lesson": 234, "level": "B1", "cat": "sostantivo"},
    {"id": "w2116", "it": "l'obiettivo", "nl": "de lens (camera)", "ph": "o-bjet-TI-vo",
     "ex": "Ho comprato un nuovo obiettivo.", "exNl": "Ik heb een nieuwe lens gekocht.",
     "lesson": 234, "level": "B1", "cat": "sostantivo"},
    {"id": "w2117", "it": "lo scatto", "nl": "de foto / het shot", "ph": "SKAT-to",
     "ex": "Che bello scatto!", "exNl": "Wat een mooie foto!",
     "lesson": 234, "level": "B1", "cat": "sostantivo"},
    {"id": "w2118", "it": "inquadrare", "nl": "kaderen / in beeld brengen", "ph": "in-kwa-DRA-re",
     "ex": "Devi inquadrare meglio il soggetto.", "exNl": "Je moet het onderwerp beter kaderen.",
     "lesson": 234, "level": "B1", "cat": "verbo"},
    {"id": "w2119", "it": "il design", "nl": "het design", "ph": "di-ZAIN",
     "ex": "Il design italiano è famoso nel mondo.", "exNl": "Italiaans design is wereldberoemd.",
     "lesson": 234, "level": "B1", "cat": "sostantivo"},
    {"id": "w2120", "it": "creativo", "nl": "creatief", "ph": "kre-a-TI-vo",
     "ex": "È una persona molto creativa.", "exNl": "Het is een heel creatief persoon.",
     "lesson": 234, "level": "B1", "cat": "aggettivo"},
    {"id": "w2121", "it": "l'immagine", "nl": "het beeld / de afbeelding", "ph": "im-MA-dji-ne",
     "ex": "Questa immagine è molto suggestiva.", "exNl": "Dit beeld is heel sfeervol.",
     "lesson": 234, "level": "B1", "cat": "sostantivo"},
    {"id": "w2122", "it": "lo stile", "nl": "de stijl", "ph": "STI-le",
     "ex": "Il suo stile è molto originale.", "exNl": "Zijn stijl is heel origineel.",
     "lesson": 234, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 235: Kranten & journalistiek ════════════════════════════════════
    {"id": "w2123", "it": "il giornalista", "nl": "de journalist", "ph": "djor-na-LIS-ta",
     "ex": "Il giornalista ha scritto un bell'articolo.", "exNl": "De journalist heeft een mooi artikel geschreven.",
     "lesson": 235, "level": "B1", "cat": "sostantivo"},
    {"id": "w2124", "it": "l'articolo", "nl": "het artikel", "ph": "ar-TI-ko-lo",
     "ex": "Ho letto un articolo interessante.", "exNl": "Ik heb een interessant artikel gelezen.",
     "lesson": 235, "level": "B1", "cat": "sostantivo"},
    {"id": "w2125", "it": "la notizia", "nl": "het nieuws(bericht)", "ph": "no-TI-tsja",
     "ex": "Hai sentito la notizia?", "exNl": "Heb je het nieuws gehoord?",
     "lesson": 235, "level": "B1", "cat": "sostantivo"},
    {"id": "w2126", "it": "la stampa", "nl": "de pers", "ph": "STAM-pa",
     "ex": "La stampa ha riportato la notizia.", "exNl": "De pers heeft het nieuws gemeld.",
     "lesson": 235, "level": "B1", "cat": "sostantivo"},
    {"id": "w2127", "it": "pubblicare", "nl": "publiceren", "ph": "pub-bli-KA-re",
     "ex": "Hanno pubblicato il libro ieri.", "exNl": "Ze hebben het boek gisteren gepubliceerd.",
     "lesson": 235, "level": "B1", "cat": "verbo"},
    {"id": "w2128", "it": "l'intervista", "nl": "het interview", "ph": "in-ter-VIS-ta",
     "ex": "L'intervista è stata molto interessante.", "exNl": "Het interview was heel interessant.",
     "lesson": 235, "level": "B1", "cat": "sostantivo"},
    {"id": "w2129", "it": "il titolo", "nl": "de titel / kop", "ph": "TI-to-lo",
     "ex": "Il titolo dell'articolo è accattivante.", "exNl": "De kop van het artikel is pakkend.",
     "lesson": 235, "level": "B1", "cat": "sostantivo"},
    {"id": "w2130", "it": "la redazione", "nl": "de redactie", "ph": "re-da-TSJO-ne",
     "ex": "Lavora nella redazione del giornale.", "exNl": "Ze werkt op de redactie van de krant.",
     "lesson": 235, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 236: Radio & televisie ══════════════════════════════════════════
    {"id": "w2131", "it": "il telegiornale", "nl": "het journaal", "ph": "te-le-djor-NA-le",
     "ex": "Guardo il telegiornale ogni sera.", "exNl": "Ik kijk elke avond naar het journaal.",
     "lesson": 236, "level": "B1", "cat": "sostantivo"},
    {"id": "w2132", "it": "la trasmissione", "nl": "de uitzending", "ph": "traz-mis-SJO-ne",
     "ex": "La trasmissione inizia alle nove.", "exNl": "De uitzending begint om negen uur.",
     "lesson": 236, "level": "B1", "cat": "sostantivo"},
    {"id": "w2133", "it": "il canale", "nl": "het kanaal / de zender", "ph": "ka-NA-le",
     "ex": "Cambia canale, per favore.", "exNl": "Zap naar een ander kanaal, alsjeblieft.",
     "lesson": 236, "level": "B1", "cat": "sostantivo"},
    {"id": "w2134", "it": "il conduttore", "nl": "de presentator", "ph": "kon-dut-TO-re",
     "ex": "Il conduttore è molto simpatico.", "exNl": "De presentator is heel sympathiek.",
     "lesson": 236, "level": "B1", "cat": "sostantivo"},
    {"id": "w2135", "it": "trasmettere", "nl": "uitzenden", "ph": "traz-MET-te-re",
     "ex": "Trasmettono la partita in diretta.", "exNl": "Ze zenden de wedstrijd live uit.",
     "lesson": 236, "level": "B1", "cat": "verbo"},
    {"id": "w2136", "it": "il telespettatore", "nl": "de televisiekijker", "ph": "te-le-spet-ta-TO-re",
     "ex": "Il programma ha milioni di telespettatori.", "exNl": "Het programma heeft miljoenen kijkers.",
     "lesson": 236, "level": "B1", "cat": "sostantivo"},
    {"id": "w2137", "it": "l'emittente", "nl": "de omroep / zender", "ph": "e-mit-TEN-te",
     "ex": "L'emittente ha sede a Milano.", "exNl": "De omroep is gevestigd in Milaan.",
     "lesson": 236, "level": "B1", "cat": "sostantivo"},
    {"id": "w2138", "it": "in diretta", "nl": "live / rechtstreeks", "ph": "in di-RET-ta",
     "ex": "Lo spettacolo va in diretta.", "exNl": "De show is live.",
     "lesson": 236, "level": "B1", "cat": "espressione"},

    # ═══ LES 237: Reclame & marketing ════════════════════════════════════════
    {"id": "w2139", "it": "la pubblicità", "nl": "de reclame", "ph": "pub-bli-tsji-TA",
     "ex": "La pubblicità in TV è troppa.", "exNl": "Er is te veel reclame op tv.",
     "lesson": 237, "level": "B1", "cat": "sostantivo"},
    {"id": "w2140", "it": "il marchio", "nl": "het merk", "ph": "MAR-kjo",
     "ex": "Questo marchio è molto conosciuto.", "exNl": "Dit merk is heel bekend.",
     "lesson": 237, "level": "B1", "cat": "sostantivo"},
    {"id": "w2141", "it": "lo slogan", "nl": "de slogan", "ph": "SLO-gan",
     "ex": "Lo slogan è facile da ricordare.", "exNl": "De slogan is makkelijk te onthouden.",
     "lesson": 237, "level": "B1", "cat": "sostantivo"},
    {"id": "w2142", "it": "il consumatore", "nl": "de consument", "ph": "kon-su-ma-TO-re",
     "ex": "Il consumatore ha diritto all'informazione.", "exNl": "De consument heeft recht op informatie.",
     "lesson": 237, "level": "B1", "cat": "sostantivo"},
    {"id": "w2143", "it": "promuovere", "nl": "promoten / bevorderen", "ph": "pro-MWO-ve-re",
     "ex": "Dobbiamo promuovere il nuovo prodotto.", "exNl": "We moeten het nieuwe product promoten.",
     "lesson": 237, "level": "B1", "cat": "verbo"},
    {"id": "w2144", "it": "la campagna", "nl": "de campagne", "ph": "kam-PA-nja",
     "ex": "La campagna pubblicitaria è efficace.", "exNl": "De reclamecampagne is effectief.",
     "lesson": 237, "level": "B1", "cat": "sostantivo"},
    {"id": "w2145", "it": "il target", "nl": "de doelgroep", "ph": "TAR-get",
     "ex": "Il target sono i giovani.", "exNl": "De doelgroep is jongeren.",
     "lesson": 237, "level": "B1", "cat": "sostantivo"},
    {"id": "w2146", "it": "influenzare", "nl": "beïnvloeden", "ph": "in-flu-en-TSA-re",
     "ex": "La pubblicità può influenzare le scelte.", "exNl": "Reclame kan keuzes beïnvloeden.",
     "lesson": 237, "level": "B1", "cat": "verbo"},

    # ═══ LES 238: Mode & trends ══════════════════════════════════════════════
    {"id": "w2147", "it": "la moda", "nl": "de mode", "ph": "MO-da",
     "ex": "Milano è la capitale della moda.", "exNl": "Milaan is de hoofdstad van de mode.",
     "lesson": 238, "level": "B1", "cat": "sostantivo"},
    {"id": "w2148", "it": "la tendenza", "nl": "de trend", "ph": "ten-DEN-tsa",
     "ex": "Le tendenze cambiano ogni stagione.", "exNl": "De trends veranderen elk seizoen.",
     "lesson": 238, "level": "B1", "cat": "sostantivo"},
    {"id": "w2149", "it": "lo stilista", "nl": "de modeontwerper", "ph": "sti-LIS-ta",
     "ex": "Lo stilista ha presentato la nuova collezione.", "exNl": "De modeontwerper heeft de nieuwe collectie gepresenteerd.",
     "lesson": 238, "level": "B1", "cat": "sostantivo"},
    {"id": "w2150", "it": "la sfilata", "nl": "de modeshow", "ph": "sfi-LA-ta",
     "ex": "La sfilata è stata spettacolare.", "exNl": "De modeshow was spectaculair.",
     "lesson": 238, "level": "B1", "cat": "sostantivo"},
    {"id": "w2151", "it": "elegante", "nl": "elegant", "ph": "e-le-GAN-te",
     "ex": "Sei molto elegante questa sera.", "exNl": "Je bent heel elegant vanavond.",
     "lesson": 238, "level": "B1", "cat": "aggettivo"},
    {"id": "w2152", "it": "il tessuto", "nl": "de stof / het textiel", "ph": "tes-SU-to",
     "ex": "Questo tessuto è di alta qualità.", "exNl": "Deze stof is van hoge kwaliteit.",
     "lesson": 238, "level": "B1", "cat": "sostantivo"},
    {"id": "w2153", "it": "la collezione", "nl": "de collectie", "ph": "kol-le-TSJO-ne",
     "ex": "La collezione autunno-inverno è bella.", "exNl": "De herfst-wintercollectie is mooi.",
     "lesson": 238, "level": "B1", "cat": "sostantivo"},
    {"id": "w2154", "it": "indossare", "nl": "dragen (kleding)", "ph": "in-dos-SA-re",
     "ex": "Indossa un vestito rosso.", "exNl": "Ze draagt een rode jurk.",
     "lesson": 238, "level": "B1", "cat": "verbo"},

    # ═══ LES 239: Evenementen & festivals ════════════════════════════════════
    {"id": "w2155", "it": "l'evento", "nl": "het evenement", "ph": "e-VEN-to",
     "ex": "L'evento è stato un grande successo.", "exNl": "Het evenement was een groot succes.",
     "lesson": 239, "level": "B1", "cat": "sostantivo"},
    {"id": "w2156", "it": "il festival", "nl": "het festival", "ph": "FES-ti-val",
     "ex": "Il festival del cinema è a Venezia.", "exNl": "Het filmfestival is in Venetië.",
     "lesson": 239, "level": "B1", "cat": "sostantivo"},
    {"id": "w2157", "it": "la fiera", "nl": "de beurs / kermis", "ph": "FJE-ra",
     "ex": "La fiera del libro è molto grande.", "exNl": "De boekenbeurs is heel groot.",
     "lesson": 239, "level": "B1", "cat": "sostantivo"},
    {"id": "w2158", "it": "il palco", "nl": "het podium (buiten)", "ph": "PAL-ko",
     "ex": "Il cantante è salito sul palco.", "exNl": "De zanger is het podium opgegaan.",
     "lesson": 239, "level": "B1", "cat": "sostantivo"},
    {"id": "w2159", "it": "organizzare", "nl": "organiseren", "ph": "or-ga-ni-DZA-re",
     "ex": "Chi organizza l'evento?", "exNl": "Wie organiseert het evenement?",
     "lesson": 239, "level": "B1", "cat": "verbo"},
    {"id": "w2160", "it": "il biglietto", "nl": "het kaartje", "ph": "bi-LJET-to",
     "ex": "Ho comprato i biglietti per il concerto.", "exNl": "Ik heb kaartjes voor het concert gekocht.",
     "lesson": 239, "level": "B1", "cat": "sostantivo"},
    {"id": "w2161", "it": "la cerimonia", "nl": "de ceremonie", "ph": "tsje-ri-MO-nja",
     "ex": "La cerimonia di apertura è stata bellissima.", "exNl": "De openingsceremonie was prachtig.",
     "lesson": 239, "level": "B1", "cat": "sostantivo"},
    {"id": "w2162", "it": "lo spettacolo", "nl": "de show / het spektakel", "ph": "spet-TA-ko-lo",
     "ex": "Lo spettacolo è stato incredibile.", "exNl": "De show was ongelooflijk.",
     "lesson": 239, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 240: Toetsles B1 — Blok 12 (les 231–240) ═══════════════════════
    {"id": "w2163", "it": "l'opera", "nl": "het (kunst)werk / de opera", "ph": "O-pe-ra",
     "ex": "Questa è un'opera d'arte straordinaria.", "exNl": "Dit is een buitengewoon kunstwerk.",
     "lesson": 240, "level": "B1", "cat": "sostantivo"},
    {"id": "w2164", "it": "il pubblico", "nl": "het publiek", "ph": "PUB-bli-ko",
     "ex": "Il pubblico ha applaudito con entusiasmo.", "exNl": "Het publiek heeft enthousiast geapplaudisseerd.",
     "lesson": 240, "level": "B1", "cat": "sostantivo"},
    {"id": "w2165", "it": "ispirare", "nl": "inspireren", "ph": "is-pi-RA-re",
     "ex": "L'Italia mi ispira molto.", "exNl": "Italië inspireert me heel erg.",
     "lesson": 240, "level": "B1", "cat": "verbo"},
    {"id": "w2166", "it": "la critica", "nl": "de kritiek", "ph": "KRI-ti-ka",
     "ex": "La critica ha elogiato il film.", "exNl": "De kritiek heeft de film geprezen.",
     "lesson": 240, "level": "B1", "cat": "sostantivo"},
    {"id": "w2167", "it": "il capolavoro", "nl": "het meesterwerk", "ph": "ka-po-la-VO-ro",
     "ex": "Il David di Michelangelo è un capolavoro.", "exNl": "De David van Michelangelo is een meesterwerk.",
     "lesson": 240, "level": "B1", "cat": "sostantivo"},
    {"id": "w2168", "it": "contemporaneo", "nl": "hedendaags", "ph": "kon-tem-po-RA-ne-o",
     "ex": "Mi piace l'arte contemporanea.", "exNl": "Ik hou van hedendaagse kunst.",
     "lesson": 240, "level": "B1", "cat": "aggettivo"},
    {"id": "w2169", "it": "il premio", "nl": "de prijs (onderscheiding)", "ph": "PRE-mjo",
     "ex": "Ha vinto il premio come miglior attore.", "exNl": "Hij heeft de prijs voor beste acteur gewonnen.",
     "lesson": 240, "level": "B1", "cat": "sostantivo"},
    {"id": "w2170", "it": "la cultura", "nl": "de cultuur", "ph": "kul-TU-ra",
     "ex": "La cultura italiana è ricchissima.", "exNl": "De Italiaanse cultuur is heel rijk.",
     "lesson": 240, "level": "B1", "cat": "sostantivo"},
]
