#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_es_b1_blok3.py — Spaans B1 blok 3 (v1.60: lessen 241–300). Thema-opbouw gespiegeld aan Italiaans B1,
met Spaanse grammatica (passiva met ser/se, imperativo formal, hacer + infinitivo, verbos pronominales, herhaling van alle tijden).
Vervangt alleen les 241–300 in de bestaande Spaanse data; IDs lopen door vanaf het hoogste bestaande ID.
Draai opnieuw na bewerken: python3 scripts/generate_es_b1_blok3.py
Formaat: L(id, emoji, title, description, grammar_title, grammar_body, [ (es, nl, ph, ex, exNl, cat) × 8 ])
"""
import json, re
from pathlib import Path

OUT = Path(__file__).parent.parent / 'www' / 'data' / 'es'
FIRST, LAST = 241, 300

def L(id, emoji, title, desc, gt, gb, words):
    return dict(id=id, emoji=emoji, title=title, description=desc, grammar=dict(title=gt, body=gb), words=words)

LESSONS = [
L(241, '🏛️', 'Politiek — basis', 'De passieve vorm met ser en se.',
  'Passiva met ser en pasiva refleja', 'Ser + participio: La ley fue aprobada por el Parlamento. Pasiva refleja (vaker): Se aprobó la ley. Se eligen los diputados cada cuatro años. Herkenning volstaat op B1.',
  [('el parlamento', 'het parlement', 'el par-la-MEN-to', 'El Parlamento aprobó la reforma.', 'Het parlement nam de hervorming aan.', 'politica'),
   ('el presidente del gobierno', 'de premier', 'el pre-si-DEN-te del go-BJER-no', 'El presidente del gobierno compareció ante la prensa.', 'De premier verscheen voor de pers.', 'politica'),
   ('el diputado', 'het parlementslid', 'el di-poe-TA-do', 'Los diputados debaten la ley.', 'De parlementsleden debatteren over de wet.', 'politica'),
   ('aprobar una ley', 'een wet aannemen', 'a-pro-BAR OE-na lei', 'La ley fue aprobada ayer.', 'De wet werd gisteren aangenomen.', 'espressione'),
   ('el ministro', 'de minister', 'el mi-NIS-tro', 'El ministro de Sanidad dimitió.', 'De minister van Volksgezondheid trad af.', 'politica'),
   ('la oposición', 'de oppositie', 'la o-po-si-SJON', 'La oposición critica la medida.', 'De oppositie bekritiseert de maatregel.', 'politica'),
   ('el alcalde', 'de burgemeester', 'el al-KAL-de', 'El alcalde inauguró el parque.', 'De burgemeester opende het park.', 'politica'),
   ('la medida', 'de maatregel', 'la me-DIE-da', 'Es una medida impopular.', 'Het is een impopulaire maatregel.', 'politica')]),
L(242, '🗳️', 'Verkiezingen & democratie', 'Over verkiezingen praten.',
  'Over verkiezingen praten', 'Votar, las elecciones generales / municipales, la campaña electoral, el candidato, la mayoría absoluta, la abstención, el escaño (de zetel), la urna (de stembus).',
  [('el votante', 'de kiezer', 'el vo-TAN-te', 'Los votantes jóvenes son decisivos.', 'Jonge kiezers zijn beslissend.', 'politica'),
   ('el sondeo', 'de peiling', 'el son-DE-o', 'Los sondeos dan empate.', 'De peilingen voorspellen een gelijkspel.', 'politica'),
   ('la campaña electoral', 'de verkiezingscampagne', 'la kam-PA-nja e-lek-to-RAL', 'La campaña electoral dura quince días.', 'De verkiezingscampagne duurt vijftien dagen.', 'politica'),
   ('el escaño', 'de zetel (parlement)', 'el es-KA-njo', 'Ganaron veinte escaños.', 'Ze wonnen twintig zetels.', 'politica'),
   ('la mayoría absoluta', 'de absolute meerderheid', 'la ma-jo-RIE-a ab-so-LOE-ta', 'Nadie obtuvo la mayoría absoluta.', 'Niemand behaalde de absolute meerderheid.', 'politica'),
   ('la abstención', 'het thuisblijven / de onthouding', 'la abs-ten-SJON', 'La abstención fue del cuarenta por ciento.', 'Veertig procent bleef thuis.', 'politica'),
   ('la urna', 'de stembus', 'la OER-na', 'Los ciudadanos acudieron a las urnas.', 'De burgers gingen naar de stembus.', 'politica'),
   ('la coalición', 'de coalitie', 'la ko-a-li-SJON', 'Formaron una coalición de gobierno.', 'Ze vormden een regeringscoalitie.', 'politica')]),
L(243, '⚖️', 'Rechten & plichten', 'Rechten en plichten.',
  'Rechten en plichten', 'Tener derecho a (recht hebben op), estar obligado a (verplicht zijn), la igualdad ante la ley, la libertad de expresión, el deber (de plicht), cumplir con (nakomen).',
  [('la obligación', 'de verplichting', 'la o-bli-ga-SJON', 'Es una obligación legal.', 'Het is een wettelijke verplichting.', 'politica'),
   ('el deber', 'de plicht', 'el de-BER', 'Votar es un deber cívico.', 'Stemmen is een burgerplicht.', 'politica'),
   ('estar obligado a', 'verplicht zijn om', 'es-TAR o-bli-GA-do a', 'Estás obligado a declarar.', 'Je bent verplicht aangifte te doen.', 'espressione'),
   ('cumplir con', 'nakomen / voldoen aan', 'koem-PLIER kon', 'Cumplió con su obligación.', 'Hij kwam zijn verplichting na.', 'verbo'),
   ('la igualdad ante la ley', 'de gelijkheid voor de wet', 'la i-gwal-DAD AN-te la lei', 'La igualdad ante la ley es un principio básico.', 'Gelijkheid voor de wet is een basisprincipe.', 'politica'),
   ('el ciudadano de a pie', 'de gewone burger', 'el sjoe-da-DA-no de a pje', 'El ciudadano de a pie no lo entiende.', 'De gewone burger begrijpt het niet.', 'espressione'),
   ('los derechos humanos', 'de mensenrechten', 'los de-RE-tsjos oe-MA-nos', 'Defienden los derechos humanos.', 'Ze verdedigen de mensenrechten.', 'politica'),
   ('el referéndum', 'het referendum', 'el rre-fe-REN-doem', 'Convocaron un referéndum.', 'Ze schreven een referendum uit.', 'politica')]),
L(244, '⚖️', 'Justitie & wetgeving', 'Juridische taal.',
  'Juridische taal', 'El juez (de rechter), el abogado, el juicio (het proces), el acusado, la sentencia (het vonnis), condenar, absolver (vrijspreken), la multa, denunciar (aangifte doen).',
  [('el juez', 'de rechter', 'el chwes', 'El juez dictó sentencia.', 'De rechter sprak het vonnis uit.', 'giustizia'),
   ('el juicio', 'het proces / de rechtszaak', 'el CHWI-sjo', 'El juicio empieza el lunes.', 'Het proces begint maandag.', 'giustizia'),
   ('el acusado', 'de verdachte / beklaagde', 'el a-koe-SA-do', 'El acusado se declaró inocente.', 'De verdachte pleitte onschuldig.', 'giustizia'),
   ('la sentencia', 'het vonnis', 'la sen-TEN-sja', 'La sentencia fue muy dura.', 'Het vonnis was heel zwaar.', 'giustizia'),
   ('condenar', 'veroordelen', 'kon-de-NAR', 'Lo condenaron a dos años.', 'Hij werd veroordeeld tot twee jaar.', 'verbo'),
   ('absolver', 'vrijspreken', 'ab-sol-VER', 'El tribunal lo absolvió.', 'De rechtbank sprak hem vrij.', 'verbo'),
   ('denunciar', 'aangifte doen / aanklagen', 'de-noen-SJAR', 'Denunció el robo en comisaría.', 'Hij deed aangifte van de diefstal op het bureau.', 'verbo'),
   ('el testigo', 'de getuige', 'el tes-TIE-go', 'El testigo declaró ante el juez.', 'De getuige legde een verklaring af voor de rechter.', 'giustizia')]),
L(245, '🌍', 'Immigratie & integratie', 'Over migratie praten.',
  'Over migratie praten', 'Emigrar / inmigrar, el inmigrante, el refugiado, el permiso de residencia (de verblijfsvergunning), integrarse, la nacionalidad, el país de origen, la acogida (de opvang).',
  [('emigrar', 'emigreren', 'e-mi-GRAR', 'Muchos españoles emigraron en los sesenta.', 'Veel Spanjaarden emigreerden in de jaren zestig.', 'verbo'),
   ('el inmigrante', 'de immigrant', 'el in-mi-GRAN-te', 'Los inmigrantes aportan mucho.', 'Immigranten dragen veel bij.', 'societa'),
   ('el refugiado', 'de vluchteling', 'el rre-foe-CHJA-do', 'Acogieron a mil refugiados.', 'Ze vingen duizend vluchtelingen op.', 'societa'),
   ('el permiso de residencia', 'de verblijfsvergunning', 'el per-MIE-so de rre-si-DEN-sja', 'Solicitó el permiso de residencia.', 'Hij vroeg een verblijfsvergunning aan.', 'burocrazia'),
   ('integrarse', 'integreren', 'in-te-GRAR-se', 'Se integró rápidamente.', 'Ze integreerde snel.', 'verbo'),
   ('la nacionalidad', 'de nationaliteit', 'la na-sjo-na-li-DAD', 'Tiene doble nacionalidad.', 'Hij heeft een dubbele nationaliteit.', 'societa'),
   ('el país de origen', 'het land van herkomst', 'el pa-IES de o-RIE-chen', 'Volvió a su país de origen.', 'Hij ging terug naar zijn land van herkomst.', 'societa'),
   ('la acogida', 'de opvang / het onthaal', 'la a-ko-CHIE-da', 'La acogida fue muy cálida.', 'Het onthaal was heel warm.', 'societa')]),
L(246, '🤲', 'Vrijwilligerswerk & hulp', 'Over vrijwilligerswerk praten.',
  'Over vrijwilligerswerk praten', 'Hacer voluntariado, la ONG (de ngo), la asociación, recaudar fondos (geld inzamelen), donar, echar una mano (een handje helpen), el comedor social (de gaarkeuken).',
  [('el voluntario', 'de vrijwilliger', 'el vo-loen-TA-rjo', 'Los voluntarios reparten comida.', 'De vrijwilligers delen eten uit.', 'societa'),
   ('la ONG', 'de ngo / hulporganisatie', 'la o-e-ne-CHE', 'Trabaja para una ONG.', 'Hij werkt voor een ngo.', 'societa'),
   ('recaudar fondos', 'geld inzamelen', 'rre-kau-DAR FON-dos', 'Recaudaron fondos para el hospital.', 'Ze zamelden geld in voor het ziekenhuis.', 'espressione'),
   ('donar', 'doneren', 'do-NAR', 'Dona sangre dos veces al año.', 'Hij geeft twee keer per jaar bloed.', 'verbo'),
   ('echar una mano', 'een handje helpen', 'e-TSJAR OE-na MA-no', '¿Me echas una mano?', 'Help je me even?', 'espressione'),
   ('el comedor social', 'de gaarkeuken', 'el ko-me-DOR so-SJAL', 'Sirve comidas en un comedor social.', 'Hij serveert maaltijden in een gaarkeuken.', 'societa'),
   ('la cooperación', 'de samenwerking / ontwikkelingshulp', 'la ko-o-pe-ra-SJON', 'Trabaja en cooperación internacional.', 'Ze werkt in internationale samenwerking.', 'societa'),
   ('desinteresado', 'belangeloos', 'de-sin-te-re-SA-do', 'Fue una ayuda desinteresada.', 'Het was belangeloze hulp.', 'aggettivo')]),
L(247, '⛪', 'Religie & geloof', 'Over geloof praten.',
  'Over geloof praten', 'Creer en (geloven in), ser creyente / ateo / agnóstico, rezar (bidden), la misa, la fe (het geloof), la peregrinación, el Camino de Santiago, respetar las creencias.',
  [('la fe', 'het geloof', 'la fe', 'Tiene mucha fe.', 'Ze heeft een sterk geloof.', 'religione'),
   ('creyente', 'gelovig', 'kre-JEN-te', 'No soy creyente, pero respeto la religión.', 'Ik ben niet gelovig, maar respecteer religie.', 'aggettivo'),
   ('ateo', 'atheïst(isch)', 'a-TE-o', 'Se declara ateo.', 'Hij noemt zich atheïst.', 'aggettivo'),
   ('rezar', 'bidden', 'rre-SAR', 'Reza todas las noches.', 'Ze bidt elke avond.', 'verbo'),
   ('la misa', 'de mis', 'la MIE-sa', 'Van a misa los domingos.', 'Ze gaan zondags naar de mis.', 'religione'),
   ('la peregrinación', 'de pelgrimstocht', 'la pe-re-gri-na-SJON', 'Hizo la peregrinación a Santiago.', 'Hij maakte de pelgrimstocht naar Santiago.', 'religione'),
   ('la creencia', 'de overtuiging / het geloof', 'la kre-EN-sja', 'Respeto todas las creencias.', 'Ik respecteer alle overtuigingen.', 'religione'),
   ('el peregrino', 'de pelgrim', 'el pe-re-GRIE-no', 'Los peregrinos llegan cansados.', 'De pelgrims komen moe aan.', 'religione')]),
L(248, '🌈', 'Gelijkheid & diversiteit', 'Over gelijkheid praten.',
  'Over gelijkheid praten', 'La igualdad de género, la brecha salarial (de loonkloof), la discriminación, el prejuicio, la diversidad, el colectivo, luchar por, visibilizar.',
  [('la igualdad de género', 'de gendergelijkheid', 'la i-gwal-DAD de CHE-ne-ro', 'Luchan por la igualdad de género.', 'Ze strijden voor gendergelijkheid.', 'societa'),
   ('la brecha salarial', 'de loonkloof', 'la BRE-tsja sa-la-RJAL', 'La brecha salarial sigue existiendo.', 'De loonkloof bestaat nog steeds.', 'societa'),
   ('la discriminación', 'de discriminatie', 'la dis-kri-mi-na-SJON', 'Sufrió discriminación en el trabajo.', 'Ze werd gediscrimineerd op het werk.', 'societa'),
   ('la inclusión', 'de inclusie', 'la in-kloe-SJON', 'Apostamos por la inclusión.', 'We zetten in op inclusie.', 'societa'),
   ('la xenofobia', 'de vreemdelingenhaat', 'la kse-no-FO-bja', 'Hay que combatir la xenofobia.', 'Vreemdelingenhaat moet bestreden worden.', 'societa'),
   ('el colectivo', 'de groep / gemeenschap', 'el ko-lek-TIE-vo', 'Es un colectivo vulnerable.', 'Het is een kwetsbare groep.', 'societa'),
   ('luchar por', 'strijden voor', 'loe-TSJAR por', 'Luchó por sus derechos.', 'Ze streed voor haar rechten.', 'verbo'),
   ('el estereotipo', 'het stereotype', 'el es-te-re-o-TIE-po', 'Rompe con los estereotipos.', 'Ze breekt met de stereotypen.', 'societa')]),
L(249, '🕊️', 'Oorlog & vrede', 'Over oorlog en vrede praten.',
  'Over oorlog en vrede praten', 'Estallar (uitbreken), el conflicto armado, el ejército, el soldado, la víctima, el alto el fuego (het staakt-het-vuren), negociar la paz, la reconciliación.',
  [('estallar', 'uitbreken', 'es-ta-JAR', 'La guerra estalló en 1936.', 'De oorlog brak uit in 1936.', 'verbo'),
   ('el ejército', 'het leger', 'el e-CHER-si-to', 'El ejército ocupó la ciudad.', 'Het leger bezette de stad.', 'storia'),
   ('el soldado', 'de soldaat', 'el sol-DA-do', 'Miles de soldados murieron.', 'Duizenden soldaten stierven.', 'storia'),
   ('la víctima', 'het slachtoffer', 'la VIK-ti-ma', 'Hubo muchas víctimas civiles.', 'Er waren veel burgerslachtoffers.', 'storia'),
   ('el alto el fuego', 'het staakt-het-vuren', 'el AL-to el FWE-go', 'Acordaron un alto el fuego.', 'Ze kwamen een staakt-het-vuren overeen.', 'storia'),
   ('la tregua', 'het bestand / de wapenstilstand', 'la TRE-gwa', 'Firmaron una tregua de un mes.', 'Ze tekenden een bestand van een maand.', 'storia'),
   ('el bombardeo', 'het bombardement', 'el bom-bar-DE-o', 'Guernica sufrió un bombardeo en 1937.', 'Guernica werd in 1937 gebombardeerd.', 'storia'),
   ('la reconciliación', 'de verzoening', 'la rre-kon-si-lja-SJON', 'La reconciliación tardó décadas.', 'De verzoening duurde decennia.', 'storia')]),
L(250, '📋', 'Toetsles B1 — Blok 13', 'Samenvatting van blok 13.',
  'Samenvatting Blok 13', 'Je herkent de passieve vorm en kunt over politiek, recht, migratie en samenleving praten. In de toets: een leestekst en 20 woorden uit lessen 241–249.',
  [('el sindicato', 'de vakbond', 'el sin-di-KA-to', 'El sindicato convocó una huelga.', 'De vakbond riep een staking uit.', 'politica'),
   ('la justicia', 'de rechtvaardigheid / justitie', 'la choes-TIE-sja', 'Piden justicia.', 'Ze eisen gerechtigheid.', 'giustizia'),
   ('la manifestación', 'de demonstratie', 'la ma-ni-fes-ta-SJON', 'Hubo una manifestación en el centro.', 'Er was een demonstratie in het centrum.', 'politica'),
   ('protestar', 'protesteren', 'pro-tes-TAR', 'Protestan contra la reforma.', 'Ze protesteren tegen de hervorming.', 'verbo'),
   ('la reforma', 'de hervorming', 'la rre-FOR-ma', 'La reforma laboral es polémica.', 'De arbeidshervorming is omstreden.', 'politica'),
   ('polémico', 'omstreden', 'po-LE-mi-ko', 'Es una decisión polémica.', 'Het is een omstreden beslissing.', 'aggettivo'),
   ('la opinión pública', 'de publieke opinie', 'la o-pi-NJON POE-bli-ka', 'La opinión pública está dividida.', 'De publieke opinie is verdeeld.', 'politica'),
   ('comprometerse con', 'zich inzetten voor', 'kom-pro-me-TER-se kon', 'Se comprometió con la causa.', 'Hij zette zich in voor de zaak.', 'verbo')]),
L(251, '📝', 'Solliciteren — verdieping', 'Formele briefconventies.',
  'Formele briefconventies', 'Estimado/a señor/a: … Me dirijo a usted para … Adjunto mi currículum. Quedo a su disposición. Atentamente / Un cordial saludo. La carta de presentación (de motivatiebrief).',
  [('la carta de presentación', 'de motivatiebrief', 'la KAR-ta de pre-sen-ta-SJON', 'Adjunto mi carta de presentación.', 'Bijgevoegd mijn motivatiebrief.', 'lavoro'),
   ('me dirijo a usted', 'ik richt mij tot u', 'me di-RIE-cho a oes-TED', 'Me dirijo a usted para solicitar el puesto.', 'Ik richt mij tot u om te solliciteren naar de functie.', 'espressione'),
   ('adjuntar', 'bijvoegen', 'ad-choen-TAR', 'Adjunto mi currículum.', 'Ik voeg mijn cv bij.', 'verbo'),
   ('quedo a su disposición', 'ik sta tot uw beschikking', 'KE-do a soe dis-po-si-SJON', 'Quedo a su disposición para una entrevista.', 'Ik sta tot uw beschikking voor een gesprek.', 'espressione'),
   ('el puesto vacante', 'de vacature', 'el PWES-to va-KAN-te', 'Hay un puesto vacante en contabilidad.', 'Er is een vacature bij de boekhouding.', 'lavoro'),
   ('la referencia', 'de referentie', 'la rre-fe-REN-sja', 'Puedo aportar referencias.', 'Ik kan referenties overleggen.', 'lavoro'),
   ('el perfil', 'het profiel', 'el per-FIL', 'Mi perfil encaja con el puesto.', 'Mijn profiel past bij de functie.', 'lavoro'),
   ('un cordial saludo', 'met vriendelijke groet', 'oen kor-DJAL sa-LOE-do', 'Un cordial saludo, Ana López.', 'Met vriendelijke groet, Ana López.', 'espressione')]),
L(252, '🤝', 'Het sollicitatiegesprek', 'Sollicitatiegesprek.',
  'Sollicitatiegesprek', 'Hábleme de usted. ¿Cuáles son sus puntos fuertes y débiles? ¿Por qué quiere trabajar aquí? Tengo experiencia en… Se me da bien (ik ben goed in). Trabajar bajo presión.',
  [('el punto fuerte', 'het sterke punt', 'el POEN-to FWER-te', 'Mi punto fuerte es la organización.', 'Mijn sterke punt is organisatie.', 'lavoro'),
   ('el punto débil', 'het zwakke punt', 'el POEN-to DE-bil', '¿Cuál es su punto débil?', 'Wat is uw zwakke punt?', 'lavoro'),
   ('dárselo bien a alguien', 'goed zijn in', 'DAR-se-lo bjen', 'Se me dan bien los idiomas.', 'Ik ben goed in talen.', 'espressione'),
   ('la disponibilidad', 'de beschikbaarheid', 'la dis-po-ni-bi-li-DAD', 'Tengo disponibilidad inmediata.', 'Ik ben per direct beschikbaar.', 'lavoro'),
   ('el periodo de prueba', 'de proeftijd', 'el pe-RIE-o-do de PRWE-ba', 'Hay un periodo de prueba de tres meses.', 'Er is een proeftijd van drie maanden.', 'lavoro'),
   ('la expectativa salarial', 'de salarisverwachting', 'la eks-pek-ta-TIE-va sa-la-RJAL', '¿Cuál es su expectativa salarial?', 'Wat is uw salarisverwachting?', 'lavoro'),
   ('encajar en', 'passen in', 'en-ka-CHAR en', 'Creo que encajo en el equipo.', 'Ik denk dat ik in het team pas.', 'verbo'),
   ('la trayectoria profesional', 'de loopbaan', 'la tra-jek-TO-rja pro-fe-sjo-NAL', 'Hábleme de su trayectoria profesional.', 'Vertel over uw loopbaan.', 'lavoro')]),
L(253, '📊', 'Vergaderen — verdieping', 'Vergaderen in het Spaans.',
  'Vergaderen in het Spaans', 'El orden del día (de agenda), el acta (de notulen), tomar la palabra, pasar al siguiente punto, llegar a un consenso, aplazar (uitstellen), los ruegos y preguntas (de rondvraag).',
  [('el orden del día', 'de agenda (vergadering)', 'el OR-den del DIE-a', 'Hay cinco puntos en el orden del día.', 'Er staan vijf punten op de agenda.', 'ufficio'),
   ('el acta', 'de notulen', 'el AK-ta', '¿Quién redacta el acta?', 'Wie maakt de notulen?', 'ufficio'),
   ('tomar la palabra', 'het woord nemen', 'to-MAR la pa-LA-bra', 'Tomó la palabra para explicar el plan.', 'Hij nam het woord om het plan uit te leggen.', 'espressione'),
   ('el siguiente punto', 'het volgende punt', 'el si-GJEN-te POEN-to', 'Pasemos al siguiente punto.', 'Laten we naar het volgende punt gaan.', 'ufficio'),
   ('el consenso', 'de consensus', 'el kon-SEN-so', 'Llegamos a un consenso.', 'We bereikten consensus.', 'ufficio'),
   ('aplazar', 'uitstellen', 'a-pla-SAR', 'Aplazaron la reunión.', 'Ze stelden de vergadering uit.', 'verbo'),
   ('ruegos y preguntas', 'de rondvraag', 'RRWE-gos i pre-GOEN-tas', 'Terminamos con ruegos y preguntas.', 'We sluiten af met de rondvraag.', 'ufficio'),
   ('convocar', 'bijeenroepen', 'kon-vo-KAR', 'Convocaron una reunión urgente.', 'Ze riepen een spoedvergadering bijeen.', 'verbo')]),
L(254, '📈', 'Presentaties geven', 'Een presentatie structureren.',
  'Een presentatie structureren', 'En primer lugar… A continuación… Por último… Como pueden ver en la diapositiva (dia)… Para resumir… ¿Alguna pregunta? Los datos muestran que…',
  [('la diapositiva', 'de dia / slide', 'la dja-po-si-TIE-va', 'Como ven en esta diapositiva…', 'Zoals u op deze dia ziet…', 'ufficio'),
   ('en primer lugar', 'ten eerste', 'en pri-MER loe-GAR', 'En primer lugar, presentaré los datos.', 'Ten eerste presenteer ik de cijfers.', 'espressione'),
   ('en segundo lugar', 'ten tweede', 'en se-GOEN-do loe-GAR', 'En segundo lugar, analizaremos los costes.', 'Ten tweede analyseren we de kosten.', 'espressione'),
   ('por último', 'ten slotte', 'por OEL-ti-mo', 'Por último, las conclusiones.', 'Ten slotte de conclusies.', 'espressione'),
   ('para resumir', 'samenvattend', 'PA-ra rre-soe-MIER', 'Para resumir: las ventas han subido.', 'Samenvattend: de verkoop is gestegen.', 'espressione'),
   ('el gráfico', 'de grafiek', 'el GRA-fi-ko', 'El gráfico muestra la evolución.', 'De grafiek toont de ontwikkeling.', 'ufficio'),
   ('demostrar', 'aantonen', 'de-mos-TRAR', 'Los datos demuestran la tendencia.', 'De cijfers tonen de trend aan.', 'verbo'),
   ('el turno de preguntas', 'de vragenronde', 'el TOER-no de pre-GOEN-tas', 'Abrimos el turno de preguntas.', 'We openen de vragenronde.', 'ufficio')]),
L(255, '✉️', 'E-mails & brieven', 'Formele e-mails.',
  'Formele e-mails', 'Asunto (onderwerp), en relación con (met betrekking tot), le escribo para, le agradecería que (ik zou het op prijs stellen als) + subjuntivo, a la espera de su respuesta, reenviar (doorsturen).',
  [('el asunto', 'het onderwerp (e-mail)', 'el a-SOEN-to', 'Escribe un asunto claro.', 'Schrijf een duidelijk onderwerp.', 'ufficio'),
   ('en relación con', 'met betrekking tot', 'en rre-la-SJON kon', 'En relación con su pedido…', 'Met betrekking tot uw bestelling…', 'espressione'),
   ('le agradecería que', 'ik zou het op prijs stellen als u', 'le a-gra-de-se-RIE-a ke', 'Le agradecería que me confirmara la fecha.', 'Ik zou het op prijs stellen als u de datum bevestigt.', 'espressione'),
   ('a la espera de su respuesta', 'in afwachting van uw antwoord', 'a la es-PE-ra de soe rres-PWES-ta', 'A la espera de su respuesta, le saluda atentamente.', 'In afwachting van uw antwoord, hoogachtend.', 'espressione'),
   ('reenviar', 'doorsturen', 'rre-en-VJAR', 'Te reenvío el correo.', 'Ik stuur je de mail door.', 'verbo'),
   ('el archivo adjunto', 'de bijlage', 'el ar-TSJIE-vo ad-CHOEN-to', 'Vea el archivo adjunto.', 'Zie de bijlage.', 'ufficio'),
   ('el destinatario', 'de geadresseerde / ontvanger', 'el des-ti-na-TA-rjo', 'Comprueba el destinatario.', 'Controleer de ontvanger.', 'ufficio'),
   ('con copia a', 'met kopie aan (cc)', 'kon KO-pja a', 'Envíalo con copia a la directora.', 'Stuur het met een kopie aan de directeur.', 'espressione')]),
L(256, '🤝', 'Onderhandelen', 'Onderhandelingstaal.',
  'Onderhandelingstaal', 'Hacer una oferta, la contraoferta, estar dispuesto a (bereid zijn), ceder en, llegar a un acuerdo, las condiciones, el plazo de entrega (de levertijd), el descuento por volumen.',
  [('la contraoferta', 'het tegenbod', 'la kon-tra-o-FER-ta', 'Hicieron una contraoferta.', 'Ze deden een tegenbod.', 'affari'),
   ('estar dispuesto a', 'bereid zijn om', 'es-TAR dis-PWES-to a', 'Estamos dispuestos a negociar.', 'We zijn bereid te onderhandelen.', 'espressione'),
   ('llegar a un acuerdo', 'tot een akkoord komen', 'je-GAR a oen a-KWER-do', 'Por fin llegamos a un acuerdo.', 'Eindelijk kwamen we tot een akkoord.', 'espressione'),
   ('las condiciones', 'de voorwaarden', 'las kon-di-SJO-nes', 'Las condiciones son aceptables.', 'De voorwaarden zijn acceptabel.', 'affari'),
   ('el plazo de entrega', 'de levertijd', 'el PLA-so de en-TRE-ga', 'El plazo de entrega es de dos semanas.', 'De levertijd is twee weken.', 'affari'),
   ('la rebaja por volumen', 'de volumekorting', 'la rre-BA-cha por vo-LOE-men', '¿Nos harían una rebaja por volumen?', 'Zou u ons volumekorting geven?', 'affari'),
   ('el margen', 'de marge', 'el MAR-chen', 'Nuestro margen es pequeño.', 'Onze marge is klein.', 'affari'),
   ('innegociable', 'niet onderhandelbaar', 'i-ne-go-SJA-ble', 'El precio es innegociable.', 'De prijs is niet onderhandelbaar.', 'aggettivo')]),
L(257, '🏢', 'Bedrijfscultuur', 'Spaanse bedrijfscultuur.',
  'Spaanse bedrijfscultuur', 'La jornada partida (gesplitste werkdag met lange lunchpauze), la jornada intensiva (doorlopend, in de zomer), el tuteo in het bedrijf, la sobremesa, la conciliación (werk-privébalans), el enchufe (kruiwagen).',
  [('la jornada partida', 'de gesplitste werkdag', 'la chor-NA-da par-TIE-da', 'Tenemos jornada partida: de 9 a 14 y de 16 a 19.', 'We hebben een gesplitste werkdag: 9 tot 14 en 16 tot 19 uur.', 'lavoro'),
   ('la jornada intensiva', 'de doorlopende werkdag', 'la chor-NA-da in-ten-SIE-va', 'En verano hacemos jornada intensiva.', 'In de zomer werken we doorlopend.', 'lavoro'),
   ('la conciliación', 'de werk-privébalans', 'la kon-si-lja-SJON', 'La conciliación es un tema importante.', 'Werk-privébalans is een belangrijk thema.', 'lavoro'),
   ('el enchufe', 'de kruiwagen (relaties)', 'el en-TSJOE-fe', 'Consiguió el trabajo por enchufe.', 'Hij kreeg de baan via een kruiwagen.', 'lavoro'),
   ('la jerarquía', 'de hiërarchie', 'la che-rar-KIE-a', 'La jerarquía es menos rígida que antes.', 'De hiërarchie is minder strikt dan vroeger.', 'lavoro'),
   ('la plantilla', 'het personeelsbestand', 'la plan-TIE-ja', 'La plantilla es de cincuenta personas.', 'Het personeelsbestand telt vijftig mensen.', 'lavoro'),
   ('el convenio colectivo', 'de cao', 'el kon-VE-njo ko-lek-TIE-vo', 'El convenio colectivo fija las vacaciones.', 'De cao legt de vakantiedagen vast.', 'lavoro'),
   ('el ambiente laboral', 'de werksfeer', 'el am-BJEN-te la-bo-RAL', 'Hay buen ambiente laboral.', 'Er is een goede werksfeer.', 'lavoro')]),
L(258, '🚢', 'Import & export', 'Handelstaal.',
  'Handelstaal', 'Importar / exportar, la aduana (de douane), el arancel (het invoerrecht), la mercancía (de goederen), el proveedor, el envío, la factura proforma, el transporte marítimo.',
  [('exportar', 'exporteren', 'eks-por-TAR', 'España exporta aceite a todo el mundo.', 'Spanje exporteert olie naar de hele wereld.', 'verbo'),
   ('el despacho de aduanas', 'de douaneafhandeling', 'el des-PA-tsjo de a-DWA-nas', 'El despacho de aduanas tardó tres días.', 'De douaneafhandeling duurde drie dagen.', 'affari'),
   ('el arancel', 'het invoerrecht / tarief', 'el a-ran-SEL', 'Subieron los aranceles.', 'Ze verhoogden de invoerrechten.', 'affari'),
   ('la mercancía', 'de goederen / handelswaar', 'la mer-kan-SIE-a', 'La mercancía llegó dañada.', 'De goederen kwamen beschadigd aan.', 'affari'),
   ('el proveedor', 'de leverancier', 'el pro-ve-e-DOR', 'Buscamos un nuevo proveedor.', 'We zoeken een nieuwe leverancier.', 'affari'),
   ('el envío', 'de zending / verzending', 'el en-VIE-o', 'El envío tarda cinco días.', 'De zending duurt vijf dagen.', 'affari'),
   ('el comercio exterior', 'de buitenlandse handel', 'el ko-MER-sjo eks-te-RJOR', 'Trabaja en comercio exterior.', 'Ze werkt in de buitenlandse handel.', 'affari'),
   ('el contenedor marítimo', 'de zeecontainer', 'el kon-te-ne-DOR ma-RIE-ti-mo', 'Llenaron tres contenedores marítimos.', 'Ze vulden drie zeecontainers.', 'affari')]),
L(259, '📞', 'Klantenservice', 'Klantenservice.',
  'Klantenservice', '¿En qué puedo ayudarle? Le paso con (ik verbind u door met)… La reclamación (de klacht), el número de pedido, la garantía, devolver, el reembolso, disculpe las molestias.',
  [('la atención al cliente', 'de klantenservice', 'la a-ten-SJON al KLJEN-te', 'Llamé a atención al cliente.', 'Ik belde de klantenservice.', 'affari'),
   ('la reclamación', 'de klacht / reclamatie', 'la rre-kla-ma-SJON', 'Quiero poner una reclamación.', 'Ik wil een klacht indienen.', 'affari'),
   ('le paso con', 'ik verbind u door met', 'le PA-so kon', 'Le paso con el departamento técnico.', 'Ik verbind u door met de technische dienst.', 'espressione'),
   ('el número de pedido', 'het bestelnummer', 'el NOE-me-ro de pe-DIE-do', '¿Me da su número de pedido?', 'Mag ik uw bestelnummer?', 'affari'),
   ('el servicio posventa', 'de aftersales / service na verkoop', 'el ser-VIE-sjo pos-VEN-ta', 'El servicio posventa es excelente.', 'De service na verkoop is uitstekend.', 'affari'),
   ('disculpe las molestias', 'excuses voor het ongemak', 'dis-KOEL-pe las mo-LES-tjas', 'Disculpe las molestias ocasionadas.', 'Excuses voor het veroorzaakte ongemak.', 'espressione'),
   ('tramitar', 'in behandeling nemen / afhandelen', 'tra-mi-TAR', 'Tramitaremos su solicitud hoy.', 'We handelen uw aanvraag vandaag af.', 'verbo'),
   ('la hoja de reclamaciones', 'het klachtenformulier', 'la O-cha de rre-kla-ma-SJO-nes', 'Pedí la hoja de reclamaciones.', 'Ik vroeg om het klachtenformulier.', 'affari')]),
L(260, '📋', 'Toetsles B1 — Blok 14', 'Samenvatting van blok 14.',
  'Samenvatting Blok 14', 'Je kunt solliciteren, vergaderen, presenteren, onderhandelen en zakelijk schrijven in het Spaans. In de toets: een leestekst en 20 woorden uit lessen 251–259.',
  [('la empresa multinacional', 'de multinational', 'la em-PRE-sa moel-ti-na-sjo-NAL', 'Trabaja en una multinacional.', 'Ze werkt bij een multinational.', 'affari'),
   ('el accionista', 'de aandeelhouder', 'el ak-sjo-NIS-ta', 'Los accionistas aprobaron las cuentas.', 'De aandeelhouders keurden de jaarrekening goed.', 'affari'),
   ('la cifra de negocios', 'de omzet', 'la SIE-fra de ne-GO-sjos', 'La cifra de negocios creció un diez por ciento.', 'De omzet groeide met tien procent.', 'affari'),
   ('el beneficio', 'de winst', 'el be-ne-FIE-sjo', 'Los beneficios bajaron.', 'De winst daalde.', 'affari'),
   ('la pérdida', 'het verlies', 'la PER-di-da', 'Cerraron el año con pérdidas.', 'Ze sloten het jaar af met verlies.', 'affari'),
   ('emprender', 'ondernemen', 'em-pren-DER', 'Decidió emprender a los treinta.', 'Hij besloot op zijn dertigste te gaan ondernemen.', 'verbo'),
   ('la competencia', 'de concurrentie', 'la kom-pe-TEN-sja', 'La competencia es feroz.', 'De concurrentie is moordend.', 'affari'),
   ('rentable', 'rendabel', 'rren-TA-ble', 'El negocio es rentable.', 'De zaak is rendabel.', 'aggettivo')]),
L(261, '🏥', 'In het ziekenhuis', 'Imperativo formal voor instructies.',
  'Imperativo formal (usted) voor instructies', 'Vorm = subjuntivo presente: Respire hondo. Siéntese. No se mueva. Tome una pastilla cada ocho horas. Met voornaamwoorden: Quítese la camisa; ontkennend: No se la quite.',
  [('respire hondo', 'haal diep adem (u)', 'rres-PIE-re ON-do', 'Respire hondo, por favor.', 'Haalt u diep adem, alstublieft.', 'espressione'),
   ('no se mueva', 'beweeg niet (u)', 'no se MWE-va', 'No se mueva durante la radiografía.', 'Beweeg niet tijdens de röntgenfoto.', 'espressione'),
   ('quítese', 'doe uit (u)', 'KIE-te-se', 'Quítese la camisa.', 'Doet u uw overhemd uit.', 'espressione'),
   ('la radiografía', 'de röntgenfoto', 'la rra-djo-gra-FIE-a', 'Le harán una radiografía.', 'Ze maken een röntgenfoto van u.', 'salute'),
   ('el análisis de sangre', 'het bloedonderzoek', 'el a-NA-li-sis de SAN-gre', 'Venga en ayunas para el análisis de sangre.', 'Kom nuchter voor het bloedonderzoek.', 'salute'),
   ('en ayunas', 'nuchter (niet gegeten)', 'en a-JOE-nas', 'Tiene que venir en ayunas.', 'U moet nuchter komen.', 'espressione'),
   ('la planta', 'de verdieping / afdeling (ziekenhuis)', 'la PLAN-ta', 'Está ingresado en la tercera planta.', 'Hij is opgenomen op de derde verdieping.', 'salute'),
   ('dar el alta', 'ontslaan (uit het ziekenhuis)', 'dar el AL-ta', 'Le dieron el alta ayer.', 'Hij werd gisteren ontslagen uit het ziekenhuis.', 'espressione')]),
L(262, '💊', 'De apotheek', 'Bij de apotheek.',
  'Bij de apotheek', 'Con receta / sin receta (op / zonder recept), el prospecto (de bijsluiter), la dosis, los efectos secundarios, el genérico, el jarabe (de drank/siroop), la pomada (de zalf).',
  [('con receta', 'op recept', 'kon rre-SE-ta', 'Este medicamento es con receta.', 'Dit medicijn is op recept.', 'espressione'),
   ('el prospecto', 'de bijsluiter', 'el pros-PEK-to', 'Lea el prospecto antes de tomarlo.', 'Lees de bijsluiter voor gebruik.', 'salute'),
   ('la dosis', 'de dosis', 'la DO-sis', 'No supere la dosis recomendada.', 'Overschrijd de aanbevolen dosis niet.', 'salute'),
   ('los efectos secundarios', 'de bijwerkingen', 'los e-FEK-tos se-koen-DA-rjos', 'Puede tener efectos secundarios.', 'Het kan bijwerkingen hebben.', 'salute'),
   ('el genérico', 'het merkloze medicijn', 'el che-NE-ri-ko', 'El genérico es más barato.', 'Het merkloze medicijn is goedkoper.', 'salute'),
   ('el jarabe', 'de (hoest)drank', 'el cha-RA-be', 'Un jarabe para la tos.', 'Een hoestdrank.', 'salute'),
   ('la pomada', 'de zalf', 'la po-MA-da', 'Aplique la pomada dos veces al día.', 'Breng de zalf twee keer per dag aan.', 'salute'),
   ('el antibiótico', 'het antibioticum', 'el an-ti-BJO-ti-ko', 'Termina todo el antibiótico.', 'Maak de antibioticakuur af.', 'salute')]),
L(263, '🧠', 'Geestelijke gezondheid', 'Over geestelijke gezondheid praten.',
  'Over geestelijke gezondheid praten', 'La salud mental, la ansiedad, la depresión, el psicólogo, el psiquiatra, pedir ayuda, el ataque de pánico, el agotamiento (uitputting), cuidarse.',
  [('la salud mental', 'de geestelijke gezondheid', 'la sa-LOED men-TAL', 'La salud mental importa.', 'Geestelijke gezondheid is belangrijk.', 'salute'),
   ('la ansiedad', 'de angst(stoornis)', 'la an-sje-DAD', 'Sufre de ansiedad.', 'Ze lijdt aan angst.', 'salute'),
   ('la depresión', 'de depressie', 'la de-pre-SJON', 'Superó una depresión.', 'Hij overwon een depressie.', 'salute'),
   ('el psicólogo', 'de psycholoog', 'el si-KO-lo-go', 'Va al psicólogo cada semana.', 'Ze gaat elke week naar de psycholoog.', 'professione'),
   ('el psiquiatra', 'de psychiater', 'el si-KJA-tra', 'El psiquiatra le recetó medicación.', 'De psychiater schreef medicatie voor.', 'professione'),
   ('el ataque de pánico', 'de paniekaanval', 'el a-TA-ke de PA-ni-ko', 'Tuvo un ataque de pánico en el metro.', 'Hij kreeg een paniekaanval in de metro.', 'salute'),
   ('el agotamiento', 'de uitputting', 'el a-go-ta-MJEN-to', 'Sufre agotamiento físico y mental.', 'Hij lijdt aan fysieke en mentale uitputting.', 'salute'),
   ('pedir ayuda', 'hulp vragen', 'pe-DIER a-JOE-da', 'No tengas miedo de pedir ayuda.', 'Wees niet bang om hulp te vragen.', 'espressione')]),
L(264, '🚑', 'Eerste hulp', 'Noodsituaties.',
  'Noodsituaties', '¡Llame al 112! Está inconsciente (bewusteloos). Se ha desmayado (flauwgevallen). Está sangrando. El botiquín (de EHBO-doos), la herida, la quemadura, la ambulancia, urgencias.',
  [('desmayarse', 'flauwvallen', 'des-ma-JAR-se', 'Se desmayó por el calor.', 'Ze viel flauw door de hitte.', 'verbo'),
   ('inconsciente', 'bewusteloos', 'in-kon-SJEN-te', 'Está inconsciente pero respira.', 'Hij is bewusteloos maar ademt.', 'aggettivo'),
   ('sangrar', 'bloeden', 'san-GRAR', 'La herida sangra mucho.', 'De wond bloedt hevig.', 'verbo'),
   ('el botiquín', 'de EHBO-doos', 'el bo-ti-KIEN', 'Hay un botiquín en la cocina.', 'Er is een EHBO-doos in de keuken.', 'salute'),
   ('la quemadura', 'de brandwond', 'la ke-ma-DOE-ra', 'Pon la quemadura bajo el agua fría.', 'Houd de brandwond onder koud water.', 'salute'),
   ('la camilla', 'de brancard', 'la ka-MIE-ja', 'Lo llevaron en camilla.', 'Ze droegen hem op een brancard.', 'salute'),
   ('la venda', 'het verband', 'la VEN-da', 'Cambia la venda cada día.', 'Verschoon het verband elke dag.', 'salute'),
   ('atragantarse', 'zich verslikken', 'a-tra-gan-TAR-se', 'Se atragantó con una espina.', 'Hij verslikte zich in een graat.', 'verbo')]),
L(265, '🔬', 'Wetenschap — basis', 'Over wetenschap praten.',
  'Over wetenschap praten', 'El científico, el experimento, la teoría, demostrar, el descubrimiento, el método científico, los datos, la prueba (het bewijs), según un estudio reciente.',
  [('el científico', 'de wetenschapper', 'el sjen-TIE-fi-ko', 'Los científicos advierten del peligro.', 'Wetenschappers waarschuwen voor het gevaar.', 'scienza'),
   ('el hallazgo', 'de vondst / bevinding', 'el a-JAS-go', 'Fue un hallazgo importante.', 'Het was een belangrijke bevinding.', 'scienza'),
   ('la evidencia', 'het bewijs(materiaal)', 'la e-vi-DEN-sja', 'No hay evidencia científica.', 'Er is geen wetenschappelijk bewijs.', 'scienza'),
   ('el microscopio', 'de microscoop', 'el mi-kros-KO-pjo', 'Lo observó con el microscopio.', 'Hij bekeek het onder de microscoop.', 'scienza'),
   ('el método', 'de methode', 'el ME-to-do', 'Siguieron el método científico.', 'Ze volgden de wetenschappelijke methode.', 'scienza'),
   ('comprobar', 'controleren / nagaan', 'kom-pro-BAR', 'Hay que comprobar los resultados.', 'De resultaten moeten gecontroleerd worden.', 'verbo'),
   ('el avance científico', 'de wetenschappelijke vooruitgang', 'el a-VAN-se sjen-TIE-fi-ko', 'Los avances científicos salvan vidas.', 'Wetenschappelijke vooruitgang redt levens.', 'scienza'),
   ('la muestra', 'het monster / de steekproef', 'la MWES-tra', 'Analizaron cien muestras.', 'Ze analyseerden honderd monsters.', 'scienza')]),
L(266, '🧬', 'Biologie & geneeskunde', 'Biologische en medische termen.',
  'Biologische en medische termen', 'La célula (de cel), el gen, el ADN, la vacuna, el virus, la bacteria, el sistema inmunitario, el tratamiento, el ensayo clínico (de klinische proef).',
  [('la célula', 'de cel', 'la SE-loe-la', 'El cuerpo tiene billones de células.', 'Het lichaam heeft biljoenen cellen.', 'scienza'),
   ('el gen', 'het gen', 'el chen', 'Es un gen hereditario.', 'Het is een erfelijk gen.', 'scienza'),
   ('el ADN', 'het DNA', 'el a-de-E-ne', 'Analizaron el ADN.', 'Ze analyseerden het DNA.', 'scienza'),
   ('el investigador', 'de onderzoeker', 'el in-ves-ti-ga-DOR', 'Es investigadora en el CSIC.', 'Ze is onderzoeker bij het CSIC.', 'professione'),
   ('la bacteria', 'de bacterie', 'la bak-TE-rja', 'Los antibióticos matan bacterias.', 'Antibiotica doden bacteriën.', 'scienza'),
   ('el sistema inmunitario', 'het immuunsysteem', 'el sis-TE-ma in-moe-ni-TA-rjo', 'Fortalece el sistema inmunitario.', 'Het versterkt het immuunsysteem.', 'salute'),
   ('el ensayo clínico', 'de klinische proef', 'el en-SA-jo KLIE-ni-ko', 'El fármaco está en ensayo clínico.', 'Het geneesmiddel is in klinische proef.', 'scienza'),
   ('hereditario', 'erfelijk', 'e-re-di-TA-rjo', 'Es una enfermedad hereditaria.', 'Het is een erfelijke ziekte.', 'aggettivo')]),
L(267, '🔢', 'Wiskunde & natuurkunde', 'Wiskundige termen.',
  'Wiskundige termen', 'Sumar, restar, multiplicar, dividir. La mitad, el doble, el triple, el porcentaje, la fórmula, la ecuación, la gravedad, la velocidad, la energía.',
  [('sumar', 'optellen', 'soe-MAR', 'Suma dos y tres.', 'Tel twee en drie op.', 'verbo'),
   ('restar', 'aftrekken', 'rres-TAR', 'Resta diez de cincuenta.', 'Trek tien van vijftig af.', 'verbo'),
   ('multiplicar', 'vermenigvuldigen', 'moel-ti-pli-KAR', 'Multiplica por cuatro.', 'Vermenigvuldig met vier.', 'verbo'),
   ('dividir', 'delen', 'di-vi-DIER', 'Divide entre dos.', 'Deel door twee.', 'verbo'),
   ('el porcentaje', 'het percentage', 'el por-sen-TA-che', '¿Qué porcentaje aprobó?', 'Welk percentage slaagde?', 'scienza'),
   ('la ecuación', 'de vergelijking', 'la e-kwa-SJON', 'Resuelve la ecuación.', 'Los de vergelijking op.', 'scienza'),
   ('la gravedad', 'de zwaartekracht', 'la gra-ve-DAD', 'La gravedad atrae los objetos.', 'De zwaartekracht trekt voorwerpen aan.', 'scienza'),
   ('la velocidad', 'de snelheid', 'la ve-lo-si-DAD', 'La velocidad de la luz es constante.', 'De lichtsnelheid is constant.', 'scienza')]),
L(268, '💡', 'Uitvindingen & ontdekkingen', 'Uitvindingen beschrijven.',
  'Uitvindingen beschrijven', 'Inventar, el inventor, la patente, servir para (dienen om), funcionar con, revolucionar. Fue inventado por… (passief). El submarino de Isaac Peral, la fregona (de dweil met emmer) is een Spaanse uitvinding.',
  [('patentar', 'patenteren', 'pa-ten-TAR', 'Patentó su invento en 1956.', 'Hij patenteerde zijn uitvinding in 1956.', 'verbo'),
   ('el inventor', 'de uitvinder', 'el in-ven-TOR', 'El inventor era de Zaragoza.', 'De uitvinder kwam uit Zaragoza.', 'scienza'),
   ('la patente', 'het patent / octrooi', 'la pa-TEN-te', 'Registró la patente en 1956.', 'Hij registreerde het patent in 1956.', 'scienza'),
   ('funcionar con', 'werken op (energie)', 'foen-sjo-NAR kon', 'Funciona con pilas.', 'Het werkt op batterijen.', 'espressione'),
   ('revolucionar', 'revolutioneren', 'rre-vo-loe-sjo-NAR', 'Internet revolucionó la comunicación.', 'Internet revolutioneerde de communicatie.', 'verbo'),
   ('el submarino', 'de onderzeeër', 'el soeb-ma-RIE-no', 'Isaac Peral diseñó un submarino.', 'Isaac Peral ontwierp een onderzeeër.', 'scienza'),
   ('ingenioso', 'ingenieus / vindingrijk', 'in-che-NJO-so', 'Es una solución ingeniosa.', 'Het is een ingenieuze oplossing.', 'aggettivo'),
   ('el prototipo', 'het prototype', 'el pro-to-TIE-po', 'Construyeron un prototipo.', 'Ze bouwden een prototype.', 'scienza')]),
L(269, '🚀', 'Ruimtevaart & sterrenkunde', 'Over de ruimte praten.',
  'Over de ruimte praten', 'El universo, la galaxia, el planeta, la estrella, el satélite, el cohete (de raket), el astronauta, la órbita, el telescopio, el eclipse, la Vía Láctea.',
  [('el universo', 'het heelal', 'el oe-ni-VER-so', 'El universo se expande.', 'Het heelal dijt uit.', 'scienza'),
   ('la galaxia', 'het sterrenstelsel', 'la ga-LAK-sja', 'Hay miles de millones de galaxias.', 'Er zijn miljarden sterrenstelsels.', 'scienza'),
   ('el cohete', 'de raket', 'el ko-E-te', 'El cohete despegó a las seis.', 'De raket steeg om zes uur op.', 'scienza'),
   ('el astronauta', 'de astronaut', 'el as-tro-NAU-ta', 'Pedro Duque fue el primer astronauta español.', 'Pedro Duque was de eerste Spaanse astronaut.', 'scienza'),
   ('la órbita', 'de baan (om een hemellichaam)', 'la OR-bi-ta', 'El satélite está en órbita.', 'De satelliet is in een baan om de aarde.', 'scienza'),
   ('el telescopio', 'de telescoop', 'el te-les-KO-pjo', 'El telescopio está en Canarias.', 'De telescoop staat op de Canarische Eilanden.', 'scienza'),
   ('el eclipse', 'de eclips', 'el e-KLIP-se', 'Habrá un eclipse solar en agosto.', 'Er is in augustus een zonsverduistering.', 'scienza'),
   ('la Vía Láctea', 'de Melkweg', 'la VIE-a LAK-te-a', 'Vimos la Vía Láctea desde el desierto.', 'We zagen de Melkweg vanuit de woestijn.', 'scienza')]),
L(270, '📋', 'Toetsles B1 — Blok 15', 'Samenvatting van blok 15.',
  'Samenvatting Blok 15', 'Je kent de formele gebiedende wijs en kunt over gezondheid, wetenschap en techniek praten. In de toets: een leestekst en 20 woorden uit lessen 261–269.',
  [('la cirugía', 'de chirurgie / operatie', 'la si-roe-CHIE-a', 'Necesita cirugía.', 'Hij heeft een operatie nodig.', 'salute'),
   ('el diagnóstico', 'de diagnose', 'el djag-NOS-ti-ko', 'El diagnóstico fue rápido.', 'De diagnose was snel gesteld.', 'salute'),
   ('la enfermedad crónica', 'de chronische ziekte', 'la en-fer-me-DAD KRO-ni-ka', 'Tiene una enfermedad crónica.', 'Ze heeft een chronische ziekte.', 'salute'),
   ('la revisión médica', 'de medische controle', 'la rre-vi-SJON ME-di-ka', 'Me hago una revisión médica al año.', 'Ik laat me elk jaar medisch controleren.', 'salute'),
   ('el laboratorio farmacéutico', 'het farmaceutisch bedrijf', 'el la-bo-ra-TO-rjo far-ma-SEU-ti-ko', 'Trabaja en un laboratorio farmacéutico.', 'Hij werkt bij een farmaceutisch bedrijf.', 'scienza'),
   ('el fenómeno', 'het verschijnsel', 'el fe-NO-me-no', 'Es un fenómeno natural.', 'Het is een natuurverschijnsel.', 'scienza'),
   ('la inteligencia artificial', 'de kunstmatige intelligentie', 'la in-te-li-CHEN-sja ar-ti-fi-SJAL', 'La inteligencia artificial avanza rápido.', 'Kunstmatige intelligentie ontwikkelt zich snel.', 'scienza'),
   ('el hito', 'de mijlpaal', 'el IE-to', 'Fue un hito en la medicina.', 'Het was een mijlpaal in de geneeskunde.', 'sostantivo')]),
L(271, '💇', 'De kapper & schoonheid', 'Hacer + infinitivo / dejarse + infinitivo.',
  'Hacer / dejarse + infinitivo', 'Iets laten doen: Me corto el pelo (ik laat mijn haar knippen), me dejo crecer la barba, se hace la manicura, hacerse un tatuaje. Letterlijk reflexief, geen "laten".',
  [('cortarse el pelo', 'zijn haar laten knippen', 'kor-TAR-se el PE-lo', 'Me corto el pelo cada mes.', 'Ik laat mijn haar elke maand knippen.', 'espressione'),
   ('las puntas', 'de puntjes (haar)', 'las POEN-tas', 'Solo las puntas, por favor.', 'Alleen de puntjes, alstublieft.', 'bellezza'),
   ('el flequillo', 'de pony', 'el fle-KIE-jo', 'Quiero flequillo.', 'Ik wil een pony.', 'bellezza'),
   ('teñirse', 'zijn haar verven', 'te-NJIER-se', 'Se tiñe el pelo de rojo.', 'Ze verft haar haar rood.', 'verbo'),
   ('el bigote', 'de snor', 'el bi-GO-te', 'Se dejó bigote.', 'Hij liet een snor staan.', 'bellezza'),
   ('la manicura', 'de manicure', 'la ma-ni-KOE-ra', 'Se hace la manicura los viernes.', 'Ze laat op vrijdag haar nagels doen.', 'bellezza'),
   ('el tatuaje', 'de tatoeage', 'el ta-TWA-che', 'Se hizo un tatuaje en el brazo.', 'Hij liet een tatoeage op zijn arm zetten.', 'bellezza'),
   ('la crema hidratante', 'de vochtinbrengende crème', 'la KRE-ma i-dra-TAN-te', 'Uso crema hidratante cada noche.', 'Ik gebruik elke avond vochtinbrengende crème.', 'bellezza')]),
L(272, '🚗', 'De auto & garage', 'Bij de garage.',
  'Bij de garage', 'El taller (de garage), la avería (de pech), el motor, los frenos, la rueda de repuesto, la ITV (de apk), el seguro a todo riesgo, pinchar (lek rijden), la grúa (de takelwagen).',
  [('el taller mecánico', 'de garage (werkplaats)', 'el ta-JER me-KA-ni-ko', 'Llevé el coche al taller mecánico.', 'Ik bracht de auto naar de garage.', 'trasporto'),
   ('el pinchazo', 'de lekke band', 'el pin-TSJA-so', 'Tuvimos un pinchazo en la autopista.', 'We kregen een lekke band op de snelweg.', 'trasporto'),
   ('los frenos', 'de remmen', 'los FRE-nos', 'Los frenos hacen ruido.', 'De remmen maken lawaai.', 'trasporto'),
   ('la rueda de repuesto', 'het reservewiel', 'la RRWE-da de rre-PWES-to', '¿Dónde está la rueda de repuesto?', 'Waar is het reservewiel?', 'trasporto'),
   ('la ITV', 'de apk-keuring', 'la i-te-OE-ve', 'El coche no pasó la ITV.', 'De auto kwam niet door de apk.', 'trasporto'),
   ('pinchar', 'een lekke band krijgen', 'pin-TSJAR', 'Pinchamos en medio del campo.', 'We kregen een lekke band midden op het platteland.', 'verbo'),
   ('la grúa', 'de takelwagen / sleepwagen', 'la GROE-a', 'Llamamos a la grúa.', 'We belden de sleepwagen.', 'trasporto'),
   ('el seguro a todo riesgo', 'de allriskverzekering', 'el se-GOE-ro a TO-do RRJES-go', 'Tengo seguro a todo riesgo.', 'Ik heb een allriskverzekering.', 'trasporto')]),
L(273, '📮', 'Post & pakketjes', 'Post en bezorging.',
  'Post en bezorging', 'Correos (de posterijen), el sello, el sobre, el paquete, certificado (aangetekend), el remitente, el código postal, el repartidor (de bezorger), recoger en la oficina.',
  [('el sello', 'de postzegel', 'el SE-jo', 'Necesito un sello para Holanda.', 'Ik heb een postzegel voor Nederland nodig.', 'posta'),
   ('el sobre', 'de envelop', 'el SO-bre', 'Mete la carta en el sobre.', 'Doe de brief in de envelop.', 'posta'),
   ('certificado', 'aangetekend', 'ser-ti-fi-KA-do', 'Envíalo certificado.', 'Stuur het aangetekend.', 'aggettivo'),
   ('el remitente', 'de afzender', 'el rre-mi-TEN-te', 'Escribe el remitente detrás.', 'Schrijf de afzender achterop.', 'posta'),
   ('el código postal', 'de postcode', 'el KO-di-go pos-TAL', '¿Cuál es tu código postal?', 'Wat is je postcode?', 'posta'),
   ('el repartidor', 'de bezorger', 'el rre-par-ti-DOR', 'El repartidor llamó dos veces.', 'De bezorger belde twee keer aan.', 'professione'),
   ('el aviso', 'het bericht / de kennisgeving', 'el a-VIE-so', 'Dejaron un aviso en el buzón.', 'Ze lieten een bericht achter in de brievenbus.', 'posta'),
   ('el seguimiento', 'de tracking / het volgen', 'el se-gi-MJEN-to', 'Tengo el número de seguimiento.', 'Ik heb het volgnummer.', 'posta')]),
L(274, '🏦', 'De bank & verzekeringen', 'Verzekeringen regelen.',
  'Verzekeringen regelen', 'La póliza (de polis), la prima (de premie), la cobertura (de dekking), la franquicia (het eigen risico), el siniestro (de schade), dar parte (schade melden), el seguro de hogar / de vida.',
  [('la póliza', 'de polis', 'la PO-li-sa', 'Lee bien la póliza.', 'Lees de polis goed.', 'finanza'),
   ('la prima', 'de premie', 'la PRIE-ma', 'La prima sube cada año.', 'De premie stijgt elk jaar.', 'finanza'),
   ('la cobertura', 'de dekking', 'la ko-ber-TOE-ra', '¿Qué cobertura tiene?', 'Welke dekking heeft u?', 'finanza'),
   ('la franquicia', 'het eigen risico', 'la fran-KIE-sja', 'La franquicia es de 300 euros.', 'Het eigen risico is 300 euro.', 'finanza'),
   ('el siniestro', 'het schadegeval', 'el si-NJES-tro', 'Declaré el siniestro por teléfono.', 'Ik meldde de schade telefonisch.', 'finanza'),
   ('dar parte', 'schade melden / aangifte doen', 'dar PAR-te', 'Di parte al seguro.', 'Ik heb het bij de verzekering gemeld.', 'espressione'),
   ('el seguro de hogar', 'de inboedel-/opstalverzekering', 'el se-GOE-ro de o-GAR', 'El seguro de hogar cubre el robo.', 'De inboedelverzekering dekt diefstal.', 'finanza'),
   ('indemnizar', 'schadeloosstellen / uitkeren', 'in-dem-ni-SAR', 'El seguro me indemnizó.', 'De verzekering keerde uit.', 'verbo')]),
L(275, '👨‍🍳', 'Recepten & koken verdieping', 'Een recept volgen.',
  'Een recept volgen', 'Werkwoorden in het recept: picar (fijnhakken), sofreír (fruiten), hervir, freír, hornear, remover (roeren), añadir, sazonar (kruiden), a fuego lento (op laag vuur).',
  [('picar', 'fijnhakken', 'pi-KAR', 'Pica la cebolla muy fina.', 'Hak de ui heel fijn.', 'cucina'),
   ('sofreír', 'fruiten / aanbakken', 'so-fre-IER', 'Sofríe el ajo en aceite.', 'Fruit de knoflook in olie.', 'cucina'),
   ('hervir', 'koken (water)', 'er-VIER', 'Hierve el agua con sal.', 'Breng het water met zout aan de kook.', 'cucina'),
   ('hornear', 'bakken (in de oven)', 'or-ne-AR', 'Hornea 40 minutos a 180 grados.', 'Bak 40 minuten op 180 graden.', 'cucina'),
   ('remover', 'roeren', 'rre-mo-VER', 'Remueve sin parar.', 'Blijf roeren.', 'cucina'),
   ('sazonar', 'kruiden / op smaak brengen', 'sa-so-NAR', 'Sazona al gusto.', 'Breng op smaak.', 'cucina'),
   ('a fuego lento', 'op laag vuur', 'a FWE-go LEN-to', 'Cocina a fuego lento una hora.', 'Laat een uur op laag vuur koken.', 'espressione'),
   ('la pizca', 'het snufje', 'la PIS-ka', 'Una pizca de sal.', 'Een snufje zout.', 'cucina')]),
L(276, '🧹', 'Huishouden & schoonmaken', 'Huishoudelijke taken.',
  'Huishoudelijke taken', 'Barrer (vegen), fregar el suelo (dweilen), fregar los platos, pasar la aspiradora, quitar el polvo, tender la ropa (de was ophangen), planchar, sacar la basura.',
  [('barrer', 'vegen', 'ba-RRER', 'Barro la cocina cada día.', 'Ik veeg de keuken elke dag.', 'casa'),
   ('fregar', 'dweilen / afwassen', 'fre-GAR', 'Friego el suelo los sábados.', 'Ik dweil de vloer op zaterdag.', 'casa'),
   ('pasar la aspiradora', 'stofzuigen', 'pa-SAR la as-pi-ra-DO-ra', '¿Has pasado la aspiradora?', 'Heb je gestofzuigd?', 'espressione'),
   ('quitar el polvo', 'afstoffen', 'ki-TAR el POL-vo', 'Quita el polvo de las estanterías.', 'Stof de planken af.', 'espressione'),
   ('tender la ropa', 'de was ophangen', 'ten-DER la RRO-pa', 'Tiende la ropa en la terraza.', 'Hang de was op het terras.', 'espressione'),
   ('planchar', 'strijken', 'plan-TSJAR', 'Odio planchar.', 'Ik haat strijken.', 'verbo'),
   ('la lejía', 'de bleek', 'la le-CHIE-a', 'Limpia el baño con lejía.', 'Maak de badkamer schoon met bleek.', 'casa'),
   ('la bayeta', 'het schoonmaakdoekje', 'la ba-JE-ta', 'Pásale una bayeta a la mesa.', 'Haal even een doekje over de tafel.', 'casa')]),
L(277, '🔧', 'Doe-het-zelf & reparatie', 'Reparaties beschrijven.',
  'Reparaties beschrijven', 'Está roto / estropeado (kapot), arreglar, el destornillador (de schroevendraaier), el martillo, el taladro (de boor), el clavo, el tornillo, colgar un cuadro, el fontanero.',
  [('estropeado', 'kapot / defect', 'es-tro-pe-A-do', 'La lavadora está estropeada.', 'De wasmachine is kapot.', 'aggettivo'),
   ('el destornillador', 'de schroevendraaier', 'el des-tor-ni-ja-DOR', 'Pásame el destornillador.', 'Geef me de schroevendraaier.', 'casa'),
   ('el martillo', 'de hamer', 'el mar-TIE-jo', 'Necesito un martillo.', 'Ik heb een hamer nodig.', 'casa'),
   ('el taladro', 'de boormachine', 'el ta-LA-dro', 'Usa el taladro para la pared.', 'Gebruik de boor voor de muur.', 'casa'),
   ('el tornillo', 'de schroef', 'el tor-NIE-jo', 'Falta un tornillo.', 'Er ontbreekt een schroef.', 'casa'),
   ('el clavo', 'de spijker', 'el KLA-vo', 'Clava un clavo aquí.', 'Sla hier een spijker in.', 'casa'),
   ('el electricista', 'de elektricien', 'el e-lek-tri-SIS-ta', 'El electricista arregló el enchufe.', 'De elektricien repareerde het stopcontact.', 'professione'),
   ('la fuga de agua', 'de waterlekkage', 'la FOE-ga de A-gwa', 'Hay una fuga de agua en el baño.', 'Er is een waterlekkage in de badkamer.', 'casa')]),
L(278, '🌻', 'Tuinieren & buitenleven', 'Over de tuin praten.',
  'Over de tuin praten', 'El césped (het gazon), cortar el césped, la manguera (de tuinslang), la barbacoa, la hamaca, el cobertizo (het schuurtje), la valla (het hek), sembrar (zaaien).',
  [('el césped', 'het gazon', 'el SES-ped', 'Hay que cortar el césped.', 'Het gazon moet gemaaid worden.', 'natura'),
   ('la manguera', 'de tuinslang', 'la man-GE-ra', 'Riega con la manguera.', 'Geef water met de tuinslang.', 'casa'),
   ('la barbacoa', 'de barbecue', 'la bar-ba-KO-a', 'El domingo hacemos barbacoa.', 'Zondag barbecueën we.', 'casa'),
   ('la hamaca', 'de hangmat / ligstoel', 'la a-MA-ka', 'Duerme la siesta en la hamaca.', 'Hij doet zijn siësta in de hangmat.', 'casa'),
   ('el cobertizo', 'het schuurtje', 'el ko-ber-TIE-so', 'Las herramientas están en el cobertizo.', 'Het gereedschap ligt in het schuurtje.', 'casa'),
   ('la valla', 'het hek / de omheining', 'la VA-ja', 'Pintamos la valla de blanco.', 'We verfden het hek wit.', 'casa'),
   ('sembrar', 'zaaien', 'sem-BRAR', 'Sembramos tomates en abril.', 'We zaaien tomaten in april.', 'verbo'),
   ('el toldo', 'het zonnescherm', 'el TOL-do', 'Baja el toldo, hace mucho sol.', 'Doe het zonnescherm omlaag, de zon is fel.', 'casa')]),
L(279, '🎉', 'Feest & vieren', 'Feesten en uitnodigen.',
  'Feesten en uitnodigen', 'Dar una fiesta, invitar a, brindar por (toosten op), ¡salud!, la sorpresa, el anfitrión (de gastheer), los invitados, pasarlo en grande (het geweldig naar je zin hebben).',
  [('brindar por', 'toosten op', 'brin-DAR por', 'Brindemos por los novios.', 'Laten we toosten op het bruidspaar.', 'verbo'),
   ('el anfitrión', 'de gastheer', 'el an-fi-TRJON', 'El anfitrión nos recibió en la puerta.', 'De gastheer ontving ons bij de deur.', 'eventi'),
   ('el invitado', 'de gast / genodigde', 'el in-vi-TA-do', 'Había cincuenta invitados.', 'Er waren vijftig gasten.', 'eventi'),
   ('pasarlo en grande', 'het geweldig naar je zin hebben', 'pa-SAR-lo en GRAN-de', 'Lo pasamos en grande.', 'We hadden het geweldig naar onze zin.', 'espressione'),
   ('la fiesta sorpresa', 'het verrassingsfeest', 'la FJES-ta sor-PRE-sa', 'Le organizaron una fiesta sorpresa.', 'Ze organiseerden een verrassingsfeest voor haar.', 'eventi'),
   ('el brindis', 'de toost', 'el BRIN-dis', 'Hizo un brindis emocionante.', 'Hij hield een ontroerende toost.', 'eventi'),
   ('la despedida de soltero', 'het vrijgezellenfeest', 'la des-pe-DIE-da de sol-TE-ro', 'La despedida de soltero es en Ibiza.', 'Het vrijgezellenfeest is op Ibiza.', 'eventi'),
   ('apuntarse a', 'zich opgeven voor / meedoen', 'a-poen-TAR-se a', '¿Te apuntas a la cena?', 'Doe je mee met het etentje?', 'verbo')]),
L(280, '📋', 'Toetsles B1 — Blok 16', 'Samenvatting van blok 16.',
  'Samenvatting Blok 16', 'Je kent hacer/dejarse + infinitivo en kunt praktische zaken regelen: auto, post, verzekering, keuken, huishouden, klussen en feesten. In de toets: een leestekst en 20 woorden uit lessen 271–279.',
  [('la herramienta', 'het gereedschap', 'la e-rra-MJEN-ta', 'Guarda las herramientas.', 'Berg het gereedschap op.', 'casa'),
   ('el electrodoméstico', 'het huishoudelijk apparaat', 'el e-lek-tro-do-MES-ti-ko', 'Compramos electrodomésticos nuevos.', 'We kochten nieuwe huishoudelijke apparaten.', 'casa'),
   ('averiarse', 'kapotgaan / defect raken', 'a-ve-RJAR-se', 'Se averió el lavavajillas.', 'De vaatwasser ging kapot.', 'verbo'),
   ('el presupuesto de reparación', 'de reparatieofferte', 'el pre-soe-PWES-to de rre-pa-ra-SJON', 'Pedí un presupuesto de reparación.', 'Ik vroeg een reparatieofferte.', 'casa'),
   ('el mantenimiento', 'het onderhoud', 'el man-te-ni-MJEN-to', 'El mantenimiento es caro.', 'Het onderhoud is duur.', 'casa'),
   ('hacer bricolaje', 'klussen', 'a-SER bri-ko-LA-che', 'Le encanta hacer bricolaje.', 'Hij klust graag.', 'espressione'),
   ('apañárselas', 'zich weten te redden', 'a-pa-NJAR-se-las', 'Me las apaño solo.', 'Ik red me wel alleen.', 'espressione'),
   ('de segunda mano', 'tweedehands', 'de se-GOEN-da MA-no', 'Lo compré de segunda mano.', 'Ik kocht het tweedehands.', 'espressione')]),
L(281, '💬', 'Uitdrukkingen — deel 1', 'Idioom met lichaamsdelen.',
  'Idioom met lichaamsdelen', 'Costar un ojo de la cara (een rib uit je lijf kosten), no tener pelos en la lengua (geen blad voor de mond nemen), estar hasta las narices (het spuugzat zijn), tomar el pelo (voor de gek houden).',
  [('costar un ojo de la cara', 'een rib uit je lijf kosten', 'kos-TAR oen O-cho de la KA-ra', 'Ese coche cuesta un ojo de la cara.', 'Die auto kost een rib uit je lijf.', 'espressione'),
   ('no tener pelos en la lengua', 'geen blad voor de mond nemen', 'no te-NER PE-los en la LEN-gwa', 'Mi abuela no tiene pelos en la lengua.', 'Mijn oma neemt geen blad voor de mond.', 'espressione'),
   ('estar hasta las narices', 'het spuugzat zijn', 'es-TAR AS-ta las na-RIE-ses', 'Estoy hasta las narices del ruido.', 'Ik ben het lawaai spuugzat.', 'espressione'),
   ('tomar el pelo', 'voor de gek houden', 'to-MAR el PE-lo', '¿Me estás tomando el pelo?', 'Hou je me voor de gek?', 'espressione'),
   ('meter la pata', 'een flater slaan', 'me-TER la PA-ta', 'Metí la pata en la reunión.', 'Ik sloeg een flater in de vergadering.', 'espressione'),
   ('echar una mano a alguien', 'iemand helpen', 'e-TSJAR OE-na MA-no', 'Siempre echa una mano a sus vecinos.', 'Hij helpt zijn buren altijd.', 'espressione'),
   ('tener la cabeza en las nubes', 'met je hoofd in de wolken lopen', 'te-NER la ka-BE-sa en las NOE-bes', 'Hoy tienes la cabeza en las nubes.', 'Je loopt vandaag met je hoofd in de wolken.', 'espressione'),
   ('hablar por los codos', 'honderduit praten', 'a-BLAR por los KO-dos', 'Mi hermana habla por los codos.', 'Mijn zus praat honderduit.', 'espressione')]),
L(282, '💬', 'Uitdrukkingen — deel 2', 'Dagelijkse uitdrukkingen.',
  'Dagelijkse uitdrukkingen', 'Estar en las nubes, ser pan comido (een eitje zijn), ponerse las pilas (de handen uit de mouwen steken), dar en el clavo (de spijker op de kop slaan), estar como una cabra (knettergek zijn).',
  [('ser pan comido', 'een eitje zijn', 'ser pan ko-MIE-do', 'El examen fue pan comido.', 'Het examen was een eitje.', 'espressione'),
   ('ponerse las pilas', 'de handen uit de mouwen steken', 'po-NER-se las PIE-las', 'Tienes que ponerte las pilas.', 'Je moet de handen uit de mouwen steken.', 'espressione'),
   ('dar en el clavo', 'de spijker op de kop slaan', 'dar en el KLA-vo', 'Has dado en el clavo.', 'Je slaat de spijker op de kop.', 'espressione'),
   ('estar como una cabra', 'knettergek zijn', 'es-TAR KO-mo OE-na KA-bra', 'Tu primo está como una cabra.', 'Je neef is knettergek.', 'espressione'),
   ('no pegar ojo', 'geen oog dichtdoen', 'no pe-GAR O-cho', 'No pegué ojo en toda la noche.', 'Ik heb de hele nacht geen oog dichtgedaan.', 'espressione'),
   ('ir al grano', 'ter zake komen', 'ier al GRA-no', 'Ve al grano, por favor.', 'Kom ter zake, alsjeblieft.', 'espressione'),
   ('tirar la toalla', 'de handdoek in de ring gooien', 'ti-RAR la to-A-ja', 'No tires la toalla todavía.', 'Gooi de handdoek nog niet in de ring.', 'espressione'),
   ('estar en las nubes', 'er met je gedachten niet bij zijn', 'es-TAR en las NOE-bes', 'Perdona, estaba en las nubes.', 'Sorry, ik was er met mijn gedachten niet bij.', 'espressione')]),
L(283, '📜', 'Spreekwoorden', 'Spaanse spreekwoorden.',
  'Spaanse spreekwoorden', 'Más vale tarde que nunca. No hay mal que por bien no venga (elk nadeel heeft zijn voordeel). A quien madruga, Dios le ayuda (de morgenstond heeft goud in de mond). En boca cerrada no entran moscas.',
  [('más vale tarde que nunca', 'beter laat dan nooit', 'mas VA-le TAR-de ke NOEN-ka', 'Llegó al final, más vale tarde que nunca.', 'Hij kwam uiteindelijk, beter laat dan nooit.', 'proverbio'),
   ('no hay mal que por bien no venga', 'elk nadeel heeft zijn voordeel', 'no ai mal ke por bjen no VEN-ga', 'Perdí el trabajo, pero encontré uno mejor: no hay mal que por bien no venga.', 'Ik verloor mijn baan, maar vond een betere: elk nadeel heeft zijn voordeel.', 'proverbio'),
   ('a quien madruga, Dios le ayuda', 'de morgenstond heeft goud in de mond', 'a kjen ma-DROE-ga djos le a-JOE-da', 'Levántate: a quien madruga, Dios le ayuda.', 'Sta op: de morgenstond heeft goud in de mond.', 'proverbio'),
   ('en boca cerrada no entran moscas', 'spreken is zilver, zwijgen is goud', 'en BO-ka se-RRA-da no EN-tran MOS-kas', 'Mejor callar: en boca cerrada no entran moscas.', 'Beter zwijgen: spreken is zilver, zwijgen is goud.', 'proverbio'),
   ('más vale prevenir que curar', 'voorkomen is beter dan genezen', 'mas VA-le pre-ve-NIER ke koe-RAR', 'Ponte el casco: más vale prevenir que curar.', 'Zet je helm op: voorkomen is beter dan genezen.', 'proverbio'),
   ('ojos que no ven, corazón que no siente', 'wat niet weet, wat niet deert', 'O-chos ke no ven ko-ra-SON ke no SJEN-te', 'No se lo digas: ojos que no ven, corazón que no siente.', 'Zeg het hem niet: wat niet weet, wat niet deert.', 'proverbio'),
   ('dime con quién andas y te diré quién eres', 'zeg me wie je vrienden zijn en ik zeg wie je bent', 'DIE-me kon kjen AN-das', 'Dime con quién andas y te diré quién eres.', 'Zeg me met wie je omgaat en ik zeg je wie je bent.', 'proverbio'),
   ('no dejes para mañana lo que puedas hacer hoy', 'stel niet uit tot morgen wat je vandaag kunt doen', 'no DE-ches PA-ra ma-NJA-na', 'Hazlo ya: no dejes para mañana lo que puedas hacer hoy.', 'Doe het nu: stel niet uit tot morgen wat je vandaag kunt doen.', 'proverbio')]),
L(284, '🔗', 'Vaste werkwoordcombinaties', 'Verbos pronominales met andere betekenis.',
  'Verbos pronominales', 'Sommige werkwoorden veranderen van betekenis met se: ir (gaan) / irse (weggaan), dormir / dormirse (in slaap vallen), quedar (afspreken) / quedarse (blijven), llevar / llevarse (meenemen), acordar / acordarse de (zich herinneren).',
  [('irse', 'weggaan', 'IER-se', 'Me voy, es tarde.', 'Ik ga weg, het is laat.', 'verbo'),
   ('ponerse a', 'beginnen te', 'po-NER-se a', 'Se puso a llover.', 'Het begon te regenen.', 'verbo'),
   ('volverse', 'worden (verandering)', 'vol-VER-se', 'Se ha vuelto muy serio.', 'Hij is heel serieus geworden.', 'verbo'),
   ('llevarse', 'meenemen', 'je-VAR-se', 'Llévate el paraguas.', 'Neem de paraplu mee.', 'verbo'),
   ('fijarse en', 'letten op / opmerken', 'fi-CHAR-se en', 'Fíjate en los detalles.', 'Let op de details.', 'verbo'),
   ('negarse a', 'weigeren om', 'ne-GAR-se a', 'Se negó a firmar.', 'Hij weigerde te tekenen.', 'verbo'),
   ('encontrarse con', 'tegenkomen', 'en-kon-TRAR-se kon', 'Me encontré con Luis en el mercado.', 'Ik kwam Luis tegen op de markt.', 'verbo'),
   ('ocuparse de', 'zorgen voor / zich bezighouden met', 'o-koe-PAR-se de', 'Yo me ocupo de la cena.', 'Ik zorg voor het eten.', 'verbo')]),
L(285, '✍️', 'Formeel schrijven', 'Formeel schrijven.',
  'Formeel schrijven', 'Por la presente (hierbij), le comunico que, en virtud de (krachtens), sin otro particular (zonder verder iets), reciba un cordial saludo, les rogamos disculpen, lo antes posible (zo spoedig mogelijk).',
  [('por la presente', 'hierbij / bij dezen', 'por la pre-SEN-te', 'Por la presente le comunico mi dimisión.', 'Hierbij deel ik u mijn ontslag mee.', 'espressione'),
   ('le comunico que', 'ik deel u mee dat', 'le ko-moe-NIE-ko ke', 'Le comunico que su solicitud ha sido aceptada.', 'Ik deel u mee dat uw aanvraag is aanvaard.', 'espressione'),
   ('sin otro particular', 'zonder verder iets (slotformule)', 'sin O-tro par-ti-koe-LAR', 'Sin otro particular, reciba un cordial saludo.', 'Zonder verder iets, met vriendelijke groet.', 'espressione'),
   ('lo antes posible', 'zo spoedig mogelijk', 'lo AN-tes po-SIE-ble', 'Respondan lo antes posible.', 'Antwoordt u zo spoedig mogelijk.', 'espressione'),
   ('la solicitud', 'de aanvraag / het verzoek', 'la so-li-si-TOED', 'Presenté la solicitud ayer.', 'Ik diende de aanvraag gisteren in.', 'burocrazia'),
   ('la instancia', 'het verzoekschrift', 'la ins-TAN-sja', 'Hay que rellenar una instancia.', 'Er moet een verzoekschrift ingevuld worden.', 'burocrazia'),
   ('el abajo firmante', 'ondergetekende', 'el a-BA-cho fir-MAN-te', 'El abajo firmante declara que…', 'Ondergetekende verklaart dat…', 'espressione'),
   ('a la atención de', 'ter attentie van', 'a la a-ten-SJON de', 'A la atención del director.', 'Ter attentie van de directeur.', 'espressione')]),
L(286, '😄', 'Informeel taalgebruik', 'Informele taal.',
  'Informele taal', 'Spreektaal: guay (cool), flipar (versteld staan), currar (werken), la pasta (poen), el finde (weekend), quedar (afspreken), ¡qué fuerte! (niet te geloven!), vale.',
  [('guay', 'cool / tof', 'gwai', '¡Qué guay tu moto!', 'Wat een toffe scooter!', 'aggettivo'),
   ('flipar', 'versteld staan / flippen', 'fli-PAR', 'Flipé con el concierto.', 'Ik stond versteld van het concert.', 'verbo'),
   ('currar', 'werken (spreektaal)', 'koe-RRAR', 'Mañana curro hasta las ocho.', 'Morgen werk ik tot acht uur.', 'verbo'),
   ('la pasta', 'poen / geld (spreektaal)', 'la PAS-ta', 'No tengo pasta.', 'Ik heb geen poen.', 'sostantivo'),
   ('el finde', 'het weekend (spreektaal)', 'el FIN-de', '¿Qué haces el finde?', 'Wat doe je dit weekend?', 'sostantivo'),
   ('¡qué fuerte!', 'niet te geloven! / wauw!', 'ke FWER-te', '¿Se casan? ¡Qué fuerte!', 'Gaan ze trouwen? Niet te geloven!', 'espressione'),
   ('la movida', 'het gedoe / de scene', 'la mo-VIE-da', 'Menuda movida en el aeropuerto.', 'Wat een gedoe op het vliegveld.', 'sostantivo'),
   ('pillar', 'pakken / snappen (spreektaal)', 'pi-JAR', '¿Lo pillas?', 'Snap je het?', 'verbo')]),
L(287, '📱', 'Telefoneren', 'Telefoneren in het Spaans.',
  'Telefoneren in het Spaans', '¿Diga? / ¿Dígame? (hallo, bij opnemen). ¿De parte de quién? (met wie spreek ik?). Un momento, no cuelgue (hang niet op). Se ha equivocado de número. Le devuelvo la llamada.',
  [('¿diga?', 'hallo? (opnemen)', 'DIE-ga', '¿Diga? ¿Quién es?', 'Hallo? Met wie?', 'espressione'),
   ('¿de parte de quién?', 'met wie spreek ik?', 'de PAR-te de kjen', '¿De parte de quién, por favor?', 'Met wie spreek ik, alstublieft?', 'espressione'),
   ('no cuelgue', 'blijf aan de lijn (u)', 'no KWEL-ge', 'Un momento, no cuelgue.', 'Een ogenblik, blijft u aan de lijn.', 'espressione'),
   ('equivocarse de número', 'een verkeerd nummer bellen', 'e-ki-vo-KAR-se de NOE-me-ro', 'Se ha equivocado de número.', 'U heeft het verkeerde nummer.', 'espressione'),
   ('devolver la llamada', 'terugbellen', 'de-vol-VER la ja-MA-da', 'Le devuelvo la llamada en una hora.', 'Ik bel u over een uur terug.', 'espressione'),
   ('dejar un recado', 'een boodschap achterlaten', 'de-CHAR oen rre-KA-do', '¿Quiere dejar un recado?', 'Wilt u een boodschap achterlaten?', 'espressione'),
   ('colgar', 'ophangen (telefoon)', 'kol-GAR', 'Me colgó sin despedirse.', 'Hij hing op zonder gedag te zeggen.', 'verbo'),
   ('el buzón de voz', 'de voicemail', 'el boe-SON de vos', 'Déjame un mensaje en el buzón de voz.', 'Spreek een bericht in op mijn voicemail.', 'tecnologia')]),
L(288, '😤', 'Klachten & problemen', 'Klachten uiten.',
  'Klachten uiten', 'Quería quejarme de (ik wil klagen over), esto es inaceptable, exijo (ik eis), no es la primera vez que, ¿me puede atender el responsable?, quiero que me devuelvan el dinero.',
  [('reclamar', 'reclameren / opeisen', 'rre-kla-MAR', 'Reclamé el importe pagado.', 'Ik eiste het betaalde bedrag terug.', 'verbo'),
   ('inaceptable', 'onaanvaardbaar', 'i-nak-sep-TA-ble', 'Esto es inaceptable.', 'Dit is onaanvaardbaar.', 'aggettivo'),
   ('exigir', 'eisen', 'ek-si-CHIER', 'Exijo una explicación.', 'Ik eis een verklaring.', 'verbo'),
   ('el encargado', 'de leidinggevende / verantwoordelijke', 'el en-kar-GA-do', 'Quiero hablar con el encargado.', 'Ik wil de leidinggevende spreken.', 'sostantivo'),
   ('no es la primera vez que', 'het is niet de eerste keer dat', 'no es la pri-ME-ra ves ke', 'No es la primera vez que pasa.', 'Het is niet de eerste keer dat dit gebeurt.', 'espressione'),
   ('la indemnización', 'de schadevergoeding', 'la in-dem-ni-sa-SJON', 'Pido una indemnización.', 'Ik vraag een schadevergoeding.', 'affari'),
   ('defectuoso', 'defect / gebrekkig', 'de-fek-TWO-so', 'El producto llegó defectuoso.', 'Het product kwam defect aan.', 'aggettivo'),
   ('el perjuicio', 'de schade / het nadeel', 'el per-CHWI-sjo', 'El retraso me causó un gran perjuicio.', 'De vertraging bezorgde me grote schade.', 'affari')]),
L(289, '🙏', 'Complimenten & bedankjes', 'Complimenten en bedankjes.',
  'Complimenten & bedankjes', '¡Qué bien te queda! ¡Enhorabuena! Te lo agradezco de corazón (ik dank je van harte). No tenías que haberte molestado. Es todo un detalle (dat is heel attent). No hay de qué (graag gedaan).',
  [('agradecer de corazón', 'van harte bedanken', 'a-gra-de-SER de ko-ra-SON', 'Te lo agradezco de corazón.', 'Ik dank je van harte.', 'espressione'),
   ('no hay de qué', 'graag gedaan', 'no ai de ke', '—Gracias. —No hay de qué.', '—Bedankt. —Graag gedaan.', 'espressione'),
   ('el detalle', 'de attentie / het gebaar', 'el de-TA-je', 'Es todo un detalle por tu parte.', 'Dat is heel attent van je.', 'sostantivo'),
   ('no tenías que haberte molestado', 'dat had je niet hoeven doen', 'no te-NIE-as ke a-BER-te mo-les-TA-do', '¡Flores! No tenías que haberte molestado.', 'Bloemen! Dat had je niet hoeven doen.', 'espressione'),
   ('halagar', 'vleien / complimenteren', 'a-la-GAR', 'Me halaga que lo digas.', 'Het vleit me dat je dat zegt.', 'verbo'),
   ('el cumplido', 'het compliment', 'el koem-PLIE-do', 'Le hizo un cumplido.', 'Hij gaf haar een compliment.', 'sostantivo'),
   ('estar agradecido', 'dankbaar zijn', 'es-TAR a-gra-de-SIE-do', 'Estoy muy agradecido por tu ayuda.', 'Ik ben heel dankbaar voor je hulp.', 'espressione'),
   ('quedar en deuda con', 'bij iemand in het krijt staan', 'ke-DAR en DEU-da kon', 'Quedo en deuda contigo.', 'Ik sta bij je in het krijt.', 'espressione')]),
L(290, '📋', 'Toetsles B1 — Blok 17', 'Samenvatting van blok 17.',
  'Samenvatting Blok 17', 'Je kent idioom, spreekwoorden, pronominale werkwoorden en de registers formeel, informeel en telefonisch. In de toets: een leestekst en 20 woorden uit lessen 281–289.',
  [('el dicho', 'het gezegde', 'el DIE-tsjo', 'Como dice el dicho…', 'Zoals het gezegde luidt…', 'proverbio'),
   ('la expresión hecha', 'de vaste uitdrukking', 'la eks-pre-SJON E-tsja', 'Es una expresión hecha.', 'Het is een vaste uitdrukking.', 'sostantivo'),
   ('el doble sentido', 'de dubbele betekenis', 'el DO-ble sen-TIE-do', 'La frase tiene doble sentido.', 'De zin heeft een dubbele betekenis.', 'sostantivo'),
   ('literalmente', 'letterlijk', 'li-te-ral-MEN-te', 'No lo traduzcas literalmente.', 'Vertaal het niet letterlijk.', 'avverbio'),
   ('el tono', 'de toon', 'el TO-no', 'No me gusta ese tono.', 'Ik hou niet van die toon.', 'sostantivo'),
   ('la ironía', 'de ironie', 'la i-ro-NIE-a', 'Lo dijo con ironía.', 'Hij zei het ironisch.', 'sostantivo'),
   ('el sarcasmo', 'het sarcasme', 'el sar-KAS-mo', 'Detecto sarcasmo en tu voz.', 'Ik hoor sarcasme in je stem.', 'sostantivo'),
   ('la cortesía verbal', 'de taalbeleefdheid', 'la kor-te-SIE-a ver-BAL', 'La cortesía verbal varía por país.', 'Taalbeleefdheid verschilt per land.', 'sostantivo')]),
L(291, '⏳', 'Verleden tijden — herhaling', 'Alle verleden tijden.',
  'Alle verleden tijden', 'Perfecto (hoy, esta semana: he comido), indefinido (ayer: comí), imperfecto (achtergrond, gewoonte: comía), pluscuamperfecto (eerder dan: había comido). Signaalwoorden kiezen de tijd.',
  [('hace un rato', 'zonet / een tijdje geleden', 'A-se oen RRA-to', 'Ha llamado hace un rato.', 'Hij heeft zonet gebeld.', 'espressione'),
   ('en aquel entonces', 'in die tijd / destijds', 'en a-KEL en-TON-ses', 'En aquel entonces no había móviles.', 'Destijds waren er geen mobieltjes.', 'espressione'),
   ('antiguamente', 'vroeger / in vroeger tijden', 'an-ti-gwa-MEN-te', 'Antiguamente se viajaba en diligencia.', 'Vroeger reisde men per postkoets.', 'avverbio'),
   ('hasta ahora', 'tot nu toe', 'AS-ta a-O-ra', 'Hasta ahora todo ha ido bien.', 'Tot nu toe is alles goed gegaan.', 'espressione'),
   ('aquel día', 'die dag', 'a-KEL DIE-a', 'Aquel día llovió sin parar.', 'Die dag regende het onophoudelijk.', 'espressione'),
   ('últimamente', 'de laatste tijd', 'OEL-ti-ma-MEN-te', 'Últimamente duermo mal.', 'De laatste tijd slaap ik slecht.', 'avverbio'),
   ('acostumbrar a', 'gewoon zijn te', 'a-kos-toem-BRAR a', 'Acostumbraba a pasear por la tarde.', 'Hij was gewoon \'s middags te wandelen.', 'verbo'),
   ('acabar de', 'net gedaan hebben', 'a-ka-BAR de', 'Acabo de llegar.', 'Ik ben net aangekomen.', 'espressione')]),
L(292, '🧠', 'Subjuntivo — herhaling', 'Subjuntivo overzicht.',
  'Subjuntivo overzicht', 'Na wens (quiero que), emotie (me alegro de que), twijfel (dudo que), onpersoonlijk (es importante que), doel (para que), toekomst in bijzin (cuando llegues), ontkende mening (no creo que). Presente en imperfecto.',
  [('me alegro de que', 'ik ben blij dat', 'me a-LE-gro de ke', 'Me alegro de que estés aquí.', 'Ik ben blij dat je hier bent.', 'espressione'),
   ('es importante que', 'het is belangrijk dat', 'es im-por-TAN-te ke', 'Es importante que descanses.', 'Het is belangrijk dat je uitrust.', 'espressione'),
   ('siento que', 'het spijt me dat', 'SJEN-to ke', 'Siento que no puedas venir.', 'Het spijt me dat je niet kunt komen.', 'espressione'),
   ('es probable que', 'het is waarschijnlijk dat', 'es pro-BA-ble ke', 'Es probable que llegue tarde.', 'Hij komt waarschijnlijk laat.', 'espressione'),
   ('cuando llegues', 'wanneer je aankomt (toekomst)', 'KWAN-do JE-ges', 'Llámame cuando llegues.', 'Bel me wanneer je aankomt.', 'espressione'),
   ('no creo que', 'ik denk niet dat', 'no KRE-o ke', 'No creo que sea buena idea.', 'Ik denk niet dat het een goed idee is.', 'espressione'),
   ('qué raro que', 'wat vreemd dat', 'ke RRA-ro ke', 'Qué raro que no haya llamado.', 'Wat vreemd dat hij niet gebeld heeft.', 'espressione'),
   ('tal vez', 'misschien', 'tal ves', 'Tal vez tengas razón.', 'Misschien heb je gelijk.', 'avverbio')]),
L(293, '💭', 'Condicional — herhaling', 'Condicional overzicht.',
  'Condicional overzicht', 'Beleefdheid (¿Podría…?), advies (Yo que tú, iría), wens (Me gustaría), vermoeden in het verleden (Serían las diez), irreëel (Si pudiera, viajaría), toekomst in het verleden (Dijo que vendría).',
  [('yo que tú', 'als ik jou was', 'jo ke toe', 'Yo que tú, aceptaría.', 'Als ik jou was, zou ik accepteren.', 'espressione'),
   ('¿podría…?', 'zou u kunnen…?', 'po-DRIE-a', '¿Podría ayudarme?', 'Zou u me kunnen helpen?', 'espressione'),
   ('serían las diez', 'het zal een uur of tien geweest zijn', 'se-RIE-an las djes', 'Serían las diez cuando llegó.', 'Het zal een uur of tien geweest zijn toen hij aankwam.', 'espressione'),
   ('¿te importaría…?', 'zou je het erg vinden om…?', 'te im-por-ta-RIE-a', '¿Te importaría cerrar la ventana?', 'Zou je het erg vinden het raam dicht te doen?', 'espressione'),
   ('deberías', 'je zou moeten', 'de-be-RIE-as', 'Deberías descansar más.', 'Je zou meer moeten rusten.', 'espressione'),
   ('me encantaría', 'ik zou het heerlijk vinden', 'me en-kan-ta-RIE-a', 'Me encantaría visitar Cuba.', 'Ik zou Cuba heel graag bezoeken.', 'espressione'),
   ('sería mejor que', 'het zou beter zijn als', 'se-RIE-a me-CHOR ke', 'Sería mejor que esperáramos.', 'Het zou beter zijn als we zouden wachten.', 'espressione'),
   ('dijo que vendría', 'hij zei dat hij zou komen', 'DIE-cho ke ven-DRIE-a', 'Dijo que vendría a las ocho.', 'Hij zei dat hij om acht uur zou komen.', 'espressione')]),
L(294, '🔀', 'Voorwaardelijke zinnen — alle types', 'Si-zinnen: reëel, irreëel, verleden.',
  'Si-zinnen: alle types', 'Type 1: Si tengo tiempo, voy. Type 2: Si tuviera tiempo, iría. Type 3: Si hubiera tenido tiempo, habría ido. Gemengd: Si hubiera estudiado, ahora tendría trabajo.',
  [('si hubiera tenido', 'als ik had gehad', 'si oe-BJE-ra te-NIE-do', 'Si hubiera tenido tiempo, habría ido.', 'Als ik tijd had gehad, zou ik zijn gegaan.', 'espressione'),
   ('si hubiera estudiado', 'als ik had gestudeerd', 'si oe-BJE-ra es-toe-DJA-do', 'Si hubiera estudiado, ahora tendría trabajo.', 'Als ik had gestudeerd, zou ik nu werk hebben.', 'espressione'),
   ('a no ser que', 'tenzij', 'a no ser ke', 'Iremos, a no ser que llueva.', 'We gaan, tenzij het regent.', 'espressione'),
   ('con tal de', 'als het maar / mits', 'kon tal de', 'Haría cualquier cosa con tal de verla.', 'Ik zou alles doen om haar te zien.', 'espressione'),
   ('de lo contrario', 'anders', 'de lo kon-TRA-rjo', 'Estudia; de lo contrario, suspenderás.', 'Studeer; anders zak je.', 'espressione'),
   ('en ese caso', 'in dat geval', 'en E-se KA-so', 'En ese caso, no voy.', 'In dat geval ga ik niet.', 'espressione'),
   ('de haber sabido', 'als ik had geweten', 'de a-BER sa-BIE-do', 'De haber sabido, no habría venido.', 'Als ik het had geweten, was ik niet gekomen.', 'espressione'),
   ('siempre y cuando', 'op voorwaarde dat', 'SJEM-pre i KWAN-do', 'Te presto el coche siempre y cuando lo cuides.', 'Ik leen je de auto op voorwaarde dat je er zuinig op bent.', 'espressione')]),
L(295, '🗣️', 'Indirecte rede — verdieping', 'Indirecte rede met bevelen en vragen.',
  'Indirecte rede verdieping', 'Bevelen: "Ven" → Me dijo que viniera (subjuntivo). Vragen: "¿Vienes?" → Me preguntó si venía. Tijd en plaats verschuiven: hoy → aquel día, aquí → allí, mañana → al día siguiente.',
  [('al día siguiente', 'de volgende dag', 'al DIE-a si-GJEN-te', 'Dijo que vendría al día siguiente.', 'Hij zei dat hij de volgende dag zou komen.', 'espressione'),
   ('el día anterior', 'de dag ervoor', 'el DIE-a an-te-RJOR', 'Contó que había llegado el día anterior.', 'Hij vertelde dat hij de dag ervoor was aangekomen.', 'espressione'),
   ('me ordenó que', 'hij beval me om', 'me or-de-NO ke', 'Me ordenó que saliera.', 'Hij beval me naar buiten te gaan.', 'espressione'),
   ('me aconsejó que', 'hij raadde me aan om', 'me a-kon-se-CHO ke', 'Me aconsejó que descansara.', 'Hij raadde me aan uit te rusten.', 'espressione'),
   ('me rogó que', 'hij smeekte me om', 'me rro-GO ke', 'Me rogó que no me fuera.', 'Hij smeekte me niet weg te gaan.', 'espressione'),
   ('me prohibió que', 'hij verbood me om', 'me pro-i-BJO ke', 'Me prohibió que fumara en casa.', 'Hij verbood me thuis te roken.', 'espressione'),
   ('me sugirió que', 'hij stelde me voor om', 'me soe-chi-RJO ke', 'Me sugirió que probara el gazpacho.', 'Hij stelde voor dat ik de gazpacho zou proberen.', 'espressione'),
   ('en aquel lugar', 'op die plek (indirecte rede)', 'en a-KEL loe-GAR', 'Dijo que en aquel lugar hacía frío.', 'Hij zei dat het op die plek koud was.', 'espressione')]),
L(296, '📝', 'Connectoren & tekststructuur', 'Conectores textuales.',
  'Conectores textuales', 'Opsommen: en primer lugar, además, asimismo. Tegenstellen: sin embargo, no obstante, en cambio. Gevolg: por consiguiente, así pues. Afsluiten: en definitiva, en resumen, en conclusión.',
  [('por otra parte', 'anderzijds / bovendien', 'por O-tra PAR-te', 'Por otra parte, el coste es alto.', 'Anderzijds zijn de kosten hoog.', 'espressione'),
   ('de hecho', 'in feite / sterker nog', 'de E-tsjo', 'De hecho, ya lo sabía.', 'In feite wist ik het al.', 'espressione'),
   ('por consiguiente', 'bijgevolg', 'por kon-si-GJEN-te', 'Por consiguiente, se cancela el acto.', 'Bijgevolg wordt het evenement geannuleerd.', 'espressione'),
   ('en definitiva', 'kortom / al met al', 'en de-fi-ni-TIE-va', 'En definitiva, fue un éxito.', 'Al met al was het een succes.', 'espressione'),
   ('en cuanto a', 'wat betreft', 'en KWAN-to a', 'En cuanto al precio, es razonable.', 'Wat de prijs betreft, die is redelijk.', 'espressione'),
   ('es decir', 'dat wil zeggen', 'es de-SIER', 'Es bilingüe, es decir, habla dos lenguas.', 'Ze is tweetalig, dat wil zeggen, ze spreekt twee talen.', 'espressione'),
   ('así pues', 'dus / zodoende', 'a-SIE pwes', 'Así pues, empezamos mañana.', 'Dus beginnen we morgen.', 'espressione'),
   ('en resumidas cuentas', 'kort samengevat', 'en rre-soe-MIE-das KWEN-tas', 'En resumidas cuentas, no hay dinero.', 'Kort samengevat: er is geen geld.', 'espressione')]),
L(297, '🔤', 'Woordvorming & afleidingen', 'Woordvorming.',
  'Woordvorming', 'Achtervoegsels: -ción (acción), -dad (felicidad), -miento (crecimiento), -ero (panadero), -able (amable), -oso (famoso), -mente (rápidamente). Voorvoegsels: des- (deshacer), in-/im- (imposible), re- (rehacer).',
  [('deshacer', 'ongedaan maken / uit elkaar halen', 'de-sa-SER', 'Deshaz la maleta.', 'Pak de koffer uit.', 'verbo'),
   ('rehacer', 'overdoen / opnieuw maken', 'rre-a-SER', 'Tuve que rehacer el trabajo.', 'Ik moest het werk overdoen.', 'verbo'),
   ('la amabilidad', 'de vriendelijkheid', 'la a-ma-bi-li-DAD', 'Gracias por su amabilidad.', 'Dank voor uw vriendelijkheid.', 'sostantivo'),
   ('el envejecimiento', 'de vergrijzing / veroudering', 'el en-ve-che-si-MJEN-to', 'El envejecimiento de la población es un reto.', 'De vergrijzing is een uitdaging.', 'sostantivo'),
   ('inolvidable', 'onvergetelijk', 'i-nol-vi-DA-ble', 'Fue un viaje inolvidable.', 'Het was een onvergetelijke reis.', 'aggettivo'),
   ('lluvioso', 'regenachtig', 'joe-VJO-so', 'Un día lluvioso.', 'Een regenachtige dag.', 'aggettivo'),
   ('la fontanería', 'het loodgieterswerk (van fontanero)', 'la fon-ta-ne-RIE-a', 'La fontanería es un buen oficio.', 'Loodgieterswerk is een goed vak.', 'sostantivo'),
   ('impuntual', 'onpunctueel', 'im-poen-TWAL', 'Es muy impuntual.', 'Hij is heel onpunctueel.', 'aggettivo')]),
L(298, '⚠️', 'Valse vrienden NL-ES', 'Valse vrienden.',
  'Valse vrienden', 'Woorden die lijken op Nederlands maar iets anders betekenen: constipado (verkouden, niet verstopt), embarazada (zwanger, niet in verlegenheid), actual (huidig), éxito (succes), largo (lang), carta (brief).',
  [('constipado', 'verkouden (niet: verstopt)', 'kons-ti-PA-do', 'Estoy constipado desde ayer.', 'Ik ben sinds gisteren verkouden.', 'aggettivo'),
   ('embarazada', 'zwanger (niet: in verlegenheid)', 'em-ba-ra-SA-da', 'Está embarazada de cinco meses.', 'Ze is vijf maanden zwanger.', 'aggettivo'),
   ('actual', 'huidig (niet: actueel = de actualidad)', 'ak-TWAL', 'El gobierno actual.', 'De huidige regering.', 'aggettivo'),
   ('exitoso', 'succesvol (niet: exotisch)', 'ek-si-TO-so', 'Fue una campaña exitosa.', 'Het was een succesvolle campagne.', 'aggettivo'),
   ('la carpeta', 'de map (niet: tapijt)', 'la kar-PE-ta', 'Guarda los papeles en la carpeta.', 'Bewaar de papieren in de map.', 'sostantivo'),
   ('sensible', 'gevoelig (niet: verstandig)', 'sen-SIE-ble', 'Es una persona muy sensible.', 'Het is een heel gevoelig persoon.', 'aggettivo'),
   ('la ropa', 'de kleding (niet: rob)', 'la RRO-pa', 'Compré ropa nueva.', 'Ik kocht nieuwe kleding.', 'sostantivo'),
   ('el firmante', 'de ondertekenaar (niet: firma)', 'el fir-MAN-te', 'Los firmantes del acuerdo.', 'De ondertekenaars van het akkoord.', 'sostantivo')]),
L(299, '👔', 'Formeel register — verdieping', 'Formeel vs. informeel.',
  'Formeel vs. informeel', 'Informeel → formeel: ¿Qué tal? → ¿Cómo está usted?; vale → de acuerdo; oye → disculpe; gracias → se lo agradezco; un montón → una gran cantidad; cosas → asuntos.',
  [('¿cómo está usted?', 'hoe maakt u het?', 'KO-mo es-TA oes-TED', 'Buenos días, ¿cómo está usted?', 'Goedemorgen, hoe maakt u het?', 'espressione'),
   ('conforme', 'akkoord / in overeenstemming', 'kon-FOR-me', 'Estoy conforme con las condiciones.', 'Ik ga akkoord met de voorwaarden.', 'aggettivo'),
   ('disculpe', 'pardon / neemt u mij niet kwalijk', 'dis-KOEL-pe', 'Disculpe, ¿la salida?', 'Pardon, de uitgang?', 'espressione'),
   ('se lo agradezco', 'ik dank u', 'se lo a-gra-DES-ko', 'Se lo agradezco mucho.', 'Ik dank u zeer.', 'espressione'),
   ('una gran cantidad de', 'een grote hoeveelheid', 'OE-na gran kan-ti-DAD de', 'Recibimos una gran cantidad de solicitudes.', 'We ontvingen een grote hoeveelheid aanvragen.', 'espressione'),
   ('el asunto pendiente', 'de openstaande kwestie', 'el a-SOEN-to pen-DJEN-te', 'Tenemos varios asuntos pendientes.', 'We hebben verschillende openstaande kwesties.', 'sostantivo'),
   ('si es tan amable', 'als u zo vriendelijk wilt zijn', 'si es tan a-MA-ble', 'Firme aquí, si es tan amable.', 'Tekent u hier, als u zo vriendelijk wilt zijn.', 'espressione'),
   ('tenga la bondad de', 'weest u zo goed om', 'TEN-ga la bon-DAD de', 'Tenga la bondad de esperar.', 'Weest u zo goed even te wachten.', 'espressione')]),
L(300, '🎓', '🎓 B1 volledig afgerond!', 'Gefeliciteerd: Spaans B1 is compleet!',
  '🎓 B1 — ¡Enhorabuena!', 'Je hebt 300 lessen en meer dan 2400 Spaanse woorden achter de rug: alle tijden van de indicativo, de subjuntivo presente en imperfecto, de condicional, voorwaardelijke zinnen, indirecte rede en de registers. ¡Lo has conseguido!',
  [('conseguirlo', 'het bereiken / het voor elkaar krijgen', 'kon-se-GIER-lo', '¡Lo has conseguido!', 'Je hebt het voor elkaar!', 'espressione'),
   ('el triunfo', 'de triomf', 'el TRJOEN-fo', 'Fue un triunfo personal.', 'Het was een persoonlijke triomf.', 'sostantivo'),
   ('la perseverancia', 'de volharding', 'la per-se-ve-RAN-sja', 'La perseverancia da frutos.', 'Volharding werpt vruchten af.', 'sostantivo'),
   ('culminar', 'bekronen / voltooien', 'koel-mi-NAR', 'Culminaste el nivel B1.', 'Je hebt niveau B1 voltooid.', 'verbo'),
   ('el camino recorrido', 'de afgelegde weg', 'el ka-MIE-no rre-ko-RRIE-do', 'Mira el camino recorrido.', 'Kijk naar de afgelegde weg.', 'sostantivo'),
   ('desenvolverse', 'zich redden / uit de voeten kunnen', 'de-sen-vol-VER-se', 'Te desenvuelves bien en español.', 'Je kunt je goed redden in het Spaans.', 'verbo'),
   ('el siguiente nivel', 'het volgende niveau', 'el si-GJEN-te ni-VEL', 'El siguiente nivel es el B2.', 'Het volgende niveau is B2.', 'sostantivo'),
   ('¡a por el B2!', 'op naar B2!', 'a por el be dos', '¡Enhorabuena y a por el B2!', 'Gefeliciteerd en op naar B2!', 'espressione')]),
]

# ── Validatie + schrijven ────────────────────────────────────────────────────
from collections import Counter
assert [l['id'] for l in LESSONS] == list(range(FIRST, LAST + 1)), 'les-IDs'
vocab = json.load(open(OUT / 'vocabulary.json', encoding='utf-8'))
curriculum = json.load(open(OUT / 'curriculum.json', encoding='utf-8'))
vocab = [w for w in vocab if not FIRST <= w['lesson'] <= LAST]; curriculum = [l for l in curriculum if not FIRST <= l['id'] <= LAST]
ART = re.compile(r"^(?:(?:el|la|los|las|un|una|unos|unas)\s+)", re.I)
norm = lambda s: ART.sub('', s.lower()).strip()
existing = {norm(w['it']) for w in vocab}
seen = Counter(); n = max(int(w['id'][1:]) for w in vocab) + 1
new_vocab, new_curr = [], []
for l in LESSONS:
    assert len(l['words']) == 8, f"les {l['id']}: {len(l['words'])} woorden"
    ids = []
    for es, nl, ph, ex, exNl, cat in l['words']:
        k = norm(es); seen[k] += 1
        assert k not in existing, f"les {l['id']}: '{es}' bestaat al"
        wid = f'e{n:03d}'; n += 1
        new_vocab.append({'id': wid, 'it': es, 'nl': nl, 'ph': ph, 'ex': ex, 'exNl': exNl, 'lesson': l['id'], 'level': 'B1', 'cat': cat})
        ids.append(wid)
    new_curr.append({'id': l['id'], 'title': l['title'], 'emoji': l['emoji'], 'level': 'B1', 'description': l['description'], 'grammar': l['grammar'], 'words': ids})
dups = [k for k, c in seen.items() if c > 1]
assert not dups, f'dubbel binnen blok: {dups}'
vocab += new_vocab; curriculum += new_curr
curriculum.sort(key=lambda l: l['id'])
json.dump(vocab, open(OUT / 'vocabulary.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'vocabulary.json', 'a').write('\n')
json.dump(curriculum, open(OUT / 'curriculum.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'curriculum.json', 'a').write('\n')
print(f'Spaans B1 blok 3: {len(new_curr)} lessen, {len(new_vocab)} woorden → totaal {len(curriculum)} lessen, {len(vocab)} woorden')
