#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_es_b1.py — Spaans B1 (v1.58: blok 1, lessen 121–180). Thema-opbouw gespiegeld aan Italiaans B1,
met Spaanse grammatica (imperfecto/indefinido, condicional, subjuntivo, estilo indirecto, hipótesis).
Voegt toe aan de bestaande Spaanse data (A1/A2 blijven; eerdere B1-entries worden vervangen).
Draai opnieuw na bewerken: python3 scripts/generate_es_b1.py
Formaat: L(id, emoji, title, description, grammar_title, grammar_body, [ (es, nl, ph, ex, exNl, cat) × 8 ])
"""
import json, re
from pathlib import Path

OUT = Path(__file__).parent.parent / 'www' / 'data' / 'es'

def L(id, emoji, title, desc, gt, gb, words):
    return dict(id=id, emoji=emoji, title=title, description=desc, grammar=dict(title=gt, body=gb), words=words)

LESSONS = [
L(121, '⏳', 'Imperfecto — verdieping', 'Het verleden beschrijven: achtergrond, gewoontes en herinneringen.',
  'Imperfecto: gebruik in verhalen', 'Het imperfecto schetst de achtergrond: Era de noche y llovía. Gewoontes: Cuando era niño, solía jugar en la calle. Beschrijvingen: Mi abuela tenía el pelo blanco.',
  [('contar', 'vertellen', 'kon-TAR', 'Mi abuelo contaba historias de la guerra.', 'Mijn opa vertelde verhalen over de oorlog.', 'verbo'),
   ('crecer', 'opgroeien / groeien', 'kre-SER', 'Crecí en un pueblo pequeño.', 'Ik groeide op in een klein dorp.', 'verbo'),
   ('la infancia', 'de kindertijd', 'la in-FAN-sja', 'Tuve una infancia feliz.', 'Ik had een gelukkige kindertijd.', 'sostantivo'),
   ('describir', 'beschrijven', 'des-kri-BIER', 'Describía la casa con detalle.', 'Hij beschreef het huis tot in detail.', 'verbo'),
   ('el plazo', 'de termijn / deadline', 'el PLA-so', 'El plazo termina el viernes.', 'De termijn loopt vrijdag af.', 'sostantivo'),
   ('asistir a', 'bijwonen / volgen', 'a-sis-TIER a', 'Asistía a clases de piano.', 'Ik volgde pianolessen.', 'verbo'),
   ('la memoria', 'het geheugen / de herinnering', 'la me-MO-rja', 'Tengo buena memoria para las caras.', 'Ik heb een goed geheugen voor gezichten.', 'sostantivo'),
   ('recordar', 'zich herinneren', 're-kor-DAR', 'Recuerdo aquel verano perfectamente.', 'Ik herinner me die zomer perfect.', 'verbo')]),
L(122, '🔀', 'Indefinido — onregelmatig', 'De sterke verleden tijden: tuve, hice, dije, traduje.',
  'Onregelmatige pretérito indefinido', 'Sterke stammen zonder accent: tuve, estuve, pude, puse, supe, hice, quise, vine, dije, traje. Uitgangen: -e, -iste, -o, -imos, -isteis, -ieron (na j: dijeron, tradujeron).',
  [('traducir', 'vertalen', 'tra-doe-SIER', 'Tradujo el libro al español.', 'Hij vertaalde het boek in het Spaans.', 'verbo'),
   ('producir', 'produceren', 'pro-doe-SIER', 'La fábrica produjo mil coches.', 'De fabriek produceerde duizend auto\'s.', 'verbo'),
   ('proponer', 'voorstellen', 'pro-po-NER', 'Propuso una solución.', 'Hij stelde een oplossing voor.', 'verbo'),
   ('suponer', 'veronderstellen', 'soe-po-NER', 'Supuse que estabas cansado.', 'Ik veronderstelde dat je moe was.', 'verbo'),
   ('el ruido', 'het lawaai', 'el RWI-do', 'Hubo un ruido enorme.', 'Er was een enorm lawaai.', 'sostantivo'),
   ('la fábrica', 'de fabriek', 'la FA-bri-ka', 'La fábrica cerró en 2010.', 'De fabriek sloot in 2010.', 'sostantivo'),
   ('atraer', 'aantrekken', 'a-tra-ER', 'La ciudad atrajo a muchos turistas.', 'De stad trok veel toeristen aan.', 'verbo'),
   ('introducir', 'invoeren / introduceren', 'in-tro-doe-SIER', 'Introdujeron una ley nueva.', 'Ze voerden een nieuwe wet in.', 'verbo')]),
L(123, '⚖️', 'Imperfecto vs. indefinido', 'Achtergrond tegenover gebeurtenis.',
  'Imperfecto vs. indefinido', 'Imperfecto = achtergrond, gewoonte, beschrijving; indefinido = afgeronde gebeurtenis. Dormía cuando sonó el teléfono (ik sliep toen de telefoon ging).',
  [('de pronto', 'plotseling', 'de PRON-to', 'De pronto se apagó la luz.', 'Plotseling ging het licht uit.', 'avverbio'),
   ('suceder', 'gebeuren', 'soe-se-DER', '¿Qué sucedió después?', 'Wat gebeurde er daarna?', 'verbo'),
   ('darse cuenta de', 'zich realiseren', 'DAR-se KWEN-ta de', 'Me di cuenta de que era tarde.', 'Ik realiseerde me dat het laat was.', 'espressione'),
   ('dormirse', 'in slaap vallen', 'dor-MIER-se', 'Me dormí en el sofá.', 'Ik viel in slaap op de bank.', 'verbo'),
   ('en aquel momento', 'op dat moment', 'en a-KEL mo-MEN-to', 'En aquel momento llegó Ana.', 'Op dat moment kwam Ana aan.', 'espressione'),
   ('lavarse', 'zich wassen', 'la-VAR-se', 'Se lavaba las manos cuando llamaron.', 'Hij waste zijn handen toen er werd gebeld.', 'verbo'),
   ('mientras tanto', 'intussen', 'MJEN-tras TAN-to', 'Mientras tanto, yo preparaba la cena.', 'Intussen maakte ik het eten klaar.', 'espressione'),
   ('al final', 'uiteindelijk', 'al fi-NAL', 'Al final no fuimos.', 'Uiteindelijk gingen we niet.', 'espressione')]),
L(124, '💭', 'Herinneringen', 'Vertellen over vroeger.',
  'Herinneringen vertellen met het imperfecto', 'Me acuerdo de que... (ik herinner me dat). En aquella época (in die tijd). Solíamos ir a la playa (we gingen altijd naar het strand).',
  [('en aquella época', 'in die tijd', 'en a-KE-ja E-po-ka', 'En aquella época no había internet.', 'In die tijd was er geen internet.', 'espressione'),
   ('acordarse de', 'zich herinneren', 'a-kor-DAR-se de', '¿Te acuerdas de tu primer profesor?', 'Herinner je je je eerste leraar?', 'verbo'),
   ('la juventud', 'de jeugd', 'la choe-ven-TOED', 'En mi juventud viajaba mucho.', 'In mijn jeugd reisde ik veel.', 'sostantivo'),
   ('el compañero de clase', 'de klasgenoot', 'el kom-pa-NJE-ro de KLA-se', 'Vi a un compañero de clase.', 'Ik zag een klasgenoot.', 'sostantivo'),
   ('el juguete', 'het speelgoed', 'el choe-GE-te', 'Mi juguete favorito era un tren.', 'Mijn favoriete speelgoed was een trein.', 'sostantivo'),
   ('el cuento', 'het sprookje / verhaal', 'el KWEN-to', 'Mi madre me leía cuentos.', 'Mijn moeder las me sprookjes voor.', 'sostantivo'),
   ('el patio', 'de binnenplaats', 'el PA-tjo', 'Jugábamos en el patio del colegio.', 'We speelden op de binnenplaats van school.', 'sostantivo'),
   ('la niñez', 'de kinderjaren', 'la ni-NJES', 'La niñez pasa rápido.', 'De kinderjaren gaan snel voorbij.', 'sostantivo')]),
L(125, '🔄', 'Gewoontes vroeger', 'Wat je vroeger altijd deed.',
  'Gewoontes beschrijven: soler + infinitief', 'Solía levantarme temprano (ik stond altijd vroeg op). De vez en cuando (af en toe), a diario (dagelijks), casi nunca.',
  [('soler', 'gewoon zijn te / plegen', 'so-LER', 'Solíamos cenar a las nueve.', 'We aten altijd om negen uur.', 'verbo'),
   ('de vez en cuando', 'af en toe', 'de ves en KWAN-do', 'De vez en cuando íbamos al cine.', 'Af en toe gingen we naar de bioscoop.', 'espressione'),
   ('la costumbre', 'de gewoonte', 'la kos-TOEM-bre', 'Es una costumbre familiar.', 'Het is een familiegewoonte.', 'sostantivo'),
   ('a diario', 'dagelijks', 'a DJA-rjo', 'Leía a diario.', 'Ik las dagelijks.', 'avverbio'),
   ('aburrirse', 'zich vervelen', 'a-boe-RRIER-se', 'Nunca me aburría en el campo.', 'Ik verveelde me nooit op het platteland.', 'verbo'),
   ('esquiar', 'skiën', 'es-ki-AR', 'Esquiábamos cada invierno.', 'We skieden elke winter.', 'verbo'),
   ('la pila', 'de batterij', 'la PIE-la', 'La radio funcionaba con pilas.', 'De radio werkte op batterijen.', 'sostantivo'),
   ('jugar al fútbol', 'voetballen', 'choe-GAR al FOET-bol', 'Jugaba al fútbol en la calle.', 'Ik voetbalde op straat.', 'espressione')]),
L(126, '📖', 'Verhalen vertellen — deel 1', 'Een verhaal opbouwen.',
  'Vertelstructuur', 'Érase una vez (er was eens). La historia tiene lugar en (speelt zich af in). El protagonista (de hoofdpersoon). Al principio... luego... al final.',
  [('érase una vez', 'er was eens', 'E-ra-se OE-na ves', 'Érase una vez un rey muy viejo.', 'Er was eens een heel oude koning.', 'espressione'),
   ('el protagonista', 'de hoofdpersoon', 'el pro-ta-go-NIS-ta', 'La protagonista es una periodista.', 'De hoofdpersoon is een journaliste.', 'sostantivo'),
   ('tener lugar', 'plaatsvinden', 'te-NER loe-GAR', 'La historia tiene lugar en Cuba.', 'Het verhaal speelt zich af in Cuba.', 'espressione'),
   ('apasionante', 'meeslepend / boeiend', 'a-pa-sjo-NAN-te', 'Es una novela apasionante.', 'Het is een meeslepende roman.', 'aggettivo'),
   ('ambientado', 'gesitueerd', 'am-bjen-TA-do', 'Un cuento ambientado en Madrid.', 'Een verhaal dat zich afspeelt in Madrid.', 'aggettivo'),
   ('el capítulo', 'het hoofdstuk', 'el ka-PIE-toe-lo', 'Leí dos capítulos anoche.', 'Ik las gisteravond twee hoofdstukken.', 'sostantivo'),
   ('la narración', 'de vertelling', 'la na-rra-SJON', 'La narración es lenta al principio.', 'De vertelling is traag in het begin.', 'sostantivo'),
   ('el narrador', 'de verteller', 'el na-rra-DOR', 'El narrador es un niño.', 'De verteller is een kind.', 'sostantivo')]),
L(127, '📚', 'Verhalen vertellen — deel 2', 'Verbindingswoorden in verhalen.',
  'Verbindingswoorden in verhalen', 'Luego / después (daarna), a continuación (vervolgens), finalmente (uiteindelijk), por suerte (gelukkig), sin embargo (echter).',
  [('luego', 'daarna / vervolgens', 'LWE-go', 'Luego fuimos a cenar.', 'Daarna gingen we eten.', 'avverbio'),
   ('finalmente', 'uiteindelijk', 'fi-nal-MEN-te', 'Finalmente encontraron la salida.', 'Uiteindelijk vonden ze de uitgang.', 'avverbio'),
   ('por suerte', 'gelukkig', 'por SWER-te', 'Por suerte, nadie resultó herido.', 'Gelukkig raakte niemand gewond.', 'espressione'),
   ('lograr', 'erin slagen', 'lo-GRAR', 'Logró escapar.', 'Hij slaagde erin te ontsnappen.', 'verbo'),
   ('anular', 'annuleren', 'a-noe-LAR', 'Anularon el vuelo.', 'Ze annuleerden de vlucht.', 'verbo'),
   ('el desenlace', 'de ontknoping / het einde', 'el de-sen-LA-se', 'El desenlace me sorprendió.', 'De ontknoping verraste me.', 'sostantivo'),
   ('a continuación', 'vervolgens', 'a kon-ti-noe-a-SJON', 'A continuación, el héroe vuelve a casa.', 'Vervolgens keert de held naar huis terug.', 'espressione'),
   ('sin embargo', 'echter', 'sin em-BAR-go', 'Sin embargo, no todo salió bien.', 'Echter, niet alles ging goed.', 'espressione')]),
L(128, '🌦️', 'Het weer beschrijven', 'Het weer in verhalen en voorspellingen.',
  'Weer in verschillende tijden', 'Llovía (het regende), llovió (het heeft geregend), lloverá (het zal regenen). Hacía frío, hubo tormenta, habrá niebla.',
  [('la tempestad', 'de storm', 'la tem-pes-TAD', 'La tempestad duró toda la noche.', 'De storm duurde de hele nacht.', 'meteo'),
   ('el hielo', 'het ijs', 'el JE-lo', 'Había hielo en la carretera.', 'Er lag ijs op de weg.', 'meteo'),
   ('el relámpago', 'de bliksem', 'el re-LAM-pa-go', 'Un relámpago iluminó el cielo.', 'Een bliksemflits verlichtte de hemel.', 'meteo'),
   ('el trueno', 'de donder', 'el TRWE-no', 'El trueno asustó al perro.', 'De donder liet de hond schrikken.', 'meteo'),
   ('la nevada', 'de sneeuwval', 'la ne-VA-da', 'La nevada cerró las carreteras.', 'De sneeuwval sloot de wegen af.', 'meteo'),
   ('seco', 'droog', 'SE-ko', 'El verano fue muy seco.', 'De zomer was heel droog.', 'aggettivo'),
   ('la previsión', 'de voorspelling', 'la pre-vi-SJON', 'La previsión anuncia lluvia.', 'De voorspelling meldt regen.', 'meteo'),
   ('la brisa', 'de bries', 'la BRIE-sa', 'Soplaba una brisa suave.', 'Er waaide een zachte bries.', 'meteo')]),
L(129, '😢', 'Emoties in het verleden', 'Gevoelens beschrijven in het imperfecto.',
  'Emoties met het imperfecto', 'Estaba nervioso (ik was nerveus), tenía miedo (ik was bang), me sentía aliviado. Voor een plotselinge emotie het indefinido: me alegré mucho.',
  [('la rabia', 'de woede', 'la RA-bja', 'Sentía mucha rabia.', 'Ik voelde veel woede.', 'emozione'),
   ('aliviado', 'opgelucht', 'a-li-VJA-do', 'Me sentí aliviado al verla.', 'Ik voelde me opgelucht toen ik haar zag.', 'emozione'),
   ('harto', 'het zat', 'AR-to', 'Estaba harto de esperar.', 'Ik was het wachten zat.', 'emozione'),
   ('la alegría', 'de vreugde', 'la a-le-GRIE-a', '¡Qué alegría verte!', 'Wat een vreugde om je te zien!', 'emozione'),
   ('la ilusión', 'de hoop / het enthousiasme', 'la i-loe-SJON', 'Tenía mucha ilusión por el viaje.', 'Ik keek enorm uit naar de reis.', 'emozione'),
   ('conmovido', 'ontroerd', 'kon-mo-VIE-do', 'Estaba conmovida por la carta.', 'Ze was ontroerd door de brief.', 'emozione'),
   ('entusiasmado', 'enthousiast', 'en-toe-sjas-MA-do', 'Los niños estaban entusiasmados.', 'De kinderen waren enthousiast.', 'emozione'),
   ('la tristeza', 'het verdriet', 'la tris-TE-sa', 'Sentí una gran tristeza.', 'Ik voelde een groot verdriet.', 'emozione')]),
L(130, '📝', 'Toetsles — Blok 1', 'Samenvatting van blok 1.',
  'Samenvatting Blok 1', 'Je kent nu het verschil tussen imperfecto en indefinido en de belangrijkste onregelmatige vormen. In de toets: 20 woorden uit lessen 121–129.',
  [('el acontecimiento', 'de gebeurtenis', 'el a-kon-te-si-MJEN-to', 'Fue un acontecimiento histórico.', 'Het was een historische gebeurtenis.', 'sostantivo'),
   ('la época', 'het tijdperk', 'la E-po-ka', 'Fue una época difícil.', 'Het was een moeilijke tijd.', 'sostantivo'),
   ('desaparecer', 'verdwijnen', 'de-sa-pa-re-SER', 'El pueblo desapareció bajo el agua.', 'Het dorp verdween onder water.', 'verbo'),
   ('permanecer', 'blijven', 'per-ma-ne-SER', 'Permaneció en silencio.', 'Hij bleef stil.', 'verbo'),
   ('transformar', 'transformeren', 'trans-for-MAR', 'El turismo transformó la isla.', 'Het toerisme transformeerde het eiland.', 'verbo'),
   ('la generación', 'de generatie', 'la che-ne-ra-SJON', 'Mi generación creció sin móviles.', 'Mijn generatie groeide op zonder mobieltjes.', 'sostantivo'),
   ('antiguo', 'oud / vroeger', 'an-TIE-gwo', 'Mi antiguo colegio ya no existe.', 'Mijn vroegere school bestaat niet meer.', 'aggettivo'),
   ('la década', 'het decennium', 'la DE-ka-da', 'En la década de los ochenta.', 'In de jaren tachtig.', 'sostantivo')]),
L(131, '🌟', 'Condicional — regelmatig', 'De zou-vorm: wensen en beleefdheid.',
  'Condicional simple: vorming', 'Infinitief + -ía, -ías, -ía, -íamos, -íais, -ían: hablaría, comería, viviría. Gebruik: wensen (me gustaría), beleefdheid (¿podría?), advies (yo que tú, iría).',
  [('desear', 'wensen / verlangen', 'de-se-AR', 'Desearía vivir cerca del mar.', 'Ik zou graag bij zee wonen.', 'verbo'),
   ('imaginar', 'zich voorstellen', 'i-ma-chi-NAR', 'Imagino que sería difícil.', 'Ik stel me voor dat het moeilijk zou zijn.', 'verbo'),
   ('aceptar', 'accepteren', 'ak-sep-TAR', 'Aceptaría el trabajo sin dudar.', 'Ik zou de baan zonder twijfel accepteren.', 'verbo'),
   ('renunciar a', 'afzien van', 're-noen-SJAR a', 'No renunciaría a mis vacaciones.', 'Ik zou niet afzien van mijn vakantie.', 'verbo'),
   ('trasladarse', 'verhuizen (voor werk)', 'tras-la-DAR-se', 'Me trasladaría a Bilbao.', 'Ik zou naar Bilbao verhuizen.', 'verbo'),
   ('el deseo', 'de wens', 'el de-SE-o', 'Mi mayor deseo es viajar.', 'Mijn grootste wens is reizen.', 'sostantivo'),
   ('con mucho gusto', 'graag / met plezier', 'kon MOE-tsjo GOES-to', 'Te ayudaría con mucho gusto.', 'Ik zou je graag helpen.', 'espressione'),
   ('preferir', 'de voorkeur geven', 'pre-fe-RIER', 'Preferiría quedarme en casa.', 'Ik zou liever thuisblijven.', 'verbo')]),
L(132, '✨', 'Condicional — onregelmatig', 'Onregelmatige stammen: tendría, haría, podría.',
  'Onregelmatige condicional', 'Dezelfde stammen als het futuro: tendr-, har-, podr-, pondr-, saldr-, vendr-, dir-, sabr-, querr-, habr-, cabr-, valdr-. Podría ayudarte (ik zou je kunnen helpen).',
  [('caber', 'passen (ruimte)', 'ka-BER', 'No cabría en el coche.', 'Het zou niet in de auto passen.', 'verbo'),
   ('valer', 'waard zijn / kosten', 'va-LER', '¿Cuánto valdría esa casa?', 'Hoeveel zou dat huis waard zijn?', 'verbo'),
   ('saber', 'weten / kunnen', 'sa-BER', 'No sabría qué decir.', 'Ik zou niet weten wat ik moest zeggen.', 'verbo'),
   ('poner', 'zetten / leggen', 'po-NER', 'Pondría la mesa junto a la ventana.', 'Ik zou de tafel bij het raam zetten.', 'verbo'),
   ('haber', 'er zijn (hulpwerkwoord)', 'a-BER', 'Habría que preguntar.', 'Men zou het moeten vragen.', 'verbo'),
   ('satisfacer', 'tevredenstellen', 'sa-tis-fa-SER', 'Eso satisfaría a todos.', 'Dat zou iedereen tevredenstellen.', 'verbo'),
   ('mantener', 'onderhouden / behouden', 'man-te-NER', 'Mantendría la calma.', 'Ik zou kalm blijven.', 'verbo'),
   ('valer la pena', 'de moeite waard zijn', 'va-LER la PE-na', 'Valdría la pena intentarlo.', 'Het zou de moeite waard zijn het te proberen.', 'espressione')]),
L(133, '🎩', 'Beleefd verzoeken', 'Iets vragen zonder bot te zijn.',
  'Beleefde verzoeken', '¿Podría...? ¿Le importaría...? (Zou u het erg vinden om...?) ¿Me haría el favor de...? Altijd met usted tegen onbekenden.',
  [('el favor', 'de gunst', 'el fa-VOR', '¿Me haría un favor?', 'Zou u me een gunst willen doen?', 'sostantivo'),
   ('permitir', 'toestaan', 'per-mi-TIER', '¿Me permite pasar?', 'Mag ik erlangs?', 'verbo'),
   ('molestar', 'storen', 'mo-les-TAR', '¿Le molestaría cerrar la ventana?', 'Zou u het erg vinden het raam te sluiten?', 'verbo'),
   ('indicar', 'aanwijzen / aangeven', 'in-di-KAR', '¿Podría indicarme el camino?', 'Zou u me de weg kunnen wijzen?', 'verbo'),
   ('prestar', 'lenen (aan iemand)', 'pres-TAR', '¿Me prestarías tu bolígrafo?', 'Zou je me je pen willen lenen?', 'verbo'),
   ('mover', 'verplaatsen', 'mo-VER', '¿Podría mover su coche?', 'Zou u uw auto kunnen verplaatsen?', 'verbo'),
   ('el permiso', 'de toestemming', 'el per-MIE-so', 'Con permiso.', 'Met uw permissie.', 'sostantivo'),
   ('lamentar', 'betreuren / spijt hebben', 'la-men-TAR', 'Lamento molestarle.', 'Het spijt me dat ik u stoor.', 'verbo')]),
L(134, '🌈', 'Wensen & dromen', 'Dromen en verlangens uitdrukken.',
  'Wensen uitdrukken', 'Me gustaría + infinitief (ik zou graag willen). Ojalá + subjuntivo (was het maar zo). Sueño con (ik droom van). Llegar a ser (worden).',
  [('llegar a ser', 'worden (uiteindelijk)', 'je-GAR a ser', 'Le gustaría llegar a ser médico.', 'Hij zou graag dokter worden.', 'espressione'),
   ('cumplir', 'vervullen / waarmaken', 'koem-PLIER', 'Cumplió su sueño de vivir en Madrid.', 'Ze maakte haar droom waar om in Madrid te wonen.', 'verbo'),
   ('la ambición', 'de ambitie', 'la am-bi-SJON', 'Tiene mucha ambición.', 'Ze heeft veel ambitie.', 'sostantivo'),
   ('realizar', 'verwezenlijken', 're-a-li-SAR', 'Quiero realizar mis proyectos.', 'Ik wil mijn plannen verwezenlijken.', 'verbo'),
   ('la fantasía', 'de fantasie', 'la fan-ta-SIE-a', 'Los niños tienen mucha fantasía.', 'Kinderen hebben veel fantasie.', 'sostantivo'),
   ('barato', 'goedkoop', 'ba-RA-to', 'Sería más barato en tren.', 'Het zou goedkoper zijn met de trein.', 'aggettivo'),
   ('con ganas', 'met zin / gretig', 'kon GA-nas', 'Estudia con ganas.', 'Hij studeert met zin.', 'espressione'),
   ('soñar despierto', 'dagdromen', 'so-NJAR des-PJER-to', 'Me gusta soñar despierto.', 'Ik hou van dagdromen.', 'espressione')]),
L(135, '💡', 'Advies geven', 'Raad geven met de condicional.',
  'Advies met de condicional', 'Yo que tú / en tu lugar + condicional: Yo que tú, aceptaría. Deberías (je zou moeten). Te aconsejo que + subjuntivo komt in les 141.',
  [('aconsejar', 'aanraden', 'a-kon-se-CHAR', 'Te aconsejaría descansar.', 'Ik zou je aanraden te rusten.', 'verbo'),
   ('el consejo', 'het advies', 'el kon-SE-cho', 'Un buen consejo: ve despacio.', 'Een goed advies: ga langzaam.', 'sostantivo'),
   ('sugerir', 'suggereren', 'soe-che-RIER', 'Sugiero cambiar de plan.', 'Ik stel voor van plan te veranderen.', 'verbo'),
   ('considerar', 'overwegen', 'kon-si-de-RAR', 'Deberías considerar la oferta.', 'Je zou het aanbod moeten overwegen.', 'verbo'),
   ('en tu lugar', 'op jouw plaats', 'en toe loe-GAR', 'En tu lugar, hablaría con ella.', 'In jouw plaats zou ik met haar praten.', 'espressione'),
   ('la elección', 'de keuze', 'la e-lek-SJON', 'Es tu elección.', 'Het is jouw keuze.', 'sostantivo'),
   ('la decisión', 'de beslissing', 'la de-si-SJON', 'Fue una decisión difícil.', 'Het was een moeilijke beslissing.', 'sostantivo'),
   ('la solución', 'de oplossing', 'la so-loe-SJON', 'Hay una solución sencilla.', 'Er is een eenvoudige oplossing.', 'sostantivo')]),
L(136, '🍽️', 'Op restaurant', 'Beleefd bestellen en betalen.',
  'Beleefde restauranttaal', 'Quisiéramos una mesa para cuatro. ¿Nos podría traer la carta de vinos? ¿Está incluido el servicio? La propina no es obligatoria en España.',
  [('la guarnición', 'het bijgerecht', 'la gwar-ni-SJON', '¿Qué guarnición lleva el pescado?', 'Welk bijgerecht komt bij de vis?', 'ristorante'),
   ('el cubierto', 'het couvert / bestek', 'el koe-BJER-to', 'Falta un cubierto.', 'Er ontbreekt een couvert.', 'ristorante'),
   ('el plato del día', 'het daggerecht', 'el PLA-to del DIE-a', '¿Cuál es el plato del día?', 'Wat is het daggerecht?', 'ristorante'),
   ('la propina', 'de fooi', 'la pro-PIE-na', 'Dejamos una propina.', 'We laten een fooi achter.', 'ristorante'),
   ('la botella', 'de fles', 'la bo-TE-ja', 'Una botella de agua con gas.', 'Een fles bruisend water.', 'ristorante'),
   ('el restaurante', 'het restaurant', 'el res-tau-RAN-te', 'Este restaurante es famoso por el arroz.', 'Dit restaurant is beroemd om zijn rijst.', 'ristorante'),
   ('reservar mesa', 'een tafel reserveren', 're-ser-VAR ME-sa', 'Quisiera reservar mesa para dos.', 'Ik zou graag een tafel voor twee reserveren.', 'ristorante'),
   ('la carta de vinos', 'de wijnkaart', 'la KAR-ta de VIE-nos', '¿Nos trae la carta de vinos?', 'Brengt u ons de wijnkaart?', 'ristorante')]),
L(137, '✈️', 'Reisplannen maken', 'Een reis plannen en bespreken.',
  'Reisplannen bespreken', 'Iríamos en barco (we zouden per boot gaan). Habría que reservar con antelación. ¿Qué ruta seguiríais? Me encantaría hacer un crucero.',
  [('las vacaciones', 'de vakantie', 'las va-ka-SJO-nes', 'Las vacaciones empiezan en julio.', 'De vakantie begint in juli.', 'viaggio'),
   ('el barco', 'het schip / de boot', 'el BAR-ko', 'Iríamos en barco a Mallorca.', 'We zouden per boot naar Mallorca gaan.', 'viaggio'),
   ('la salida', 'het vertrek', 'la sa-LIE-da', 'La salida es a las siete.', 'Het vertrek is om zeven uur.', 'viaggio'),
   ('con antelación', 'van tevoren', 'kon an-te-la-SJON', 'Reserva con antelación.', 'Reserveer van tevoren.', 'espressione'),
   ('explorar', 'verkennen', 'eks-plo-RAR', 'Me gustaría explorar el norte.', 'Ik zou graag het noorden verkennen.', 'verbo'),
   ('el crucero', 'de cruise', 'el kroe-SE-ro', 'Un crucero por el Mediterráneo.', 'Een cruise over de Middellandse Zee.', 'viaggio'),
   ('la ruta', 'de route', 'la ROE-ta', 'La ruta pasa por Granada.', 'De route gaat via Granada.', 'viaggio'),
   ('el viajero', 'de reiziger', 'el vja-CHE-ro', 'Los viajeros esperan en el andén.', 'De reizigers wachten op het perron.', 'viaggio')]),
L(138, '🏨', 'Accommodatie', 'Kamers, klachten en wensen in het hotel.',
  'In het hotel', '¿Tendrían una habitación con vistas al mar? ¿El desayuno está incluido? Quisiera presentar una queja (een klacht indienen).',
  [('desayuno incluido', 'ontbijt inbegrepen', 'de-sa-JOE-no in-KLWI-do', '¿El precio es con desayuno incluido?', 'Is de prijs met ontbijt inbegrepen?', 'alloggio'),
   ('la sala de estar', 'de woonkamer / lounge', 'la SA-la de es-TAR', 'La sala de estar tiene chimenea.', 'De lounge heeft een open haard.', 'alloggio'),
   ('la ducha', 'de douche', 'la DOE-tsja', 'La ducha no tiene agua caliente.', 'De douche heeft geen warm water.', 'alloggio'),
   ('la queja', 'de klacht', 'la KE-cha', 'Quisiera presentar una queja.', 'Ik zou graag een klacht indienen.', 'alloggio'),
   ('interior', 'binnen- (zonder uitzicht)', 'in-te-RJOR', 'La habitación es interior.', 'De kamer heeft geen uitzicht.', 'aggettivo'),
   ('la vista al mar', 'het uitzicht op zee', 'la VIS-ta al mar', 'Una habitación con vista al mar.', 'Een kamer met uitzicht op zee.', 'alloggio'),
   ('la pensión', 'het pension', 'la pen-SJON', 'Dormimos en una pensión barata.', 'We sliepen in een goedkoop pension.', 'alloggio'),
   ('el albergue', 'de jeugdherberg', 'el al-BER-ge', 'El albergue está lleno.', 'De jeugdherberg is vol.', 'alloggio')]),
L(139, '🚆', 'Vervoer & richting', 'Onderweg met de auto en het openbaar vervoer.',
  'Vervoer en richting', 'Gire en la rotonda (neem de rotonde), coja la autopista, adelante con cuidado (haal voorzichtig in). Despacio (langzaam).',
  [('el semáforo', 'het stoplicht', 'el se-MA-fo-ro', 'Gire a la derecha en el semáforo.', 'Sla rechtsaf bij het stoplicht.', 'trasporto'),
   ('el cruce', 'het kruispunt', 'el KROE-se', 'En el cruce, siga recto.', 'Op het kruispunt gaat u rechtdoor.', 'trasporto'),
   ('despacio', 'langzaam', 'des-PA-sjo', 'Conduce despacio, hay niebla.', 'Rijd langzaam, er is mist.', 'avverbio'),
   ('la rotonda', 'de rotonde', 'la ro-TON-da', 'Tome la segunda salida en la rotonda.', 'Neem de tweede afslag op de rotonde.', 'trasporto'),
   ('el peaje', 'de tol', 'el pe-A-che', 'La autopista tiene peaje.', 'De snelweg is een tolweg.', 'trasporto'),
   ('la autopista', 'de snelweg', 'la au-to-PIS-ta', 'Cogimos la autopista a Valencia.', 'We namen de snelweg naar Valencia.', 'trasporto'),
   ('el carril', 'de rijstrook', 'el ka-RRIEL', 'Cambia de carril con cuidado.', 'Wissel voorzichtig van rijstrook.', 'trasporto'),
   ('adelantar', 'inhalen', 'a-de-lan-TAR', 'Está prohibido adelantar aquí.', 'Inhalen is hier verboden.', 'verbo')]),
L(140, '📝', 'Toetsles — Blok 2', 'Samenvatting van blok 2.',
  'Samenvatting Blok 2', 'Je kent nu de condicional, regelmatig en onregelmatig, en gebruikt hem voor wensen, beleefdheid en advies. In de toets: 20 woorden uit lessen 131–139.',
  [('cortés', 'beleefd / hoffelijk', 'kor-TES', 'Fue muy cortés con nosotros.', 'Hij was heel beleefd tegen ons.', 'aggettivo'),
   ('el viaje', 'de reis', 'el VJA-che', 'Fue un viaje inolvidable.', 'Het was een onvergetelijke reis.', 'sostantivo'),
   ('cómodo', 'comfortabel', 'KO-mo-do', 'El asiento es muy cómodo.', 'De stoel is heel comfortabel.', 'aggettivo'),
   ('la bicicleta', 'de fiets', 'la bi-si-KLE-ta', 'Alquilaría una bicicleta.', 'Ik zou een fiets huren.', 'sostantivo'),
   ('individual', 'individueel / eenpersoons-', 'in-di-vi-DWAL', 'Una habitación individual, por favor.', 'Een eenpersoonskamer, alstublieft.', 'aggettivo'),
   ('exactamente', 'precies', 'ek-sak-ta-MEN-te', 'Es exactamente lo que quería.', 'Het is precies wat ik wilde.', 'avverbio'),
   ('confirmar', 'bevestigen', 'kon-fir-MAR', '¿Podría confirmar la reserva?', 'Zou u de reservering kunnen bevestigen?', 'verbo'),
   ('posponer', 'uitstellen', 'pos-po-NER', 'Tuvimos que posponer el viaje.', 'We moesten de reis uitstellen.', 'verbo')]),
L(141, '🧠', 'Subjuntivo — introductie', 'De aanvoegende wijs na twijfel, wens en noodzaak.',
  'Subjuntivo presente: introductie', 'Vorming: yo-stam + tegengestelde uitgang: hablar → hable, comer → coma, vivir → viva. Na: quiero que, es necesario que, dudo que, es posible que. No creo que sea verdad.',
  [('dudar', 'twijfelen', 'doe-DAR', 'Dudo que venga.', 'Ik betwijfel of hij komt.', 'verbo'),
   ('es posible que', 'het is mogelijk dat', 'es po-SIE-ble ke', 'Es posible que llueva.', 'Het is mogelijk dat het regent.', 'espressione'),
   ('es necesario que', 'het is nodig dat', 'es ne-se-SA-rjo ke', 'Es necesario que estudies.', 'Het is nodig dat je studeert.', 'espressione'),
   ('probable', 'waarschijnlijk', 'pro-BA-ble', 'Es probable que lleguen tarde.', 'Het is waarschijnlijk dat ze laat komen.', 'aggettivo'),
   ('imposible', 'onmogelijk', 'im-po-SIE-ble', 'Es imposible que sea él.', 'Het is onmogelijk dat hij het is.', 'aggettivo'),
   ('la posibilidad', 'de mogelijkheid', 'la po-si-bi-li-DAD', 'Hay una posibilidad.', 'Er is een mogelijkheid.', 'sostantivo'),
   ('la duda', 'de twijfel', 'la DOE-da', 'No tengo ninguna duda.', 'Ik heb geen enkele twijfel.', 'sostantivo'),
   ('quiero que', 'ik wil dat', 'KJE-ro ke', 'Quiero que vengas conmigo.', 'Ik wil dat je met me meekomt.', 'espressione')]),
L(142, '🔮', 'Subjuntivo — onregelmatig', 'Onregelmatige vormen en voegwoorden die de subjuntivo eisen.',
  'Onregelmatige subjuntivo', 'Sea (ser), esté (estar), vaya (ir), haya (haber), sepa (saber), dé (dar), tenga, haga, ponga, venga, diga. Na: para que, antes de que, a menos que, con tal de que, aunque.',
  [('cualquiera', 'welke dan ook', 'kwal-KJE-ra', 'Cualquiera que sea el problema, lo resolveremos.', 'Wat het probleem ook is, we lossen het op.', 'espressione'),
   ('dondequiera', 'waar dan ook', 'don-de-KJE-ra', 'Dondequiera que vayas, te seguiré.', 'Waar je ook gaat, ik volg je.', 'espressione'),
   ('quienquiera', 'wie dan ook', 'kjen-KJE-ra', 'Quienquiera que sea, no abras.', 'Wie het ook is, doe niet open.', 'espressione'),
   ('con tal de que', 'mits / op voorwaarde dat', 'kon tal de ke', 'Voy con tal de que vengas tú.', 'Ik ga, mits jij ook komt.', 'espressione'),
   ('para que', 'opdat / zodat', 'PA-ra ke', 'Te lo digo para que lo sepas.', 'Ik zeg het je zodat je het weet.', 'espressione'),
   ('a pesar de que', 'hoewel / ondanks dat', 'a pe-SAR de ke', 'Salió a pesar de que llovía.', 'Hij ging naar buiten hoewel het regende.', 'espressione'),
   ('a menos que', 'tenzij', 'a ME-nos ke', 'Iremos a menos que haga frío.', 'We gaan, tenzij het koud is.', 'espressione'),
   ('antes de que', 'voordat', 'AN-tes de ke', 'Llámame antes de que salgas.', 'Bel me voordat je vertrekt.', 'espressione')]),
L(143, '💬', 'Meningen geven', 'Meningen met en zonder subjuntivo.',
  'Meningen met subjuntivo', 'Creo que + indicativo (creo que tiene razón), no creo que + subjuntivo (no creo que tenga razón). Me parece que / no me parece que werkt hetzelfde.',
  [('la opinión', 'de mening', 'la o-pi-NJON', 'Respeto tu opinión.', 'Ik respecteer je mening.', 'sostantivo'),
   ('sorprendente', 'verrassend', 'sor-pren-DEN-te', 'Es sorprendente que no lo sepa.', 'Het is verrassend dat hij het niet weet.', 'aggettivo'),
   ('de acuerdo', 'akkoord / eens', 'de a-KWER-do', 'Estamos de acuerdo en eso.', 'Daar zijn we het over eens.', 'espressione'),
   ('el punto de vista', 'het standpunt', 'el POEN-to de VIS-ta', 'Desde mi punto de vista, es injusto.', 'Vanuit mijn standpunt is het oneerlijk.', 'sostantivo'),
   ('sostener', 'beweren / verdedigen', 'sos-te-NER', 'Sostiene que fue un error.', 'Hij beweert dat het een fout was.', 'verbo'),
   ('convencer', 'overtuigen', 'kon-ven-SER', 'No me convence.', 'Het overtuigt me niet.', 'verbo'),
   ('tener razón', 'gelijk hebben', 'te-NER ra-SON', 'No creo que tengas razón.', 'Ik denk niet dat je gelijk hebt.', 'espressione'),
   ('estar equivocado', 'ongelijk hebben', 'es-TAR e-ki-vo-KA-do', 'Creo que estás equivocado.', 'Ik denk dat je het mis hebt.', 'espressione')]),
L(144, '❤️', 'Emoties & subjuntivo', 'Gevoelens over wat een ander doet.',
  'Emoties + subjuntivo', 'Me alegro de que vengas (ik ben blij dat je komt). Siento que estés enfermo. Me molesta que grites. Es una pena que no puedas venir.',
  [('extraño', 'vreemd', 'eks-TRA-njo', 'Es extraño que no llame.', 'Het is vreemd dat hij niet belt.', 'aggettivo'),
   ('sentir que', 'het spijt me dat', 'sen-TIER ke', 'Siento que no puedas venir.', 'Het spijt me dat je niet kunt komen.', 'espressione'),
   ('es una pena que', 'het is jammer dat', 'es OE-na PE-na ke', 'Es una pena que llueva.', 'Het is jammer dat het regent.', 'espressione'),
   ('temer', 'vrezen', 'te-MER', 'Temo que sea demasiado tarde.', 'Ik vrees dat het te laat is.', 'verbo'),
   ('la sensación', 'het gevoel', 'la sen-sa-SJON', 'Tengo la sensación de que algo va mal.', 'Ik heb het gevoel dat er iets mis is.', 'sostantivo'),
   ('la preocupación', 'de bezorgdheid', 'la pre-o-koe-pa-SJON', 'Es una preocupación constante.', 'Het is een voortdurende zorg.', 'sostantivo'),
   ('sorprenderse de', 'zich verbazen over', 'sor-pren-DER-se de', 'Me sorprendo de que lo sepas.', 'Ik verbaas me dat je het weet.', 'verbo'),
   ('avergonzarse', 'zich schamen', 'a-ver-gon-SAR-se', 'Se avergüenza de su error.', 'Hij schaamt zich voor zijn fout.', 'verbo')]),
L(145, '💼', 'Werk & solliciteren', 'Solliciteren en loopbaan.',
  'Werktaal', 'Solicitar un puesto (een functie aanvragen), el candidato ideal, tener experiencia en, despedir (ontslaan), el salario (het salaris).',
  [('la carrera profesional', 'de carrière', 'la ka-RRE-ra pro-fe-sjo-NAL', 'Quiere hacer carrera profesional en Madrid.', 'Hij wil carrière maken in Madrid.', 'lavoro'),
   ('el asistente', 'de assistent', 'el a-sis-TEN-te', 'Buscamos un asistente de dirección.', 'We zoeken een directieassistent.', 'lavoro'),
   ('el candidato', 'de kandidaat', 'el kan-di-DA-to', 'Hay diez candidatos para el puesto.', 'Er zijn tien kandidaten voor de functie.', 'lavoro'),
   ('el socio', 'de partner / vennoot', 'el SO-sjo', 'Mi socio se encarga de las ventas.', 'Mijn vennoot doet de verkoop.', 'lavoro'),
   ('despedir', 'ontslaan', 'des-pe-DIER', 'Despidieron a veinte empleados.', 'Ze ontsloegen twintig werknemers.', 'verbo'),
   ('el salario', 'het loon', 'el sa-LA-rjo', 'El salario mínimo ha subido.', 'Het minimumloon is gestegen.', 'lavoro'),
   ('el puesto', 'de functie / de baan', 'el PWES-to', 'Solicité el puesto de gerente.', 'Ik solliciteerde naar de functie van manager.', 'lavoro'),
   ('solicitar', 'aanvragen / solliciteren', 'so-li-si-TAR', 'Solicitó una beca.', 'Ze vroeg een beurs aan.', 'verbo')]),
L(146, '🖥️', 'Op kantoor', 'Kantoor- en vergadertaal.',
  'Kantoor- en vergadertaal', 'Tenemos una reunión a las diez. ¿Me envías el informe? La fecha límite es el viernes. Hay que hacer una presentación.',
  [('el escritorio', 'het bureau', 'el es-kri-TO-rjo', 'Mi escritorio está junto a la ventana.', 'Mijn bureau staat bij het raam.', 'ufficio'),
   ('la fecha límite', 'de deadline', 'la FE-tsja LIE-mi-te', 'La fecha límite es mañana.', 'De deadline is morgen.', 'ufficio'),
   ('la llamada', 'het telefoongesprek', 'la ja-MA-da', 'Tengo una llamada con el cliente.', 'Ik heb een gesprek met de klant.', 'ufficio'),
   ('la presentación', 'de presentatie', 'la pre-sen-ta-SJON', 'La presentación dura veinte minutos.', 'De presentatie duurt twintig minuten.', 'ufficio'),
   ('el informe', 'het rapport', 'el in-FOR-me', 'Envíame el informe antes del viernes.', 'Stuur me het rapport voor vrijdag.', 'ufficio'),
   ('la impresora', 'de printer', 'la im-pre-SO-ra', 'La impresora no tiene papel.', 'De printer heeft geen papier.', 'ufficio'),
   ('la jornada laboral', 'de werkdag', 'la chor-NA-da la-bo-RAL', 'La jornada laboral es de ocho horas.', 'De werkdag is acht uur.', 'ufficio'),
   ('la agenda', 'de agenda', 'la a-CHEN-da', 'Lo apunto en la agenda.', 'Ik zet het in de agenda.', 'ufficio')]),
L(147, '👷', 'Beroepen & vaardigheden', 'Over beroepen en competenties praten.',
  'Beroepen en vaardigheden', 'Ser competente en, tener habilidad para, estar cualificado para. El contable, el arquitecto, el fontanero, el electricista.',
  [('el personal', 'het personeel', 'el per-so-NAL', 'El personal es muy profesional.', 'Het personeel is heel professioneel.', 'professione'),
   ('el experto', 'de expert', 'el eks-PER-to', 'Es experta en energía solar.', 'Ze is expert in zonne-energie.', 'professione'),
   ('el contable', 'de accountant / boekhouder', 'el kon-TA-ble', 'El contable revisa las cuentas.', 'De boekhouder controleert de rekeningen.', 'professione'),
   ('el arquitecto', 'de architect', 'el ar-ki-TEK-to', 'La arquitecta diseñó el puente.', 'De architecte ontwierp de brug.', 'professione'),
   ('competente', 'bekwaam / competent', 'kom-pe-TEN-te', 'Es muy competente en su trabajo.', 'Ze is heel bekwaam in haar werk.', 'aggettivo'),
   ('la habilidad', 'de vaardigheid', 'la a-bi-li-DAD', 'Tiene habilidad para los idiomas.', 'Hij heeft aanleg voor talen.', 'sostantivo'),
   ('cualificado', 'gekwalificeerd', 'kwa-li-fi-KA-do', 'Buscan personal cualificado.', 'Ze zoeken gekwalificeerd personeel.', 'aggettivo'),
   ('el fontanero', 'de loodgieter', 'el fon-ta-NE-ro', 'Llamé al fontanero.', 'Ik belde de loodgieter.', 'professione')]),
L(148, '🗣️', 'Discussiëren', 'Argumenteren en tegenspreken.',
  'Discussietaal', 'Por un lado... por otro lado (enerzijds... anderzijds). En primer lugar, además, en conclusión. Admito que, pero... No exageres.',
  [('no obstante', 'echter / desondanks', 'no obs-TAN-te', 'No obstante, hay excepciones.', 'Er zijn echter uitzonderingen.', 'espressione'),
   ('asimismo', 'bovendien / eveneens', 'a-si-MIS-mo', 'Asimismo, hay que pensar en el coste.', 'Bovendien moeten we aan de kosten denken.', 'avverbio'),
   ('al contrario', 'integendeel', 'al kon-TRA-rjo', 'Al contrario, me parece buena idea.', 'Integendeel, ik vind het een goed idee.', 'espressione'),
   ('en conclusión', 'tot slot / concluderend', 'en kon-kloe-SJON', 'En conclusión, votamos que sí.', 'Concluderend stemmen we voor.', 'espressione'),
   ('el argumento', 'het argument', 'el ar-goe-MEN-to', 'Es un argumento sólido.', 'Het is een sterk argument.', 'sostantivo'),
   ('debatir', 'debatteren', 'de-ba-TIER', 'Debatimos durante horas.', 'We debatteerden urenlang.', 'verbo'),
   ('admitir', 'toegeven', 'ad-mi-TIER', 'Admito que me equivoqué.', 'Ik geef toe dat ik me vergiste.', 'verbo'),
   ('exagerar', 'overdrijven', 'ek-sa-che-RAR', 'No exageres, no fue tan grave.', 'Overdrijf niet, zo erg was het niet.', 'verbo')]),
L(149, '🎭', 'Gevoelens uitdrukken', 'Stemming en karakter beschrijven.',
  'Gevoelens en gemoedstoestand', 'Estar de buen / mal humor. Tener paciencia, tener valor. Soportar (verdragen), quejarse de (klagen over).',
  [('el humor', 'de stemming / het humeur', 'el oe-MOR', 'Hoy estoy de buen humor.', 'Vandaag ben ik in een goede stemming.', 'emozione'),
   ('ansioso', 'angstig / gespannen', 'an-SJO-so', 'Estaba ansioso antes del examen.', 'Ik was gespannen voor het examen.', 'emozione'),
   ('la emoción', 'de emotie', 'la e-mo-SJON', 'No pudo ocultar la emoción.', 'Hij kon zijn emotie niet verbergen.', 'emozione'),
   ('la confianza en sí mismo', 'het zelfvertrouwen', 'la kon-FJAN-sa en si MIS-mo', 'Le falta confianza en sí mismo.', 'Het ontbreekt hem aan zelfvertrouwen.', 'emozione'),
   ('el valor', 'de moed', 'el va-LOR', 'Tuvo el valor de decir la verdad.', 'Hij had de moed de waarheid te zeggen.', 'emozione'),
   ('la paciencia', 'het geduld', 'la pa-SJEN-sja', 'Hay que tener paciencia.', 'Je moet geduld hebben.', 'emozione'),
   ('soportar', 'verdragen', 'so-por-TAR', 'No soporto el ruido.', 'Ik kan niet tegen lawaai.', 'verbo'),
   ('quejarse de', 'klagen over', 'ke-CHAR-se de', 'Siempre se queja del tiempo.', 'Hij klaagt altijd over het weer.', 'verbo')]),
L(150, '📝', 'Toetsles — Blok 3', 'Samenvatting van blok 3.',
  'Samenvatting Blok 3', 'Je kent de subjuntivo presente na twijfel, wens, emotie en voegwoorden als para que en antes de que. In de toets: 20 woorden uit lessen 141–149.',
  [('expresar', 'uitdrukken', 'eks-pre-SAR', 'Es difícil expresar lo que siento.', 'Het is moeilijk uit te drukken wat ik voel.', 'verbo'),
   ('el sentimiento', 'het gevoel', 'el sen-ti-MJEN-to', 'Es un sentimiento nuevo.', 'Het is een nieuw gevoel.', 'sostantivo'),
   ('la propuesta', 'het voorstel', 'la pro-PWES-ta', 'Aceptaron la propuesta.', 'Ze accepteerden het voorstel.', 'sostantivo'),
   ('el compromiso', 'het compromis / de verbintenis', 'el kom-pro-MIE-so', 'Llegamos a un compromiso.', 'We kwamen tot een compromis.', 'sostantivo'),
   ('la responsabilidad', 'de verantwoordelijkheid', 'la res-pon-sa-bi-li-DAD', 'Es mi responsabilidad.', 'Het is mijn verantwoordelijkheid.', 'sostantivo'),
   ('fiable', 'betrouwbaar', 'FJA-ble', 'Es una persona fiable.', 'Het is een betrouwbaar persoon.', 'aggettivo'),
   ('la colaboración', 'de samenwerking', 'la ko-la-bo-ra-SJON', 'Gracias por la colaboración.', 'Bedankt voor de samenwerking.', 'sostantivo'),
   ('opinar', 'vinden / van mening zijn', 'o-pi-NAR', '¿Qué opinas tú?', 'Wat vind jij?', 'verbo')]),
L(151, '🔗', 'Pronombres combinados', 'Twee voornaamwoorden tegelijk: se lo, me la.',
  'Gecombineerde voornaamwoorden', 'Indirect + direct: me lo, te la, nos los. "Le/les" + lo/la wordt "se": Se lo di (ik gaf het hem). Aan een infinitief plakken: quiero dártelo.',
  [('explicar', 'uitleggen', 'eks-pli-KAR', 'Te lo explico ahora.', 'Ik leg het je nu uit.', 'verbo'),
   ('pedir prestado', 'lenen (van iemand)', 'pe-DIER pres-TA-do', 'Se lo pedí prestado.', 'Ik leende het van hem.', 'verbo'),
   ('mostrar', 'laten zien', 'mos-TRAR', 'Me la mostró con orgullo.', 'Hij liet het me trots zien.', 'verbo'),
   ('regalar', 'cadeau geven', 're-ga-LAR', 'Se lo regalé por su cumpleaños.', 'Ik gaf het haar cadeau voor haar verjaardag.', 'verbo'),
   ('prometer', 'beloven', 'pro-me-TER', 'Me lo prometiste.', 'Je hebt het me beloofd.', 'verbo'),
   ('recomendar', 'aanbevelen', 're-ko-men-DAR', 'Te la recomiendo.', 'Ik raad hem je aan.', 'verbo'),
   ('recordar a', 'herinneren aan', 're-kor-DAR a', 'Recuérdamelo mañana.', 'Herinner me er morgen aan.', 'verbo'),
   ('enseñar', 'onderwijzen / laten zien', 'en-se-NJAR', 'Nos lo enseñó el profesor.', 'De leraar heeft het ons geleerd.', 'verbo')]),
L(152, '🎯', 'Pronombres — oefening', 'Nog meer werkwoorden met twee voornaamwoorden.',
  'Gecombineerde voornaamwoorden in de praktijk', 'Bij gebiedende wijs achteraan: dámelo (geef het mij), tráemela. Bij ontkenning ervoor: no me lo des.',
  [('pasar', 'doorgeven / aangeven', 'pa-SAR', 'Pásamelo, por favor.', 'Geef het even aan, alsjeblieft.', 'verbo'),
   ('preparar', 'voorbereiden / klaarmaken', 'pre-pa-RAR', 'Te lo preparo enseguida.', 'Ik maak het meteen voor je klaar.', 'verbo'),
   ('traer', 'brengen', 'tra-ER', 'Tráemela, por favor.', 'Breng hem me, alsjeblieft.', 'verbo'),
   ('mandar', 'sturen', 'man-DAR', 'Se lo mandé por correo.', 'Ik stuurde het hem per post.', 'verbo'),
   ('garantizar', 'garanderen', 'ga-ran-ti-SAR', 'Te lo garantizo.', 'Ik garandeer het je.', 'verbo'),
   ('esconder', 'verbergen', 'es-kon-DER', 'Nos lo escondió.', 'Hij verborg het voor ons.', 'verbo'),
   ('revelar', 'onthullen', 're-ve-LAR', 'No me lo reveló.', 'Hij onthulde het me niet.', 'verbo'),
   ('comunicar', 'meedelen', 'ko-moe-ni-KAR', 'Se lo comunicaremos por escrito.', 'We delen het hun schriftelijk mee.', 'verbo')]),
L(153, '🔄', 'Passieve vorm', 'De lijdende vorm en de pasiva refleja.',
  'De passieve vorm', 'Ser + participio: El puente fue construido en 1920 (het deelwoord past zich aan). Vaker de pasiva refleja: Se construyó el puente en 1920. Se venden pisos.',
  [('inventar', 'uitvinden', 'in-ven-TAR', 'El teléfono fue inventado en el siglo XIX.', 'De telefoon werd in de negentiende eeuw uitgevonden.', 'verbo'),
   ('construir', 'bouwen', 'kons-troe-IER', 'La catedral fue construida en 1300.', 'De kathedraal werd in 1300 gebouwd.', 'verbo'),
   ('crear', 'creëren / maken', 'kre-AR', 'La empresa fue creada por dos amigos.', 'Het bedrijf werd door twee vrienden opgericht.', 'verbo'),
   ('recibir', 'ontvangen', 're-si-BIER', 'La carta fue recibida ayer.', 'De brief werd gisteren ontvangen.', 'verbo'),
   ('aprobar (una ley)', 'goedkeuren', 'a-pro-BAR', 'La ley fue aprobada por el parlamento.', 'De wet werd door het parlement goedgekeurd.', 'verbo'),
   ('entregar', 'bezorgen / overhandigen', 'en-tre-GAR', 'El paquete fue entregado a tiempo.', 'Het pakket werd op tijd bezorgd.', 'verbo'),
   ('publicar', 'publiceren', 'poe-bli-KAR', 'El libro se publicó en 1605.', 'Het boek werd in 1605 gepubliceerd.', 'verbo'),
   ('fundar', 'stichten / oprichten', 'foen-DAR', 'La ciudad fue fundada por los romanos.', 'De stad werd door de Romeinen gesticht.', 'verbo')]),
L(154, '🏥', 'Bij de dokter', 'Medische gesprekken.',
  'Medische taal', '¿Qué le pasa? Me duele... desde hace... El médico receta un tratamiento. Es grave / no es grave. Hay que hacer pruebas.',
  [('la enfermedad', 'de ziekte', 'la en-fer-me-DAD', 'Es una enfermedad rara.', 'Het is een zeldzame ziekte.', 'salute'),
   ('enfermo', 'ziek', 'en-FER-mo', 'Lleva tres días enfermo.', 'Hij is al drie dagen ziek.', 'aggettivo'),
   ('el comprimido', 'de tablet', 'el kom-pri-MIE-do', 'Un comprimido cada ocho horas.', 'Elke acht uur een tablet.', 'salute'),
   ('la consulta', 'het spreekuur / consult', 'la kon-SOEL-ta', 'Tengo consulta a las diez.', 'Ik heb om tien uur een consult.', 'salute'),
   ('el tratamiento', 'de behandeling / kuur', 'el tra-ta-MJEN-to', 'El tratamiento dura dos semanas.', 'De behandeling duurt twee weken.', 'salute'),
   ('la médica', 'de dokter (vrouw)', 'la ME-di-ka', 'La médica me recetó reposo.', 'De dokter schreef me rust voor.', 'salute'),
   ('grave', 'ernstig', 'GRA-ve', 'No es nada grave.', 'Het is niets ernstigs.', 'aggettivo'),
   ('recetar', 'voorschrijven', 're-se-TAR', 'Me recetó antibióticos.', 'Hij schreef me antibiotica voor.', 'verbo')]),
L(155, '🧘', 'Gezondheid & welzijn', 'Gezond leven en advies.',
  'Gezondheidsadvies', 'Es importante que duermas bien (subjuntivo na advies). Te recomiendo que hagas ejercicio. Una dieta equilibrada, el peso ideal.',
  [('el sueño reparador', 'de goede nachtrust', 'el SWE-njo re-pa-ra-DOR', 'Necesito un sueño reparador.', 'Ik heb een goede nachtrust nodig.', 'salute'),
   ('saludable', 'gezond (levensstijl)', 'sa-loe-DA-ble', 'Lleva una vida saludable.', 'Hij leidt een gezond leven.', 'aggettivo'),
   ('la dieta', 'het dieet', 'la DJE-ta', 'Estoy a dieta.', 'Ik ben op dieet.', 'salute'),
   ('la calma', 'de rust / de kalmte', 'la KAL-ma', 'Mantén la calma.', 'Blijf kalm.', 'salute'),
   ('el peso', 'het gewicht', 'el PE-so', 'Ha perdido peso.', 'Ze is afgevallen.', 'salute'),
   ('débil', 'zwak', 'DE-bil', 'Me siento débil.', 'Ik voel me zwak.', 'aggettivo'),
   ('el gimnasio', 'de sportschool', 'el chim-NA-sjo', 'Voy al gimnasio tres veces por semana.', 'Ik ga drie keer per week naar de sportschool.', 'salute'),
   ('equilibrado', 'evenwichtig', 'e-ki-li-BRA-do', 'Una dieta equilibrada es clave.', 'Een evenwichtig dieet is de sleutel.', 'aggettivo')]),
L(156, '🦴', 'Het lichaam', 'Meer lichaamsdelen.',
  'Lichaamsdelen en beschrijvingen', 'Me duele el hombro. Me he torcido el tobillo (ik heb mijn enkel verzwikt). Tengo la piel seca. Los pulmones, el hígado, el corazón.',
  [('el hombro', 'de schouder', 'el OM-bro', 'Me duele el hombro derecho.', 'Mijn rechterschouder doet pijn.', 'corpo'),
   ('la piel', 'de huid', 'la pjel', 'Tengo la piel muy seca.', 'Ik heb een heel droge huid.', 'corpo'),
   ('la oreja', 'het oor', 'la o-RE-cha', 'Tiene las orejas grandes.', 'Hij heeft grote oren.', 'corpo'),
   ('la muñeca', 'de pols', 'la moe-NJE-ka', 'Me rompí la muñeca.', 'Ik brak mijn pols.', 'corpo'),
   ('el tobillo', 'de enkel', 'el to-BIE-jo', 'Me he torcido el tobillo.', 'Ik heb mijn enkel verzwikt.', 'corpo'),
   ('el codo', 'de elleboog', 'el KO-do', 'Se golpeó el codo.', 'Hij stootte zijn elleboog.', 'corpo'),
   ('el pulmón', 'de long', 'el poel-MON', 'Fumar daña los pulmones.', 'Roken beschadigt de longen.', 'corpo'),
   ('el hígado', 'de lever', 'el IE-ga-do', 'El alcohol afecta al hígado.', 'Alcohol tast de lever aan.', 'corpo')]),
L(157, '⚽', 'Sport & beweging', 'Over sport praten.',
  'Over sport praten', 'Empatar (gelijkspelen), el campeón, el entrenamiento (de training). El árbitro pitó falta. Los hinchas animan al equipo.',
  [('el campeón', 'de kampioen', 'el kam-pe-ON', 'Es el campeón del mundo.', 'Hij is wereldkampioen.', 'sport'),
   ('el jugador', 'de speler', 'el choe-ga-DOR', 'El jugador fue expulsado.', 'De speler kreeg een rode kaart.', 'sport'),
   ('empatar', 'gelijkspelen', 'em-pa-TAR', 'Empataron a dos.', 'Ze speelden twee-twee gelijk.', 'verbo'),
   ('el ejercicio', 'de oefening', 'el e-cher-SIE-sjo', 'Hago ejercicio cada mañana.', 'Ik doe elke ochtend oefeningen.', 'sport'),
   ('el hincha', 'de fan / supporter', 'el IN-tsja', 'Los hinchas llenaron el estadio.', 'De supporters vulden het stadion.', 'sport'),
   ('el entrenamiento', 'de training', 'el en-tre-na-MJEN-to', 'El entrenamiento es a las seis.', 'De training is om zes uur.', 'sport'),
   ('saltar', 'springen', 'sal-TAR', 'Saltó dos metros.', 'Hij sprong twee meter.', 'verbo'),
   ('el estadio', 'het stadion', 'el es-TA-djo', 'El estadio estaba lleno.', 'Het stadion was vol.', 'sport')]),
L(158, '🍳', 'Voeding & koken', 'Kooktaal en voedsel.',
  'Kooktaal', 'Cocer a fuego lento (op laag vuur koken), añadir una pizca de sal (een snufje zout). Está crudo / hecho / quemado.',
  [('cremoso', 'romig', 'kre-MO-so', 'Una salsa cremosa.', 'Een romige saus.', 'aggettivo'),
   ('el plátano', 'de banaan', 'el PLA-ta-no', 'Un batido de plátano.', 'Een bananenmilkshake.', 'cucina'),
   ('el trozo', 'het stuk', 'el TRO-so', 'Un trozo de tarta.', 'Een stuk taart.', 'cucina'),
   ('el chocolate', 'de chocolade', 'el tsjo-ko-LA-te', 'Chocolate con churros.', 'Chocolade met churros.', 'cucina'),
   ('el hambre', 'de honger', 'el AM-bre', 'Tengo un hambre terrible.', 'Ik heb ontzettende honger.', 'cucina'),
   ('la comida', 'de maaltijd / het eten', 'la ko-MIE-da', 'La comida está lista.', 'Het eten is klaar.', 'cucina'),
   ('una pizca de', 'een snufje', 'OE-na PIS-ka de', 'Añade una pizca de sal.', 'Voeg een snufje zout toe.', 'cucina'),
   ('crudo', 'rauw', 'KROE-do', 'La carne está cruda.', 'Het vlees is rauw.', 'aggettivo')]),
L(159, '🌍', 'Milieu & natuur', 'Milieuproblemen bespreken.',
  'Milieutaal', 'El calentamiento global, el desperdicio de alimentos, las energías renovables. Es urgente que reduzcamos las emisiones (subjuntivo).',
  [('la naturaleza', 'de natuur', 'la na-toe-ra-LE-sa', 'Me encanta la naturaleza.', 'Ik hou van de natuur.', 'ambiente'),
   ('el ecosistema', 'het ecosysteem', 'el e-ko-sis-TE-ma', 'El ecosistema es frágil.', 'Het ecosysteem is kwetsbaar.', 'ambiente'),
   ('el desperdicio', 'de verspilling', 'el des-per-DIE-sjo', 'El desperdicio de comida es un problema.', 'Voedselverspilling is een probleem.', 'ambiente'),
   ('el calentamiento global', 'de opwarming van de aarde', 'el ka-len-ta-MJEN-to glo-BAL', 'El calentamiento global es real.', 'De opwarming van de aarde is echt.', 'ambiente'),
   ('desperdiciar', 'verspillen', 'des-per-di-SJAR', 'No desperdicies agua.', 'Verspil geen water.', 'verbo'),
   ('la fauna', 'de fauna', 'la FAU-na', 'La fauna de la isla es única.', 'De fauna van het eiland is uniek.', 'ambiente'),
   ('la especie', 'de soort', 'la es-PE-sje', 'Muchas especies están en peligro.', 'Veel soorten zijn in gevaar.', 'ambiente'),
   ('urgente', 'dringend', 'oer-CHEN-te', 'Es urgente que actuemos.', 'Het is dringend dat we handelen.', 'aggettivo')]),
L(160, '📝', 'Toetsles — Blok 4', 'Samenvatting van blok 4.',
  'Samenvatting Blok 4', 'Je kent de gecombineerde voornaamwoorden, de passieve vorm en de woordenschat rond gezondheid, sport en milieu. In de toets: 20 woorden uit lessen 151–159.',
  [('el mejor amigo', 'de beste vriend', 'el me-CHOR a-MIE-go', 'Es mi mejor amigo desde niño.', 'Hij is mijn beste vriend sinds mijn kindertijd.', 'sostantivo'),
   ('servir para', 'dienen om / nodig zijn', 'ser-VIER PA-ra', '¿Para qué sirve esto?', 'Waar dient dit voor?', 'espressione'),
   ('empeorar', 'verslechteren', 'em-pe-o-RAR', 'La situación empeoró.', 'De situatie verslechterde.', 'verbo'),
   ('aumentar', 'toenemen / verhogen', 'au-men-TAR', 'Los precios han aumentado.', 'De prijzen zijn gestegen.', 'verbo'),
   ('disminuir', 'afnemen / verminderen', 'dis-mi-NWIER', 'El paro ha disminuido.', 'De werkloosheid is afgenomen.', 'verbo'),
   ('mantenerse', 'zich handhaven / blijven', 'man-te-NER-se', 'Se mantiene en forma.', 'Ze blijft in vorm.', 'verbo'),
   ('la consecuencia', 'het gevolg', 'la kon-se-KWEN-sja', 'Tendrá consecuencias.', 'Het zal gevolgen hebben.', 'sostantivo'),
   ('significativo', 'significant / belangrijk', 'sig-ni-fi-ka-TIE-vo', 'Es un cambio significativo.', 'Het is een belangrijke verandering.', 'aggettivo')]),
L(161, '🔄', 'Estar + gerundio', 'Wat er nu aan de hand is.',
  'Estar + gerundio (progressief)', 'Estoy hablando (ik ben aan het praten). Gerundio: -ando / -iendo; onregelmatig: leyendo, durmiendo, diciendo, pidiendo, yendo. Ook in het verleden: estaba comiendo.',
  [('estoy hablando', 'ik ben aan het praten', 'es-TOI a-BLAN-do', 'Estoy hablando por teléfono.', 'Ik ben aan het bellen.', 'espressione'),
   ('estoy leyendo', 'ik ben aan het lezen', 'es-TOI le-JEN-do', 'Estoy leyendo una novela.', 'Ik ben een roman aan het lezen.', 'espressione'),
   ('está lloviendo', 'het is aan het regenen', 'es-TA jo-VJEN-do', 'Está lloviendo desde esta mañana.', 'Het regent al sinds vanochtend.', 'espressione'),
   ('estoy buscando', 'ik ben aan het zoeken', 'es-TOI boes-KAN-do', 'Estoy buscando las llaves.', 'Ik ben de sleutels aan het zoeken.', 'espressione'),
   ('estoy aprendiendo', 'ik ben aan het leren', 'es-TOI a-pren-DJEN-do', 'Estoy aprendiendo español.', 'Ik ben Spaans aan het leren.', 'espressione'),
   ('está cambiando', 'het is aan het veranderen', 'es-TA kam-BJAN-do', 'El clima está cambiando.', 'Het klimaat is aan het veranderen.', 'espressione'),
   ('estamos esperando', 'we zijn aan het wachten', 'es-TA-mos es-pe-RAN-do', 'Estamos esperando el autobús.', 'We staan op de bus te wachten.', 'espressione'),
   ('están trabajando', 'zij zijn aan het werken', 'es-TAN tra-ba-CHAN-do', 'Están trabajando en el jardín.', 'Ze zijn in de tuin aan het werken.', 'espressione')]),
L(162, '🔗', 'Bijzinnen — oorzaak & reden', 'Redenen geven.',
  'Causale bijzinnen', 'Porque (omdat), ya que / puesto que (aangezien), como (aangezien, aan het begin), debido a (vanwege), por lo tanto (dus), por eso (daarom).',
  [('ya que', 'aangezien', 'ja ke', 'Ya que estás aquí, ayúdame.', 'Aangezien je hier bent, help me.', 'espressione'),
   ('puesto que', 'gezien het feit dat', 'PWES-to ke', 'Puesto que llueve, nos quedamos.', 'Gezien het regent, blijven we.', 'espressione'),
   ('como', 'aangezien (aan het begin)', 'KO-mo', 'Como era tarde, nos fuimos.', 'Aangezien het laat was, gingen we weg.', 'espressione'),
   ('debido a', 'vanwege', 'de-BIE-do a', 'Debido a la huelga, no hay trenes.', 'Vanwege de staking rijden er geen treinen.', 'espressione'),
   ('la razón', 'de reden', 'la ra-SON', '¿Cuál es la razón?', 'Wat is de reden?', 'sostantivo'),
   ('por lo tanto', 'dus / derhalve', 'por lo TAN-to', 'Está enfermo; por lo tanto, no viene.', 'Hij is ziek; dus komt hij niet.', 'espressione'),
   ('la causa', 'de oorzaak', 'la KAU-sa', 'Se desconoce la causa del incendio.', 'De oorzaak van de brand is onbekend.', 'sostantivo'),
   ('en consecuencia', 'als gevolg daarvan', 'en kon-se-KWEN-sja', 'En consecuencia, cerraron la fábrica.', 'Als gevolg daarvan sloten ze de fabriek.', 'espressione')]),
L(163, '↔️', 'Bijzinnen — tegenstelling', 'Tegenstellingen uitdrukken.',
  'Concessieve bijzinnen', 'Aunque + indicativo (feit) of + subjuntivo (mogelijkheid). A pesar de + zelfstandig naamwoord. Ni siquiera (zelfs niet). Más bien (eerder).',
  [('incluso si', 'ook al / zelfs als', 'in-KLOE-so si', 'Incluso si llueve, iremos.', 'Zelfs als het regent, gaan we.', 'espressione'),
   ('ni siquiera', 'zelfs niet', 'ni si-KJE-ra', 'Ni siquiera me saludó.', 'Hij groette me niet eens.', 'espressione'),
   ('a pesar de', 'ondanks', 'a pe-SAR de', 'A pesar del frío, salimos.', 'Ondanks de kou gingen we naar buiten.', 'espressione'),
   ('y sin embargo', 'en toch', 'i sin em-BAR-go', 'Es caro y sin embargo lo compré.', 'Het is duur en toch kocht ik het.', 'espressione'),
   ('o bien', 'of anders', 'o bjen', 'Vamos en tren o bien en coche.', 'We gaan met de trein of anders met de auto.', 'espressione'),
   ('afortunadamente', 'gelukkig', 'a-for-toe-na-da-MEN-te', 'Afortunadamente, no pasó nada.', 'Gelukkig gebeurde er niets.', 'avverbio'),
   ('más bien', 'eerder / liever', 'mas bjen', 'No es tímido, más bien es prudente.', 'Hij is niet verlegen, eerder voorzichtig.', 'espressione'),
   ('en cualquier caso', 'in ieder geval', 'en kwal-KJER KA-so', 'En cualquier caso, te llamo.', 'In ieder geval bel ik je.', 'espressione')]),
L(164, '⏰', 'Bijzinnen — tijd', 'Tijdsrelaties tussen gebeurtenissen.',
  'Temporele bijzinnen', 'Antes de que + subjuntivo, después de que, en cuanto (zodra), hasta que (totdat), cada vez que (telkens wanneer). Bij toekomst altijd subjuntivo: cuando llegues.',
  [('en cuanto', 'zodra', 'en KWAN-to', 'En cuanto llegue, te llamo.', 'Zodra ik aankom, bel ik je.', 'espressione'),
   ('hasta que', 'totdat', 'AS-ta ke', 'Espera hasta que vuelva.', 'Wacht tot ik terug ben.', 'espressione'),
   ('después de que', 'nadat', 'des-PWES de ke', 'Después de que cenemos, salimos.', 'Nadat we gegeten hebben, gaan we uit.', 'espressione'),
   ('cada vez que', 'telkens wanneer', 'KA-da ves ke', 'Cada vez que la veo, sonríe.', 'Telkens als ik haar zie, lacht ze.', 'espressione'),
   ('en el momento en que', 'op het moment dat', 'en el mo-MEN-to en ke', 'En el momento en que entró, todos callaron.', 'Op het moment dat hij binnenkwam, zweeg iedereen.', 'espressione'),
   ('ya', 'al / inmiddels', 'ja', 'Ya he terminado.', 'Ik ben al klaar.', 'avverbio'),
   ('al mismo tiempo', 'tegelijkertijd', 'al MIS-mo TJEM-po', 'Llegaron al mismo tiempo.', 'Ze kwamen tegelijkertijd aan.', 'espressione'),
   ('apenas', 'nauwelijks / zodra', 'a-PE-nas', 'Apenas llegó, se durmió.', 'Zodra hij aankwam, viel hij in slaap.', 'avverbio')]),
L(165, '🗨️', 'Estilo indirecto — basis', 'Doorvertellen wat iemand zei.',
  'Indirecte rede', 'Dijo que + tijdverschuiving: presente → imperfecto (dijo que estaba cansado), indefinido → pluscuamperfecto (dijo que había llegado), futuro → condicional (dijo que vendría).',
  [('afirmar', 'beweren / bevestigen', 'a-fir-MAR', 'Afirmó que era inocente.', 'Hij beweerde dat hij onschuldig was.', 'verbo'),
   ('declarar', 'verklaren', 'de-kla-RAR', 'Declaró que no sabía nada.', 'Hij verklaarde dat hij niets wist.', 'verbo'),
   ('repetir', 'herhalen', 're-pe-TIER', 'Repitió que no vendría.', 'Hij herhaalde dat hij niet zou komen.', 'verbo'),
   ('señalar', 'opmerken / wijzen op', 'se-nja-LAR', 'Señaló que había un error.', 'Hij merkte op dat er een fout zat.', 'verbo'),
   ('la conversación', 'het gesprek', 'la kon-ver-sa-SJON', 'Tuvimos una conversación larga.', 'We hadden een lang gesprek.', 'sostantivo'),
   ('advertir', 'waarschuwen', 'ad-ver-TIER', 'Me advirtió que sería difícil.', 'Hij waarschuwde me dat het moeilijk zou zijn.', 'verbo'),
   ('contar que', 'vertellen dat', 'kon-TAR ke', 'Me contó que había vivido en Perú.', 'Hij vertelde me dat hij in Peru had gewoond.', 'espressione'),
   ('asegurar', 'verzekeren', 'a-se-goe-RAR', 'Aseguró que llegaría a tiempo.', 'Hij verzekerde dat hij op tijd zou komen.', 'verbo')]),
L(166, '❓', 'Estilo indirecto — vragen', 'Vragen doorvertellen.',
  'Indirecte vragen', 'Me preguntó si venía (of ik kwam). Me preguntó dónde vivía / cuándo llegaría. Quería saber qué hacía.',
  [('preguntar', 'vragen', 'pre-goen-TAR', 'Me preguntó si tenía tiempo.', 'Hij vroeg me of ik tijd had.', 'verbo'),
   ('preguntarse', 'zich afvragen', 'pre-goen-TAR-se', 'Me pregunto por qué no llama.', 'Ik vraag me af waarom hij niet belt.', 'verbo'),
   ('informarse', 'informeren / navragen', 'in-for-MAR-se', 'Se informó sobre el horario.', 'Hij vroeg na over de tijden.', 'verbo'),
   ('querer saber', 'willen weten', 'ke-RER sa-BER', 'Quería saber dónde vivías.', 'Hij wilde weten waar je woonde.', 'espressione'),
   ('la pregunta', 'de vraag', 'la pre-GOEN-ta', 'Es una buena pregunta.', 'Het is een goede vraag.', 'sostantivo'),
   ('la respuesta', 'het antwoord', 'la res-PWES-ta', 'No tengo respuesta.', 'Ik heb geen antwoord.', 'sostantivo'),
   ('informar', 'melden / informeren', 'in-for-MAR', 'Nos informaron de que el vuelo salía tarde.', 'Ze meldden ons dat de vlucht laat vertrok.', 'verbo'),
   ('aclarar', 'verduidelijken', 'a-kla-RAR', '¿Puedes aclarar qué quieres decir?', 'Kun je verduidelijken wat je bedoelt?', 'verbo')]),
L(167, '💻', 'Technologie & internet', 'Digitale woordenschat.',
  'Digitale woordenschat', 'El cargador (de oplader), el dispositivo (het apparaat), hacer clic (klikken), conectarse a la red. Se me ha colgado el ordenador (mijn computer is vastgelopen).',
  [('el cargador', 'de oplader', 'el kar-ga-DOR', '¿Tienes un cargador?', 'Heb je een oplader?', 'tecnologia'),
   ('el código', 'de code', 'el KO-di-go', 'Introduce el código de seguridad.', 'Voer de beveiligingscode in.', 'tecnologia'),
   ('el dispositivo', 'het apparaat', 'el dis-po-si-TIE-vo', 'Conecta el dispositivo.', 'Sluit het apparaat aan.', 'tecnologia'),
   ('conectarse', 'verbinding maken', 'ko-nek-TAR-se', 'No puedo conectarme al wifi.', 'Ik kan geen verbinding maken met de wifi.', 'verbo'),
   ('hacer clic', 'klikken', 'a-SER klik', 'Haz clic en el enlace.', 'Klik op de link.', 'espressione'),
   ('la batería', 'de batterij / accu', 'la ba-te-RIE-a', 'La batería dura poco.', 'De batterij gaat kort mee.', 'tecnologia'),
   ('colgarse', 'vastlopen', 'kol-GAR-se', 'Se me ha colgado el ordenador.', 'Mijn computer is vastgelopen.', 'verbo'),
   ('el usuario', 'de gebruiker', 'el oe-SWA-rjo', 'Introduce tu nombre de usuario.', 'Voer je gebruikersnaam in.', 'tecnologia')]),
L(168, '📱', 'Sociale media', 'Praten over online leven.',
  'Sociale mediataal', 'Publicar (posten), borrar (verwijderen), el contenido, la privacidad. Me etiquetaron en una foto (ze hebben me getagd).',
  [('el vídeo', 'de video', 'el VIE-de-o', 'El vídeo tiene un millón de visitas.', 'De video heeft een miljoen weergaven.', 'social'),
   ('el comentario', 'de reactie / het commentaar', 'el ko-men-TA-rjo', 'Dejó un comentario negativo.', 'Hij liet een negatieve reactie achter.', 'social'),
   ('la versión', 'de versie', 'la ver-SJON', 'Hay una versión nueva de la app.', 'Er is een nieuwe versie van de app.', 'tecnologia'),
   ('borrar', 'wissen / verwijderen', 'bo-RRAR', 'Borré la foto.', 'Ik heb de foto verwijderd.', 'verbo'),
   ('el contenido', 'de inhoud / content', 'el kon-te-NIE-do', 'Crea contenido para redes.', 'Ze maakt content voor sociale media.', 'social'),
   ('grabar', 'opnemen', 'gra-BAR', 'Grabé un vídeo del concierto.', 'Ik nam een video van het concert op.', 'verbo'),
   ('el contacto', 'het contact', 'el kon-TAK-to', 'Tengo un contacto nuevo.', 'Ik heb een nieuw contact.', 'social'),
   ('la privacidad', 'de privacy', 'la pri-va-si-DAD', 'Me preocupa la privacidad.', 'Ik maak me zorgen over de privacy.', 'social')]),
L(169, '🎬', 'Film, boeken & muziek', 'Over entertainment praten.',
  'Over entertainment praten', 'El género (het genre), la comedia, la novela policíaca (detective). Trata de (gaat over). Me engancha (het grijpt me).',
  [('el episodio', 'de aflevering', 'el e-pi-SO-djo', 'El último episodio fue increíble.', 'De laatste aflevering was ongelooflijk.', 'sostantivo'),
   ('la novela policíaca', 'de detective(roman)', 'la no-VE-la po-li-SIE-a-ka', 'Me encantan las novelas policíacas.', 'Ik ben dol op detectives.', 'sostantivo'),
   ('la lectura', 'het lezen', 'la lek-TOE-ra', 'La lectura es mi pasatiempo favorito.', 'Lezen is mijn favoriete hobby.', 'sostantivo'),
   ('el autor', 'de auteur', 'el au-TOR', 'El autor firmó mi libro.', 'De auteur signeerde mijn boek.', 'sostantivo'),
   ('el género', 'het genre', 'el CHE-ne-ro', '¿Qué género prefieres?', 'Welk genre heb je het liefst?', 'sostantivo'),
   ('la comedia', 'de komedie', 'la ko-ME-dja', 'Es una comedia romántica.', 'Het is een romantische komedie.', 'sostantivo'),
   ('enganchar', 'grijpen / verslavend zijn', 'en-gan-TSJAR', 'Esta serie engancha.', 'Deze serie is verslavend.', 'verbo'),
   ('el héroe', 'de held', 'el E-ro-e', 'El héroe salva la ciudad.', 'De held redt de stad.', 'sostantivo')]),
L(170, '📝', 'Toetsles — Blok 5', 'Samenvatting van blok 5.',
  'Samenvatting Blok 5', 'Je kent estar + gerundio, de bijzinnen van oorzaak, tegenstelling en tijd, en de indirecte rede. In de toets: 20 woorden uit lessen 161–169.',
  [('comenzar', 'beginnen', 'ko-men-SAR', 'La película comienza a las nueve.', 'De film begint om negen uur.', 'verbo'),
   ('pasado mañana', 'overmorgen', 'pa-SA-do ma-NJA-na', 'Nos vemos pasado mañana.', 'We zien elkaar overmorgen.', 'espressione'),
   ('el lenguaje', 'het taalgebruik', 'el len-GWA-che', 'Usa un lenguaje muy formal.', 'Hij gebruikt heel formeel taalgebruik.', 'sostantivo'),
   ('casi', 'bijna', 'KA-si', 'Casi he terminado.', 'Ik ben bijna klaar.', 'avverbio'),
   ('aproximadamente', 'ongeveer', 'a-prok-si-ma-da-MEN-te', 'Tarda aproximadamente una hora.', 'Het duurt ongeveer een uur.', 'avverbio'),
   ('el significado', 'de betekenis', 'el sig-ni-fi-KA-do', '¿Cuál es el significado de esta palabra?', 'Wat is de betekenis van dit woord?', 'sostantivo'),
   ('captar', 'oppikken / snappen', 'kap-TAR', 'No capté la idea.', 'Ik snapte het idee niet.', 'verbo'),
   ('malinterpretar', 'verkeerd begrijpen', 'ma-lin-ter-pre-TAR', 'Malinterpretó mis palabras.', 'Hij begreep mijn woorden verkeerd.', 'verbo')]),
L(171, '📊', 'Vergelijkingen', 'Vergelijken op B1-niveau.',
  'Comparativo', 'Mayor/menor (ouder/jonger, groter/kleiner), superior/inferior, igual que (gelijk aan), diferente de (anders dan). Cuanto más..., más... (hoe meer..., hoe meer...).',
  [('mayor que', 'ouder dan / groter dan', 'ma-JOR ke', 'Mi hermana es mayor que yo.', 'Mijn zus is ouder dan ik.', 'espressione'),
   ('menor', 'jonger / kleiner', 'me-NOR', 'Es el menor de tres hermanos.', 'Hij is de jongste van drie broers.', 'aggettivo'),
   ('superior', 'hoger / superieur', 'soe-pe-RJOR', 'La calidad es superior.', 'De kwaliteit is hoger.', 'aggettivo'),
   ('inferior', 'lager / inferieur', 'in-fe-RJOR', 'El precio es inferior al del año pasado.', 'De prijs is lager dan vorig jaar.', 'aggettivo'),
   ('igual que', 'gelijk aan / net als', 'i-GWAL ke', 'Es igual que su padre.', 'Hij is net als zijn vader.', 'espressione'),
   ('diferente de', 'anders dan', 'di-fe-REN-te de', 'Es diferente de lo que esperaba.', 'Het is anders dan ik verwachtte.', 'espressione'),
   ('cuanto más', 'hoe meer', 'KWAN-to mas', 'Cuanto más estudio, más aprendo.', 'Hoe meer ik studeer, hoe meer ik leer.', 'espressione'),
   ('el mismo', 'dezelfde / hetzelfde', 'el MIS-mo', 'Tenemos el mismo coche.', 'We hebben dezelfde auto.', 'aggettivo')]),
L(172, '🏆', 'Superlatieven', 'De overtreffende trap en -ísimo.',
  'Superlativo relativo en absoluto', 'Relatief: el más alto de la clase. Absoluut: altísimo, buenísimo, rapidísimo. Onregelmatig: óptimo, pésimo, máximo, mínimo.',
  [('bellísimo', 'heel mooi / prachtig', 'be-JIE-si-mo', 'Un paisaje bellísimo.', 'Een prachtig landschap.', 'aggettivo'),
   ('enorme', 'heel groot / enorm', 'e-NOR-me', 'Una plaza enorme.', 'Een enorm plein.', 'aggettivo'),
   ('óptimo', 'uitstekend / optimaal', 'OP-ti-mo', 'El resultado fue óptimo.', 'Het resultaat was uitstekend.', 'aggettivo'),
   ('pésimo', 'heel slecht', 'PE-si-mo', 'El servicio fue pésimo.', 'De service was heel slecht.', 'aggettivo'),
   ('rapidísimo', 'heel snel', 'ra-pi-DIE-si-mo', 'El tren es rapidísimo.', 'De trein is razendsnel.', 'aggettivo'),
   ('lentísimo', 'heel langzaam', 'len-TIE-si-mo', 'La conexión es lentísima.', 'De verbinding is tergend langzaam.', 'aggettivo'),
   ('facilísimo', 'heel makkelijk', 'fa-si-LIE-si-mo', 'El examen fue facilísimo.', 'Het examen was heel makkelijk.', 'aggettivo'),
   ('dificilísimo', 'heel moeilijk', 'di-fi-si-LIE-si-mo', 'Es un idioma dificilísimo.', 'Het is een heel moeilijke taal.', 'aggettivo')]),
L(173, '🔮', 'Hypothese — type 1', 'Reële voorwaarden: si + presente.',
  'Voorwaardelijke zin type 1 (reëel)', 'Si + presente, presente/futuro: Si llueve, no salimos. Si tengo tiempo, te llamaré. Nooit futuro na "si".',
  [('la condición', 'de voorwaarde', 'la kon-di-SJON', 'Acepto con una condición.', 'Ik accepteer op één voorwaarde.', 'sostantivo'),
   ('en caso de que', 'in het geval dat', 'en KA-so de ke', 'En caso de que llueva, llévate paraguas.', 'In het geval dat het regent, neem een paraplu.', 'espressione'),
   ('siempre que', 'op voorwaarde dat / zolang', 'SJEM-pre ke', 'Puedes venir siempre que avises.', 'Je mag komen, zolang je het laat weten.', 'espressione'),
   ('si no', 'anders / zo niet', 'si no', 'Date prisa; si no, perdemos el tren.', 'Schiet op; anders missen we de trein.', 'espressione'),
   ('eventualmente', 'mogelijk / eventueel', 'e-ven-twal-MEN-te', 'Eventualmente podríamos cambiar la fecha.', 'Eventueel kunnen we de datum veranderen.', 'avverbio'),
   ('en el peor de los casos', 'in het ergste geval', 'en el pe-OR de los KA-sos', 'En el peor de los casos, volvemos mañana.', 'In het ergste geval komen we morgen terug.', 'espressione'),
   ('supongamos que', 'stel dat', 'soe-pon-GA-mos ke', 'Supongamos que no viene.', 'Stel dat hij niet komt.', 'espressione'),
   ('por si acaso', 'voor het geval dat', 'por si a-KA-so', 'Llevo dinero por si acaso.', 'Ik neem geld mee voor het geval dat.', 'espressione')]),
L(174, '💫', 'Hypothese — type 2', 'Irreële voorwaarden: si + imperfecto de subjuntivo.',
  'Voorwaardelijke zin type 2 (irreëel)', 'Si + imperfecto de subjuntivo, condicional: Si tuviera dinero, viajaría. Vorming: indefinido ellos (tuvieron) → tuviera, tuvieras, tuviera, tuviéramos, tuvierais, tuvieran.',
  [('si fuera', 'als ik was / zou zijn', 'si FWE-ra', 'Si fuera rico, compraría una casa.', 'Als ik rijk was, zou ik een huis kopen.', 'espressione'),
   ('si tuviera', 'als ik had', 'si toe-VJE-ra', 'Si tuviera tiempo, te ayudaría.', 'Als ik tijd had, zou ik je helpen.', 'espressione'),
   ('si pudiera', 'als ik kon', 'si poe-DJE-ra', 'Si pudiera, viviría en el sur.', 'Als ik kon, zou ik in het zuiden wonen.', 'espressione'),
   ('si supiera', 'als ik wist', 'si soe-PJE-ra', 'Si supiera la respuesta, te la diría.', 'Als ik het antwoord wist, zou ik het je zeggen.', 'espressione'),
   ('si estuviera', 'als ik was (plaats/toestand)', 'si es-toe-VJE-ra', 'Si estuviera en Madrid, iría al Prado.', 'Als ik in Madrid was, zou ik naar het Prado gaan.', 'espressione'),
   ('si quisiera', 'als ik wilde', 'si ki-SJE-ra', 'Si quisiera, podría hacerlo.', 'Als ik wilde, zou ik het kunnen.', 'espressione'),
   ('si hiciera', 'als ik deed / als het was (weer)', 'si i-SJE-ra', 'Si hiciera sol, iríamos a la playa.', 'Als de zon scheen, zouden we naar het strand gaan.', 'espressione'),
   ('si viviera', 'als ik woonde', 'si vi-VJE-ra', 'Si viviera aquí, sería feliz.', 'Als ik hier woonde, zou ik gelukkig zijn.', 'espressione')]),
L(175, '👔', 'Formeel & informeel', 'Register: tú, usted en beleefdheid.',
  'Register: formeel vs. informeel', 'Tutear (je zeggen) vs. tratar de usted (u zeggen). In Spanje is "tú" gebruikelijk, ook op het werk; "usted" bij ouderen, klanten en officiële situaties.',
  [('formal', 'formeel', 'for-MAL', 'Es una carta formal.', 'Het is een formele brief.', 'aggettivo'),
   ('informal', 'informeel', 'in-for-MAL', 'Un tono informal.', 'Een informele toon.', 'aggettivo'),
   ('tratar de usted', 'u zeggen', 'tra-TAR de oes-TED', 'A los clientes los trato de usted.', 'Tegen klanten zeg ik u.', 'espressione'),
   ('tutear', 'je/jij zeggen', 'toe-te-AR', 'En España se tutea mucho.', 'In Spanje zegt men vaak jij.', 'verbo'),
   ('la cortesía', 'de beleefdheid', 'la kor-te-SIE-a', 'Es una cuestión de cortesía.', 'Het is een kwestie van beleefdheid.', 'sostantivo'),
   ('la educación', 'de opvoeding / beleefdheid', 'la e-doe-ka-SJON', 'Es de buena educación saludar.', 'Groeten hoort bij goede manieren.', 'sostantivo'),
   ('adecuado', 'gepast', 'a-de-KWA-do', 'No es el momento adecuado.', 'Het is niet het gepaste moment.', 'aggettivo'),
   ('el registro', 'het taalregister', 'el re-CHIS-tro', 'Cambia de registro según la situación.', 'Hij past zijn register aan de situatie aan.', 'sostantivo')]),
L(176, '🗺️', 'Spaanse regio\'s', 'De geografie van Spanje.',
  'Spaanse geografie', 'España tiene diecisiete comunidades autónomas. Cada una tiene su capital, y algunas su propia lengua: catalán, gallego, euskera.',
  [('la comunidad autónoma', 'de autonome regio', 'la ko-moe-ni-DAD au-TO-no-ma', 'Andalucía es la comunidad autónoma más poblada.', 'Andalusië is de dichtstbevolkte regio.', 'geografia'),
   ('la capital', 'de hoofdstad', 'la ka-pi-TAL', 'La capital de Cataluña es Barcelona.', 'De hoofdstad van Catalonië is Barcelona.', 'geografia'),
   ('la aldea', 'het gehucht / dorp', 'la al-DE-a', 'Nació en una aldea de Galicia.', 'Ze werd geboren in een dorp in Galicië.', 'geografia'),
   ('la zona', 'de zone / het gebied', 'la SO-na', 'Es una zona muy turística.', 'Het is een heel toeristisch gebied.', 'geografia'),
   ('la frontera', 'de grens', 'la fron-TE-ra', 'La frontera con Portugal está cerca.', 'De grens met Portugal is dichtbij.', 'geografia'),
   ('el rincón', 'het hoekje / de uithoek', 'el rin-KON', 'Es un rincón precioso de Asturias.', 'Het is een prachtig hoekje van Asturië.', 'geografia'),
   ('la sierra', 'de bergketen', 'la SJE-rra', 'La Sierra Nevada tiene nieve en invierno.', 'De Sierra Nevada heeft sneeuw in de winter.', 'geografia'),
   ('típico', 'karakteristiek / typisch', 'TIE-pi-ko', 'Es un plato típico de Asturias.', 'Het is een typisch gerecht uit Asturië.', 'aggettivo')]),
L(177, '🍝', 'Spaanse keuken verdieping', 'Regionale specialiteiten.',
  'Regionale keuken', 'La especialidad de la casa. El aceite de oliva virgen extra. El jamón ibérico, el pulpo a la gallega, la fabada asturiana.',
  [('la especialidad', 'de specialiteit', 'la es-pe-sja-li-DAD', 'La especialidad de la casa es el cordero.', 'De specialiteit van het huis is lam.', 'cucina'),
   ('la salsa', 'de saus', 'la SAL-sa', 'La salsa lleva ajo y aceite.', 'De saus bevat knoflook en olie.', 'cucina'),
   ('la receta tradicional', 'het traditionele recept', 'la re-SE-ta tra-di-sjo-NAL', 'Es la receta tradicional de mi abuela.', 'Het is het traditionele recept van mijn oma.', 'cucina'),
   ('el bocadillo', 'het broodje', 'el bo-ka-DIE-jo', 'Un bocadillo de jamón.', 'Een broodje ham.', 'cucina'),
   ('delicioso', 'heerlijk', 'de-li-SJO-so', 'El pulpo estaba delicioso.', 'De octopus was heerlijk.', 'aggettivo'),
   ('el viñedo', 'de wijngaard', 'el vi-NJE-do', 'Los viñedos de La Rioja son famosos.', 'De wijngaarden van La Rioja zijn beroemd.', 'cucina'),
   ('el jamón ibérico', 'de Iberische ham', 'el cha-MON i-BE-ri-ko', 'El jamón ibérico es caro.', 'Iberische ham is duur.', 'cucina'),
   ('sabroso', 'smaakvol', 'sa-BRO-so', 'Un guiso muy sabroso.', 'Een heel smaakvolle stoofpot.', 'aggettivo')]),
L(178, '🤝', 'Cultuur & etiquette', 'Omgangsvormen in Spanje.',
  'Spaanse etiquette', 'Dos besos al saludar (twee kussen bij het begroeten). Llegar un poco tarde es normal. Se come tarde. Ser hospitalario (gastvrij).',
  [('la costumbre local', 'het lokale gebruik', 'la kos-TOEM-bre lo-KAL', 'Respeta las costumbres locales.', 'Respecteer de lokale gebruiken.', 'cultura'),
   ('el gesto', 'het gebaar', 'el CHES-to', 'Fue un gesto muy amable.', 'Het was een heel vriendelijk gebaar.', 'cultura'),
   ('maleducado', 'onbeleefd', 'ma-le-doe-KA-do', 'No seas maleducado.', 'Wees niet onbeleefd.', 'aggettivo'),
   ('la etiqueta', 'de etiquette', 'la e-ti-KE-ta', 'Hay reglas de etiqueta.', 'Er zijn etiquetteregels.', 'cultura'),
   ('la bienvenida', 'het welkom', 'la bjen-ve-NIE-da', 'Nos dieron la bienvenida.', 'Ze heetten ons welkom.', 'cultura'),
   ('la mentalidad', 'de mentaliteit', 'la men-ta-li-DAD', 'Tienen otra mentalidad.', 'Ze hebben een andere mentaliteit.', 'cultura'),
   ('hospitalario', 'gastvrij', 'os-pi-ta-LA-rjo', 'Los españoles son muy hospitalarios.', 'Spanjaarden zijn heel gastvrij.', 'aggettivo'),
   ('dar dos besos', 'twee kussen geven (begroeting)', 'dar dos BE-sos', 'En España se dan dos besos.', 'In Spanje geeft men twee kussen.', 'espressione')]),
L(179, '🚀', 'Toekomstplannen', 'Over je doelen praten.',
  'Over de toekomst praten', 'Tengo la intención de (ik ben van plan), mi objetivo es, me propongo (ik neem me voor). Con determinación y constancia (met vastberadenheid en volharding).',
  [('la intención', 'de intentie / het voornemen', 'la in-ten-SJON', 'Tengo la intención de seguir estudiando.', 'Ik ben van plan te blijven studeren.', 'sostantivo'),
   ('proponerse', 'zich voornemen', 'pro-po-NER-se', 'Me propongo leer más.', 'Ik neem me voor meer te lezen.', 'verbo'),
   ('superarse', 'zichzelf verbeteren', 'soe-pe-RAR-se', 'Cada día intento superarme.', 'Elke dag probeer ik mezelf te overtreffen.', 'verbo'),
   ('el avance', 'de vooruitgang', 'el a-VAN-se', 'Has hecho grandes avances.', 'Je hebt grote vooruitgang geboekt.', 'sostantivo'),
   ('el reto', 'de uitdaging', 'el RE-to', 'El B1 fue un reto.', 'B1 was een uitdaging.', 'sostantivo'),
   ('la determinación', 'de vastberadenheid', 'la de-ter-mi-na-SJON', 'Con determinación se consigue todo.', 'Met vastberadenheid bereik je alles.', 'sostantivo'),
   ('constante', 'constant / volhardend', 'kons-TAN-te', 'Ha sido muy constante.', 'Hij is heel volhardend geweest.', 'aggettivo'),
   ('el objetivo final', 'het einddoel', 'el ob-che-TIE-vo fi-NAL', 'Mi objetivo final es el C1.', 'Mijn einddoel is C1.', 'sostantivo')]),
L(180, '🎓', '🎓 B1 blok 1 afgerond!', 'Gefeliciteerd: het eerste B1-blok is compleet!',
  'Gefeliciteerd: B1 blok 1 compleet!', 'Je beheerst nu het imperfecto, het indefinido, de condicional, de subjuntivo presente en de voorwaardelijke zinnen. Meer dan 1400 Spaanse woorden. ¡Enhorabuena, sigue así!',
  [('el nivel', 'het niveau', 'el ni-VEL', 'Has alcanzado el nivel B1.', 'Je hebt niveau B1 bereikt.', 'sostantivo'),
   ('dominar', 'beheersen', 'do-mi-NAR', 'Dominas el subjuntivo.', 'Je beheerst de subjuntivo.', 'verbo'),
   ('con fluidez', 'vloeiend', 'kon flwi-DES', 'Hablas con fluidez.', 'Je spreekt vloeiend.', 'espressione'),
   ('la competencia lingüística', 'de taalvaardigheid', 'la kom-pe-TEN-sja lin-GWIS-ti-ka', 'Tu competencia lingüística ha mejorado.', 'Je taalvaardigheid is verbeterd.', 'sostantivo'),
   ('el esfuerzo', 'de inspanning / inzet', 'el es-FWER-so', 'Tu esfuerzo ha valido la pena.', 'Je inzet is de moeite waard geweest.', 'sostantivo'),
   ('el recorrido', 'het traject / de route', 'el re-ko-RRIE-do', 'Ha sido un largo recorrido.', 'Het was een lange weg.', 'sostantivo'),
   ('continuar', 'doorgaan / vervolgen', 'kon-ti-NWAR', 'Continúa con el siguiente bloque.', 'Ga door met het volgende blok.', 'verbo'),
   ('el éxito', 'het succes', 'el EK-si-to', 'El éxito es fruto del esfuerzo.', 'Succes is de vrucht van inzet.', 'sostantivo')]),
]

# ── Validatie + schrijven ────────────────────────────────────────────────────
from collections import Counter
assert [l['id'] for l in LESSONS] == list(range(121, 181)), 'les-IDs'
vocab = json.load(open(OUT / 'vocabulary.json', encoding='utf-8'))
curriculum = json.load(open(OUT / 'curriculum.json', encoding='utf-8'))
vocab = [w for w in vocab if w['level'] != 'B1']; curriculum = [l for l in curriculum if l['level'] != 'B1']
ART = re.compile(r"^(?:(?:el|la|los|las|un|una|unos|unas)\s+)", re.I)
norm = lambda s: ART.sub('', s.lower()).strip()
existing = {norm(w['it']) for w in vocab}
seen = Counter(); n = max(int(w['id'][1:]) for w in vocab) + 1
new_vocab, new_curr = [], []
for l in LESSONS:
    assert len(l['words']) == 8, f"les {l['id']}: {len(l['words'])} woorden"
    ids = []
    for es, nl, ph, ex, exNl, cat in l['words']:
        k = norm(es); seen[k] += 1
        assert k not in existing, f"les {l['id']}: '{es}' bestaat al"
        wid = f'e{n:03d}'; n += 1
        new_vocab.append({'id': wid, 'it': es, 'nl': nl, 'ph': ph, 'ex': ex, 'exNl': exNl, 'lesson': l['id'], 'level': 'B1', 'cat': cat})
        ids.append(wid)
    new_curr.append({'id': l['id'], 'title': l['title'], 'emoji': l['emoji'], 'level': 'B1', 'description': l['description'], 'grammar': l['grammar'], 'words': ids})
dups = [k for k, c in seen.items() if c > 1]
assert not dups, f'dubbel binnen B1: {dups}'
vocab += new_vocab; curriculum += new_curr
json.dump(vocab, open(OUT / 'vocabulary.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'vocabulary.json', 'a').write('\n')
json.dump(curriculum, open(OUT / 'curriculum.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'curriculum.json', 'a').write('\n')
print(f'Spaans B1 blok 1: {len(new_curr)} lessen, {len(new_vocab)} woorden → totaal {len(curriculum)} lessen, {len(vocab)} woorden')
