#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_es_b1_blok2.py — Spaans B1 blok 2 (v1.59: lessen 181–240). Thema-opbouw gespiegeld aan Italiaans B1,
met Spaanse grammatica (pluscuamperfecto, condicional compuesto, imperfecto de subjuntivo, diminutivos).
Vervangt alleen les 181–240 in de bestaande Spaanse data; IDs lopen door vanaf het hoogste bestaande ID.
Draai opnieuw na bewerken: python3 scripts/generate_es_b1_blok2.py
Formaat: L(id, emoji, title, description, grammar_title, grammar_body, [ (es, nl, ph, ex, exNl, cat) × 8 ])
"""
import json, re
from pathlib import Path

OUT = Path(__file__).parent.parent / 'www' / 'data' / 'es'
FIRST, LAST = 181, 240

def L(id, emoji, title, desc, gt, gb, words):
    return dict(id=id, emoji=emoji, title=title, description=desc, grammar=dict(title=gt, body=gb), words=words)

LESSONS = [
L(181, '📜', 'Pluscuamperfecto — vorming', 'Wat er al gebeurd was vóór iets anders.',
  'Pretérito pluscuamperfecto', 'Había + participio: había comido (ik had gegeten), habías salido, habíamos visto. Gebruik: een handeling die vóór een andere handeling in het verleden plaatsvond: Cuando llegué, ya se habían ido.',
  [('había terminado', 'ik was klaar / ik had afgemaakt', 'a-BIE-a ter-mi-NA-do', 'Cuando llamaste, ya había terminado.', 'Toen je belde, was ik al klaar.', 'espressione'),
   ('ya se había ido', 'hij was al weg', 'ja se a-BIE-a IE-do', 'Cuando llegué, ya se había ido.', 'Toen ik aankwam, was hij al weg.', 'espressione'),
   ('nunca había visto', 'ik had nooit gezien', 'NOEN-ka a-BIE-a VIS-to', 'Nunca había visto el mar.', 'Ik had de zee nog nooit gezien.', 'espressione'),
   ('todavía no', 'nog niet', 'to-da-VIE-a no', 'Todavía no había cenado.', 'Hij had nog niet gegeten.', 'espressione'),
   ('previamente', 'van tevoren / eerder', 'pre-vja-MEN-te', 'Lo habíamos acordado previamente.', 'We hadden het van tevoren afgesproken.', 'avverbio'),
   ('anteriormente', 'voorheen / eerder', 'an-te-rjor-MEN-te', 'Anteriormente había trabajado en Lima.', 'Eerder had hij in Lima gewerkt.', 'avverbio'),
   ('para entonces', 'tegen die tijd', 'PA-ra en-TON-ses', 'Para entonces ya habíamos vendido la casa.', 'Tegen die tijd hadden we het huis al verkocht.', 'espressione'),
   ('darse cuenta de que', 'beseffen dat', 'DAR-se KWEN-ta de ke', 'Me di cuenta de que había olvidado las llaves.', 'Ik besefte dat ik de sleutels vergeten was.', 'espressione')]),
L(182, '📜', 'Pluscuamperfecto in verhalen', 'Volgorde van gebeurtenissen vertellen.',
  'Pluscuamperfecto in verhalen', 'Combineer indefinido (de gebeurtenis) met pluscuamperfecto (wat eraan voorafging): Perdió el tren porque se había dormido. Signaalwoorden: ya, todavía no, antes, nunca.',
  [('el relato', 'het verhaal / de vertelling', 'el re-LA-to', 'Es un relato corto.', 'Het is een kort verhaal.', 'sostantivo'),
   ('el manuscrito', 'het manuscript', 'el ma-noes-KRIE-to', 'Encontraron el manuscrito en un convento.', 'Ze vonden het manuscript in een klooster.', 'sostantivo'),
   ('transcurrir', 'verstrijken / zich afspelen', 'trans-koe-RRIER', 'La historia transcurre en Toledo.', 'Het verhaal speelt zich af in Toledo.', 'verbo'),
   ('la hazaña', 'de heldendaad', 'la a-SA-nja', 'Cuenta las hazañas de un caballero.', 'Het vertelt de heldendaden van een ridder.', 'sostantivo'),
   ('entretanto', 'ondertussen', 'en-tre-TAN-to', 'Entretanto, ella había llamado a la policía.', 'Ondertussen had zij de politie gebeld.', 'avverbio'),
   ('en aquel instante', 'op dat moment', 'en a-KEL ins-TAN-te', 'En aquel instante se apagó la luz.', 'Op dat moment ging het licht uit.', 'espressione'),
   ('resultar que', 'blijken dat', 're-soel-TAR ke', 'Resultó que ya lo había comprado.', 'Het bleek dat hij het al gekocht had.', 'espressione'),
   ('a fin de cuentas', 'per slot van rekening', 'a fin de KWEN-tas', 'A fin de cuentas, todo salió bien.', 'Per slot van rekening kwam alles goed.', 'espressione')]),
L(183, '🏛️', 'Spaanse geschiedenis', 'Van de Romeinen tot de Reconquista.',
  'Geschiedenis vertellen', 'Historische feiten in het indefinido: Los romanos llegaron en el siglo III a. C. Achtergrond in het imperfecto: La península estaba dividida en reinos. Eeuwen met Romeinse cijfers: el siglo XV.',
  [('la Edad Media', 'de middeleeuwen', 'la e-DAD ME-dja', 'En la Edad Media convivían tres culturas.', 'In de middeleeuwen leefden drie culturen samen.', 'storia'),
   ('el reino', 'het koninkrijk', 'el RREI-no', 'El reino de Castilla era poderoso.', 'Het koninkrijk Castilië was machtig.', 'storia'),
   ('la conquista', 'de verovering', 'la kon-KIS-ta', 'La conquista duró siglos.', 'De verovering duurde eeuwen.', 'storia'),
   ('el imperio', 'het rijk / imperium', 'el im-PE-rjo', 'El Imperio romano dominó la península.', 'Het Romeinse Rijk beheerste het schiereiland.', 'storia'),
   ('la batalla', 'de veldslag', 'la ba-TA-ja', 'La batalla fue decisiva.', 'De veldslag was beslissend.', 'storia'),
   ('invadir', 'binnenvallen', 'in-va-DIER', 'Los musulmanes invadieron la península en 711.', 'De moslims vielen het schiereiland binnen in 711.', 'verbo'),
   ('el antepasado', 'de voorouder', 'el an-te-pa-SA-do', 'Mis antepasados eran campesinos.', 'Mijn voorouders waren boeren.', 'storia'),
   ('el acuerdo de paz', 'het vredesverdrag', 'el a-KWER-do de pas', 'Firmaron un acuerdo de paz.', 'Ze tekenden een vredesverdrag.', 'storia')]),
L(184, '🎨', 'Kunst & architectuur', 'Gebouwen en kunstwerken beschrijven.',
  'Kunst beschrijven', 'Estilos: románico, gótico, barroco, modernista. La Alhambra fue construida por los nazaríes (passief met ser + participio, in herkenning).',
  [('la bóveda', 'het gewelf', 'la BO-ve-da', 'La bóveda es impresionante.', 'Het gewelf is indrukwekkend.', 'arte'),
   ('la mezquita', 'de moskee', 'la mes-KIE-ta', 'La mezquita de Córdoba es única.', 'De moskee van Córdoba is uniek.', 'arte'),
   ('el estilo', 'de stijl', 'el es-TIE-lo', '¿De qué estilo es este edificio?', 'In welke stijl is dit gebouw?', 'arte'),
   ('la fachada', 'de gevel', 'la fa-TSJA-da', 'La fachada está llena de esculturas.', 'De gevel zit vol beelden.', 'arte'),
   ('la torre', 'de toren', 'la TO-rre', 'La torre mide cien metros.', 'De toren is honderd meter hoog.', 'arte'),
   ('restaurar', 'restaureren', 'res-tau-RAR', 'Están restaurando el palacio.', 'Ze zijn het paleis aan het restaureren.', 'verbo'),
   ('el mosaico', 'het mozaïek', 'el mo-SAI-ko', 'Los mosaicos romanos están bien conservados.', 'De Romeinse mozaïeken zijn goed bewaard.', 'arte'),
   ('el mármol', 'het marmer', 'el MAR-mol', 'La estatua es de mármol.', 'Het standbeeld is van marmer.', 'arte')]),
L(185, '🌟', 'Beroemde Spanjaarden', 'Biografieën vertellen.',
  'Biografieën vertellen', 'Nació en 1881 en Málaga. Se trasladó a París. Murió en 1973. Levensloop in het indefinido; omstandigheden in het imperfecto: Era muy joven cuando pintó su primer cuadro.',
  [('nacer', 'geboren worden', 'na-SER', 'Picasso nació en Málaga.', 'Picasso werd geboren in Málaga.', 'verbo'),
   ('fallecer', 'overlijden', 'fa-je-SER', 'Falleció a los noventa y un años.', 'Hij overleed op eenennegentigjarige leeftijd.', 'verbo'),
   ('criarse', 'opgroeien', 'kri-AR-se', 'Se crió en un pueblo de Jaén.', 'Hij groeide op in een dorp bij Jaén.', 'verbo'),
   ('la biografía', 'de biografie', 'la bjo-gra-FIE-a', 'Leí su biografía.', 'Ik las zijn biografie.', 'sostantivo'),
   ('el genio', 'het genie', 'el CHE-njo', 'Era un genio de la pintura.', 'Hij was een geniaal schilder.', 'sostantivo'),
   ('destacar', 'uitblinken / benadrukken', 'des-ta-KAR', 'Destacó como poeta.', 'Hij blonk uit als dichter.', 'verbo'),
   ('la trayectoria', 'de loopbaan / het parcours', 'la tra-jek-TO-rja', 'Tuvo una trayectoria brillante.', 'Hij had een schitterende loopbaan.', 'sostantivo'),
   ('reconocido', 'erkend / gerenommeerd', 're-ko-no-SIE-do', 'Es un científico reconocido.', 'Hij is een gerenommeerd wetenschapper.', 'aggettivo')]),
L(186, '🖼️', 'El Siglo de Oro', 'De Gouden Eeuw van de Spaanse cultuur.',
  'Historische periodes beschrijven', 'Durante el Siglo de Oro (siglos XVI–XVII) florecieron la literatura y la pintura: Cervantes, Lope de Vega, Velázquez. Durante + periode; a lo largo de (in de loop van).',
  [('florecer', 'bloeien / tot bloei komen', 'flo-re-SER', 'Las artes florecieron en Sevilla.', 'De kunsten kwamen tot bloei in Sevilla.', 'verbo'),
   ('la literatura', 'de literatuur', 'la li-te-ra-TOE-ra', 'Estudia literatura española.', 'Ze studeert Spaanse literatuur.', 'arte'),
   ('el dramaturgo', 'de toneelschrijver', 'el dra-ma-TOER-go', 'Lope de Vega fue un dramaturgo prolífico.', 'Lope de Vega was een productief toneelschrijver.', 'arte'),
   ('la pintura', 'de schilderkunst', 'la pin-TOE-ra', 'La pintura barroca es dramática.', 'De barokke schilderkunst is dramatisch.', 'arte'),
   ('la corte', 'het hof', 'la KOR-te', 'La corte se instaló en Madrid.', 'Het hof vestigde zich in Madrid.', 'storia'),
   ('a lo largo de', 'in de loop van', 'a lo LAR-go de', 'A lo largo del siglo XVII, el imperio decayó.', 'In de loop van de zeventiende eeuw verviel het rijk.', 'espressione'),
   ('la decadencia', 'het verval', 'la de-ka-DEN-sja', 'Fue una época de decadencia.', 'Het was een tijd van verval.', 'storia'),
   ('el poeta', 'de dichter', 'el po-E-ta', 'Góngora fue un gran poeta.', 'Góngora was een groot dichter.', 'arte')]),
L(187, '📰', 'Moderne geschiedenis', 'De twintigste eeuw in Spanje.',
  'Moderne geschiedenis vertellen', 'La Guerra Civil (1936–1939), la dictadura, la Transición, la Constitución de 1978. Tras (na): Tras la muerte de Franco, España se convirtió en una democracia.',
  [('la guerra civil', 'de burgeroorlog', 'la GE-rra si-VIL', 'La guerra civil empezó en 1936.', 'De burgeroorlog begon in 1936.', 'storia'),
   ('la dictadura', 'de dictatuur', 'la dik-ta-DOE-ra', 'La dictadura duró casi cuarenta años.', 'De dictatuur duurde bijna veertig jaar.', 'storia'),
   ('la transición', 'de overgang (naar democratie)', 'la tran-si-SJON', 'La Transición fue un periodo clave.', 'De Transición was een sleutelperiode.', 'storia'),
   ('la constitución', 'de grondwet', 'la kons-ti-toe-SJON', 'La Constitución se aprobó en 1978.', 'De grondwet werd in 1978 aangenomen.', 'storia'),
   ('la democracia', 'de democratie', 'la de-mo-KRA-sja', 'España es una democracia desde 1978.', 'Spanje is sinds 1978 een democratie.', 'storia'),
   ('convertirse en', 'worden / veranderen in', 'kon-ver-TIER-se en', 'Se convirtió en una potencia turística.', 'Het werd een toeristische grootmacht.', 'verbo'),
   ('tras', 'na', 'tras', 'Tras la guerra, el país quedó arruinado.', 'Na de oorlog was het land geruïneerd.', 'espressione'),
   ('el exilio', 'de ballingschap', 'el ek-SIE-ljo', 'Muchos escritores vivieron en el exilio.', 'Veel schrijvers leefden in ballingschap.', 'storia')]),
L(188, '🎄', 'Tradities & feestdagen', 'Spaanse feesten door het jaar.',
  'Tradities beschrijven', 'Se celebra (men viert), se come, se regala: onpersoonlijk "se" voor gebruiken. Nochebuena, Nochevieja, los Reyes Magos, Semana Santa, San Juan.',
  [('la Nochebuena', 'kerstavond', 'la no-tsje-BWE-na', 'En Nochebuena cenamos en familia.', 'Op kerstavond eten we met de familie.', 'cultura'),
   ('las doce uvas', 'de twaalf druiven (oudjaar)', 'las DO-se OE-vas', 'Las doce uvas traen suerte.', 'De twaalf druiven brengen geluk.', 'cultura'),
   ('la cabalgata', 'de optocht (Drie Koningen)', 'la ka-bal-GA-ta', 'La cabalgata es el 5 de enero.', 'De optocht is op 5 januari.', 'cultura'),
   ('la verbena', 'het volksfeest / straatfeest', 'la ver-BE-na', 'Hay verbena en la plaza esta noche.', 'Er is vanavond een straatfeest op het plein.', 'cultura'),
   ('la procesión', 'de processie', 'la pro-se-SJON', 'La procesión sale a medianoche.', 'De processie vertrekt om middernacht.', 'cultura'),
   ('la hoguera', 'het vreugdevuur', 'la o-GE-ra', 'En San Juan se encienden hogueras.', 'Met San Juan steekt men vreugdevuren aan.', 'cultura'),
   ('el turrón', 'de turrón (noga)', 'el toe-RRON', 'En Navidad se come turrón.', 'Met kerst eet men turrón.', 'cultura'),
   ('celebrarse', 'gevierd worden', 'se-le-BRAR-se', 'La feria se celebra en abril.', 'De feria wordt in april gevierd.', 'verbo')]),
L(189, '🎵', 'Spaanse muziek', 'Van flamenco tot pop.',
  'Over muziek praten', 'El flamenco tiene tres elementos: el cante, el baile y el toque. Me pone la piel de gallina (ik krijg er kippenvel van). Tocar un instrumento, cantar, componer.',
  [('el cante', 'de (flamenco)zang', 'el KAN-te', 'El cante jondo es muy profundo.', 'De cante jondo is heel diep.', 'musica'),
   ('el baile', 'de dans', 'el BAI-le', 'El baile flamenco es intenso.', 'De flamencodans is intens.', 'musica'),
   ('la guitarra española', 'de Spaanse gitaar', 'la gi-TA-rra es-pa-NJO-la', 'Toca la guitarra española desde niño.', 'Hij speelt sinds zijn jeugd Spaanse gitaar.', 'musica'),
   ('componer', 'componeren', 'kom-po-NER', 'Compuso su primera canción a los quince.', 'Hij componeerde zijn eerste lied op zijn vijftiende.', 'verbo'),
   ('el compás', 'de maat (muziek)', 'el kom-PAS', 'El compás del flamenco es complejo.', 'De maat van flamenco is complex.', 'musica'),
   ('el acorde', 'het akkoord', 'el a-KOR-de', 'Solo conozco tres acordes.', 'Ik ken maar drie akkoorden.', 'musica'),
   ('la gira', 'de tournee', 'la CHIE-ra', 'El grupo está de gira por Europa.', 'De band is op tournee door Europa.', 'musica'),
   ('poner la piel de gallina', 'kippenvel bezorgen', 'po-NER la pjel de ga-JIE-na', 'Esa voz me pone la piel de gallina.', 'Die stem bezorgt me kippenvel.', 'espressione')]),
L(190, '📋', 'Toetsles B1 — Blok 7', 'Samenvatting van blok 7.',
  'Samenvatting Blok 7', 'Je kent het pluscuamperfecto en kunt geschiedenis, kunst en biografieën vertellen. In de toets: een leestekst en 20 woorden uit lessen 181–189.',
  [('el acontecimiento histórico', 'de historische gebeurtenis', 'el a-kon-te-si-MJEN-to is-TO-ri-ko', 'Fue un acontecimiento histórico.', 'Het was een historische gebeurtenis.', 'storia'),
   ('la herencia cultural', 'het culturele erfgoed', 'la e-REN-sja koel-toe-RAL', 'La herencia cultural árabe es visible en Andalucía.', 'Het Arabische culturele erfgoed is zichtbaar in Andalusië.', 'cultura'),
   ('la influencia', 'de invloed', 'la in-floe-EN-sja', 'La influencia árabe se nota en la lengua.', 'De Arabische invloed is merkbaar in de taal.', 'sostantivo'),
   ('legendario', 'legendarisch', 'le-chen-DA-rjo', 'Es una figura legendaria.', 'Het is een legendarische figuur.', 'aggettivo'),
   ('conmemorar', 'herdenken', 'kon-me-mo-RAR', 'Conmemoran la fecha cada año.', 'Ze herdenken de datum elk jaar.', 'verbo'),
   ('el monumento', 'het monument', 'el mo-noe-MEN-to', 'El monumento está en la plaza.', 'Het monument staat op het plein.', 'arte'),
   ('el ciudadano', 'de burger', 'el sjoe-da-DA-no', 'Los ciudadanos votaron en masa.', 'De burgers stemden massaal.', 'storia'),
   ('la libertad', 'de vrijheid', 'la li-ber-TAD', 'La libertad de expresión es un derecho.', 'Vrijheid van meningsuiting is een recht.', 'sostantivo')]),
L(191, '💭', 'Condicional compuesto — vorming', 'Wat je gedaan zou hebben.',
  'Condicional compuesto', 'Habría + participio: habría ido (ik zou zijn gegaan), habrías dicho, habríamos comprado. Gebruik: irreële gevolgen in het verleden en vermoedens over het verleden.',
  [('habría ido', 'ik zou zijn gegaan', 'a-BRIE-a IE-do', 'Yo habría ido a la fiesta.', 'Ik zou naar het feest zijn gegaan.', 'espressione'),
   ('habría dicho', 'ik zou hebben gezegd', 'a-BRIE-a DIE-tsjo', 'Yo no habría dicho eso.', 'Ik zou dat niet hebben gezegd.', 'espressione'),
   ('habría sido', 'het zou zijn geweest', 'a-BRIE-a SIE-do', 'Habría sido más fácil en tren.', 'Het zou makkelijker zijn geweest met de trein.', 'espressione'),
   ('habría hecho', 'ik zou hebben gedaan', 'a-BRIE-a E-tsjo', '¿Qué habrías hecho tú?', 'Wat zou jij hebben gedaan?', 'espressione'),
   ('habría podido', 'ik had gekund', 'a-BRIE-a po-DIE-do', 'Habría podido ayudarte.', 'Ik had je kunnen helpen.', 'espressione'),
   ('de no ser por', 'als het niet was voor / zonder', 'de no ser por', 'De no ser por ti, habría perdido el tren.', 'Zonder jou had ik de trein gemist.', 'espressione'),
   ('de haberlo sabido', 'als ik het geweten had', 'de a-BER-lo sa-BIE-do', 'De haberlo sabido, habría venido antes.', 'Als ik het geweten had, was ik eerder gekomen.', 'espressione'),
   ('seguramente', 'waarschijnlijk / vast', 'se-goe-ra-MEN-te', 'Seguramente habría llegado tarde.', 'Hij zou vast te laat zijn gekomen.', 'avverbio')]),
L(192, '😔', 'Spijt uitdrukken', 'Terugkijken op wat anders had gekund.',
  'Spijt met condicional compuesto', 'Debería haber + participio (ik had moeten): Debería haber estudiado más. Tendría que haber llamado. Arrepentirse de (spijt hebben van).',
  [('arrepentirse de', 'spijt hebben van', 'a-rre-pen-TIER-se de', 'Me arrepiento de no haber viajado más.', 'Ik heb er spijt van dat ik niet meer gereisd heb.', 'verbo'),
   ('debería haber', 'ik had moeten', 'de-be-RIE-a a-BER', 'Debería haber estudiado más.', 'Ik had meer moeten studeren.', 'espressione'),
   ('el arrepentimiento', 'de spijt / het berouw', 'el a-rre-pen-ti-MJEN-to', 'Siente un profundo arrepentimiento.', 'Hij voelt diep berouw.', 'emozione'),
   ('reprocharse', 'zichzelf verwijten', 'rre-pro-TSJAR-se', 'Se reprocha no haber llamado.', 'Hij verwijt zichzelf dat hij niet gebeld heeft.', 'verbo'),
   ('el remordimiento', 'het schuldgevoel / de wroeging', 'el rre-mor-di-MJEN-to', 'Tiene remordimientos por lo que hizo.', 'Hij heeft wroeging over wat hij deed.', 'emozione'),
   ('perdonarse', 'zichzelf vergeven', 'per-do-NAR-se', 'No consigue perdonarse.', 'Hij kan zichzelf niet vergeven.', 'verbo'),
   ('de otro modo', 'anders / op een andere manier', 'de O-tro MO-do', 'Lo habría hecho de otro modo.', 'Ik zou het anders hebben gedaan.', 'espressione'),
   ('ya es tarde', 'het is al te laat', 'ja es TAR-de', 'Ya es tarde para cambiarlo.', 'Het is al te laat om het te veranderen.', 'espressione')]),
L(193, '🌠', 'Wensen in het verleden', 'Wat je graag anders had gezien.',
  'Wensen met ojalá + pluscuamperfecto de subjuntivo', 'Ojalá hubiera + participio (had ik maar): Ojalá hubiera estudiado medicina. Me habría gustado + infinitivo (ik had graag willen): Me habría gustado conocerla.',
  [('ojalá hubiera', 'had ik maar', 'o-cha-LA oe-BJE-ra', 'Ojalá hubiera aprendido español antes.', 'Had ik maar eerder Spaans geleerd.', 'espressione'),
   ('me habría gustado', 'ik had graag gewild', 'me a-BRIE-a goes-TA-do', 'Me habría gustado ser músico.', 'Ik was graag muzikant geworden.', 'espressione'),
   ('el anhelo', 'het verlangen', 'el a-NE-lo', 'Su mayor anhelo era volver a casa.', 'Zijn grootste verlangen was naar huis terug te gaan.', 'emozione'),
   ('añorar', 'verlangen naar / missen', 'a-njo-RAR', 'Añoro los veranos de mi infancia.', 'Ik verlang terug naar de zomers van mijn jeugd.', 'verbo'),
   ('la oportunidad perdida', 'de gemiste kans', 'la o-por-toe-ni-DAD per-DIE-da', 'Fue una oportunidad perdida.', 'Het was een gemiste kans.', 'sostantivo'),
   ('la nostalgia', 'de nostalgie / het heimwee', 'la nos-TAL-cha', 'Siento nostalgia de mi infancia.', 'Ik voel nostalgie naar mijn jeugd.', 'emozione'),
   ('echar la vista atrás', 'terugkijken', 'e-TSJAR la VIS-ta a-TRAS', 'Al echar la vista atrás, no cambiaría nada.', 'Als ik terugkijk, zou ik niets veranderen.', 'espressione'),
   ('irrealizable', 'onhaalbaar', 'i-rre-a-li-SA-ble', 'Era un sueño irrealizable.', 'Het was een onhaalbare droom.', 'aggettivo')]),
L(194, '🏦', 'Financiën & bankzaken', 'Bij de bank.',
  'Bankzaken regelen', 'Abrir una cuenta, sacar dinero del cajero, hacer una transferencia, pedir un préstamo. La comisión (de kosten), el saldo (het saldo), el tipo de interés (de rente).',
  [('la cuenta bancaria', 'de bankrekening', 'la KWEN-ta ban-KA-rja', 'Quiero abrir una cuenta bancaria.', 'Ik wil een bankrekening openen.', 'finanza'),
   ('el saldo', 'het saldo', 'el SAL-do', 'Consulta el saldo en la app.', 'Bekijk het saldo in de app.', 'finanza'),
   ('domiciliar', 'automatisch laten afschrijven', 'do-mi-si-LJAR', 'He domiciliado el recibo de la luz.', 'Ik laat de elektriciteitsrekening automatisch afschrijven.', 'verbo'),
   ('el préstamo', 'de lening', 'el PRES-ta-mo', 'Pidieron un préstamo al banco.', 'Ze vroegen een lening aan bij de bank.', 'finanza'),
   ('la hipoteca', 'de hypotheek', 'la i-po-TE-ka', 'La hipoteca es a treinta años.', 'De hypotheek loopt dertig jaar.', 'finanza'),
   ('el tipo de interés', 'de rente(voet)', 'el TIE-po de in-te-RES', 'El tipo de interés ha subido.', 'De rente is gestegen.', 'finanza'),
   ('la comisión', 'de (bank)kosten / commissie', 'la ko-mi-SJON', 'El banco cobra una comisión.', 'De bank rekent kosten.', 'finanza'),
   ('retirar', 'opnemen (geld)', 'rre-ti-RAR', 'Retiré doscientos euros.', 'Ik nam tweehonderd euro op.', 'verbo')]),
L(195, '💶', 'Economie & geld', 'Over economie praten.',
  'Over economie praten', 'La inflación sube, los precios bajan, el paro aumenta. Woordvorming: crecer → el crecimiento, invertir → la inversión, ahorrar → el ahorro.',
  [('el desempleo', 'de werkloosheid', 'el de-sem-PLE-o', 'El desempleo juvenil es alto.', 'De jeugdwerkloosheid is hoog.', 'finanza'),
   ('el crecimiento', 'de groei', 'el kre-si-MJEN-to', 'El crecimiento económico se ha frenado.', 'De economische groei is afgeremd.', 'finanza'),
   ('la inversión', 'de investering', 'la in-ver-SJON', 'Es una buena inversión.', 'Het is een goede investering.', 'finanza'),
   ('la riqueza', 'de rijkdom / welvaart', 'la rri-KE-sa', 'La riqueza está mal repartida.', 'De rijkdom is slecht verdeeld.', 'finanza'),
   ('la deuda', 'de schuld', 'la DEU-da', 'La deuda pública ha crecido.', 'De staatsschuld is gegroeid.', 'finanza'),
   ('el déficit', 'het tekort', 'el DE-fi-sit', 'El déficit público ha aumentado.', 'Het begrotingstekort is toegenomen.', 'finanza'),
   ('la crisis económica', 'de economische crisis', 'la KRI-sis e-ko-NO-mi-ka', 'La crisis económica duró años.', 'De economische crisis duurde jaren.', 'finanza'),
   ('el poder adquisitivo', 'de koopkracht', 'el po-DER ad-ki-si-TIE-vo', 'El poder adquisitivo ha bajado.', 'De koopkracht is gedaald.', 'finanza')]),
L(196, '📄', 'Belastingen & administratie', 'Formulieren en loketten.',
  'Administratieve taal', 'Rellenar un formulario, presentar la declaración de la renta, pedir cita previa, el DNI, el NIE (buitenlandersnummer), el empadronamiento (inschrijving bij de gemeente).',
  [('la declaración de la renta', 'de belastingaangifte', 'la de-kla-ra-SJON de la RREN-ta', 'Hay que presentar la declaración de la renta en junio.', 'De belastingaangifte moet in juni ingediend worden.', 'burocrazia'),
   ('el impuesto', 'de belasting', 'el im-PWES-to', 'Los impuestos han subido.', 'De belastingen zijn gestegen.', 'burocrazia'),
   ('el formulario', 'het formulier', 'el for-moe-LA-rjo', 'Rellene el formulario, por favor.', 'Vul het formulier in, alstublieft.', 'burocrazia'),
   ('la cita previa', 'de afspraak (vooraf)', 'la SIE-ta PRE-vja', 'Necesitas cita previa.', 'Je hebt een afspraak nodig.', 'burocrazia'),
   ('el empadronamiento', 'de inschrijving bij de gemeente', 'el em-pa-dro-na-MJEN-to', 'El empadronamiento es obligatorio.', 'Inschrijving bij de gemeente is verplicht.', 'burocrazia'),
   ('el trámite', 'de (administratieve) procedure', 'el TRA-mi-te', 'Es un trámite sencillo.', 'Het is een eenvoudige procedure.', 'burocrazia'),
   ('el justificante', 'het bewijs(stuk)', 'el choes-ti-fi-KAN-te', 'Guarda el justificante de pago.', 'Bewaar het betalingsbewijs.', 'burocrazia'),
   ('la Seguridad Social', 'de sociale zekerheid', 'la se-goe-ri-DAD so-SJAL', 'Está dado de alta en la Seguridad Social.', 'Hij staat ingeschreven bij de sociale zekerheid.', 'burocrazia')]),
L(197, '🏠', 'Wonen & huren', 'Een woning zoeken.',
  'Een woning zoeken', 'Piso en alquiler, se vende, el casero (de huisbaas), el inquilino (de huurder), la fianza (de borg), gastos incluidos (inclusief kosten).',
  [('el inquilino', 'de huurder', 'el in-ki-LIE-no', 'El inquilino paga el primer día del mes.', 'De huurder betaalt op de eerste van de maand.', 'casa'),
   ('el casero', 'de huisbaas', 'el ka-SE-ro', 'El casero vive en el piso de arriba.', 'De huisbaas woont boven.', 'casa'),
   ('el aval', 'de borgstelling / garantsteller', 'el a-VAL', 'El banco pide un aval.', 'De bank vraagt een borgstelling.', 'casa'),
   ('la cláusula', 'de clausule', 'la KLAU-soe-la', 'Lee bien cada cláusula.', 'Lees elke clausule goed.', 'casa'),
   ('reformado', 'gerenoveerd', 'rre-for-MA-do', 'El piso está recién reformado.', 'Het appartement is net gerenoveerd.', 'aggettivo'),
   ('gastos incluidos', 'inclusief kosten', 'GAS-tos in-kloe-IE-dos', 'Son 800 euros, gastos incluidos.', 'Het is 800 euro, inclusief kosten.', 'espressione'),
   ('la inmobiliaria', 'het makelaarskantoor', 'la in-mo-bi-LJA-rja', 'La inmobiliaria cobra una comisión.', 'De makelaar rekent commissie.', 'casa'),
   ('la comunidad de vecinos', 'de vereniging van eigenaren', 'la ko-moe-ni-DAD de ve-SIE-nos', 'La comunidad de vecinos se reúne el lunes.', 'De VvE vergadert maandag.', 'casa')]),
L(198, '📦', 'Verhuizen', 'Een verhuizing beschrijven.',
  'Verhuizen beschrijven', 'Hacer la mudanza, embalar (inpakken), desembalar, la furgoneta, el trastero (de berging). Nos mudamos la semana que viene.',
  [('la mudanza', 'de verhuizing', 'la moe-DAN-sa', 'La mudanza es el sábado.', 'De verhuizing is zaterdag.', 'casa'),
   ('desembalar', 'uitpakken', 'de-sem-ba-LAR', 'Todavía no hemos desembalado todo.', 'We hebben nog niet alles uitgepakt.', 'verbo'),
   ('embalar', 'inpakken', 'em-ba-LAR', 'Embalé los libros en cajas.', 'Ik pakte de boeken in dozen.', 'verbo'),
   ('la caja de cartón', 'de kartonnen doos', 'la KA-cha de kar-TON', 'Necesitamos más cajas de cartón.', 'We hebben meer kartonnen dozen nodig.', 'casa'),
   ('la furgoneta', 'het busje', 'la foer-go-NE-ta', 'Alquilamos una furgoneta.', 'We huurden een busje.', 'trasporto'),
   ('el trastero', 'de berging / rommelkamer', 'el tras-TE-ro', 'Lo guardo en el trastero.', 'Ik bewaar het in de berging.', 'casa'),
   ('frágil', 'breekbaar', 'FRA-chil', 'Cuidado, es frágil.', 'Voorzichtig, het is breekbaar.', 'aggettivo'),
   ('instalarse', 'zich vestigen / installeren', 'ins-ta-LAR-se', 'Ya nos hemos instalado.', 'We zijn al geïnstalleerd.', 'verbo')]),
L(199, '🏘️', 'Buurt & omgeving', 'Je buurt beschrijven.',
  'Je buurt beschrijven', 'El barrio es tranquilo / animado / céntrico. Está bien comunicado (goed bereikbaar). A dos pasos de (op een steenworp van). Los vecinos son majos.',
  [('el barrio', 'de wijk / buurt', 'el BA-rrjo', 'Vivo en un barrio tranquilo.', 'Ik woon in een rustige wijk.', 'casa'),
   ('céntrico', 'centraal gelegen', 'SEN-tri-ko', 'Es un piso muy céntrico.', 'Het is een heel centraal gelegen appartement.', 'aggettivo'),
   ('bien comunicado', 'goed bereikbaar (OV)', 'bjen ko-moe-ni-KA-do', 'El barrio está bien comunicado.', 'De wijk is goed bereikbaar.', 'espressione'),
   ('a dos pasos de', 'op een steenworp van', 'a dos PA-sos de', 'Está a dos pasos del metro.', 'Het is op een steenworp van de metro.', 'espressione'),
   ('las afueras', 'de buitenwijken / rand van de stad', 'las a-FWE-ras', 'Viven en las afueras.', 'Ze wonen aan de rand van de stad.', 'casa'),
   ('la zona peatonal', 'het voetgangersgebied', 'la SO-na pe-a-to-NAL', 'El centro es zona peatonal.', 'Het centrum is voetgangersgebied.', 'casa'),
   ('animado', 'levendig', 'a-ni-MA-do', 'Es un barrio muy animado.', 'Het is een heel levendige buurt.', 'aggettivo'),
   ('el vecindario', 'de buurtbewoners / de buurt', 'el ve-sin-DA-rjo', 'El vecindario organizó una fiesta.', 'De buurt organiseerde een feest.', 'casa')]),
L(200, '📋', 'Toetsles B1 — Blok 8', 'Samenvatting van blok 8.',
  'Samenvatting Blok 8', 'Je kent de condicional compuesto, kunt spijt en wensen uitdrukken en bank-, woon- en administratieve zaken regelen. In de toets: een leestekst en 20 woorden uit lessen 191–199.',
  [('la tarifa', 'het tarief', 'la ta-RIE-fa', 'La tarifa de la luz ha cambiado.', 'Het elektriciteitstarief is veranderd.', 'finanza'),
   ('la cuota', 'de termijn / bijdrage', 'la KWO-ta', 'Pago una cuota mensual.', 'Ik betaal een maandelijkse bijdrage.', 'finanza'),
   ('el gasto', 'de uitgave', 'el GAS-to', 'Tenemos muchos gastos este mes.', 'We hebben deze maand veel uitgaven.', 'finanza'),
   ('el ingreso', 'het inkomen / de inkomsten', 'el in-GRE-so', 'Sus ingresos son modestos.', 'Zijn inkomen is bescheiden.', 'finanza'),
   ('a plazos', 'in termijnen', 'a PLA-sos', 'Lo pagué a plazos.', 'Ik betaalde het in termijnen.', 'espressione'),
   ('el reembolso', 'de terugbetaling', 'el rre-em-BOL-so', 'Pedí el reembolso del billete.', 'Ik vroeg terugbetaling van het ticket.', 'finanza'),
   ('la vivienda', 'de woning', 'la vi-VJEN-da', 'El precio de la vivienda ha subido.', 'De woningprijzen zijn gestegen.', 'casa'),
   ('la escritura', 'de (eigendoms)akte', 'la es-kri-TOE-ra', 'Firmamos la escritura ante notario.', 'We tekenden de akte bij de notaris.', 'casa')]),
L(201, '🧠', 'Imperfecto de subjuntivo — vorming', 'De verleden tijd van de subjuntivo.',
  'Imperfecto de subjuntivo', 'Vorming: indefinido ellos (hablaron) → stam hablar- + -ra: hablara, hablaras, hablara, habláramos, hablarais, hablaran. Ook -se is mogelijk (hablase). Gebruik na verleden hoofdzin: Quería que vinieras.',
  [('quería que vinieras', 'ik wilde dat je kwam', 'ke-RIE-a ke vi-NJE-ras', 'Quería que vinieras a la cena.', 'Ik wilde dat je naar het etentje kwam.', 'espressione'),
   ('me pidió que', 'hij vroeg me om', 'me pi-DJO ke', 'Me pidió que le ayudara.', 'Hij vroeg me om hem te helpen.', 'espressione'),
   ('era necesario que', 'het was nodig dat', 'E-ra ne-se-SA-rjo ke', 'Era necesario que firmaras.', 'Het was nodig dat je tekende.', 'espressione'),
   ('no creía que', 'ik dacht niet dat', 'no kre-IE-a ke', 'No creía que fuera tan difícil.', 'Ik dacht niet dat het zo moeilijk was.', 'espressione'),
   ('como si', 'alsof', 'KO-mo si', 'Habla como si lo supiera todo.', 'Hij praat alsof hij alles weet.', 'espressione'),
   ('a fin de que', 'opdat / met als doel dat', 'a fin de ke', 'Te lo expliqué a fin de que lo entendieras.', 'Ik legde het je uit opdat je het zou begrijpen.', 'espressione'),
   ('sin que', 'zonder dat', 'sin ke', 'Salió sin que nadie lo viera.', 'Hij vertrok zonder dat iemand hem zag.', 'espressione'),
   ('de modo que', 'zodat (gevolg)', 'de MO-do ke', 'Lo organizó de modo que todos pudieran venir.', 'Hij regelde het zo dat iedereen kon komen.', 'espressione')]),
L(202, '🧠', 'Imperfecto de subjuntivo — onregelmatig', 'De onregelmatige stammen.',
  'Onregelmatige imperfecto de subjuntivo', 'Van de onregelmatige indefinido: tener → tuvieron → tuviera; estar → estuviera; poder → pudiera; decir → dijera; traer → trajera; ir/ser → fuera; haber → hubiera; hacer → hiciera.',
  [('aunque fuera', 'ook al was het', 'AUN-ke FWE-ra', 'Iría aunque fuera caro.', 'Ik zou gaan, ook al was het duur.', 'espressione'),
   ('si hubiera sabido', 'als ik had geweten', 'si oe-BJE-ra sa-BIE-do', 'Si hubiera sabido, no habría venido.', 'Als ik het had geweten, was ik niet gekomen.', 'espressione'),
   ('que dijera', 'dat hij zou zeggen', 'ke di-CHE-ra', 'Le pedí que dijera la verdad.', 'Ik vroeg hem de waarheid te zeggen.', 'espressione'),
   ('que trajera', 'dat hij zou meebrengen', 'ke tra-CHE-ra', 'Le dije que trajera vino.', 'Ik zei hem wijn mee te brengen.', 'espressione'),
   ('que pusiera', 'dat hij zou zetten/leggen', 'ke poe-SJE-ra', 'Le pedí que pusiera la mesa.', 'Ik vroeg hem de tafel te dekken.', 'espressione'),
   ('que anduviera', 'dat hij zou lopen', 'ke an-doe-VJE-ra', 'El médico le recomendó que anduviera más.', 'De dokter raadde hem aan meer te lopen.', 'espressione'),
   ('que cupiera', 'dat het zou passen', 'ke koe-PJE-ra', 'No creía que cupiera todo en la maleta.', 'Ik dacht niet dat alles in de koffer zou passen.', 'espressione'),
   ('que condujera', 'dat hij zou rijden', 'ke kon-doe-CHE-ra', 'Prefería que condujera él.', 'Ik had liever dat hij reed.', 'espressione')]),
L(203, '🤔', 'Twijfel & onzekerheid', 'Twijfel uitdrukken.',
  'Twijfel uitdrukken', 'Dudo que + subjuntivo. No estoy seguro de que + subjuntivo. Quizás / tal vez / puede que + subjuntivo. A lo mejor + indicativo (uitzondering!).',
  [('dudar de que', 'betwijfelen dat', 'doe-DAR de ke', 'Dudo de que venga.', 'Ik betwijfel of hij komt.', 'espressione'),
   ('puede que', 'misschien / het kan zijn dat', 'PWE-de ke', 'Puede que llueva mañana.', 'Misschien regent het morgen.', 'espressione'),
   ('a lo mejor', 'misschien (+ indicatief)', 'a lo me-CHOR', 'A lo mejor voy al cine.', 'Misschien ga ik naar de bioscoop.', 'espressione'),
   ('no estoy seguro de que', 'ik weet niet zeker of', 'no es-TOI se-GOE-ro de ke', 'No estoy seguro de que sea verdad.', 'Ik weet niet zeker of het waar is.', 'espressione'),
   ('la incertidumbre', 'de onzekerheid', 'la in-ser-ti-DOEM-bre', 'Vivimos tiempos de incertidumbre.', 'We leven in onzekere tijden.', 'emozione'),
   ('vacilar', 'aarzelen', 'va-si-LAR', 'Vaciló antes de responder.', 'Hij aarzelde voordat hij antwoordde.', 'verbo'),
   ('dudoso', 'twijfelachtig', 'doe-DO-so', 'Es una afirmación dudosa.', 'Het is een twijfelachtige bewering.', 'aggettivo'),
   ('quién sabe', 'wie weet', 'kjen SA-be', 'Quién sabe si volveremos.', 'Wie weet of we terugkomen.', 'espressione')]),
L(204, '💬', 'Meningen nuanceren', 'Genuanceerd je mening geven.',
  'Meningen nuanceren', 'Hasta cierto punto (tot op zekere hoogte), en parte, no del todo (niet helemaal), depende de, por un lado… por otro (enerzijds… anderzijds), no cabe duda de que (het lijdt geen twijfel dat).',
  [('hasta cierto punto', 'tot op zekere hoogte', 'AS-ta SJER-to POEN-to', 'Tienes razón hasta cierto punto.', 'Je hebt tot op zekere hoogte gelijk.', 'espressione'),
   ('no del todo', 'niet helemaal', 'no del TO-do', 'No estoy del todo de acuerdo.', 'Ik ben het er niet helemaal mee eens.', 'espressione'),
   ('por un lado… por otro', 'enerzijds… anderzijds', 'por oen LA-do por O-tro', 'Por un lado es caro, por otro es bueno.', 'Enerzijds is het duur, anderzijds is het goed.', 'espressione'),
   ('no cabe duda de que', 'het lijdt geen twijfel dat', 'no KA-be DOE-da de ke', 'No cabe duda de que es talentoso.', 'Het lijdt geen twijfel dat hij getalenteerd is.', 'espressione'),
   ('matizar', 'nuanceren', 'ma-ti-SAR', 'Quisiera matizar lo que he dicho.', 'Ik zou willen nuanceren wat ik heb gezegd.', 'verbo'),
   ('el matiz', 'de nuance', 'el ma-TIS', 'Hay un matiz importante.', 'Er is een belangrijke nuance.', 'sostantivo'),
   ('discutible', 'discutabel / betwistbaar', 'dis-koe-TIE-ble', 'Es una decisión discutible.', 'Het is een betwistbare beslissing.', 'aggettivo'),
   ('en cierto modo', 'in zekere zin', 'en SJER-to MO-do', 'En cierto modo, tiene razón.', 'In zekere zin heeft hij gelijk.', 'espressione')]),
L(205, '📚', 'Onderwijs & studie', 'Over onderwijs praten.',
  'Over onderwijs praten', 'La educación primaria, secundaria, el bachillerato, la formación profesional. Aprobar (slagen), suspender (zakken), repetir curso (blijven zitten), sacar buenas notas.',
  [('el temario', 'de leerstof / het programma', 'el te-MA-rjo', 'El temario es muy amplio.', 'De leerstof is heel uitgebreid.', 'scuola'),
   ('la escuela secundaria', 'de middelbare school', 'la es-KWE-la se-koen-DA-rja', 'Fue a la escuela secundaria en Murcia.', 'Hij ging naar de middelbare school in Murcia.', 'scuola'),
   ('la formación profesional', 'het beroepsonderwijs', 'la for-ma-SJON pro-fe-sjo-NAL', 'Hizo formación profesional de cocina.', 'Hij deed een koksopleiding.', 'scuola'),
   ('cursar', 'volgen (een opleiding)', 'koer-SAR', 'Cursa segundo de bachillerato.', 'Hij zit in het tweede jaar van de bovenbouw.', 'verbo'),
   ('el recreo', 'de pauze (school)', 'el rre-KRE-o', 'En el recreo jugábamos al fútbol.', 'In de pauze voetbalden we.', 'scuola'),
   ('repetir curso', 'blijven zitten', 're-pe-TIER KOER-so', 'Tuvo que repetir curso.', 'Hij moest blijven zitten.', 'espressione'),
   ('sacar buenas notas', 'goede cijfers halen', 'sa-KAR BWE-nas NO-tas', 'Siempre sacaba buenas notas.', 'Ze haalde altijd goede cijfers.', 'espressione'),
   ('el profesorado', 'het docententeam', 'el pro-fe-so-RA-do', 'El profesorado está en huelga.', 'De docenten staken.', 'scuola')]),
L(206, '🎓', 'Universiteit & wetenschap', 'Universitaire taal.',
  'Universitaire taal', 'La carrera (de studie), el grado, el máster, el doctorado, la beca (de beurs), la matrícula (de inschrijving), la facultad, el catedrático (de hoogleraar).',
  [('la carrera universitaria', 'de universitaire studie', 'la ka-RRE-ra oe-ni-ver-si-TA-rja', 'Estudió la carrera en Salamanca.', 'Ze deed haar studie in Salamanca.', 'scuola'),
   ('la licenciatura', 'de universitaire graad (bachelor/master)', 'la li-sen-sja-TOE-ra', 'Tiene una licenciatura en Derecho.', 'Hij heeft een rechtengraad.', 'scuola'),
   ('la matrícula', 'de inschrijving / het collegegeld', 'la ma-TRIE-koe-la', 'La matrícula cuesta mil euros.', 'Het collegegeld kost duizend euro.', 'scuola'),
   ('la facultad', 'de faculteit', 'la fa-koel-TAD', 'La facultad de Medicina está lejos.', 'De medische faculteit is ver weg.', 'scuola'),
   ('el catedrático', 'de hoogleraar', 'el ka-te-DRA-ti-ko', 'Es catedrático de Filosofía.', 'Hij is hoogleraar filosofie.', 'scuola'),
   ('el doctorado', 'het doctoraat / promotieonderzoek', 'el dok-to-RA-do', 'Está haciendo el doctorado.', 'Ze doet promotieonderzoek.', 'scuola'),
   ('el laboratorio', 'het laboratorium', 'el la-bo-ra-TO-rjo', 'Pasa horas en el laboratorio.', 'Ze brengt uren door in het laboratorium.', 'scuola'),
   ('la tesis', 'de scriptie / het proefschrift', 'la TE-sis', 'Defendió la tesis en junio.', 'Hij verdedigde zijn proefschrift in juni.', 'scuola')]),
L(207, '📖', 'Lezen & schrijven', 'Over teksten praten.',
  'Over lezen en schrijven praten', 'Redactar (opstellen), el borrador (de kladversie), corregir, el párrafo, la ortografía, el ensayo. Leer entre líneas (tussen de regels lezen).',
  [('redactar', 'opstellen / schrijven (tekst)', 'rre-dak-TAR', 'Redactó un informe de diez páginas.', 'Hij schreef een rapport van tien pagina\'s.', 'verbo'),
   ('el borrador', 'de kladversie', 'el bo-rra-DOR', 'Es solo un borrador.', 'Het is maar een kladversie.', 'sostantivo'),
   ('el párrafo', 'de alinea', 'el PA-rra-fo', 'Lee el primer párrafo.', 'Lees de eerste alinea.', 'sostantivo'),
   ('la ortografía', 'de spelling', 'la or-to-gra-FIE-a', 'Tiene faltas de ortografía.', 'Er zitten spelfouten in.', 'sostantivo'),
   ('el ensayo', 'het essay', 'el en-SA-jo', 'Escribió un ensayo sobre la libertad.', 'Hij schreef een essay over vrijheid.', 'sostantivo'),
   ('leer entre líneas', 'tussen de regels lezen', 'le-ER EN-tre LIE-ne-as', 'Hay que leer entre líneas.', 'Je moet tussen de regels lezen.', 'espressione'),
   ('el resumen', 'de samenvatting', 'el rre-SOE-men', 'Haz un resumen del texto.', 'Maak een samenvatting van de tekst.', 'sostantivo'),
   ('la nota a pie de página', 'de voetnoot', 'la NO-ta a pje de PA-chi-na', 'Añade una nota a pie de página.', 'Voeg een voetnoot toe.', 'sostantivo')]),
L(208, '📝', 'Examen & beoordeling', 'Examens bespreken.',
  'Examens bespreken', 'Presentarse a un examen, el examen oral/escrito, la convocatoria (de examenronde), la recuperación (het herexamen), estar nervioso, quedarse en blanco (een black-out hebben).',
  [('presentarse a un examen', 'examen doen', 'pre-sen-TAR-se a oen ek-SA-men', 'Me presento al examen en mayo.', 'Ik doe examen in mei.', 'espressione'),
   ('la convocatoria', 'de examenronde / oproep', 'la kon-vo-ka-TO-rja', 'Hay dos convocatorias al año.', 'Er zijn twee examenrondes per jaar.', 'scuola'),
   ('la recuperación', 'het herexamen', 'la rre-koe-pe-ra-SJON', 'Tiene la recuperación en septiembre.', 'Hij heeft het herexamen in september.', 'scuola'),
   ('quedarse en blanco', 'een black-out hebben', 'ke-DAR-se en BLAN-ko', 'Me quedé en blanco en el oral.', 'Ik had een black-out bij het mondeling.', 'espressione'),
   ('el sobresaliente', 'het hoogste cijfer (9–10)', 'el so-bre-sa-LJEN-te', 'Sacó un sobresaliente.', 'Hij haalde een tien.', 'scuola'),
   ('el tribunal', 'de examencommissie', 'el tri-boe-NAL', 'El tribunal fue muy exigente.', 'De examencommissie was heel veeleisend.', 'scuola'),
   ('el cuestionario', 'de vragenlijst', 'el kwes-tjo-NA-rjo', 'Rellena el cuestionario.', 'Vul de vragenlijst in.', 'scuola'),
   ('la calificación', 'de beoordeling / het cijfer', 'la ka-li-fi-ka-SJON', 'Las calificaciones salen el viernes.', 'De cijfers komen vrijdag.', 'scuola')]),
L(209, '✍️', 'Taalgebruik & stijl', 'Registers in het Spaans.',
  'Registers in het Spaans', 'Coloquial (spreektaal), culto (verzorgd), vulgar, técnico. Spreektaal: mola (is gaaf), tío/tía (joh), vale (oké). Formeel: le ruego (ik verzoek u), atentamente.',
  [('coloquial', 'informeel / spreektaal-', 'ko-lo-KJAL', 'Es una expresión coloquial.', 'Het is een uitdrukking uit de spreektaal.', 'aggettivo'),
   ('culto', 'verzorgd / ontwikkeld', 'KOEL-to', 'Usa un lenguaje culto.', 'Hij gebruikt verzorgd taalgebruik.', 'aggettivo'),
   ('molar', 'gaaf zijn (spreektaal)', 'mo-LAR', 'Esa canción mola mucho.', 'Dat nummer is echt gaaf.', 'verbo'),
   ('chaval', 'jongen / knul (spreektaal)', 'tsja-VAL', 'Ese chaval es muy listo.', 'Die knul is heel slim.', 'sostantivo'),
   ('le ruego', 'ik verzoek u', 'le RRWE-go', 'Le ruego que me disculpe.', 'Ik verzoek u mij te verontschuldigen.', 'espressione'),
   ('atentamente', 'hoogachtend', 'a-ten-ta-MEN-te', 'Atentamente, Juan Pérez.', 'Hoogachtend, Juan Pérez.', 'avverbio'),
   ('el refrán', 'het spreekwoord', 'el rre-FRAN', 'Hay un refrán para todo.', 'Er is voor alles een spreekwoord.', 'sostantivo'),
   ('la jerga', 'het jargon / de slang', 'la CHER-ga', 'No entiendo la jerga de los jóvenes.', 'Ik begrijp de jongerentaal niet.', 'sostantivo')]),
L(210, '📋', 'Toetsles B1 — Blok 9', 'Samenvatting van blok 9.',
  'Samenvatting Blok 9', 'Je kent het imperfecto de subjuntivo, kunt twijfel en nuances uitdrukken en over onderwijs en taal praten. In de toets: een leestekst en 20 woorden uit lessen 201–209.',
  [('el conocimiento', 'de kennis', 'el ko-no-si-MJEN-to', 'El conocimiento es poder.', 'Kennis is macht.', 'sostantivo'),
   ('la sabiduría', 'de wijsheid', 'la sa-bi-doe-RIE-a', 'La sabiduría viene con los años.', 'Wijsheid komt met de jaren.', 'sostantivo'),
   ('aprender de memoria', 'uit het hoofd leren', 'a-pren-DER de me-MO-rja', 'Aprendí el poema de memoria.', 'Ik leerde het gedicht uit het hoofd.', 'espressione'),
   ('el apunte', 'de aantekening', 'el a-POEN-te', 'Déjame tus apuntes.', 'Leen me je aantekeningen.', 'scuola'),
   ('razonar', 'redeneren', 'rra-so-NAR', 'Hay que razonar la respuesta.', 'Je moet het antwoord beredeneren.', 'verbo'),
   ('el enfoque', 'de benadering / invalshoek', 'el en-FO-ke', 'Es un enfoque original.', 'Het is een originele benadering.', 'sostantivo'),
   ('plantear', 'aan de orde stellen / opwerpen', 'plan-te-AR', 'Planteó una pregunta difícil.', 'Hij wierp een moeilijke vraag op.', 'verbo'),
   ('la hipótesis', 'de hypothese', 'la i-PO-te-sis', 'La hipótesis se confirmó.', 'De hypothese werd bevestigd.', 'sostantivo')]),
L(211, '🤝', 'Relaties & vriendschap', 'Wederkerige werkwoorden.',
  'Wederkerige werkwoorden in relaties', 'Nos conocimos (we leerden elkaar kennen), se llevan bien (ze kunnen goed met elkaar opschieten), se pelean, se reconcilian. Llevarse bien/mal con.',
  [('llevarse bien con', 'goed kunnen opschieten met', 'je-VAR-se bjen kon', 'Me llevo bien con mis suegros.', 'Ik kan goed opschieten met mijn schoonouders.', 'relazioni'),
   ('conocerse', 'elkaar leren kennen', 'ko-no-SER-se', 'Nos conocimos en la universidad.', 'We leerden elkaar kennen op de universiteit.', 'verbo'),
   ('fiarse de', 'vertrouwen (op iemand)', 'FJAR-se de', 'No me fío de él.', 'Ik vertrouw hem niet.', 'verbo'),
   ('la complicidad', 'de verstandhouding / medeplichtigheid', 'la kom-pli-si-DAD', 'Hay mucha complicidad entre ellas.', 'Er is een sterke verstandhouding tussen hen.', 'relazioni'),
   ('apoyarse', 'elkaar steunen', 'a-po-JAR-se', 'Nos apoyamos en los malos momentos.', 'We steunen elkaar in moeilijke tijden.', 'verbo'),
   ('hacer buenas migas', 'het goed met elkaar kunnen vinden', 'a-SER BWE-nas MIE-gas', 'Hicieron buenas migas enseguida.', 'Ze konden het meteen goed met elkaar vinden.', 'espressione'),
   ('el compañerismo', 'de kameraadschap', 'el kom-pa-nje-RIS-mo', 'Hay buen compañerismo en el equipo.', 'Er heerst goede kameraadschap in het team.', 'relazioni'),
   ('distanciarse', 'uit elkaar groeien', 'dis-tan-SJAR-se', 'Con los años se distanciaron.', 'Met de jaren groeiden ze uit elkaar.', 'verbo')]),
L(212, '❤️', 'Liefde & romantiek', 'Over liefde praten.',
  'Over liefde praten', 'Enamorarse de (verliefd worden op), estar enamorado de, salir con (verkering hebben met), la pareja, comprometerse (zich verloven), casarse con.',
  [('enamorarse de', 'verliefd worden op', 'e-na-mo-RAR-se de', 'Se enamoró de ella a primera vista.', 'Hij werd op het eerste gezicht verliefd op haar.', 'verbo'),
   ('salir con', 'verkering hebben met', 'sa-LIER kon', 'Sale con un chico de Bilbao.', 'Ze heeft verkering met een jongen uit Bilbao.', 'espressione'),
   ('comprometerse', 'zich verloven', 'kom-pro-me-TER-se', 'Se comprometieron en verano.', 'Ze verloofden zich in de zomer.', 'verbo'),
   ('el flechazo', 'liefde op het eerste gezicht', 'el fle-TSJA-so', 'Fue un flechazo.', 'Het was liefde op het eerste gezicht.', 'relazioni'),
   ('la cita romántica', 'de romantische date', 'la SIE-ta rro-MAN-ti-ka', 'Tienen una cita romántica esta noche.', 'Ze hebben vanavond een romantische date.', 'relazioni'),
   ('el cariño', 'de genegenheid / liefde', 'el ka-RIE-njo', 'Le tengo mucho cariño.', 'Ik ben erg op hem gesteld.', 'emozione'),
   ('el afecto', 'de genegenheid', 'el a-FEK-to', 'Le demuestra mucho afecto.', 'Hij toont haar veel genegenheid.', 'emozione'),
   ('romper con', 'het uitmaken met', 'rrom-PER kon', 'Rompió con su novio.', 'Ze maakte het uit met haar vriend.', 'espressione')]),
L(213, '🕊️', 'Conflicten & verzoening', 'Ruzie en het goedmaken.',
  'Conflicten beschrijven', 'Discutir (ruziën), pelearse, enfadarse con, hacer las paces (het goedmaken), pedir perdón, perdonar, reconciliarse, el malentendido.',
  [('pelearse', 'ruzie maken / vechten', 'pe-le-AR-se', 'Los hermanos se pelean por todo.', 'De broers maken over alles ruzie.', 'verbo'),
   ('hacer las paces', 'het goedmaken', 'a-SER las PA-ses', 'Al final hicieron las paces.', 'Uiteindelijk maakten ze het goed.', 'espressione'),
   ('reconciliarse', 'zich verzoenen', 'rre-kon-si-LJAR-se', 'Se reconciliaron tras meses.', 'Ze verzoenden zich na maanden.', 'verbo'),
   ('el malentendido', 'het misverstand', 'el ma-len-ten-DIE-do', 'Todo fue un malentendido.', 'Het was allemaal een misverstand.', 'relazioni'),
   ('ofender', 'beledigen', 'o-fen-DER', 'No quería ofenderte.', 'Ik wilde je niet beledigen.', 'verbo'),
   ('guardar rencor', 'wrok koesteren', 'gwar-DAR rren-KOR', 'No le guardo rencor.', 'Ik koester geen wrok tegen hem.', 'espressione'),
   ('ceder', 'toegeven / inbinden', 'se-DER', 'Ninguno de los dos quería ceder.', 'Geen van beiden wilde toegeven.', 'verbo'),
   ('la disculpa', 'de verontschuldiging', 'la dis-KOEL-pa', 'Aceptó mis disculpas.', 'Hij aanvaardde mijn verontschuldigingen.', 'relazioni')]),
L(214, '🎭', 'Karakter & persoonlijkheid', 'Karaktereigenschappen.',
  'Karaktereigenschappen', 'Ser + eigenschap: es terco (koppig), es cabezota, es generoso, es tacaño (gierig), es sensato (verstandig), es orgulloso. Tener mal genio (een slecht humeur hebben).',
  [('terco', 'koppig', 'TER-ko', 'Es terco como una mula.', 'Hij is zo koppig als een ezel.', 'aggettivo'),
   ('tacaño', 'gierig', 'ta-KA-njo', 'No seas tan tacaño.', 'Wees niet zo gierig.', 'aggettivo'),
   ('sensato', 'verstandig', 'sen-SA-to', 'Es una persona muy sensata.', 'Het is een heel verstandig persoon.', 'aggettivo'),
   ('presumido', 'verwaand / ijdel', 'pre-soe-MIE-do', 'Es un poco presumido.', 'Hij is een beetje verwaand.', 'aggettivo'),
   ('humilde', 'bescheiden / nederig', 'oe-MIL-de', 'Es humilde a pesar de su éxito.', 'Hij is bescheiden ondanks zijn succes.', 'aggettivo'),
   ('tener mal genio', 'een slecht humeur hebben', 'te-NER mal CHE-njo', 'Mi abuelo tenía mal genio.', 'Mijn opa had een slecht humeur.', 'espressione'),
   ('el rasgo', 'de (karakter)trek', 'el RRAS-go', 'La paciencia es su mejor rasgo.', 'Geduld is zijn beste eigenschap.', 'sostantivo'),
   ('extrovertido', 'extravert', 'eks-tro-ver-TIE-do', 'Es muy extrovertida.', 'Ze is heel extravert.', 'aggettivo')]),
L(215, '🧠', 'Psychologie & gevoelens', 'Gevoelens uitdrukken.',
  'Gevoelens uitdrukken', 'Me da vergüenza (ik schaam me), me da rabia (ik word er boos van), me pone nervioso, me siento + bijvoeglijk naamwoord. Sentirse identificado con.',
  [('la vergüenza', 'de schaamte', 'la ver-GWEN-sa', 'Me da vergüenza hablar en público.', 'Ik schaam me om in het openbaar te spreken.', 'emozione'),
   ('la frustración', 'de frustratie', 'la froes-tra-SJON', 'Sentí mucha frustración.', 'Ik voelde veel frustratie.', 'emozione'),
   ('la autoestima', 'het zelfvertrouwen / de eigenwaarde', 'la au-to-es-TIE-ma', 'Tiene la autoestima baja.', 'Ze heeft weinig zelfvertrouwen.', 'emozione'),
   ('la inseguridad', 'de onzekerheid (persoonlijk)', 'la in-se-goe-ri-DAD', 'Supera su inseguridad poco a poco.', 'Ze overwint haar onzekerheid beetje bij beetje.', 'emozione'),
   ('desahogarse', 'zijn hart luchten', 'de-sa-o-GAR-se', 'Necesito desahogarme.', 'Ik moet mijn hart luchten.', 'verbo'),
   ('el estado de ánimo', 'de gemoedstoestand', 'el es-TA-do de A-ni-mo', 'Su estado de ánimo ha mejorado.', 'Zijn stemming is verbeterd.', 'emozione'),
   ('la terapia', 'de therapie', 'la te-RA-pja', 'Va a terapia los martes.', 'Hij gaat op dinsdag naar therapie.', 'salute'),
   ('sentirse identificado con', 'zich herkennen in', 'sen-TIER-se i-den-ti-fi-KA-do kon', 'Me siento identificado con el protagonista.', 'Ik herken me in de hoofdpersoon.', 'espressione')]),
L(216, '🌟', 'Dromen & ambities', 'Dromen en plannen uitdrukken.',
  'Dromen en plannen uitdrukken', 'Mi sueño es + infinitivo. Aspirar a (streven naar), lograr (bereiken), perseguir un sueño, ponerse una meta, a largo plazo (op lange termijn).',
  [('aspirar a', 'streven naar', 'as-pi-RAR a', 'Aspira a ser directora.', 'Ze streeft ernaar directeur te worden.', 'verbo'),
   ('el propósito', 'het voornemen / doel', 'el pro-PO-si-to', 'Mi propósito es leer más.', 'Mijn voornemen is meer te lezen.', 'sostantivo'),
   ('perseguir un sueño', 'een droom najagen', 'per-se-GIER oen SWE-njo', 'Persigue su sueño de ser actor.', 'Hij jaagt zijn droom na om acteur te worden.', 'espressione'),
   ('la rivalidad', 'de rivaliteit', 'la rri-va-li-DAD', 'Hay rivalidad entre los dos equipos.', 'Er is rivaliteit tussen de twee teams.', 'sostantivo'),
   ('a largo plazo', 'op lange termijn', 'a LAR-go PLA-so', 'Es un plan a largo plazo.', 'Het is een plan voor de lange termijn.', 'espressione'),
   ('la vocación', 'de roeping', 'la vo-ka-SJON', 'La medicina es su vocación.', 'Geneeskunde is zijn roeping.', 'sostantivo'),
   ('realizarse', 'zichzelf verwezenlijken', 'rre-a-li-SAR-se', 'Se realiza con su trabajo.', 'Ze komt tot haar recht in haar werk.', 'verbo'),
   ('ilusionarse', 'enthousiast worden / hoop koesteren', 'i-loe-sjo-NAR-se', 'No te ilusiones demasiado.', 'Maak je niet te veel hoop.', 'verbo')]),
L(217, '🏆', 'Succes & falen', 'Succes en falen beschrijven.',
  'Succes en falen beschrijven', 'Tener éxito, triunfar, fracasar (mislukken), el fracaso, rendirse (opgeven), volver a intentarlo, aprender de los errores, salir adelante (erbovenop komen).',
  [('triunfar', 'triomferen / slagen', 'trjoen-FAR', 'Triunfó en el extranjero.', 'Hij brak door in het buitenland.', 'verbo'),
   ('fracasar', 'mislukken / falen', 'fra-ka-SAR', 'El proyecto fracasó.', 'Het project mislukte.', 'verbo'),
   ('el fracaso', 'de mislukking', 'el fra-KA-so', 'El fracaso forma parte del camino.', 'Mislukking hoort bij de weg.', 'sostantivo'),
   ('rendirse', 'opgeven', 'rren-DIER-se', 'Nunca se rinde.', 'Hij geeft nooit op.', 'verbo'),
   ('volver a intentarlo', 'het opnieuw proberen', 'vol-VER a in-ten-TAR-lo', 'Volvió a intentarlo y lo consiguió.', 'Hij probeerde het opnieuw en het lukte.', 'espressione'),
   ('salir adelante', 'erbovenop komen / zich redden', 'sa-LIER a-de-LAN-te', 'Con esfuerzo salió adelante.', 'Met inzet kwam hij erbovenop.', 'espressione'),
   ('la derrota', 'de nederlaag', 'la de-RRO-ta', 'Aceptó la derrota con dignidad.', 'Hij aanvaardde de nederlaag waardig.', 'sostantivo'),
   ('el mérito', 'de verdienste', 'el ME-ri-to', 'El mérito es todo suyo.', 'De verdienste is helemaal van hem.', 'sostantivo')]),
L(218, '😊', 'Geluk & tevredenheid', 'Over geluk praten.',
  'Over geluk praten', 'Ser feliz vs. estar contento. Disfrutar de (genieten van), agradecer (dankbaar zijn), valorar (waarderen), conformarse con (genoegen nemen met), estar a gusto (zich op zijn gemak voelen).',
  [('la felicidad', 'het geluk', 'la fe-li-si-DAD', 'La felicidad está en las cosas pequeñas.', 'Geluk zit in kleine dingen.', 'emozione'),
   ('la plenitud', 'de volheid / vervulling', 'la ple-ni-TOED', 'Vive una etapa de plenitud.', 'Hij beleeft een periode van vervulling.', 'emozione'),
   ('agradecer', 'dankbaar zijn / bedanken', 'a-gra-de-SER', 'Agradezco lo que tengo.', 'Ik ben dankbaar voor wat ik heb.', 'verbo'),
   ('valorar', 'waarderen', 'va-lo-RAR', 'Valora cada momento.', 'Waardeer elk moment.', 'verbo'),
   ('conformarse con', 'genoegen nemen met', 'kon-for-MAR-se kon', 'Se conforma con poco.', 'Hij neemt genoegen met weinig.', 'verbo'),
   ('estar a gusto', 'zich op zijn gemak voelen', 'es-TAR a GOES-to', 'Aquí estoy muy a gusto.', 'Hier voel ik me heel erg op mijn gemak.', 'espressione'),
   ('la serenidad', 'de sereniteit / gemoedsrust', 'la se-re-ni-DAD', 'Afronta todo con serenidad.', 'Hij gaat alles met gemoedsrust tegemoet.', 'emozione'),
   ('sonreír', 'glimlachen', 'son-rre-IER', 'Sonríe más, te sienta bien.', 'Lach wat meer, het staat je goed.', 'verbo')]),
L(219, '🧘', 'Stress & ontspanning', 'Over stress en ontspanning praten.',
  'Over stress en ontspanning praten', 'Estar estresado, agobiarse (zich overweldigd voelen), estar quemado (opgebrand zijn), desconectar, relajarse, tomarse un respiro (even pauze nemen).',
  [('agobiarse', 'zich overweldigd voelen', 'a-go-BJAR-se', 'Me agobio con tanto trabajo.', 'Ik raak overweldigd door zoveel werk.', 'verbo'),
   ('estar quemado', 'opgebrand zijn', 'es-TAR ke-MA-do', 'Está quemado de su trabajo.', 'Hij is opgebrand door zijn werk.', 'espressione'),
   ('desconectar', 'ontspannen / afschakelen', 'des-ko-nek-TAR', 'Necesito desconectar el fin de semana.', 'Ik moet in het weekend afschakelen.', 'verbo'),
   ('tomarse un respiro', 'even pauze nemen', 'to-MAR-se oen rres-PIE-ro', 'Tómate un respiro.', 'Neem even pauze.', 'espressione'),
   ('la presión', 'de druk', 'la pre-SJON', 'Trabaja bajo mucha presión.', 'Hij werkt onder veel druk.', 'emozione'),
   ('el insomnio', 'de slapeloosheid', 'el in-SOM-njo', 'Sufre de insomnio.', 'Hij lijdt aan slapeloosheid.', 'salute'),
   ('respirar hondo', 'diep ademhalen', 'rres-pi-RAR ON-do', 'Respira hondo y cuenta hasta diez.', 'Haal diep adem en tel tot tien.', 'espressione'),
   ('el ejercicio de respiración', 'de ademhalingsoefening', 'el e-cher-SIE-sjo de rres-pi-ra-SJON', 'Hago ejercicios de respiración.', 'Ik doe ademhalingsoefeningen.', 'salute')]),
L(220, '📋', 'Toetsles B1 — Blok 10', 'Samenvatting van blok 10.',
  'Samenvatting Blok 10', 'Je kunt relaties, karakter, gevoelens, dromen en succes beschrijven. In de toets: een leestekst en 20 woorden uit lessen 211–219.',
  [('la empatía', 'de empathie', 'la em-pa-TIE-a', 'La empatía es fundamental.', 'Empathie is fundamenteel.', 'emozione'),
   ('la madurez', 'de volwassenheid / rijpheid', 'la ma-doe-RES', 'Reaccionó con madurez.', 'Hij reageerde volwassen.', 'sostantivo'),
   ('la actitud', 'de houding', 'la ak-ti-TOED', 'Tiene una actitud positiva.', 'Ze heeft een positieve houding.', 'sostantivo'),
   ('comportarse', 'zich gedragen', 'kom-por-TAR-se', 'Se comportó muy bien.', 'Hij gedroeg zich heel goed.', 'verbo'),
   ('la lealtad', 'de loyaliteit', 'la le-al-TAD', 'Valoro mucho la lealtad.', 'Ik waardeer loyaliteit enorm.', 'relazioni'),
   ('el vínculo', 'de band', 'el VIN-koe-lo', 'Tienen un vínculo muy fuerte.', 'Ze hebben een heel sterke band.', 'relazioni'),
   ('desconfiar de', 'wantrouwen', 'des-kon-FJAR de', 'Desconfía de los desconocidos.', 'Hij wantrouwt onbekenden.', 'verbo'),
   ('la tolerancia', 'de verdraagzaamheid', 'la to-le-RAN-sja', 'La tolerancia es una virtud.', 'Verdraagzaamheid is een deugd.', 'emozione')]),
L(221, '🐕', 'Huisdieren', 'Verkleinwoorden -ito/-illo.',
  'Verkleinwoorden (-ito / -illo)', 'Perro → perrito, gato → gatito, casa → casita, pan → panecillo, pequeño → pequeñito. Ook liefkozend: abuelita, Juanito. Let op spelling: poco → poquito.',
  [('el perrito', 'het hondje', 'el pe-RRIE-to', 'Adoptamos un perrito.', 'We adopteerden een hondje.', 'animali'),
   ('el gatito', 'het katje', 'el ga-TIE-to', 'El gatito duerme todo el día.', 'Het katje slaapt de hele dag.', 'animali'),
   ('la mascota', 'het huisdier', 'la mas-KO-ta', '¿Tienes mascota?', 'Heb je een huisdier?', 'animali'),
   ('el veterinario', 'de dierenarts', 'el ve-te-ri-NA-rjo', 'Llevo al perro al veterinario.', 'Ik breng de hond naar de dierenarts.', 'animali'),
   ('la correa', 'de riem (hond)', 'la ko-RRE-a', 'Ponle la correa.', 'Doe hem de riem om.', 'animali'),
   ('la jaula', 'de kooi', 'la CHAU-la', 'El pájaro está en la jaula.', 'De vogel zit in de kooi.', 'animali'),
   ('ladrar', 'blaffen', 'la-DRAR', 'El perro ladra a los extraños.', 'De hond blaft naar vreemden.', 'verbo'),
   ('maullar', 'miauwen', 'mau-JAR', 'El gato maúlla cuando tiene hambre.', 'De kat miauwt als hij honger heeft.', 'verbo')]),
L(222, '🦁', 'Wilde dieren', 'Dieren beschrijven.',
  'Dieren beschrijven', 'El león es feroz, el elefante es enorme, la tortuga es lenta. En peligro de extinción (met uitsterven bedreigd), salvaje (wild), la especie (de soort).',
  [('salvaje', 'wild', 'sal-VA-che', 'Es un animal salvaje.', 'Het is een wild dier.', 'aggettivo'),
   ('el depredador', 'het roofdier', 'el de-pre-da-DOR', 'El lobo es un depredador.', 'De wolf is een roofdier.', 'animali'),
   ('en peligro de extinción', 'met uitsterven bedreigd', 'en pe-LIE-gro de eks-tin-SJON', 'El lince ibérico está en peligro de extinción.', 'De Iberische lynx wordt met uitsterven bedreigd.', 'espressione'),
   ('el lobo', 'de wolf', 'el LO-bo', 'Los lobos viven en manada.', 'Wolven leven in een roedel.', 'animali'),
   ('el oso', 'de beer', 'el O-so', 'El oso pardo vive en los Pirineos.', 'De bruine beer leeft in de Pyreneeën.', 'animali'),
   ('el águila', 'de adelaar', 'el A-gi-la', 'El águila vuela muy alto.', 'De adelaar vliegt heel hoog.', 'animali'),
   ('la manada', 'de kudde / roedel', 'la ma-NA-da', 'La manada cruzó el río.', 'De kudde stak de rivier over.', 'animali'),
   ('feroz', 'woest / fel', 'fe-ROS', 'El tigre es un depredador feroz.', 'De tijger is een woest roofdier.', 'aggettivo')]),
L(223, '🌿', 'Planten & tuinieren', 'Over planten praten.',
  'Over planten praten', 'Regar (water geven), plantar, podar (snoeien), la semilla (het zaad), la raíz, florecer, marchitarse (verwelken). Tener buena mano con las plantas (groene vingers hebben).',
  [('regar', 'water geven', 'rre-GAR', 'Hay que regar las plantas cada día.', 'De planten moeten elke dag water krijgen.', 'verbo'),
   ('podar', 'snoeien', 'po-DAR', 'Podamos los rosales en febrero.', 'We snoeien de rozenstruiken in februari.', 'verbo'),
   ('la semilla', 'het zaad(je)', 'la se-MIE-ja', 'Planté semillas de tomate.', 'Ik plantte tomatenzaadjes.', 'natura'),
   ('la raíz', 'de wortel', 'la rra-IES', 'Las raíces son profundas.', 'De wortels zijn diep.', 'natura'),
   ('marchitarse', 'verwelken', 'mar-tsji-TAR-se', 'Las flores se han marchitado.', 'De bloemen zijn verwelkt.', 'verbo'),
   ('la maceta', 'de bloempot', 'la ma-SE-ta', 'Compré una maceta grande.', 'Ik kocht een grote bloempot.', 'natura'),
   ('el huerto', 'de moestuin', 'el WER-to', 'Tenemos un huerto con lechugas.', 'We hebben een moestuin met sla.', 'natura'),
   ('tener buena mano con las plantas', 'groene vingers hebben', 'te-NER BWE-na MA-no kon las PLAN-tas', 'Mi madre tiene buena mano con las plantas.', 'Mijn moeder heeft groene vingers.', 'espressione')]),
L(224, '🏔️', 'Landschappen & geografie', 'Landschappen beschrijven.',
  'Landschappen beschrijven', 'La meseta (de hoogvlakte), el valle, la llanura (de vlakte), la cordillera, el acantilado (de klif), la península. El paisaje es árido / verde / montañoso.',
  [('la meseta', 'de hoogvlakte', 'la me-SE-ta', 'Madrid está en la meseta central.', 'Madrid ligt op de centrale hoogvlakte.', 'geografia'),
   ('el desierto', 'de woestijn', 'el de-SJER-to', 'El desierto de Tabernas está en Almería.', 'De woestijn van Tabernas ligt in Almería.', 'geografia'),
   ('la llanura', 'de vlakte', 'la ja-NOE-ra', 'La llanura se extiende hasta el horizonte.', 'De vlakte strekt zich uit tot de horizon.', 'geografia'),
   ('la cordillera', 'de bergketen', 'la kor-di-JE-ra', 'La cordillera Cantábrica es verde.', 'Het Cantabrisch Gebergte is groen.', 'geografia'),
   ('el acantilado', 'de klif', 'el a-kan-ti-LA-do', 'Los acantilados son impresionantes.', 'De kliffen zijn indrukwekkend.', 'geografia'),
   ('árido', 'dor / droog', 'A-ri-do', 'El sur es más árido.', 'Het zuiden is droger.', 'aggettivo'),
   ('montañoso', 'bergachtig', 'mon-ta-NJO-so', 'Es una región montañosa.', 'Het is een bergachtige streek.', 'aggettivo'),
   ('el horizonte', 'de horizon', 'el o-ri-SON-te', 'El sol se pone en el horizonte.', 'De zon gaat onder aan de horizon.', 'geografia')]),
L(225, '🏖️', 'De zee & het strand', 'Aan zee.',
  'Aan zee', 'La marea alta/baja (vloed/eb), la ola, la orilla (de oever/vloedlijn), la arena, bucear (duiken), la sombrilla (de parasol), hacer pie (kunnen staan in het water).',
  [('la marea', 'het getij', 'la ma-RE-a', 'La marea está subiendo.', 'Het wordt vloed.', 'natura'),
   ('la orilla', 'de oever / vloedlijn', 'la o-RIE-ja', 'Paseamos por la orilla.', 'We wandelden langs de vloedlijn.', 'natura'),
   ('bucear', 'duiken', 'boe-se-AR', 'Aprendí a bucear en Menorca.', 'Ik leerde duiken op Menorca.', 'verbo'),
   ('la sombrilla', 'de parasol', 'la som-BRIE-ja', 'Alquilamos una sombrilla.', 'We huurden een parasol.', 'natura'),
   ('hacer pie', 'kunnen staan (in het water)', 'a-SER pje', 'Aquí no hago pie.', 'Hier kan ik niet staan.', 'espressione'),
   ('la bandera roja', 'de rode vlag (zwemverbod)', 'la ban-DE-ra RRO-cha', 'Hay bandera roja: prohibido bañarse.', 'De rode vlag hangt: zwemmen verboden.', 'natura'),
   ('el socorrista', 'de strandwacht', 'el so-ko-RRIS-ta', 'El socorrista vigila la playa.', 'De strandwacht houdt het strand in de gaten.', 'professione'),
   ('la cala', 'de kleine baai', 'la KA-la', 'Descubrimos una cala escondida.', 'We ontdekten een verborgen baai.', 'natura')]),
L(226, '⛰️', 'Bergen & wandelen', 'In de bergen.',
  'In de bergen', 'Hacer senderismo, la ruta, el sendero (het pad), la cima (de top), el refugio (de berghut), la pendiente (de helling), la mochila. Está señalizado (het is bewegwijzerd).',
  [('el sendero', 'het (wandel)pad', 'el sen-DE-ro', 'El sendero está bien señalizado.', 'Het pad is goed bewegwijzerd.', 'natura'),
   ('la cima', 'de top', 'la SIE-ma', 'Llegamos a la cima al mediodía.', 'We bereikten de top om twaalf uur.', 'natura'),
   ('el refugio', 'de berghut', 'el rre-FOE-chjo', 'Dormimos en un refugio.', 'We sliepen in een berghut.', 'natura'),
   ('la pendiente', 'de helling', 'la pen-DJEN-te', 'La pendiente es muy pronunciada.', 'De helling is heel steil.', 'natura'),
   ('señalizado', 'bewegwijzerd', 'se-nja-li-SA-do', 'La ruta está señalizada.', 'De route is bewegwijzerd.', 'aggettivo'),
   ('el desnivel', 'het hoogteverschil', 'el des-ni-VEL', 'Hay 800 metros de desnivel.', 'Er is 800 meter hoogteverschil.', 'natura'),
   ('la cumbre', 'de bergtop / piek', 'la KOEM-bre', 'La cumbre está nevada.', 'De bergtop is besneeuwd.', 'natura'),
   ('las botas de montaña', 'de bergschoenen', 'las BO-tas de mon-TA-nja', 'Necesitas botas de montaña.', 'Je hebt bergschoenen nodig.', 'natura')]),
L(227, '🌍', 'Klimaat & klimaatverandering', 'Over het klimaat praten.',
  'Over het klimaat praten', 'El calentamiento global, el efecto invernadero (het broeikaseffect), la sequía (de droogte), la ola de calor, el deshielo (het smelten), las emisiones.',
  [('la capa de ozono', 'de ozonlaag', 'la KA-pa de o-SO-no', 'La capa de ozono se está recuperando.', 'De ozonlaag herstelt zich.', 'ambiente'),
   ('el efecto invernadero', 'het broeikaseffect', 'el e-FEK-to in-ver-na-DE-ro', 'El CO₂ aumenta el efecto invernadero.', 'CO₂ versterkt het broeikaseffect.', 'ambiente'),
   ('el tornado', 'de tornado', 'el tor-NA-do', 'Un tornado arrasó el pueblo.', 'Een tornado verwoestte het dorp.', 'ambiente'),
   ('la contaminación atmosférica', 'de luchtvervuiling', 'la kon-ta-mi-na-SJON at-mos-FE-ri-ka', 'La contaminación atmosférica es grave en invierno.', 'De luchtvervuiling is ernstig in de winter.', 'ambiente'),
   ('el deshielo', 'het smelten (van ijs)', 'el de-SJE-lo', 'El deshielo de los polos avanza.', 'Het smelten van de polen gaat door.', 'ambiente'),
   ('el fenómeno extremo', 'het extreme weersverschijnsel', 'el fe-NO-me-no eks-TRE-mo', 'Los fenómenos extremos son más frecuentes.', 'Extreme weersverschijnselen komen vaker voor.', 'ambiente'),
   ('el nivel del mar', 'de zeespiegel', 'el ni-VEL del mar', 'El nivel del mar sube.', 'De zeespiegel stijgt.', 'ambiente'),
   ('la inundación', 'de overstroming', 'la i-noen-da-SJON', 'Las inundaciones causaron daños.', 'De overstromingen richtten schade aan.', 'ambiente')]),
L(228, '♻️', 'Duurzaamheid & recycling', 'Over duurzaamheid praten.',
  'Over duurzaamheid praten', 'Reciclar, reutilizar, reducir. El contenedor amarillo (plastic), azul (papier), verde (glas), marrón (gft). Sostenible, el residuo (het afval), el envase (de verpakking).',
  [('el reciclaje', 'de recycling', 'el rre-si-KLA-che', 'El reciclaje reduce los residuos.', 'Recycling vermindert het afval.', 'ambiente'),
   ('el vertedero', 'de vuilstortplaats', 'el ver-te-DE-ro', 'El vertedero está lleno.', 'De vuilstort is vol.', 'ambiente'),
   ('el residuo', 'het afval / restproduct', 'el rre-SIE-dwo', 'Los residuos orgánicos van al marrón.', 'Organisch afval gaat in de bruine bak.', 'ambiente'),
   ('el envase', 'de verpakking', 'el en-VA-se', 'Los envases van al contenedor amarillo.', 'Verpakkingen gaan in de gele container.', 'ambiente'),
   ('el contenedor', 'de (afval)container', 'el kon-te-ne-DOR', '¿Dónde está el contenedor del vidrio?', 'Waar is de glascontainer?', 'ambiente'),
   ('la bolsa de tela', 'de stoffen tas', 'la BOL-sa de TE-la', 'Llevo siempre una bolsa de tela.', 'Ik neem altijd een stoffen tas mee.', 'ambiente'),
   ('desechable', 'wegwerp-', 'de-se-TSJA-ble', 'Evita los productos desechables.', 'Vermijd wegwerpproducten.', 'aggettivo'),
   ('el compostaje', 'het composteren', 'el kom-pos-TA-che', 'Hacemos compostaje en casa.', 'We composteren thuis.', 'ambiente')]),
L(229, '⚡', 'Energie & grondstoffen', 'Over energie praten.',
  'Over energie praten', 'Las energías renovables: solar, eólica (wind), hidráulica. Los combustibles fósiles, el petróleo, el gas natural, la central nuclear, el consumo, ahorrar energía.',
  [('el aerogenerador', 'de windturbine', 'el a-e-ro-che-ne-ra-DOR', 'Hay aerogeneradores en la colina.', 'Er staan windturbines op de heuvel.', 'ambiente'),
   ('la energía eólica', 'de windenergie', 'la e-ner-CHIE-a e-O-li-ka', 'La energía eólica crece cada año.', 'Windenergie groeit elk jaar.', 'ambiente'),
   ('la placa solar', 'het zonnepaneel', 'la PLA-ka so-LAR', 'Instalamos placas solares en el tejado.', 'We plaatsten zonnepanelen op het dak.', 'ambiente'),
   ('el combustible fósil', 'de fossiele brandstof', 'el kom-boes-TIE-ble FO-sil', 'Dependemos de los combustibles fósiles.', 'We zijn afhankelijk van fossiele brandstoffen.', 'ambiente'),
   ('el petróleo', 'de aardolie', 'el pe-TRO-le-o', 'El precio del petróleo ha subido.', 'De olieprijs is gestegen.', 'ambiente'),
   ('la central nuclear', 'de kerncentrale', 'la sen-TRAL noe-kle-AR', 'Cerrarán la central nuclear en 2030.', 'Ze sluiten de kerncentrale in 2030.', 'ambiente'),
   ('el consumo', 'het verbruik', 'el kon-SOE-mo', 'Hay que reducir el consumo de energía.', 'Het energieverbruik moet omlaag.', 'ambiente'),
   ('la materia prima', 'de grondstof', 'la ma-TE-rja PRIE-ma', 'Las materias primas escasean.', 'Grondstoffen worden schaars.', 'ambiente')]),
L(230, '📋', 'Toetsles B1 — Blok 11', 'Samenvatting van blok 11.',
  'Samenvatting Blok 11', 'Je kent de verkleinwoorden en kunt dieren, natuur, klimaat en energie bespreken. In de toets: een leestekst en 20 woorden uit lessen 221–229.',
  [('el ecologista', 'de milieuactivist', 'el e-ko-lo-CHIS-ta', 'Los ecologistas protestaron.', 'De milieuactivisten protesteerden.', 'ambiente'),
   ('el hábitat', 'de leefomgeving / habitat', 'el A-bi-tat', 'Destruyen su hábitat natural.', 'Ze vernietigen hun natuurlijke leefomgeving.', 'ambiente'),
   ('la reserva natural', 'het natuurreservaat', 'la rre-SER-va na-toe-RAL', 'Doñana es una reserva natural.', 'Doñana is een natuurreservaat.', 'ambiente'),
   ('amenazar', 'bedreigen', 'a-me-na-SAR', 'La sequía amenaza las cosechas.', 'De droogte bedreigt de oogsten.', 'verbo'),
   ('la cosecha', 'de oogst', 'la ko-SE-tsja', 'La cosecha fue buena este año.', 'De oogst was dit jaar goed.', 'natura'),
   ('el pinar', 'het dennenbos', 'el pi-NAR', 'Paseamos por el pinar.', 'We wandelden door het dennenbos.', 'natura'),
   ('el incendio forestal', 'de bosbrand', 'el in-SEN-djo fo-res-TAL', 'Los incendios forestales aumentan.', 'Bosbranden nemen toe.', 'ambiente'),
   ('concienciar', 'bewust maken', 'kon-sjen-SJAR', 'Hay que concienciar a la población.', 'De bevolking moet bewust gemaakt worden.', 'verbo')]),
L(231, '🎬', 'Film & bioscoop', 'Over films praten.',
  'Over films praten', 'El estreno (de première), la taquilla (de kassa), el reparto (de cast), el guion (het script), doblada (nagesynchroniseerd), en versión original subtitulada (V.O.S.).',
  [('el estreno', 'de première', 'el es-TRE-no', 'El estreno es el viernes.', 'De première is vrijdag.', 'cinema'),
   ('la taquilla', 'de kassa / het kassasucces', 'la ta-KIE-ja', 'Fue un éxito de taquilla.', 'Het was een kassasucces.', 'cinema'),
   ('el reparto', 'de cast / rolverdeling', 'el rre-PAR-to', 'El reparto es excelente.', 'De cast is uitstekend.', 'cinema'),
   ('el guion', 'het script', 'el gi-ON', 'El guion es original.', 'Het script is origineel.', 'cinema'),
   ('doblado', 'nagesynchroniseerd', 'do-BLA-do', 'Prefiero no ver películas dobladas.', 'Ik zie liever geen nagesynchroniseerde films.', 'aggettivo'),
   ('la versión original', 'de originele versie', 'la ver-SJON o-ri-chi-NAL', 'La ponen en versión original subtitulada.', 'Ze draaien hem in de originele versie met ondertitels.', 'cinema'),
   ('la banda sonora', 'de soundtrack', 'la BAN-da so-NO-ra', 'La banda sonora es preciosa.', 'De soundtrack is prachtig.', 'cinema'),
   ('el cortometraje', 'de korte film', 'el kor-to-me-TRA-che', 'Rodó un cortometraje.', 'Hij maakte een korte film.', 'cinema')]),
L(232, '🎭', 'Theater & zarzuela', 'Theater en opera.',
  'Theater & opera', 'La función (de voorstelling), el escenario (het podium), el telón (het doek), el intermedio (de pauze), el aplauso, la zarzuela (Spaanse operette), el papel (de rol).',
  [('la función', 'de voorstelling', 'la foen-SJON', 'La función empieza a las ocho.', 'De voorstelling begint om acht uur.', 'teatro'),
   ('el decorado', 'het decor', 'el de-ko-RA-do', 'El decorado era muy sencillo.', 'Het decor was heel eenvoudig.', 'teatro'),
   ('el telón', 'het doek', 'el te-LON', 'Se levanta el telón.', 'Het doek gaat op.', 'teatro'),
   ('el intermedio', 'de pauze (theater)', 'el in-ter-ME-djo', 'En el intermedio tomamos algo.', 'In de pauze dronken we wat.', 'teatro'),
   ('la zarzuela', 'de zarzuela (Spaanse operette)', 'la sar-SWE-la', 'La zarzuela es típicamente española.', 'De zarzuela is typisch Spaans.', 'teatro'),
   ('el papel', 'de rol', 'el pa-PEL', 'Interpreta el papel principal.', 'Ze speelt de hoofdrol.', 'teatro'),
   ('la ópera', 'de opera', 'la O-pe-ra', 'Fuimos a la ópera en el Liceu.', 'We gingen naar de opera in het Liceu.', 'teatro'),
   ('ensayar', 'repeteren', 'en-sa-JAR', 'Ensayan todos los días.', 'Ze repeteren elke dag.', 'verbo')]),
L(233, '🖌️', 'Schilderkunst & musea', 'Kunst bespreken.',
  'Kunst bespreken', 'El lienzo (het doek), el óleo (olieverf), la acuarela, el retrato, el paisaje, la exposición, el bodegón (het stilleven). Representa / transmite / evoca.',
  [('el lienzo', 'het (schilders)doek', 'el LJEN-so', 'Pinta sobre lienzo.', 'Ze schildert op doek.', 'arte'),
   ('el óleo', 'de olieverf', 'el O-le-o', 'Es un óleo del siglo XVII.', 'Het is een olieverfschilderij uit de zeventiende eeuw.', 'arte'),
   ('la acuarela', 'de aquarel', 'la a-kwa-RE-la', 'Prefiero la acuarela.', 'Ik heb liever aquarel.', 'arte'),
   ('el bodegón', 'het stilleven', 'el bo-de-GON', 'Pintó muchos bodegones.', 'Hij schilderde veel stillevens.', 'arte'),
   ('el autorretrato', 'het zelfportret', 'el au-to-rre-TRA-to', 'Frida Kahlo pintó muchos autorretratos.', 'Frida Kahlo schilderde veel zelfportretten.', 'arte'),
   ('transmitir', 'overbrengen', 'trans-mi-TIER', 'El cuadro transmite tristeza.', 'Het schilderij brengt verdriet over.', 'verbo'),
   ('la pincelada', 'de penseelstreek', 'la pin-se-LA-da', 'Las pinceladas son sueltas.', 'De penseelstreken zijn los.', 'arte'),
   ('el coleccionista', 'de verzamelaar', 'el ko-lek-sjo-NIS-ta', 'Un coleccionista compró la obra.', 'Een verzamelaar kocht het werk.', 'arte')]),
L(234, '📷', 'Fotografie & design', 'Over fotografie praten.',
  'Over fotografie praten', 'Enfocar (scherpstellen), el encuadre (de kadrering), la luz natural, el primer plano (de close-up), retocar (bewerken), el diseño gráfico, el logotipo.',
  [('enfocar', 'scherpstellen', 'en-fo-KAR', 'Enfoca bien antes de disparar.', 'Stel goed scherp voordat je afdrukt.', 'verbo'),
   ('el encuadre', 'de kadrering', 'el en-KWA-dre', 'El encuadre es perfecto.', 'De kadrering is perfect.', 'arte'),
   ('el primer plano', 'de close-up', 'el pri-MER PLA-no', 'Hizo un primer plano de su cara.', 'Hij maakte een close-up van haar gezicht.', 'arte'),
   ('retocar', 'bewerken / retoucheren', 'rre-to-KAR', 'Retocó la foto en el ordenador.', 'Hij bewerkte de foto op de computer.', 'verbo'),
   ('la luz natural', 'het natuurlijke licht', 'la loes na-toe-RAL', 'Prefiero fotografiar con luz natural.', 'Ik fotografeer liever met natuurlijk licht.', 'arte'),
   ('el diseño gráfico', 'het grafisch ontwerp', 'el di-SE-njo GRA-fi-ko', 'Estudia diseño gráfico.', 'Ze studeert grafisch ontwerp.', 'arte'),
   ('el logotipo', 'het logo', 'el lo-go-TIE-po', 'Diseñaron un logotipo nuevo.', 'Ze ontwierpen een nieuw logo.', 'arte'),
   ('el trípode', 'het statief', 'el TRIE-po-de', 'Usa un trípode para fotos nocturnas.', 'Gebruik een statief voor nachtfoto\'s.', 'arte')]),
L(235, '📰', 'Kranten & journalistiek', 'Krantenkoppen lezen.',
  'Krantenkoppen lezen', 'El titular (de kop), la portada (de voorpagina), la sección, el editorial, la fuente (de bron), la rueda de prensa (de persconferentie), según fuentes oficiales.',
  [('la columna', 'de column', 'la ko-LOEM-na', 'Escribe una columna semanal.', 'Hij schrijft een wekelijkse column.', 'media'),
   ('el suplemento', 'de bijlage (krant)', 'el soe-ple-MEN-to', 'El suplemento dominical trae recetas.', 'De zondagsbijlage bevat recepten.', 'media'),
   ('el editorial', 'het hoofdartikel', 'el e-di-to-RJAL', 'El editorial critica al gobierno.', 'Het hoofdartikel bekritiseert de regering.', 'media'),
   ('la fuente fiable', 'de betrouwbare bron', 'la FWEN-te FJA-ble', 'Contrasta con fuentes fiables.', 'Controleer met betrouwbare bronnen.', 'media'),
   ('la rueda de prensa', 'de persconferentie', 'la RRWE-da de PREN-sa', 'Dio una rueda de prensa.', 'Hij gaf een persconferentie.', 'media'),
   ('el corresponsal', 'de correspondent', 'el ko-rres-pon-SAL', 'Es corresponsal en Buenos Aires.', 'Ze is correspondent in Buenos Aires.', 'media'),
   ('la noticia de última hora', 'het laatste nieuws / breaking news', 'la no-TIE-sja de OEL-ti-ma O-ra', 'Noticia de última hora: dimite el ministro.', 'Laatste nieuws: de minister treedt af.', 'media'),
   ('la libertad de prensa', 'de persvrijheid', 'la li-ber-TAD de PREN-sa', 'La libertad de prensa es esencial.', 'Persvrijheid is essentieel.', 'media')]),
L(236, '📺', 'Radio & televisie', 'Over media praten.',
  'Over media praten', 'El telediario (het journaal), la cadena (de zender), el presentador, la audiencia (het kijkerspubliek), en directo (live), el concurso (de spelshow), hacer zapping.',
  [('el documental', 'de documentaire', 'el do-koe-men-TAL', 'Vimos un documental sobre Doñana.', 'We zagen een documentaire over Doñana.', 'media'),
   ('la cadena', 'de zender', 'la ka-DE-na', '¿En qué cadena lo ponen?', 'Op welke zender komt het?', 'media'),
   ('el presentador', 'de presentator', 'el pre-sen-ta-DOR', 'El presentador es muy conocido.', 'De presentator is heel bekend.', 'media'),
   ('la audiencia', 'het kijkerspubliek / de kijkcijfers', 'la au-DJEN-sja', 'El programa tiene mucha audiencia.', 'Het programma heeft hoge kijkcijfers.', 'media'),
   ('en directo', 'live', 'en di-REK-to', 'Lo retransmiten en directo.', 'Ze zenden het live uit.', 'espressione'),
   ('el concurso', 'de spelshow / wedstrijd', 'el kon-KOER-so', 'Participó en un concurso de televisión.', 'Hij deed mee aan een spelshow.', 'media'),
   ('hacer zapping', 'zappen', 'a-SER SA-pin', 'Pasa la noche haciendo zapping.', 'Hij zapt de hele avond.', 'espressione'),
   ('la emisora', 'de radiozender', 'la e-mi-SO-ra', 'Escucho una emisora local.', 'Ik luister naar een lokale radiozender.', 'media')]),
L(237, '📢', 'Reclame & marketing', 'Reclametaal.',
  'Reclametaal', 'El anuncio, la campaña publicitaria, el eslogan, la marca (het merk), el consumidor, la oferta, ¡no te lo pierdas! (mis het niet!), por tiempo limitado.',
  [('la campaña publicitaria', 'de reclamecampagne', 'la kam-PA-nja poe-bli-si-TA-rja', 'Lanzaron una campaña publicitaria.', 'Ze lanceerden een reclamecampagne.', 'marketing'),
   ('el eslogan', 'de slogan', 'el es-LO-gan', 'El eslogan es pegadizo.', 'De slogan is pakkend.', 'marketing'),
   ('el consumidor', 'de consument', 'el kon-soe-mi-DOR', 'Protegen al consumidor.', 'Ze beschermen de consument.', 'marketing'),
   ('el patrocinador', 'de sponsor', 'el pa-tro-si-na-DOR', 'El patrocinador paga la camiseta.', 'De sponsor betaalt het shirt.', 'marketing'),
   ('pegadizo', 'pakkend / aanstekelijk', 'pe-ga-DIE-so', 'Es una melodía pegadiza.', 'Het is een pakkende melodie.', 'aggettivo'),
   ('¡no te lo pierdas!', 'mis het niet!', 'no te lo PJER-das', '¡Ofertas increíbles, no te lo pierdas!', 'Ongelooflijke aanbiedingen, mis het niet!', 'espressione'),
   ('por tiempo limitado', 'voor beperkte tijd', 'por TJEM-po li-mi-TA-do', 'Solo por tiempo limitado.', 'Alleen voor beperkte tijd.', 'espressione'),
   ('el público objetivo', 'de doelgroep', 'el POE-bli-ko ob-che-TIE-vo', 'El público objetivo son los jóvenes.', 'De doelgroep zijn jongeren.', 'marketing')]),
L(238, '👗', 'Mode & trends', 'Over mode praten.',
  'Over mode praten', 'Estar de moda, pasado de moda (uit de mode), la tendencia, la temporada (het seizoen), el diseñador, la pasarela (de catwalk), quedar bien/mal (goed/slecht staan).',
  [('la tendencia', 'de trend', 'la ten-DEN-sja', 'Es la tendencia de esta temporada.', 'Het is de trend van dit seizoen.', 'moda'),
   ('pasado de moda', 'uit de mode', 'pa-SA-do de MO-da', 'Esos pantalones están pasados de moda.', 'Die broek is uit de mode.', 'espressione'),
   ('el diseñador', 'de ontwerper', 'el di-se-nja-DOR', 'Es un diseñador español famoso.', 'Hij is een beroemde Spaanse ontwerper.', 'moda'),
   ('la pasarela', 'de catwalk', 'la pa-sa-RE-la', 'Desfiló en la pasarela de Madrid.', 'Ze liep op de catwalk van Madrid.', 'moda'),
   ('favorecer', 'flatteren / goed staan', 'fa-vo-re-SER', 'Ese color te favorece.', 'Die kleur staat je goed.', 'verbo'),
   ('la prenda', 'het kledingstuk', 'la PREN-da', 'Es una prenda básica.', 'Het is een basiskledingstuk.', 'moda'),
   ('la marca de lujo', 'het luxemerk', 'la MAR-ka de LOE-cho', 'Las marcas de lujo son caras.', 'Luxemerken zijn duur.', 'moda'),
   ('el estampado', 'de print / het dessin', 'el es-tam-PA-do', 'Lleva una camisa de estampado floral.', 'Hij draagt een overhemd met bloemenprint.', 'moda')]),
L(239, '🎪', 'Evenementen & festivals', 'Evenementen beschrijven.',
  'Evenementen beschrijven', 'El cartel (de line-up/affiche), la entrada agotada (uitverkocht), el aforo (de capaciteit), el recinto (het terrein), la actuación (het optreden), el ambiente.',
  [('el cartel', 'de line-up / het affiche', 'el kar-TEL', 'El cartel del festival es impresionante.', 'De line-up van het festival is indrukwekkend.', 'eventi'),
   ('agotado', 'uitverkocht', 'a-go-TA-do', 'Las entradas están agotadas.', 'De kaarten zijn uitverkocht.', 'aggettivo'),
   ('el aforo', 'de capaciteit (publiek)', 'el a-FO-ro', 'El aforo es de cinco mil personas.', 'De capaciteit is vijfduizend mensen.', 'eventi'),
   ('el recinto', 'het terrein / de locatie', 'el rre-SIN-to', 'El recinto abre a las cinco.', 'Het terrein gaat om vijf uur open.', 'eventi'),
   ('la actuación', 'het optreden', 'la ak-twa-SJON', 'Su actuación fue memorable.', 'Zijn optreden was memorabel.', 'eventi'),
   ('el ambiente', 'de sfeer', 'el am-BJEN-te', 'Había un ambiente increíble.', 'Er hing een ongelooflijke sfeer.', 'eventi'),
   ('la carpa', 'de tent (evenement)', 'la KAR-pa', 'El concierto es en la carpa grande.', 'Het concert is in de grote tent.', 'eventi'),
   ('el organizador', 'de organisator', 'el or-ga-ni-sa-DOR', 'El organizador canceló el evento.', 'De organisator annuleerde het evenement.', 'eventi')]),
L(240, '📋', 'Toetsles B1 — Blok 12', 'Samenvatting van blok 12.',
  'Samenvatting Blok 12', 'Je kunt over film, theater, kunst, media, reclame, mode en evenementen praten. In de toets: een leestekst en 20 woorden uit lessen 231–239. Hiermee is B1 blok 2 afgerond.',
  [('la crítica', 'de recensie / kritiek', 'la KRIE-ti-ka', 'La crítica fue muy positiva.', 'De recensie was heel positief.', 'media'),
   ('el espectador', 'de toeschouwer', 'el es-pek-ta-DOR', 'Los espectadores aplaudieron de pie.', 'De toeschouwers gaven een staande ovatie.', 'eventi'),
   ('la creatividad', 'de creativiteit', 'la kre-a-ti-vi-DAD', 'La creatividad no tiene límites.', 'Creativiteit kent geen grenzen.', 'sostantivo'),
   ('inspirarse en', 'zich laten inspireren door', 'ins-pi-RAR-se en', 'Se inspiró en la naturaleza.', 'Ze liet zich inspireren door de natuur.', 'verbo'),
   ('la obra de arte', 'het kunstwerk', 'la O-bra de AR-te', 'Es una obra de arte única.', 'Het is een uniek kunstwerk.', 'arte'),
   ('el talento', 'het talent', 'el ta-LEN-to', 'Tiene mucho talento.', 'Ze heeft veel talent.', 'sostantivo'),
   ('la fama', 'de roem', 'la FA-ma', 'La fama le llegó tarde.', 'De roem kwam laat voor hem.', 'sostantivo'),
   ('innovador', 'vernieuwend', 'i-no-va-DOR', 'Es un enfoque innovador.', 'Het is een vernieuwende aanpak.', 'aggettivo')]),
]

# ── Validatie + schrijven ────────────────────────────────────────────────────
from collections import Counter
assert [l['id'] for l in LESSONS] == list(range(FIRST, LAST + 1)), 'les-IDs'
vocab = json.load(open(OUT / 'vocabulary.json', encoding='utf-8'))
curriculum = json.load(open(OUT / 'curriculum.json', encoding='utf-8'))
vocab = [w for w in vocab if not FIRST <= w['lesson'] <= LAST]; curriculum = [l for l in curriculum if not FIRST <= l['id'] <= LAST]
ART = re.compile(r"^(?:(?:el|la|los|las|un|una|unos|unas)\s+)", re.I)
norm = lambda s: ART.sub('', s.lower()).strip()
existing = {norm(w['it']) for w in vocab}
seen = Counter(); n = max(int(w['id'][1:]) for w in vocab) + 1
new_vocab, new_curr = [], []
for l in LESSONS:
    assert len(l['words']) == 8, f"les {l['id']}: {len(l['words'])} woorden"
    ids = []
    for es, nl, ph, ex, exNl, cat in l['words']:
        k = norm(es); seen[k] += 1
        assert k not in existing, f"les {l['id']}: '{es}' bestaat al"
        wid = f'e{n:03d}'; n += 1
        new_vocab.append({'id': wid, 'it': es, 'nl': nl, 'ph': ph, 'ex': ex, 'exNl': exNl, 'lesson': l['id'], 'level': 'B1', 'cat': cat})
        ids.append(wid)
    new_curr.append({'id': l['id'], 'title': l['title'], 'emoji': l['emoji'], 'level': 'B1', 'description': l['description'], 'grammar': l['grammar'], 'words': ids})
dups = [k for k, c in seen.items() if c > 1]
assert not dups, f'dubbel binnen blok: {dups}'
vocab += new_vocab; curriculum += new_curr
curriculum.sort(key=lambda l: l['id'])
json.dump(vocab, open(OUT / 'vocabulary.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'vocabulary.json', 'a').write('\n')
json.dump(curriculum, open(OUT / 'curriculum.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'curriculum.json', 'a').write('\n')
print(f'Spaans B1 blok 2: {len(new_curr)} lessen, {len(new_vocab)} woorden → totaal {len(curriculum)} lessen, {len(vocab)} woorden')
