"""B1-lessen 241–270 (blokken 13–15) voor Vocado: Maatschappij, Zakelijk, Gezondheid & Wetenschap."""

# ── LESSEN ────────────────────────────────────────────────────────────────────

LESSONS = [
    # ═══ BLOK 13: MAATSCHAPPIJ & POLITIEK (241–250) ══════════════════════════
    {
        "id": 241, "title": "Politiek — basis", "emoji": "🏛️", "level": "B1",
        "description": "Leer basisbegrippen uit de politiek.",
        "grammar": {
            "title": "Passiva met venire",
            "body": "Naast essere + voltooid deelwoord kun je in het Italiaans ook venire gebruiken voor de passieve vorm. Dit benadrukt dat de actie plaatsvindt (niet een toestand beschrijft).\n\n• La legge viene approvata. (De wet wordt goedgekeurd.)\n• Il presidente viene eletto ogni cinque anni. (De president wordt elke vijf jaar gekozen.)\n\nVuistregel: venire + voltooid deelwoord = actie die gebeurt. Essere + voltooid deelwoord = toestand of resultaat.\n\nLet op: venire-passief werkt alleen met enkelvoudige tijden (presente, imperfetto, futuro), niet met samengestelde tijden."
        },
        "words": ["w2171","w2172","w2173","w2174","w2175","w2176","w2177","w2178"]
    },
    {
        "id": 242, "title": "Verkiezingen & democratie", "emoji": "🗳️", "level": "B1",
        "description": "Woordenschat rond verkiezingen, stemmen en democratie.",
        "words": ["w2179","w2180","w2181","w2182","w2183","w2184","w2185","w2186"]
    },
    {
        "id": 243, "title": "Rechten & plichten", "emoji": "⚖️", "level": "B1",
        "description": "Praat over burgerrechten, plichten en grondwettelijke begrippen.",
        "words": ["w2187","w2188","w2189","w2190","w2191","w2192","w2193","w2194"]
    },
    {
        "id": 244, "title": "Justitie & wetgeving", "emoji": "🔨", "level": "B1",
        "description": "Leer woorden over rechtspraak, wetten en het juridische systeem.",
        "words": ["w2195","w2196","w2197","w2198","w2199","w2200","w2201","w2202"]
    },
    {
        "id": 245, "title": "Immigratie & integratie", "emoji": "🌍", "level": "B1",
        "description": "Bespreek immigratie, integratie en multiculturele samenleving.",
        "words": ["w2203","w2204","w2205","w2206","w2207","w2208","w2209","w2210"]
    },
    {
        "id": 246, "title": "Vrijwilligerswerk & hulp", "emoji": "🤝", "level": "B1",
        "description": "Woorden over vrijwilligerswerk, liefdadigheid en hulpverlening.",
        "words": ["w2211","w2212","w2213","w2214","w2215","w2216","w2217","w2218"]
    },
    {
        "id": 247, "title": "Religie & geloof", "emoji": "🕊️", "level": "B1",
        "description": "Leer basisbegrippen rond religie, geloof en spiritualiteit.",
        "words": ["w2219","w2220","w2221","w2222","w2223","w2224","w2225","w2226"]
    },
    {
        "id": 248, "title": "Gelijkheid & diversiteit", "emoji": "🌈", "level": "B1",
        "description": "Praat over gelijkheid, diversiteit en inclusie.",
        "words": ["w2227","w2228","w2229","w2230","w2231","w2232","w2233","w2234"]
    },
    {
        "id": 249, "title": "Oorlog & vrede", "emoji": "☮️", "level": "B1",
        "description": "Woordenschat over conflicten, vrede en internationale betrekkingen.",
        "words": ["w2235","w2236","w2237","w2238","w2239","w2240","w2241","w2242"]
    },
    {
        "id": 250, "title": "Toetsles B1 — Blok 13 (les 241–250)", "emoji": "📝", "level": "B1",
        "description": "Herhaling van alle woorden uit blok 13: maatschappij en politiek.",
        "words": ["w2243","w2244","w2245","w2246","w2247","w2248","w2249","w2250"]
    },

    # ═══ BLOK 14: ZAKELIJK ITALIAANS (251–260) ═══════════════════════════════
    {
        "id": 251, "title": "Solliciteren — verdieping", "emoji": "📄", "level": "B1",
        "description": "Verdiep je sollicitatievaardigheden met formeel taalgebruik.",
        "grammar": {
            "title": "Formele briefconventies",
            "body": "In zakelijke brieven en e-mails gebruik je vaste formuleringen:\n\n• Aanhef: Gentile Signore/Signora (Geachte heer/mevrouw), Spettabile Ditta (Geachte firma)\n• Opening: Le scrivo in merito a… (Ik schrijf u met betrekking tot…)\n• Verzoek: La prego di… (Ik verzoek u om…), Vorrei chiedere… (Ik zou willen vragen…)\n• Afsluiting: In attesa di un Suo riscontro (In afwachting van uw reactie), Cordiali saluti (Met vriendelijke groet)\n\nGebruik altijd Lei (u-vorm) en de bijbehorende werkwoordsvorm (derde persoon enkelvoud)."
        },
        "words": ["w2251","w2252","w2253","w2254","w2255","w2256","w2257","w2258"]
    },
    {
        "id": 252, "title": "Het sollicitatiegesprek", "emoji": "🤵", "level": "B1",
        "description": "Bereid je voor op een sollicitatiegesprek in het Italiaans.",
        "words": ["w2259","w2260","w2261","w2262","w2263","w2264","w2265","w2266"]
    },
    {
        "id": 253, "title": "Vergaderen — verdieping", "emoji": "📋", "level": "B1",
        "description": "Verdiep je vergaderwoordenschat met formele uitdrukkingen.",
        "words": ["w2267","w2268","w2269","w2270","w2271","w2272","w2273","w2274"]
    },
    {
        "id": 254, "title": "Presentaties geven", "emoji": "📊", "level": "B1",
        "description": "Leer een presentatie structureren en geven in het Italiaans.",
        "words": ["w2275","w2276","w2277","w2278","w2279","w2280","w2281","w2282"]
    },
    {
        "id": 255, "title": "E-mails & brieven", "emoji": "📧", "level": "B1",
        "description": "Schrijf zakelijke e-mails en brieven in correct Italiaans.",
        "words": ["w2283","w2284","w2285","w2286","w2287","w2288","w2289","w2290"]
    },
    {
        "id": 256, "title": "Onderhandelen", "emoji": "🤝", "level": "B1",
        "description": "Leer onderhandelen en afspraken maken in zakelijke contexten.",
        "words": ["w2291","w2292","w2293","w2294","w2295","w2296","w2297","w2298"]
    },
    {
        "id": 257, "title": "Bedrijfscultuur", "emoji": "🏢", "level": "B1",
        "description": "Ontdek Italiaanse bedrijfscultuur en zakelijke omgangsvormen.",
        "words": ["w2299","w2300","w2301","w2302","w2303","w2304","w2305","w2306"]
    },
    {
        "id": 258, "title": "Import & export", "emoji": "🚢", "level": "B1",
        "description": "Woordenschat rond internationale handel, import en export.",
        "words": ["w2307","w2308","w2309","w2310","w2311","w2312","w2313","w2314"]
    },
    {
        "id": 259, "title": "Klantenservice", "emoji": "📞", "level": "B1",
        "description": "Leer klachten afhandelen en service bieden in het Italiaans.",
        "words": ["w2315","w2316","w2317","w2318","w2319","w2320","w2321","w2322"]
    },
    {
        "id": 260, "title": "Toetsles B1 — Blok 14 (les 251–260)", "emoji": "📝", "level": "B1",
        "description": "Herhaling van alle woorden uit blok 14: zakelijk Italiaans.",
        "words": ["w2323","w2324","w2325","w2326","w2327","w2328","w2329","w2330"]
    },

    # ═══ BLOK 15: GEZONDHEID & WETENSCHAP (261–270) ══════════════════════════
    {
        "id": 261, "title": "In het ziekenhuis", "emoji": "🏥", "level": "B1",
        "description": "Leer je redden in een Italiaans ziekenhuis.",
        "grammar": {
            "title": "Gebiedende wijs voor instructies",
            "body": "In medische contexten hoor je vaak de formele gebiedende wijs (imperativo con Lei). Deze wordt gevormd met de congiuntivo presente:\n\n• Prenda questa medicina. (Neem dit medicijn.)\n• Si sieda qui, per favore. (Gaat u hier zitten, alstublieft.)\n• Respiri profondamente. (Adem diep in.)\n• Non si preoccupi. (Maakt u zich geen zorgen.)\n\nVuistregel: voor de Lei-vorm gebruik je de hij/zij-vorm van de congiuntivo. Bij reflexieve werkwoorden komt si ervoor: si sieda, si riposi."
        },
        "words": ["w2331","w2332","w2333","w2334","w2335","w2336","w2337","w2338"]
    },
    {
        "id": 262, "title": "De apotheek", "emoji": "💊", "level": "B1",
        "description": "Koop medicijnen en vraag advies in een Italiaanse apotheek.",
        "words": ["w2339","w2340","w2341","w2342","w2343","w2344","w2345","w2346"]
    },
    {
        "id": 263, "title": "Geestelijke gezondheid", "emoji": "🧠", "level": "B1",
        "description": "Praat over stress, welzijn en geestelijke gezondheid.",
        "words": ["w2347","w2348","w2349","w2350","w2351","w2352","w2353","w2354"]
    },
    {
        "id": 264, "title": "Eerste hulp", "emoji": "🚑", "level": "B1",
        "description": "Leer noodsituaties beschrijven en eerste hulp vragen.",
        "words": ["w2355","w2356","w2357","w2358","w2359","w2360","w2361","w2362"]
    },
    {
        "id": 265, "title": "Wetenschap — basis", "emoji": "🔬", "level": "B1",
        "description": "Basiswoorden uit de wetenschap en het onderzoek.",
        "words": ["w2363","w2364","w2365","w2366","w2367","w2368","w2369","w2370"]
    },
    {
        "id": 266, "title": "Biologie & geneeskunde", "emoji": "🧬", "level": "B1",
        "description": "Leer termen uit de biologie en medische wetenschap.",
        "words": ["w2371","w2372","w2373","w2374","w2375","w2376","w2377","w2378"]
    },
    {
        "id": 267, "title": "Wiskunde & natuurkunde", "emoji": "📐", "level": "B1",
        "description": "Wiskundige en natuurkundige basisbegrippen in het Italiaans.",
        "words": ["w2379","w2380","w2381","w2382","w2383","w2384","w2385","w2386"]
    },
    {
        "id": 268, "title": "Uitvindingen & ontdekkingen", "emoji": "💡", "level": "B1",
        "description": "Praat over beroemde uitvindingen en wetenschappelijke ontdekkingen.",
        "words": ["w2387","w2388","w2389","w2390","w2391","w2392","w2393","w2394"]
    },
    {
        "id": 269, "title": "Ruimtevaart & sterrenkunde", "emoji": "🚀", "level": "B1",
        "description": "Ontdek de ruimte: planeten, sterren en ruimtereizen.",
        "words": ["w2395","w2396","w2397","w2398","w2399","w2400","w2401","w2402"]
    },
    {
        "id": 270, "title": "Toetsles B1 — Blok 15 (les 261–270)", "emoji": "📝", "level": "B1",
        "description": "Herhaling van alle woorden uit blok 15: gezondheid en wetenschap.",
        "words": ["w2403","w2404","w2405","w2406","w2407","w2408","w2409","w2410"]
    },
]

# ── WOORDEN ───────────────────────────────────────────────────────────────────

WORDS = [
    # ═══ LES 241: Politiek — basis ═══════════════════════════════════════════
    {"id": "w2171", "it": "la politica", "nl": "de politiek", "ph": "po-LI-ti-ka",
     "ex": "La politica italiana è molto complessa.", "exNl": "De Italiaanse politiek is erg complex.",
     "lesson": 241, "level": "B1", "cat": "sostantivo"},
    {"id": "w2172", "it": "il governo", "nl": "de regering", "ph": "go-VER-no",
     "ex": "Il governo ha approvato una nuova legge.", "exNl": "De regering heeft een nieuwe wet goedgekeurd.",
     "lesson": 241, "level": "B1", "cat": "sostantivo"},
    {"id": "w2173", "it": "il parlamento", "nl": "het parlement", "ph": "par-la-MEN-to",
     "ex": "Il parlamento si riunisce ogni settimana.", "exNl": "Het parlement komt elke week bijeen.",
     "lesson": 241, "level": "B1", "cat": "sostantivo"},
    {"id": "w2174", "it": "il partito", "nl": "de partij", "ph": "par-TI-to",
     "ex": "A quale partito appartieni?", "exNl": "Bij welke partij hoor je?",
     "lesson": 241, "level": "B1", "cat": "sostantivo"},
    {"id": "w2175", "it": "il deputato", "nl": "het parlementslid", "ph": "de-pu-TA-to",
     "ex": "Il deputato ha parlato in aula.", "exNl": "Het parlementslid heeft in de zaal gesproken.",
     "lesson": 241, "level": "B1", "cat": "sostantivo"},
    {"id": "w2176", "it": "la democrazia", "nl": "de democratie", "ph": "de-mo-kra-TSI-a",
     "ex": "La democrazia è un valore fondamentale.", "exNl": "Democratie is een fundamentele waarde.",
     "lesson": 241, "level": "B1", "cat": "sostantivo"},
    {"id": "w2177", "it": "governare", "nl": "regeren", "ph": "go-ver-NA-re",
     "ex": "Governare un paese non è facile.", "exNl": "Een land regeren is niet makkelijk.",
     "lesson": 241, "level": "B1", "cat": "verbo"},
    {"id": "w2178", "it": "la riforma", "nl": "de hervorming", "ph": "ri-FOR-ma",
     "ex": "La riforma viene discussa in parlamento.", "exNl": "De hervorming wordt besproken in het parlement.",
     "lesson": 241, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 242: Verkiezingen & democratie ══════════════════════════════════
    {"id": "w2179", "it": "le elezioni", "nl": "de verkiezingen", "ph": "e-le-TSJO-ni",
     "ex": "Le elezioni si terranno a giugno.", "exNl": "De verkiezingen worden in juni gehouden.",
     "lesson": 242, "level": "B1", "cat": "sostantivo"},
    {"id": "w2180", "it": "votare", "nl": "stemmen", "ph": "vo-TA-re",
     "ex": "Domani andrò a votare.", "exNl": "Morgen ga ik stemmen.",
     "lesson": 242, "level": "B1", "cat": "verbo"},
    {"id": "w2181", "it": "il voto", "nl": "de stem", "ph": "VO-to",
     "ex": "Ogni voto conta.", "exNl": "Elke stem telt.",
     "lesson": 242, "level": "B1", "cat": "sostantivo"},
    {"id": "w2182", "it": "il candidato", "nl": "de kandidaat", "ph": "kan-di-DA-to",
     "ex": "Chi è il tuo candidato preferito?", "exNl": "Wie is jouw favoriete kandidaat?",
     "lesson": 242, "level": "B1", "cat": "sostantivo"},
    {"id": "w2183", "it": "la campagna elettorale", "nl": "de verkiezingscampagne", "ph": "kam-PA-nja e-let-to-RA-le",
     "ex": "La campagna elettorale dura tre mesi.", "exNl": "De verkiezingscampagne duurt drie maanden.",
     "lesson": 242, "level": "B1", "cat": "espressione"},
    {"id": "w2184", "it": "il sondaggio", "nl": "de peiling", "ph": "son-DAD-djo",
     "ex": "Secondo i sondaggi, il partito è in testa.", "exNl": "Volgens de peilingen staat de partij op kop.",
     "lesson": 242, "level": "B1", "cat": "sostantivo"},
    {"id": "w2185", "it": "la maggioranza", "nl": "de meerderheid", "ph": "mad-djo-RAN-tsa",
     "ex": "La legge è stata approvata a maggioranza.", "exNl": "De wet is met meerderheid goedgekeurd.",
     "lesson": 242, "level": "B1", "cat": "sostantivo"},
    {"id": "w2186", "it": "l'opposizione", "nl": "de oppositie", "ph": "op-po-zi-TSJO-ne",
     "ex": "L'opposizione ha votato contro.", "exNl": "De oppositie heeft tegen gestemd.",
     "lesson": 242, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 243: Rechten & plichten ═════════════════════════════════════════
    {"id": "w2187", "it": "il diritto", "nl": "het recht", "ph": "di-RIT-to",
     "ex": "Tutti hanno diritto all'istruzione.", "exNl": "Iedereen heeft recht op onderwijs.",
     "lesson": 243, "level": "B1", "cat": "sostantivo"},
    {"id": "w2188", "it": "il dovere", "nl": "de plicht", "ph": "do-VE-re",
     "ex": "Pagare le tasse è un dovere civico.", "exNl": "Belasting betalen is een burgerplicht.",
     "lesson": 243, "level": "B1", "cat": "sostantivo"},
    {"id": "w2189", "it": "la libertà", "nl": "de vrijheid", "ph": "li-ber-TA",
     "ex": "La libertà di parola è un diritto fondamentale.", "exNl": "Vrijheid van meningsuiting is een grondrecht.",
     "lesson": 243, "level": "B1", "cat": "sostantivo"},
    {"id": "w2190", "it": "la costituzione", "nl": "de grondwet", "ph": "ko-sti-tu-TSJO-ne",
     "ex": "La costituzione italiana è del 1948.", "exNl": "De Italiaanse grondwet is uit 1948.",
     "lesson": 243, "level": "B1", "cat": "sostantivo"},
    {"id": "w2191", "it": "il cittadino", "nl": "de burger", "ph": "tsjiit-ta-DI-no",
     "ex": "Ogni cittadino ha diritto di voto.", "exNl": "Elke burger heeft stemrecht.",
     "lesson": 243, "level": "B1", "cat": "sostantivo"},
    {"id": "w2192", "it": "l'uguaglianza", "nl": "de gelijkheid", "ph": "u-gwa-LJAN-tsa",
     "ex": "L'uguaglianza davanti alla legge è garantita.", "exNl": "Gelijkheid voor de wet is gegarandeerd.",
     "lesson": 243, "level": "B1", "cat": "sostantivo"},
    {"id": "w2193", "it": "rispettare", "nl": "respecteren", "ph": "ris-pet-TA-re",
     "ex": "Bisogna rispettare le regole.", "exNl": "Je moet de regels respecteren.",
     "lesson": 243, "level": "B1", "cat": "verbo"},
    {"id": "w2194", "it": "la giustizia", "nl": "de rechtvaardigheid", "ph": "djus-TI-tsja",
     "ex": "Lottiamo per la giustizia sociale.", "exNl": "We strijden voor sociale rechtvaardigheid.",
     "lesson": 243, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 244: Justitie & wetgeving ═══════════════════════════════════════
    {"id": "w2195", "it": "la legge", "nl": "de wet", "ph": "LED-dje",
     "ex": "La legge è uguale per tutti.", "exNl": "De wet is voor iedereen gelijk.",
     "lesson": 244, "level": "B1", "cat": "sostantivo"},
    {"id": "w2196", "it": "il tribunale", "nl": "de rechtbank", "ph": "tri-bu-NA-le",
     "ex": "Il caso verrà discusso in tribunale.", "exNl": "De zaak wordt besproken in de rechtbank.",
     "lesson": 244, "level": "B1", "cat": "sostantivo"},
    {"id": "w2197", "it": "il giudice", "nl": "de rechter", "ph": "DJU-di-tsje",
     "ex": "Il giudice ha pronunciato la sentenza.", "exNl": "De rechter heeft het vonnis uitgesproken.",
     "lesson": 244, "level": "B1", "cat": "sostantivo"},
    {"id": "w2198", "it": "l'avvocato", "nl": "de advocaat", "ph": "av-vo-KA-to",
     "ex": "Ho bisogno di un avvocato.", "exNl": "Ik heb een advocaat nodig.",
     "lesson": 244, "level": "B1", "cat": "sostantivo"},
    {"id": "w2199", "it": "il reato", "nl": "het misdrijf", "ph": "re-A-to",
     "ex": "Il furto è un reato.", "exNl": "Diefstal is een misdrijf.",
     "lesson": 244, "level": "B1", "cat": "sostantivo"},
    {"id": "w2200", "it": "la pena", "nl": "de straf", "ph": "PE-na",
     "ex": "La pena è stata ridotta.", "exNl": "De straf is verminderd.",
     "lesson": 244, "level": "B1", "cat": "sostantivo"},
    {"id": "w2201", "it": "condannare", "nl": "veroordelen", "ph": "kon-dan-NA-re",
     "ex": "L'imputato è stato condannato.", "exNl": "De verdachte is veroordeeld.",
     "lesson": 244, "level": "B1", "cat": "verbo"},
    {"id": "w2202", "it": "la prova", "nl": "het bewijs", "ph": "PRO-va",
     "ex": "Non ci sono prove sufficienti.", "exNl": "Er is onvoldoende bewijs.",
     "lesson": 244, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 245: Immigratie & integratie ════════════════════════════════════
    {"id": "w2203", "it": "l'immigrazione", "nl": "de immigratie", "ph": "im-mi-gra-TSJO-ne",
     "ex": "L'immigrazione è un tema attuale.", "exNl": "Immigratie is een actueel thema.",
     "lesson": 245, "level": "B1", "cat": "sostantivo"},
    {"id": "w2204", "it": "l'immigrato", "nl": "de immigrant", "ph": "im-mi-GRA-to",
     "ex": "L'immigrato ha ottenuto il permesso di soggiorno.", "exNl": "De immigrant heeft een verblijfsvergunning gekregen.",
     "lesson": 245, "level": "B1", "cat": "sostantivo"},
    {"id": "w2205", "it": "il rifugiato", "nl": "de vluchteling", "ph": "ri-fu-DJA-to",
     "ex": "I rifugiati cercano protezione.", "exNl": "De vluchtelingen zoeken bescherming.",
     "lesson": 245, "level": "B1", "cat": "sostantivo"},
    {"id": "w2206", "it": "l'integrazione", "nl": "de integratie", "ph": "in-te-gra-TSJO-ne",
     "ex": "L'integrazione richiede impegno da entrambe le parti.", "exNl": "Integratie vereist inzet van beide kanten.",
     "lesson": 245, "level": "B1", "cat": "sostantivo"},
    {"id": "w2207", "it": "il permesso di soggiorno", "nl": "de verblijfsvergunning", "ph": "per-MES-so di sod-DJOR-no",
     "ex": "Il permesso di soggiorno va rinnovato.", "exNl": "De verblijfsvergunning moet verlengd worden.",
     "lesson": 245, "level": "B1", "cat": "espressione"},
    {"id": "w2208", "it": "accogliere", "nl": "opvangen / verwelkomen", "ph": "ak-KO-lje-re",
     "ex": "La comunità ha accolto bene i nuovi arrivati.", "exNl": "De gemeenschap heeft de nieuwkomers goed opgevangen.",
     "lesson": 245, "level": "B1", "cat": "verbo"},
    {"id": "w2209", "it": "la frontiera", "nl": "de grens", "ph": "fron-TJE-ra",
     "ex": "Abbiamo attraversato la frontiera.", "exNl": "We zijn de grens overgestoken.",
     "lesson": 245, "level": "B1", "cat": "sostantivo"},
    {"id": "w2210", "it": "la cittadinanza", "nl": "het burgerschap", "ph": "tsjiit-ta-di-NAN-tsa",
     "ex": "Ha richiesto la cittadinanza italiana.", "exNl": "Hij heeft het Italiaanse burgerschap aangevraagd.",
     "lesson": 245, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 246: Vrijwilligerswerk & hulp ═══════════════════════════════════
    {"id": "w2211", "it": "il volontariato", "nl": "het vrijwilligerswerk", "ph": "vo-lon-ta-ri-A-to",
     "ex": "Faccio volontariato ogni sabato.", "exNl": "Ik doe elke zaterdag vrijwilligerswerk.",
     "lesson": 246, "level": "B1", "cat": "sostantivo"},
    {"id": "w2212", "it": "il volontario", "nl": "de vrijwilliger", "ph": "vo-lon-TA-rjo",
     "ex": "I volontari hanno distribuito cibo.", "exNl": "De vrijwilligers hebben voedsel uitgedeeld.",
     "lesson": 246, "level": "B1", "cat": "sostantivo"},
    {"id": "w2213", "it": "l'associazione", "nl": "de vereniging", "ph": "as-so-tsja-TSJO-ne",
     "ex": "L'associazione aiuta le famiglie bisognose.", "exNl": "De vereniging helpt behoeftige gezinnen.",
     "lesson": 246, "level": "B1", "cat": "sostantivo"},
    {"id": "w2214", "it": "donare", "nl": "doneren / schenken", "ph": "do-NA-re",
     "ex": "Puoi donare vestiti e libri.", "exNl": "Je kunt kleding en boeken doneren.",
     "lesson": 246, "level": "B1", "cat": "verbo"},
    {"id": "w2215", "it": "la donazione", "nl": "de donatie", "ph": "do-na-TSJO-ne",
     "ex": "Abbiamo ricevuto molte donazioni.", "exNl": "We hebben veel donaties ontvangen.",
     "lesson": 246, "level": "B1", "cat": "sostantivo"},
    {"id": "w2216", "it": "la solidarietà", "nl": "de solidariteit", "ph": "so-li-da-rje-TA",
     "ex": "La solidarietà è importante nei momenti difficili.", "exNl": "Solidariteit is belangrijk in moeilijke tijden.",
     "lesson": 246, "level": "B1", "cat": "sostantivo"},
    {"id": "w2217", "it": "la raccolta fondi", "nl": "de fondsenwerving", "ph": "rak-KOL-ta FON-di",
     "ex": "Organizziamo una raccolta fondi per la scuola.", "exNl": "We organiseren een fondsenwerving voor de school.",
     "lesson": 246, "level": "B1", "cat": "espressione"},
    {"id": "w2218", "it": "sostenere", "nl": "steunen / ondersteunen", "ph": "sos-te-NE-re",
     "ex": "Dobbiamo sostenere chi è in difficoltà.", "exNl": "We moeten wie in moeilijkheden zit ondersteunen.",
     "lesson": 246, "level": "B1", "cat": "verbo"},

    # ═══ LES 247: Religie & geloof ═══════════════════════════════════════════
    {"id": "w2219", "it": "la religione", "nl": "de religie / het geloof", "ph": "re-li-DJO-ne",
     "ex": "In Italia la religione principale è il cattolicesimo.", "exNl": "In Italië is de voornaamste religie het katholicisme.",
     "lesson": 247, "level": "B1", "cat": "sostantivo"},
    {"id": "w2220", "it": "la chiesa", "nl": "de kerk", "ph": "KJE-za",
     "ex": "La chiesa del paese è molto antica.", "exNl": "De dorpskerk is erg oud.",
     "lesson": 247, "level": "B1", "cat": "sostantivo"},
    {"id": "w2221", "it": "credere", "nl": "geloven", "ph": "KRE-de-re",
     "ex": "Ognuno è libero di credere in ciò che vuole.", "exNl": "Iedereen is vrij om te geloven wat hij wil.",
     "lesson": 247, "level": "B1", "cat": "verbo"},
    {"id": "w2222", "it": "la fede", "nl": "het geloof", "ph": "FE-de",
     "ex": "La fede lo aiuta nei momenti difficili.", "exNl": "Het geloof helpt hem in moeilijke momenten.",
     "lesson": 247, "level": "B1", "cat": "sostantivo"},
    {"id": "w2223", "it": "pregare", "nl": "bidden", "ph": "pre-GA-re",
     "ex": "Mia nonna prega ogni sera.", "exNl": "Mijn oma bidt elke avond.",
     "lesson": 247, "level": "B1", "cat": "verbo"},
    {"id": "w2224", "it": "la tradizione", "nl": "de traditie", "ph": "tra-di-TSJO-ne",
     "ex": "Questa tradizione risale al Medioevo.", "exNl": "Deze traditie gaat terug tot de middeleeuwen.",
     "lesson": 247, "level": "B1", "cat": "sostantivo"},
    {"id": "w2225", "it": "sacro", "nl": "heilig / sacraal", "ph": "SA-kro",
     "ex": "Questo è un luogo sacro.", "exNl": "Dit is een heilige plek.",
     "lesson": 247, "level": "B1", "cat": "aggettivo"},
    {"id": "w2226", "it": "la cerimonia", "nl": "de ceremonie", "ph": "tsje-ri-MO-nja",
     "ex": "La cerimonia si svolge in chiesa.", "exNl": "De ceremonie vindt plaats in de kerk.",
     "lesson": 247, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 248: Gelijkheid & diversiteit ═══════════════════════════════════
    {"id": "w2227", "it": "la diversità", "nl": "de diversiteit", "ph": "di-ver-si-TA",
     "ex": "La diversità è una ricchezza.", "exNl": "Diversiteit is een rijkdom.",
     "lesson": 248, "level": "B1", "cat": "sostantivo"},
    {"id": "w2228", "it": "l'inclusione", "nl": "de inclusie", "ph": "in-klu-ZJO-ne",
     "ex": "L'inclusione è un obiettivo importante.", "exNl": "Inclusie is een belangrijk doel.",
     "lesson": 248, "level": "B1", "cat": "sostantivo"},
    {"id": "w2229", "it": "la discriminazione", "nl": "de discriminatie", "ph": "dis-kri-mi-na-TSJO-ne",
     "ex": "La discriminazione è vietata dalla legge.", "exNl": "Discriminatie is verboden bij wet.",
     "lesson": 248, "level": "B1", "cat": "sostantivo"},
    {"id": "w2230", "it": "il pregiudizio", "nl": "het vooroordeel", "ph": "pre-dju-DI-tsjo",
     "ex": "Dobbiamo combattere i pregiudizi.", "exNl": "We moeten vooroordelen bestrijden.",
     "lesson": 248, "level": "B1", "cat": "sostantivo"},
    {"id": "w2231", "it": "la parità", "nl": "de gelijkheid / pariteit", "ph": "pa-ri-TA",
     "ex": "La parità di genere è fondamentale.", "exNl": "Gendergelijkheid is fundamenteel.",
     "lesson": 248, "level": "B1", "cat": "sostantivo"},
    {"id": "w2232", "it": "la minoranza", "nl": "de minderheid", "ph": "mi-no-RAN-tsa",
     "ex": "Le minoranze devono essere tutelate.", "exNl": "Minderheden moeten beschermd worden.",
     "lesson": 248, "level": "B1", "cat": "sostantivo"},
    {"id": "w2233", "it": "tollerante", "nl": "tolerant", "ph": "tol-le-RAN-te",
     "ex": "Una società tollerante rispetta le differenze.", "exNl": "Een tolerante samenleving respecteert verschillen.",
     "lesson": 248, "level": "B1", "cat": "aggettivo"},
    {"id": "w2234", "it": "il razzismo", "nl": "het racisme", "ph": "rat-TSIZ-mo",
     "ex": "Il razzismo non ha giustificazione.", "exNl": "Racisme heeft geen rechtvaardiging.",
     "lesson": 248, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 249: Oorlog & vrede ═════════════════════════════════════════════
    {"id": "w2235", "it": "la guerra", "nl": "de oorlog", "ph": "GWER-ra",
     "ex": "La guerra porta solo sofferenza.", "exNl": "Oorlog brengt alleen maar lijden.",
     "lesson": 249, "level": "B1", "cat": "sostantivo"},
    {"id": "w2236", "it": "la pace", "nl": "de vrede", "ph": "PA-tsje",
     "ex": "Tutti desiderano la pace.", "exNl": "Iedereen verlangt naar vrede.",
     "lesson": 249, "level": "B1", "cat": "sostantivo"},
    {"id": "w2237", "it": "il conflitto", "nl": "het conflict", "ph": "kon-FLIT-to",
     "ex": "Il conflitto dura da anni.", "exNl": "Het conflict duurt al jaren.",
     "lesson": 249, "level": "B1", "cat": "sostantivo"},
    {"id": "w2238", "it": "l'esercito", "nl": "het leger", "ph": "e-ZER-tsji-to",
     "ex": "L'esercito è stato inviato nella zona.", "exNl": "Het leger is naar het gebied gestuurd.",
     "lesson": 249, "level": "B1", "cat": "sostantivo"},
    {"id": "w2239", "it": "il trattato", "nl": "het verdrag", "ph": "trat-TA-to",
     "ex": "I paesi hanno firmato un trattato di pace.", "exNl": "De landen hebben een vredesverdrag getekend.",
     "lesson": 249, "level": "B1", "cat": "sostantivo"},
    {"id": "w2240", "it": "la sicurezza", "nl": "de veiligheid", "ph": "si-ku-RET-tsa",
     "ex": "La sicurezza dei cittadini è la priorità.", "exNl": "De veiligheid van de burgers is de prioriteit.",
     "lesson": 249, "level": "B1", "cat": "sostantivo"},
    {"id": "w2241", "it": "difendere", "nl": "verdedigen", "ph": "di-FEN-de-re",
     "ex": "Dobbiamo difendere i nostri diritti.", "exNl": "We moeten onze rechten verdedigen.",
     "lesson": 249, "level": "B1", "cat": "verbo"},
    {"id": "w2242", "it": "la diplomazia", "nl": "de diplomatie", "ph": "di-plo-ma-TSI-a",
     "ex": "La diplomazia è la chiave per risolvere i conflitti.", "exNl": "Diplomatie is de sleutel om conflicten op te lossen.",
     "lesson": 249, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 250: Toetsles B1 — Blok 13 ═════════════════════════════════════
    {"id": "w2243", "it": "lo stato", "nl": "de staat", "ph": "STA-to",
     "ex": "Lo stato deve proteggere i suoi cittadini.", "exNl": "De staat moet zijn burgers beschermen.",
     "lesson": 250, "level": "B1", "cat": "sostantivo"},
    {"id": "w2244", "it": "la società", "nl": "de samenleving / maatschappij", "ph": "so-tsje-TA",
     "ex": "Viviamo in una società multiculturale.", "exNl": "We leven in een multiculturele samenleving.",
     "lesson": 250, "level": "B1", "cat": "sostantivo"},
    {"id": "w2245", "it": "il dibattito", "nl": "het debat", "ph": "di-BAT-ti-to",
     "ex": "Il dibattito politico è stato acceso.", "exNl": "Het politieke debat was verhit.",
     "lesson": 250, "level": "B1", "cat": "sostantivo"},
    {"id": "w2246", "it": "la manifestazione", "nl": "de demonstratie / betoging", "ph": "ma-ni-fes-ta-TSJO-ne",
     "ex": "C'è stata una grande manifestazione in piazza.", "exNl": "Er was een grote demonstratie op het plein.",
     "lesson": 250, "level": "B1", "cat": "sostantivo"},
    {"id": "w2247", "it": "protestare", "nl": "protesteren", "ph": "pro-tes-TA-re",
     "ex": "I cittadini hanno protestato contro la nuova legge.", "exNl": "De burgers hebben geprotesteerd tegen de nieuwe wet.",
     "lesson": 250, "level": "B1", "cat": "verbo"},
    {"id": "w2248", "it": "la crisi", "nl": "de crisis", "ph": "KRI-zi",
     "ex": "Il paese affronta una crisi economica.", "exNl": "Het land kampt met een economische crisis.",
     "lesson": 250, "level": "B1", "cat": "sostantivo"},
    {"id": "w2249", "it": "la cooperazione", "nl": "de samenwerking", "ph": "ko-o-pe-ra-TSJO-ne",
     "ex": "La cooperazione internazionale è essenziale.", "exNl": "Internationale samenwerking is essentieel.",
     "lesson": 250, "level": "B1", "cat": "sostantivo"},
    {"id": "w2250", "it": "il compromesso", "nl": "het compromis", "ph": "kom-pro-MES-so",
     "ex": "Abbiamo raggiunto un buon compromesso.", "exNl": "We hebben een goed compromis bereikt.",
     "lesson": 250, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 251: Solliciteren — verdieping ══════════════════════════════════
    {"id": "w2251", "it": "il curriculum vitae", "nl": "het cv", "ph": "kur-RI-ku-lum VI-te",
     "ex": "Ho aggiornato il mio curriculum vitae.", "exNl": "Ik heb mijn cv bijgewerkt.",
     "lesson": 251, "level": "B1", "cat": "sostantivo"},
    {"id": "w2252", "it": "la lettera di presentazione", "nl": "de sollicitatiebrief", "ph": "LET-te-ra di pre-zen-ta-TSJO-ne",
     "ex": "La lettera di presentazione deve essere personalizzata.", "exNl": "De sollicitatiebrief moet persoonlijk zijn.",
     "lesson": 251, "level": "B1", "cat": "espressione"},
    {"id": "w2253", "it": "candidarsi", "nl": "solliciteren", "ph": "kan-di-DAR-si",
     "ex": "Mi sono candidato per il posto di direttore.", "exNl": "Ik heb gesolliciteerd naar de functie van directeur.",
     "lesson": 251, "level": "B1", "cat": "verbo"},
    {"id": "w2254", "it": "l'annuncio di lavoro", "nl": "de vacature", "ph": "an-NUN-tsjo di la-VO-ro",
     "ex": "Ho visto un annuncio di lavoro interessante.", "exNl": "Ik heb een interessante vacature gezien.",
     "lesson": 251, "level": "B1", "cat": "espressione"},
    {"id": "w2255", "it": "le competenze", "nl": "de vaardigheden / competenties", "ph": "kom-pe-TEN-tse",
     "ex": "Quali competenze richiede questo lavoro?", "exNl": "Welke vaardigheden vereist dit werk?",
     "lesson": 251, "level": "B1", "cat": "sostantivo"},
    {"id": "w2256", "it": "l'esperienza lavorativa", "nl": "de werkervaring", "ph": "es-pe-RJEN-tsa la-vo-ra-TI-va",
     "ex": "Ho cinque anni di esperienza lavorativa.", "exNl": "Ik heb vijf jaar werkervaring.",
     "lesson": 251, "level": "B1", "cat": "espressione"},
    {"id": "w2257", "it": "la qualifica", "nl": "de kwalificatie", "ph": "kwa-LI-fi-ka",
     "ex": "La qualifica richiesta è una laurea.", "exNl": "De vereiste kwalificatie is een diploma.",
     "lesson": 251, "level": "B1", "cat": "sostantivo"},
    {"id": "w2258", "it": "assumere", "nl": "aannemen (personeel)", "ph": "as-SU-me-re",
     "ex": "L'azienda ha assunto dieci nuovi dipendenti.", "exNl": "Het bedrijf heeft tien nieuwe medewerkers aangenomen.",
     "lesson": 251, "level": "B1", "cat": "verbo"},

    # ═══ LES 252: Het sollicitatiegesprek ════════════════════════════════════
    {"id": "w2259", "it": "il colloquio di lavoro", "nl": "het sollicitatiegesprek", "ph": "kol-LO-kwjo di la-VO-ro",
     "ex": "Ho un colloquio di lavoro domani mattina.", "exNl": "Ik heb morgenochtend een sollicitatiegesprek.",
     "lesson": 252, "level": "B1", "cat": "espressione"},
    {"id": "w2260", "it": "il punto di forza", "nl": "het sterke punt", "ph": "PUN-to di FOR-tsa",
     "ex": "Qual è il tuo punto di forza?", "exNl": "Wat is jouw sterke punt?",
     "lesson": 252, "level": "B1", "cat": "espressione"},
    {"id": "w2261", "it": "il punto debole", "nl": "het zwakke punt", "ph": "PUN-to DE-bo-le",
     "ex": "Ogni persona ha un punto debole.", "exNl": "Ieder mens heeft een zwak punt.",
     "lesson": 252, "level": "B1", "cat": "espressione"},
    {"id": "w2262", "it": "motivato", "nl": "gemotiveerd", "ph": "mo-ti-VA-to",
     "ex": "Sono molto motivato per questa posizione.", "exNl": "Ik ben erg gemotiveerd voor deze functie.",
     "lesson": 252, "level": "B1", "cat": "aggettivo"},
    {"id": "w2263", "it": "lo stipendio", "nl": "het salaris", "ph": "sti-PEN-djo",
     "ex": "Lo stipendio è negoziabile.", "exNl": "Het salaris is onderhandelbaar.",
     "lesson": 252, "level": "B1", "cat": "sostantivo"},
    {"id": "w2264", "it": "la disponibilità", "nl": "de beschikbaarheid", "ph": "dis-po-ni-bi-li-TA",
     "ex": "Qual è la tua disponibilità?", "exNl": "Wat is jouw beschikbaarheid?",
     "lesson": 252, "level": "B1", "cat": "sostantivo"},
    {"id": "w2265", "it": "selezionare", "nl": "selecteren", "ph": "se-le-tsjo-NA-re",
     "ex": "Abbiamo selezionato tre candidati.", "exNl": "We hebben drie kandidaten geselecteerd.",
     "lesson": 252, "level": "B1", "cat": "verbo"},
    {"id": "w2266", "it": "il contratto", "nl": "het contract", "ph": "kon-TRAT-to",
     "ex": "Ho firmato il contratto a tempo indeterminato.", "exNl": "Ik heb het contract voor onbepaalde tijd getekend.",
     "lesson": 252, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 253: Vergaderen — verdieping ════════════════════════════════════
    {"id": "w2267", "it": "la riunione", "nl": "de vergadering", "ph": "ri-u-NJO-ne",
     "ex": "La riunione è fissata per le tre.", "exNl": "De vergadering is gepland om drie uur.",
     "lesson": 253, "level": "B1", "cat": "sostantivo"},
    {"id": "w2268", "it": "l'ordine del giorno", "nl": "de agenda (vergadering)", "ph": "OR-di-ne del DJOR-no",
     "ex": "Qual è l'ordine del giorno?", "exNl": "Wat staat er op de agenda?",
     "lesson": 253, "level": "B1", "cat": "espressione"},
    {"id": "w2269", "it": "il verbale", "nl": "de notulen", "ph": "ver-BA-le",
     "ex": "Chi scrive il verbale della riunione?", "exNl": "Wie schrijft de notulen van de vergadering?",
     "lesson": 253, "level": "B1", "cat": "sostantivo"},
    {"id": "w2270", "it": "proporre", "nl": "voorstellen", "ph": "pro-POR-re",
     "ex": "Vorrei proporre una nuova strategia.", "exNl": "Ik zou een nieuwe strategie willen voorstellen.",
     "lesson": 253, "level": "B1", "cat": "verbo"},
    {"id": "w2271", "it": "la decisione", "nl": "de beslissing", "ph": "de-tsji-ZJO-ne",
     "ex": "La decisione è stata presa all'unanimità.", "exNl": "De beslissing is unaniem genomen.",
     "lesson": 253, "level": "B1", "cat": "sostantivo"},
    {"id": "w2272", "it": "concordare", "nl": "overeenkomen / afspreken", "ph": "kon-kor-DA-re",
     "ex": "Abbiamo concordato una data per la riunione.", "exNl": "We zijn een datum voor de vergadering overeengekomen.",
     "lesson": 253, "level": "B1", "cat": "verbo"},
    {"id": "w2273", "it": "la scadenza", "nl": "de deadline", "ph": "ska-DEN-tsa",
     "ex": "La scadenza del progetto è venerdì.", "exNl": "De deadline van het project is vrijdag.",
     "lesson": 253, "level": "B1", "cat": "sostantivo"},
    {"id": "w2274", "it": "approvare", "nl": "goedkeuren", "ph": "ap-pro-VA-re",
     "ex": "Il consiglio ha approvato il budget.", "exNl": "De raad heeft het budget goedgekeurd.",
     "lesson": 253, "level": "B1", "cat": "verbo"},

    # ═══ LES 254: Presentaties geven ═════════════════════════════════════════
    {"id": "w2275", "it": "la presentazione", "nl": "de presentatie", "ph": "pre-zen-ta-TSJO-ne",
     "ex": "La presentazione è durata venti minuti.", "exNl": "De presentatie duurde twintig minuten.",
     "lesson": 254, "level": "B1", "cat": "sostantivo"},
    {"id": "w2276", "it": "la diapositiva", "nl": "de dia / slide", "ph": "dja-po-zi-TI-va",
     "ex": "Passiamo alla prossima diapositiva.", "exNl": "Laten we naar de volgende slide gaan.",
     "lesson": 254, "level": "B1", "cat": "sostantivo"},
    {"id": "w2277", "it": "il grafico", "nl": "de grafiek", "ph": "GRA-fi-ko",
     "ex": "Il grafico mostra la crescita delle vendite.", "exNl": "De grafiek toont de groei van de verkoop.",
     "lesson": 254, "level": "B1", "cat": "sostantivo"},
    {"id": "w2278", "it": "riassumere", "nl": "samenvatten", "ph": "ri-as-SU-me-re",
     "ex": "Vorrei riassumere i punti principali.", "exNl": "Ik wil de hoofdpunten samenvatten.",
     "lesson": 254, "level": "B1", "cat": "verbo"},
    {"id": "w2279", "it": "il pubblico", "nl": "het publiek", "ph": "PUB-bli-ko",
     "ex": "Il pubblico ha fatto molte domande.", "exNl": "Het publiek stelde veel vragen.",
     "lesson": 254, "level": "B1", "cat": "sostantivo"},
    {"id": "w2280", "it": "evidenziare", "nl": "benadrukken", "ph": "e-vi-den-TSJA-re",
     "ex": "Vorrei evidenziare un aspetto importante.", "exNl": "Ik wil een belangrijk aspect benadrukken.",
     "lesson": 254, "level": "B1", "cat": "verbo"},
    {"id": "w2281", "it": "la conclusione", "nl": "de conclusie", "ph": "kon-klu-ZJO-ne",
     "ex": "In conclusione, i risultati sono positivi.", "exNl": "Tot slot, de resultaten zijn positief.",
     "lesson": 254, "level": "B1", "cat": "sostantivo"},
    {"id": "w2282", "it": "il dato", "nl": "het gegeven / de data", "ph": "DA-to",
     "ex": "I dati confermano la nostra ipotesi.", "exNl": "De gegevens bevestigen onze hypothese.",
     "lesson": 254, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 255: E-mails & brieven ══════════════════════════════════════════
    {"id": "w2283", "it": "l'allegato", "nl": "de bijlage", "ph": "al-le-GA-to",
     "ex": "In allegato trova il documento richiesto.", "exNl": "In de bijlage vindt u het gevraagde document.",
     "lesson": 255, "level": "B1", "cat": "sostantivo"},
    {"id": "w2284", "it": "l'oggetto", "nl": "het onderwerp (e-mail)", "ph": "od-DJET-to",
     "ex": "L'oggetto dell'e-mail deve essere chiaro.", "exNl": "Het onderwerp van de e-mail moet duidelijk zijn.",
     "lesson": 255, "level": "B1", "cat": "sostantivo"},
    {"id": "w2285", "it": "il destinatario", "nl": "de ontvanger", "ph": "des-ti-na-TA-rjo",
     "ex": "Controlla il destinatario prima di inviare.", "exNl": "Controleer de ontvanger voordat je verstuurt.",
     "lesson": 255, "level": "B1", "cat": "sostantivo"},
    {"id": "w2286", "it": "il mittente", "nl": "de afzender", "ph": "mit-TEN-te",
     "ex": "Non riconosco il mittente di questa e-mail.", "exNl": "Ik herken de afzender van deze e-mail niet.",
     "lesson": 255, "level": "B1", "cat": "sostantivo"},
    {"id": "w2287", "it": "inoltrare", "nl": "doorsturen", "ph": "i-nol-TRA-re",
     "ex": "Può inoltrare il messaggio ai colleghi?", "exNl": "Kunt u het bericht doorsturen naar de collega's?",
     "lesson": 255, "level": "B1", "cat": "verbo"},
    {"id": "w2288", "it": "rispondere", "nl": "antwoorden / beantwoorden", "ph": "ris-PON-de-re",
     "ex": "Le risponderò entro domani.", "exNl": "Ik zal u uiterlijk morgen antwoorden.",
     "lesson": 255, "level": "B1", "cat": "verbo"},
    {"id": "w2289", "it": "la firma", "nl": "de handtekening", "ph": "FIR-ma",
     "ex": "Manca la firma in fondo alla lettera.", "exNl": "De handtekening onderaan de brief ontbreekt.",
     "lesson": 255, "level": "B1", "cat": "sostantivo"},
    {"id": "w2290", "it": "confermare", "nl": "bevestigen", "ph": "kon-fer-MA-re",
     "ex": "Le confermo la ricezione del documento.", "exNl": "Ik bevestig de ontvangst van het document.",
     "lesson": 255, "level": "B1", "cat": "verbo"},

    # ═══ LES 256: Onderhandelen ═══════════════════════════════════════════════
    {"id": "w2291", "it": "negoziare", "nl": "onderhandelen", "ph": "ne-go-TSJA-re",
     "ex": "Dobbiamo negoziare le condizioni del contratto.", "exNl": "We moeten over de voorwaarden van het contract onderhandelen.",
     "lesson": 256, "level": "B1", "cat": "verbo"},
    {"id": "w2292", "it": "la trattativa", "nl": "de onderhandeling", "ph": "trat-ta-TI-va",
     "ex": "Le trattative sono in corso.", "exNl": "De onderhandelingen zijn gaande.",
     "lesson": 256, "level": "B1", "cat": "sostantivo"},
    {"id": "w2293", "it": "l'accordo", "nl": "de overeenkomst", "ph": "ak-KOR-do",
     "ex": "Abbiamo raggiunto un accordo.", "exNl": "We hebben een overeenkomst bereikt.",
     "lesson": 256, "level": "B1", "cat": "sostantivo"},
    {"id": "w2294", "it": "la condizione", "nl": "de voorwaarde", "ph": "kon-di-TSJO-ne",
     "ex": "Quali sono le condizioni di pagamento?", "exNl": "Wat zijn de betalingsvoorwaarden?",
     "lesson": 256, "level": "B1", "cat": "sostantivo"},
    {"id": "w2295", "it": "lo sconto", "nl": "de korting", "ph": "SKON-to",
     "ex": "Possiamo offrire uno sconto del dieci per cento.", "exNl": "We kunnen een korting van tien procent bieden.",
     "lesson": 256, "level": "B1", "cat": "sostantivo"},
    {"id": "w2296", "it": "la proposta", "nl": "het voorstel", "ph": "pro-POS-ta",
     "ex": "La proposta è stata accettata.", "exNl": "Het voorstel is geaccepteerd.",
     "lesson": 256, "level": "B1", "cat": "sostantivo"},
    {"id": "w2297", "it": "rifiutare", "nl": "weigeren / afwijzen", "ph": "ri-fju-TA-re",
     "ex": "Hanno rifiutato la nostra offerta.", "exNl": "Ze hebben ons aanbod afgewezen.",
     "lesson": 256, "level": "B1", "cat": "verbo"},
    {"id": "w2298", "it": "la garanzia", "nl": "de garantie", "ph": "ga-ran-TSI-a",
     "ex": "Il prodotto ha due anni di garanzia.", "exNl": "Het product heeft twee jaar garantie.",
     "lesson": 256, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 257: Bedrijfscultuur ════════════════════════════════════════════
    {"id": "w2299", "it": "la gerarchia", "nl": "de hiërarchie", "ph": "dje-rar-KI-a",
     "ex": "In Italia la gerarchia aziendale è importante.", "exNl": "In Italië is de bedrijfshiërarchie belangrijk.",
     "lesson": 257, "level": "B1", "cat": "sostantivo"},
    {"id": "w2300", "it": "il capo", "nl": "de baas / chef", "ph": "KA-po",
     "ex": "Il capo ha convocato una riunione.", "exNl": "De baas heeft een vergadering bijeengeroepen.",
     "lesson": 257, "level": "B1", "cat": "sostantivo"},
    {"id": "w2301", "it": "il dipendente", "nl": "de werknemer", "ph": "di-pen-DEN-te",
     "ex": "I dipendenti ricevono un bonus a dicembre.", "exNl": "De werknemers ontvangen in december een bonus.",
     "lesson": 257, "level": "B1", "cat": "sostantivo"},
    {"id": "w2302", "it": "la formazione", "nl": "de opleiding / training", "ph": "for-ma-TSJO-ne",
     "ex": "L'azienda offre corsi di formazione.", "exNl": "Het bedrijf biedt trainingen aan.",
     "lesson": 257, "level": "B1", "cat": "sostantivo"},
    {"id": "w2303", "it": "professionale", "nl": "professioneel", "ph": "pro-fes-sjo-NA-le",
     "ex": "Mantieni sempre un atteggiamento professionale.", "exNl": "Houd altijd een professionele houding aan.",
     "lesson": 257, "level": "B1", "cat": "aggettivo"},
    {"id": "w2304", "it": "la pausa pranzo", "nl": "de lunchpauze", "ph": "PAU-za PRAN-tso",
     "ex": "In Italia la pausa pranzo è sacra.", "exNl": "In Italië is de lunchpauze heilig.",
     "lesson": 257, "level": "B1", "cat": "espressione"},
    {"id": "w2305", "it": "il lavoro di squadra", "nl": "het teamwerk", "ph": "la-VO-ro di SKWA-dra",
     "ex": "Il lavoro di squadra è fondamentale.", "exNl": "Teamwerk is fundamenteel.",
     "lesson": 257, "level": "B1", "cat": "espressione"},
    {"id": "w2306", "it": "la sede", "nl": "het (hoofd)kantoor", "ph": "SE-de",
     "ex": "La sede principale è a Milano.", "exNl": "Het hoofdkantoor is in Milaan.",
     "lesson": 257, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 258: Import & export ════════════════════════════════════════════
    {"id": "w2307", "it": "l'importazione", "nl": "de import", "ph": "im-por-ta-TSJO-ne",
     "ex": "L'importazione di vino è aumentata.", "exNl": "De import van wijn is gestegen.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},
    {"id": "w2308", "it": "l'esportazione", "nl": "de export", "ph": "es-por-ta-TSJO-ne",
     "ex": "L'esportazione di prodotti italiani è forte.", "exNl": "De export van Italiaanse producten is sterk.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},
    {"id": "w2309", "it": "la merce", "nl": "de goederen / waar", "ph": "MER-tsje",
     "ex": "La merce è arrivata in porto.", "exNl": "De goederen zijn in de haven aangekomen.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},
    {"id": "w2310", "it": "la dogana", "nl": "de douane", "ph": "do-GA-na",
     "ex": "La merce deve passare la dogana.", "exNl": "De goederen moeten door de douane.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},
    {"id": "w2311", "it": "la spedizione", "nl": "de verzending", "ph": "spe-di-TSJO-ne",
     "ex": "La spedizione arriverà tra tre giorni.", "exNl": "De verzending komt over drie dagen aan.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},
    {"id": "w2312", "it": "il fornitore", "nl": "de leverancier", "ph": "for-ni-TO-re",
     "ex": "Abbiamo cambiato fornitore.", "exNl": "We zijn van leverancier veranderd.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},
    {"id": "w2313", "it": "la fattura", "nl": "de factuur", "ph": "fat-TU-ra",
     "ex": "La fattura è stata pagata.", "exNl": "De factuur is betaald.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},
    {"id": "w2314", "it": "il magazzino", "nl": "het magazijn / de opslagplaats", "ph": "ma-gad-DZI-no",
     "ex": "Le merci sono stoccate nel magazzino.", "exNl": "De goederen zijn opgeslagen in het magazijn.",
     "lesson": 258, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 259: Klantenservice ═════════════════════════════════════════════
    {"id": "w2315", "it": "il reclamo", "nl": "de klacht", "ph": "re-KLA-mo",
     "ex": "Vorrei fare un reclamo.", "exNl": "Ik wil een klacht indienen.",
     "lesson": 259, "level": "B1", "cat": "sostantivo"},
    {"id": "w2316", "it": "il rimborso", "nl": "de terugbetaling", "ph": "rim-BOR-so",
     "ex": "Ho richiesto un rimborso.", "exNl": "Ik heb een terugbetaling aangevraagd.",
     "lesson": 259, "level": "B1", "cat": "sostantivo"},
    {"id": "w2317", "it": "la soddisfazione", "nl": "de tevredenheid", "ph": "sod-dis-fa-TSJO-ne",
     "ex": "La soddisfazione del cliente è la nostra priorità.", "exNl": "Klanttevredenheid is onze prioriteit.",
     "lesson": 259, "level": "B1", "cat": "sostantivo"},
    {"id": "w2318", "it": "il servizio clienti", "nl": "de klantenservice", "ph": "ser-VI-tsjo kli-EN-ti",
     "ex": "Contatti il nostro servizio clienti.", "exNl": "Neem contact op met onze klantenservice.",
     "lesson": 259, "level": "B1", "cat": "espressione"},
    {"id": "w2319", "it": "la sostituzione", "nl": "de vervanging", "ph": "sos-ti-tu-TSJO-ne",
     "ex": "Chiedo la sostituzione del prodotto difettoso.", "exNl": "Ik vraag om vervanging van het defecte product.",
     "lesson": 259, "level": "B1", "cat": "sostantivo"},
    {"id": "w2320", "it": "risolvere", "nl": "oplossen", "ph": "ri-ZOL-ve-re",
     "ex": "Cercheremo di risolvere il problema rapidamente.", "exNl": "We zullen proberen het probleem snel op te lossen.",
     "lesson": 259, "level": "B1", "cat": "verbo"},
    {"id": "w2321", "it": "scusarsi", "nl": "zich verontschuldigen", "ph": "sku-ZAR-si",
     "ex": "Ci scusiamo per il disagio.", "exNl": "We verontschuldigen ons voor het ongemak.",
     "lesson": 259, "level": "B1", "cat": "verbo"},
    {"id": "w2322", "it": "il difetto", "nl": "het defect / gebrek", "ph": "di-FET-to",
     "ex": "Il prodotto ha un difetto di fabbricazione.", "exNl": "Het product heeft een fabricagefout.",
     "lesson": 259, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 260: Toetsles B1 — Blok 14 ═════════════════════════════════════
    {"id": "w2323", "it": "il collega", "nl": "de collega", "ph": "kol-LE-ga",
     "ex": "Il mio collega lavora nel reparto vendite.", "exNl": "Mijn collega werkt op de verkoopafdeling.",
     "lesson": 260, "level": "B1", "cat": "sostantivo"},
    {"id": "w2324", "it": "la strategia", "nl": "de strategie", "ph": "stra-te-DJI-a",
     "ex": "La strategia aziendale è cambiata.", "exNl": "De bedrijfsstrategie is veranderd.",
     "lesson": 260, "level": "B1", "cat": "sostantivo"},
    {"id": "w2325", "it": "il bilancio", "nl": "de balans / het budget", "ph": "bi-LAN-tsjo",
     "ex": "Il bilancio annuale è positivo.", "exNl": "De jaarbalans is positief.",
     "lesson": 260, "level": "B1", "cat": "sostantivo"},
    {"id": "w2326", "it": "la concorrenza", "nl": "de concurrentie", "ph": "kon-kor-REN-tsa",
     "ex": "La concorrenza è molto forte in questo settore.", "exNl": "De concurrentie is erg sterk in deze sector.",
     "lesson": 260, "level": "B1", "cat": "sostantivo"},
    {"id": "w2327", "it": "il fatturato", "nl": "de omzet", "ph": "fat-tu-RA-to",
     "ex": "Il fatturato è cresciuto del venti per cento.", "exNl": "De omzet is met twintig procent gegroeid.",
     "lesson": 260, "level": "B1", "cat": "sostantivo"},
    {"id": "w2328", "it": "investire", "nl": "investeren", "ph": "in-ves-TI-re",
     "ex": "L'azienda vuole investire nell'innovazione.", "exNl": "Het bedrijf wil investeren in innovatie.",
     "lesson": 260, "level": "B1", "cat": "verbo"},
    {"id": "w2329", "it": "la filiale", "nl": "het filiaal", "ph": "fi-LJA-le",
     "ex": "La filiale di Roma ha aperto il mese scorso.", "exNl": "Het filiaal in Rome is vorige maand geopend.",
     "lesson": 260, "level": "B1", "cat": "sostantivo"},
    {"id": "w2330", "it": "il cliente", "nl": "de klant", "ph": "kli-EN-te",
     "ex": "Il cliente ha sempre ragione.", "exNl": "De klant heeft altijd gelijk.",
     "lesson": 260, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 261: In het ziekenhuis ══════════════════════════════════════════
    {"id": "w2331", "it": "l'ospedale", "nl": "het ziekenhuis", "ph": "os-pe-DA-le",
     "ex": "L'ospedale più vicino è a due chilometri.", "exNl": "Het dichtstbijzijnde ziekenhuis is op twee kilometer.",
     "lesson": 261, "level": "B1", "cat": "sostantivo"},
    {"id": "w2332", "it": "il reparto", "nl": "de afdeling (ziekenhuis)", "ph": "re-PAR-to",
     "ex": "Il reparto di cardiologia è al terzo piano.", "exNl": "De afdeling cardiologie is op de derde verdieping.",
     "lesson": 261, "level": "B1", "cat": "sostantivo"},
    {"id": "w2333", "it": "il paziente", "nl": "de patiënt", "ph": "pa-TSJEN-te",
     "ex": "Il paziente è stato operato ieri.", "exNl": "De patiënt is gisteren geopereerd.",
     "lesson": 261, "level": "B1", "cat": "sostantivo"},
    {"id": "w2334", "it": "l'intervento", "nl": "de operatie / ingreep", "ph": "in-ter-VEN-to",
     "ex": "L'intervento è andato bene.", "exNl": "De operatie is goed gegaan.",
     "lesson": 261, "level": "B1", "cat": "sostantivo"},
    {"id": "w2335", "it": "l'infermiere", "nl": "de verpleger / verpleegkundige", "ph": "in-fer-MJE-re",
     "ex": "L'infermiere mi ha fatto un'iniezione.", "exNl": "De verpleger heeft me een injectie gegeven.",
     "lesson": 261, "level": "B1", "cat": "sostantivo"},
    {"id": "w2336", "it": "la visita medica", "nl": "het medisch onderzoek", "ph": "VI-zi-ta ME-di-ka",
     "ex": "Devo fare una visita medica.", "exNl": "Ik moet een medisch onderzoek doen.",
     "lesson": 261, "level": "B1", "cat": "espressione"},
    {"id": "w2337", "it": "ricoverare", "nl": "opnemen (in ziekenhuis)", "ph": "ri-ko-ve-RA-re",
     "ex": "Il paziente è stato ricoverato d'urgenza.", "exNl": "De patiënt is met spoed opgenomen.",
     "lesson": 261, "level": "B1", "cat": "verbo"},
    {"id": "w2338", "it": "la diagnosi", "nl": "de diagnose", "ph": "di-A-njo-zi",
     "ex": "La diagnosi è stata confermata.", "exNl": "De diagnose is bevestigd.",
     "lesson": 261, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 262: De apotheek ════════════════════════════════════════════════
    {"id": "w2339", "it": "la farmacia", "nl": "de apotheek", "ph": "far-ma-TSI-a",
     "ex": "C'è una farmacia qui vicino?", "exNl": "Is er een apotheek hier in de buurt?",
     "lesson": 262, "level": "B1", "cat": "sostantivo"},
    {"id": "w2340", "it": "la ricetta", "nl": "het recept (medisch)", "ph": "ri-TSJET-ta",
     "ex": "Questa medicina richiede la ricetta.", "exNl": "Dit medicijn vereist een recept.",
     "lesson": 262, "level": "B1", "cat": "sostantivo"},
    {"id": "w2341", "it": "la compressa", "nl": "de tablet / pil", "ph": "kom-PRES-sa",
     "ex": "Prenda due compresse al giorno.", "exNl": "Neem twee tabletten per dag.",
     "lesson": 262, "level": "B1", "cat": "sostantivo"},
    {"id": "w2342", "it": "lo sciroppo", "nl": "de siroop / het drankje", "ph": "sji-ROP-po",
     "ex": "Lo sciroppo per la tosse va preso tre volte al giorno.", "exNl": "De hoestsiroop moet drie keer per dag ingenomen worden.",
     "lesson": 262, "level": "B1", "cat": "sostantivo"},
    {"id": "w2343", "it": "l'effetto collaterale", "nl": "de bijwerking", "ph": "ef-FET-to kol-la-te-RA-le",
     "ex": "Questo farmaco ha pochi effetti collaterali.", "exNl": "Dit medicijn heeft weinig bijwerkingen.",
     "lesson": 262, "level": "B1", "cat": "espressione"},
    {"id": "w2344", "it": "la pomata", "nl": "de zalf", "ph": "po-MA-ta",
     "ex": "Applichi la pomata sulla ferita.", "exNl": "Breng de zalf aan op de wond.",
     "lesson": 262, "level": "B1", "cat": "sostantivo"},
    {"id": "w2345", "it": "il dosaggio", "nl": "de dosering", "ph": "do-ZAD-djo",
     "ex": "Non superi il dosaggio consigliato.", "exNl": "Overschrijd de aanbevolen dosering niet.",
     "lesson": 262, "level": "B1", "cat": "sostantivo"},
    {"id": "w2346", "it": "l'allergia", "nl": "de allergie", "ph": "al-ler-DJI-a",
     "ex": "Ha qualche allergia a farmaci?", "exNl": "Heeft u een allergie voor medicijnen?",
     "lesson": 262, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 263: Geestelijke gezondheid ═════════════════════════════════════
    {"id": "w2347", "it": "lo stress", "nl": "de stress", "ph": "STRESS",
     "ex": "Lo stress del lavoro mi stanca molto.", "exNl": "De werkstress maakt me erg moe.",
     "lesson": 263, "level": "B1", "cat": "sostantivo"},
    {"id": "w2348", "it": "l'ansia", "nl": "de angst / onrust", "ph": "AN-sja",
     "ex": "L'ansia può influire sulla salute.", "exNl": "Angst kan de gezondheid beïnvloeden.",
     "lesson": 263, "level": "B1", "cat": "sostantivo"},
    {"id": "w2349", "it": "la depressione", "nl": "de depressie", "ph": "de-pres-SJO-ne",
     "ex": "La depressione è una malattia seria.", "exNl": "Depressie is een serieuze ziekte.",
     "lesson": 263, "level": "B1", "cat": "sostantivo"},
    {"id": "w2350", "it": "il benessere", "nl": "het welzijn", "ph": "be-NES-se-re",
     "ex": "Il benessere mentale è importante quanto quello fisico.", "exNl": "Geestelijk welzijn is net zo belangrijk als lichamelijk welzijn.",
     "lesson": 263, "level": "B1", "cat": "sostantivo"},
    {"id": "w2351", "it": "rilassarsi", "nl": "zich ontspannen", "ph": "ri-las-SAR-si",
     "ex": "Devi rilassarti dopo il lavoro.", "exNl": "Je moet je na het werk ontspannen.",
     "lesson": 263, "level": "B1", "cat": "verbo"},
    {"id": "w2352", "it": "lo psicologo", "nl": "de psycholoog", "ph": "psi-KO-lo-go",
     "ex": "Ho un appuntamento dallo psicologo.", "exNl": "Ik heb een afspraak bij de psycholoog.",
     "lesson": 263, "level": "B1", "cat": "sostantivo"},
    {"id": "w2353", "it": "la terapia", "nl": "de therapie", "ph": "te-ra-PI-a",
     "ex": "La terapia lo sta aiutando molto.", "exNl": "De therapie helpt hem erg.",
     "lesson": 263, "level": "B1", "cat": "sostantivo"},
    {"id": "w2354", "it": "la meditazione", "nl": "de meditatie", "ph": "me-di-ta-TSJO-ne",
     "ex": "La meditazione riduce lo stress.", "exNl": "Meditatie vermindert stress.",
     "lesson": 263, "level": "B1", "cat": "sostantivo"},

    # ��══ LES 264: Eerste hulp ════════════════════════════════════════════════
    {"id": "w2355", "it": "il pronto soccorso", "nl": "de eerste hulp / spoedeisende hulp", "ph": "PRON-to sok-KOR-so",
     "ex": "Portatelo al pronto soccorso!", "exNl": "Breng hem naar de eerste hulp!",
     "lesson": 264, "level": "B1", "cat": "espressione"},
    {"id": "w2356", "it": "l'ambulanza", "nl": "de ambulance", "ph": "am-bu-LAN-tsa",
     "ex": "Chiama un'ambulanza, è urgente!", "exNl": "Bel een ambulance, het is dringend!",
     "lesson": 264, "level": "B1", "cat": "sostantivo"},
    {"id": "w2357", "it": "la ferita", "nl": "de wond", "ph": "fe-RI-ta",
     "ex": "La ferita non è profonda.", "exNl": "De wond is niet diep.",
     "lesson": 264, "level": "B1", "cat": "sostantivo"},
    {"id": "w2358", "it": "la frattura", "nl": "de breuk (bot)", "ph": "frat-TU-ra",
     "ex": "La radiografia ha mostrato una frattura.", "exNl": "De röntgenfoto toonde een breuk.",
     "lesson": 264, "level": "B1", "cat": "sostantivo"},
    {"id": "w2359", "it": "l'ustione", "nl": "de brandwond", "ph": "us-TJO-ne",
     "ex": "L'ustione va trattata subito.", "exNl": "De brandwond moet meteen behandeld worden.",
     "lesson": 264, "level": "B1", "cat": "sostantivo"},
    {"id": "w2360", "it": "svenire", "nl": "flauwvallen", "ph": "zve-NI-re",
     "ex": "È svenuto per il caldo.", "exNl": "Hij is flauwgevallen door de hitte.",
     "lesson": 264, "level": "B1", "cat": "verbo"},
    {"id": "w2361", "it": "il bendaggio", "nl": "het verband", "ph": "ben-DAD-djo",
     "ex": "L'infermiere ha applicato un bendaggio.", "exNl": "De verpleger heeft een verband aangebracht.",
     "lesson": 264, "level": "B1", "cat": "sostantivo"},
    {"id": "w2362", "it": "soccorrere", "nl": "hulp verlenen / te hulp komen", "ph": "sok-KOR-re-re",
     "ex": "I vigili del fuoco hanno soccorso le vittime.", "exNl": "De brandweerlieden hebben de slachtoffers te hulp gekomen.",
     "lesson": 264, "level": "B1", "cat": "verbo"},

    # ═══ LES 265: Wetenschap — basis ═════════════════════════════════════════
    {"id": "w2363", "it": "la scienza", "nl": "de wetenschap", "ph": "SJEN-tsa",
     "ex": "La scienza fa progressi ogni giorno.", "exNl": "De wetenschap boekt elke dag vooruitgang.",
     "lesson": 265, "level": "B1", "cat": "sostantivo"},
    {"id": "w2364", "it": "lo scienziato", "nl": "de wetenschapper", "ph": "sjen-TSJA-to",
     "ex": "Lo scienziato ha pubblicato un nuovo studio.", "exNl": "De wetenschapper heeft een nieuwe studie gepubliceerd.",
     "lesson": 265, "level": "B1", "cat": "sostantivo"},
    {"id": "w2365", "it": "la ricerca", "nl": "het onderzoek", "ph": "ri-TSER-ka",
     "ex": "La ricerca scientifica è fondamentale.", "exNl": "Wetenschappelijk onderzoek is fundamenteel.",
     "lesson": 265, "level": "B1", "cat": "sostantivo"},
    {"id": "w2366", "it": "l'esperimento", "nl": "het experiment", "ph": "es-pe-ri-MEN-to",
     "ex": "L'esperimento ha dato risultati sorprendenti.", "exNl": "Het experiment heeft verrassende resultaten opgeleverd.",
     "lesson": 265, "level": "B1", "cat": "sostantivo"},
    {"id": "w2367", "it": "la teoria", "nl": "de theorie", "ph": "te-o-RI-a",
     "ex": "La teoria deve essere verificata.", "exNl": "De theorie moet geverifieerd worden.",
     "lesson": 265, "level": "B1", "cat": "sostantivo"},
    {"id": "w2368", "it": "il laboratorio", "nl": "het laboratorium", "ph": "la-bo-ra-TO-rjo",
     "ex": "Lavora in un laboratorio di chimica.", "exNl": "Hij werkt in een scheikundig laboratorium.",
     "lesson": 265, "level": "B1", "cat": "sostantivo"},
    {"id": "w2369", "it": "dimostrare", "nl": "aantonen / bewijzen", "ph": "di-mos-TRA-re",
     "ex": "Lo studio ha dimostrato l'efficacia del farmaco.", "exNl": "De studie heeft de werkzaamheid van het medicijn aangetoond.",
     "lesson": 265, "level": "B1", "cat": "verbo"},
    {"id": "w2370", "it": "il microscopio", "nl": "de microscoop", "ph": "mi-kros-KO-pjo",
     "ex": "Osserviamo le cellule al microscopio.", "exNl": "We bekijken de cellen onder de microscoop.",
     "lesson": 265, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 266: Biologie & geneeskunde ═════════════════════════════════════
    {"id": "w2371", "it": "la cellula", "nl": "de cel", "ph": "TSJEL-lu-la",
     "ex": "Il corpo umano è fatto di miliardi di cellule.", "exNl": "Het menselijk lichaam bestaat uit miljarden cellen.",
     "lesson": 266, "level": "B1", "cat": "sostantivo"},
    {"id": "w2372", "it": "il DNA", "nl": "het DNA", "ph": "di-enne-A",
     "ex": "Il DNA contiene le informazioni genetiche.", "exNl": "Het DNA bevat de genetische informatie.",
     "lesson": 266, "level": "B1", "cat": "sostantivo"},
    {"id": "w2373", "it": "il virus", "nl": "het virus", "ph": "VI-rus",
     "ex": "Il virus si diffonde rapidamente.", "exNl": "Het virus verspreidt zich snel.",
     "lesson": 266, "level": "B1", "cat": "sostantivo"},
    {"id": "w2374", "it": "il vaccino", "nl": "het vaccin", "ph": "vat-TSI-no",
     "ex": "Il vaccino protegge dalle malattie.", "exNl": "Het vaccin beschermt tegen ziektes.",
     "lesson": 266, "level": "B1", "cat": "sostantivo"},
    {"id": "w2375", "it": "l'organo", "nl": "het orgaan", "ph": "OR-ga-no",
     "ex": "Il cuore è un organo vitale.", "exNl": "Het hart is een vitaal orgaan.",
     "lesson": 266, "level": "B1", "cat": "sostantivo"},
    {"id": "w2376", "it": "il batterio", "nl": "de bacterie", "ph": "bat-TE-rjo",
     "ex": "Non tutti i batteri sono dannosi.", "exNl": "Niet alle bacteriën zijn schadelijk.",
     "lesson": 266, "level": "B1", "cat": "sostantivo"},
    {"id": "w2377", "it": "la cura", "nl": "de genezing / behandeling", "ph": "KU-ra",
     "ex": "I ricercatori cercano una cura per questa malattia.", "exNl": "De onderzoekers zoeken een behandeling voor deze ziekte.",
     "lesson": 266, "level": "B1", "cat": "sostantivo"},
    {"id": "w2378", "it": "genetico", "nl": "genetisch", "ph": "dje-NE-ti-ko",
     "ex": "Alcune malattie sono di origine genetica.", "exNl": "Sommige ziektes zijn van genetische oorsprong.",
     "lesson": 266, "level": "B1", "cat": "aggettivo"},

    # ═══ LES 267: Wiskunde & natuurkunde ═════════════════════════════════════
    {"id": "w2379", "it": "la matematica", "nl": "de wiskunde", "ph": "ma-te-MA-ti-ka",
     "ex": "La matematica è la base di tutte le scienze.", "exNl": "Wiskunde is de basis van alle wetenschappen.",
     "lesson": 267, "level": "B1", "cat": "sostantivo"},
    {"id": "w2380", "it": "la fisica", "nl": "de natuurkunde", "ph": "FI-zi-ka",
     "ex": "La fisica studia le leggi della natura.", "exNl": "De natuurkunde bestudeert de wetten van de natuur.",
     "lesson": 267, "level": "B1", "cat": "sostantivo"},
    {"id": "w2381", "it": "l'equazione", "nl": "de vergelijking (wiskunde)", "ph": "e-kwa-TSJO-ne",
     "ex": "Devi risolvere questa equazione.", "exNl": "Je moet deze vergelijking oplossen.",
     "lesson": 267, "level": "B1", "cat": "sostantivo"},
    {"id": "w2382", "it": "la formula", "nl": "de formule", "ph": "FOR-mu-la",
     "ex": "Quale formula dobbiamo usare?", "exNl": "Welke formule moeten we gebruiken?",
     "lesson": 267, "level": "B1", "cat": "sostantivo"},
    {"id": "w2383", "it": "l'energia", "nl": "de energie", "ph": "e-ner-DJI-a",
     "ex": "L'energia solare è rinnovabile.", "exNl": "Zonne-energie is hernieuwbaar.",
     "lesson": 267, "level": "B1", "cat": "sostantivo"},
    {"id": "w2384", "it": "la gravità", "nl": "de zwaartekracht", "ph": "gra-vi-TA",
     "ex": "La gravità tiene i piedi per terra.", "exNl": "De zwaartekracht houdt je voeten op de grond.",
     "lesson": 267, "level": "B1", "cat": "sostantivo"},
    {"id": "w2385", "it": "calcolare", "nl": "berekenen", "ph": "kal-ko-LA-re",
     "ex": "Bisogna calcolare la velocità.", "exNl": "Je moet de snelheid berekenen.",
     "lesson": 267, "level": "B1", "cat": "verbo"},
    {"id": "w2386", "it": "la percentuale", "nl": "het percentage", "ph": "per-tsjen-tu-A-le",
     "ex": "La percentuale di successo è alta.", "exNl": "Het slagingspercentage is hoog.",
     "lesson": 267, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 268: Uitvindingen & ontdekkingen ════════════════════════════════
    {"id": "w2387", "it": "l'invenzione", "nl": "de uitvinding", "ph": "in-ven-TSJO-ne",
     "ex": "La stampa è una delle più grandi invenzioni.", "exNl": "De drukpers is een van de grootste uitvindingen.",
     "lesson": 268, "level": "B1", "cat": "sostantivo"},
    {"id": "w2388", "it": "inventare", "nl": "uitvinden", "ph": "in-ven-TA-re",
     "ex": "Guglielmo Marconi ha inventato la radio.", "exNl": "Guglielmo Marconi heeft de radio uitgevonden.",
     "lesson": 268, "level": "B1", "cat": "verbo"},
    {"id": "w2389", "it": "la scoperta", "nl": "de ontdekking", "ph": "sko-PER-ta",
     "ex": "La scoperta della penicillina ha salvato milioni di vite.", "exNl": "De ontdekking van penicilline heeft miljoenen levens gered.",
     "lesson": 268, "level": "B1", "cat": "sostantivo"},
    {"id": "w2390", "it": "scoprire", "nl": "ontdekken", "ph": "sko-PRI-re",
     "ex": "Galileo scoprì le lune di Giove.", "exNl": "Galileo ontdekte de manen van Jupiter.",
     "lesson": 268, "level": "B1", "cat": "verbo"},
    {"id": "w2391", "it": "il brevetto", "nl": "het patent / octrooi", "ph": "bre-VET-to",
     "ex": "Ha registrato un brevetto per la sua invenzione.", "exNl": "Hij heeft een patent geregistreerd voor zijn uitvinding.",
     "lesson": 268, "level": "B1", "cat": "sostantivo"},
    {"id": "w2392", "it": "la tecnologia", "nl": "de technologie", "ph": "tek-no-lo-DJI-a",
     "ex": "La tecnologia cambia il nostro modo di vivere.", "exNl": "Technologie verandert onze manier van leven.",
     "lesson": 268, "level": "B1", "cat": "sostantivo"},
    {"id": "w2393", "it": "innovativo", "nl": "innovatief", "ph": "in-no-va-TI-vo",
     "ex": "Questo prodotto è molto innovativo.", "exNl": "Dit product is erg innovatief.",
     "lesson": 268, "level": "B1", "cat": "aggettivo"},
    {"id": "w2394", "it": "il progresso", "nl": "de vooruitgang", "ph": "pro-GRES-so",
     "ex": "Il progresso scientifico non si ferma.", "exNl": "De wetenschappelijke vooruitgang staat niet stil.",
     "lesson": 268, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 269: Ruimtevaart & sterrenkunde ═════════════════════════════════
    {"id": "w2395", "it": "lo spazio", "nl": "de ruimte (heelal)", "ph": "SPA-tsjo",
     "ex": "L'esplorazione dello spazio è affascinante.", "exNl": "De verkenning van de ruimte is fascinerend.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},
    {"id": "w2396", "it": "il pianeta", "nl": "de planeet", "ph": "pja-NE-ta",
     "ex": "Marte è il quarto pianeta del sistema solare.", "exNl": "Mars is de vierde planeet van het zonnestelsel.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},
    {"id": "w2397", "it": "la stella", "nl": "de ster", "ph": "STEL-la",
     "ex": "Le stelle brillano nel cielo notturno.", "exNl": "De sterren schitteren aan de nachtelijke hemel.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},
    {"id": "w2398", "it": "l'astronauta", "nl": "de astronaut", "ph": "as-tro-NAU-ta",
     "ex": "L'astronauta italiano è tornato dalla stazione spaziale.", "exNl": "De Italiaanse astronaut is teruggekeerd van het ruimtestation.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},
    {"id": "w2399", "it": "il satellite", "nl": "de satelliet", "ph": "sa-TEL-li-te",
     "ex": "Il satellite orbita intorno alla Terra.", "exNl": "De satelliet draait om de aarde.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},
    {"id": "w2400", "it": "il telescopio", "nl": "de telescoop", "ph": "te-les-KO-pjo",
     "ex": "Con il telescopio puoi osservare le stelle.", "exNl": "Met de telescoop kun je de sterren observeren.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},
    {"id": "w2401", "it": "la galassia", "nl": "het sterrenstelsel / de melkweg", "ph": "ga-LAS-sja",
     "ex": "La Via Lattea è la nostra galassia.", "exNl": "De Melkweg is ons sterrenstelsel.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},
    {"id": "w2402", "it": "l'orbita", "nl": "de baan (ruimte)", "ph": "OR-bi-ta",
     "ex": "La Terra compie un'orbita intorno al Sole in un anno.", "exNl": "De aarde voltooit in een jaar een baan om de zon.",
     "lesson": 269, "level": "B1", "cat": "sostantivo"},

    # ═══ LES 270: Toetsles B1 — Blok 15 ═════════════════════════════════════
    {"id": "w2403", "it": "il sintomo", "nl": "het symptoom", "ph": "SIN-to-mo",
     "ex": "Quali sono i sintomi della malattia?", "exNl": "Wat zijn de symptomen van de ziekte?",
     "lesson": 270, "level": "B1", "cat": "sostantivo"},
    {"id": "w2404", "it": "la prevenzione", "nl": "de preventie", "ph": "pre-ven-TSJO-ne",
     "ex": "La prevenzione è meglio della cura.", "exNl": "Voorkomen is beter dan genezen.",
     "lesson": 270, "level": "B1", "cat": "sostantivo"},
    {"id": "w2405", "it": "il risultato", "nl": "het resultaat", "ph": "ri-zul-TA-to",
     "ex": "I risultati dell'analisi sono pronti.", "exNl": "De resultaten van de analyse zijn klaar.",
     "lesson": 270, "level": "B1", "cat": "sostantivo"},
    {"id": "w2406", "it": "analizzare", "nl": "analyseren", "ph": "a-na-lid-DZA-re",
     "ex": "Dobbiamo analizzare i dati raccolti.", "exNl": "We moeten de verzamelde gegevens analyseren.",
     "lesson": 270, "level": "B1", "cat": "verbo"},
    {"id": "w2407", "it": "la radiografia", "nl": "de röntgenfoto", "ph": "ra-djo-gra-FI-a",
     "ex": "La radiografia non mostra fratture.", "exNl": "De röntgenfoto toont geen breuken.",
     "lesson": 270, "level": "B1", "cat": "sostantivo"},
    {"id": "w2408", "it": "l'universo", "nl": "het heelal / universum", "ph": "u-ni-VER-so",
     "ex": "L'universo è in continua espansione.", "exNl": "Het heelal dijt voortdurend uit.",
     "lesson": 270, "level": "B1", "cat": "sostantivo"},
    {"id": "w2409", "it": "la ricerca scientifica", "nl": "het wetenschappelijk onderzoek", "ph": "ri-TSER-ka sjen-TI-fi-ka",
     "ex": "La ricerca scientifica ha bisogno di finanziamenti.", "exNl": "Wetenschappelijk onderzoek heeft financiering nodig.",
     "lesson": 270, "level": "B1", "cat": "espressione"},
    {"id": "w2410", "it": "il fenomeno", "nl": "het fenomeen / verschijnsel", "ph": "fe-NO-me-no",
     "ex": "L'aurora boreale è un fenomeno naturale.", "exNl": "Het noorderlicht is een natuurverschijnsel.",
     "lesson": 270, "level": "B1", "cat": "sostantivo"},
]
