#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_es_a2.py — Spaans A2 (v1.57): lessen 61–120 × 8 woorden, thema-opbouw gespiegeld aan Italiaans A2.
Voegt toe aan de bestaande Spaanse data (A1 blijft staan; eerdere A2-entries worden vervangen).
Woord-IDs volgen op het hoogste bestaande ID. Draai opnieuw na bewerken: python3 scripts/generate_es_a2.py
Formaat: L(id, emoji, title, description, grammar_title, grammar_body, [ (es, nl, ph, ex, exNl, cat) × 8 ])
"""
import json, re
from pathlib import Path

OUT = Path(__file__).parent.parent / 'www' / 'data' / 'es'

def L(id, emoji, title, desc, gt, gb, words):
    return dict(id=id, emoji=emoji, title=title, description=desc, grammar=dict(title=gt, body=gb), words=words)

LESSONS = [
L(61, '💬', 'Meningen geven', 'Zeg wat je vindt en reageer op anderen.',
  'Meningen uitdrukken: creo que, me parece que', '"Creo que" (ik denk dat) en "me parece que" (het lijkt mij dat) + zin. Eens: estoy de acuerdo. Oneens: no estoy de acuerdo. Twijfel: depende.',
  [('en mi opinión', 'volgens mij', 'en mi o-pi-NJON', 'En mi opinión, es una buena idea.', 'Volgens mij is het een goed idee.', 'meningen'),
   ('estoy de acuerdo', 'ik ben het eens', 'es-TOI de a-KWER-do', 'Estoy de acuerdo contigo.', 'Ik ben het met je eens.', 'meningen'),
   ('no estoy de acuerdo', 'ik ben het niet eens', 'no es-TOI de a-KWER-do', 'No estoy de acuerdo con eso.', 'Daar ben ik het niet mee eens.', 'meningen'),
   ('depende', 'het hangt ervan af', 'de-PEN-de', '¿Vienes? — Depende de la hora.', 'Kom je? — Hangt van de tijd af.', 'meningen'),
   ('creer', 'denken, geloven', 'kre-ER', 'Creo que tienes razón.', 'Ik denk dat je gelijk hebt.', 'meningen'),
   ('importante', 'belangrijk', 'im-por-TAN-te', 'Es importante escuchar.', 'Het is belangrijk om te luisteren.', 'meningen'),
   ('de todos modos', 'hoe dan ook', 'de TO-dos MO-dos', 'De todos modos, vamos.', 'Hoe dan ook, we gaan.', 'meningen'),
   ('así', 'zo, op die manier', 'a-SIE', 'No es así.', 'Zo is het niet.', 'meningen')]),
L(62, '⏮️', 'Pretérito perfecto', 'Vertellen wat je vandaag of onlangs hebt gedaan.',
  'Pretérito perfecto: haber + deelwoord', 'He comido, has visto, ha ido. Het deelwoord: -ar → -ado, -er/-ir → -ido. Onregelmatig: hecho, dicho, visto, puesto, escrito, vuelto. Gebruik: hoy, esta semana, este año.',
  [('he comido', 'ik heb gegeten', 'e ko-MIE-do', 'Hoy he comido paella.', 'Vandaag heb ik paella gegeten.', 'verleden'),
   ('he visto', 'ik heb gezien', 'e VIS-to', 'He visto una película.', 'Ik heb een film gezien.', 'verleden'),
   ('he comprado', 'ik heb gekocht', 'e kom-PRA-do', 'He comprado pan.', 'Ik heb brood gekocht.', 'verleden'),
   ('he hecho', 'ik heb gedaan', 'e E-tsjo', 'He hecho los deberes.', 'Ik heb mijn huiswerk gedaan.', 'verleden'),
   ('he ido', 'ik ben gegaan', 'e IE-do', 'He ido al mercado.', 'Ik ben naar de markt gegaan.', 'verleden'),
   ('he llegado', 'ik ben aangekomen', 'e je-GA-do', 'He llegado tarde.', 'Ik ben te laat aangekomen.', 'verleden'),
   ('he vuelto', 'ik ben teruggekeerd', 'e VWEL-to', 'He vuelto a casa a las diez.', 'Ik ben om tien uur thuisgekomen.', 'verleden'),
   ('lo he pasado bien', 'ik heb het leuk gehad', 'lo e pa-SA-do bjen', 'Lo he pasado muy bien.', 'Ik heb het heel leuk gehad.', 'verleden')]),
L(63, '📽️', 'Het imperfecto', 'Beschrijven hoe het vroeger was.',
  'Pretérito imperfecto: gewoontes en beschrijvingen', '-ar: hablaba, hablabas, hablaba; -er/-ir: comía, vivía. Onregelmatig: era (ser), iba (ir), veía (ver). Voor gewoontes en achtergrond: cuando era pequeño, vivía en Cádiz.',
  [('cuando era', 'toen ik was', 'KWAN-do E-ra', 'Cuando era pequeño, vivía en Cádiz.', 'Toen ik klein was, woonde ik in Cádiz.', 'verleden'),
   ('vivía', 'ik woonde', 'vi-VIE-a', 'Vivía con mis abuelos.', 'Ik woonde bij mijn grootouders.', 'verleden'),
   ('iba', 'ik ging', 'IE-ba', 'Iba a la playa cada verano.', 'Ik ging elke zomer naar het strand.', 'verleden'),
   ('era', 'het was / hij was', 'E-ra', 'Era un pueblo tranquilo.', 'Het was een rustig dorp.', 'verleden'),
   ('había', 'er was / er waren', 'a-BIE-a', 'Había una plaza con una fuente.', 'Er was een plein met een fontein.', 'verleden'),
   ('antes', 'vroeger', 'AN-tes', 'Antes no había móviles.', 'Vroeger waren er geen mobieltjes.', 'verleden'),
   ('de pequeño', 'als kind', 'de pe-KE-njo', 'De pequeño jugaba en la calle.', 'Als kind speelde ik op straat.', 'verleden'),
   ('entonces', 'toen, dus', 'en-TON-ses', 'Entonces todo era diferente.', 'Toen was alles anders.', 'verleden')]),
L(64, '🔮', 'De toekomst', 'Praten over wat er gaat komen.',
  'Futuro simple: onregelmatige stammen', 'Regelmatig: hablaré, comerás, vivirá. Onregelmatige stammen: tendr- (tener), har- (hacer), podr- (poder), saldr- (salir), vendr- (venir), dir- (decir), sabr- (saber), pondr- (poner).',
  [('iré', 'ik zal gaan', 'i-RE', 'Mañana iré al médico.', 'Morgen zal ik naar de dokter gaan.', 'toekomst'),
   ('será', 'het zal zijn', 'se-RA', 'Será un día largo.', 'Het zal een lange dag worden.', 'toekomst'),
   ('haré', 'ik zal doen', 'a-RE', 'Haré todo lo posible.', 'Ik zal alles doen wat mogelijk is.', 'toekomst'),
   ('probablemente', 'waarschijnlijk', 'pro-ba-ble-MEN-te', 'Probablemente lloverá.', 'Waarschijnlijk gaat het regenen.', 'toekomst'),
   ('quizás', 'misschien', 'ki-SAS', 'Quizás vengan mañana.', 'Misschien komen ze morgen.', 'toekomst'),
   ('todavía', 'nog, nog steeds', 'to-da-VIE-a', 'Todavía no he decidido.', 'Ik heb nog niet besloten.', 'toekomst'),
   ('dentro de poco', 'zo meteen, binnenkort', 'DEN-tro de PO-ko', 'Dentro de poco empieza la película.', 'Binnenkort begint de film.', 'toekomst'),
   ('tarde o temprano', 'vroeg of laat', 'TAR-de o tem-PRA-no', 'Tarde o temprano lo sabrás.', 'Vroeg of laat kom je het te weten.', 'toekomst')]),
L(65, '⚖️', 'Vergelijken', 'Dingen met elkaar vergelijken.',
  'Comparatief en superlatief', 'Más ... que (meer dan), menos ... que (minder dan), tan ... como (even ... als). Overtreffend: el más ..., la mejor. Onregelmatig: mejor, peor, mayor, menor.',
  [('más', 'meer / -er', 'mas', 'Madrid es más grande que Sevilla.', 'Madrid is groter dan Sevilla.', 'vergelijken'),
   ('menos', 'minder', 'ME-nos', 'Este hotel es menos caro.', 'Dit hotel is minder duur.', 'vergelijken'),
   ('mejor', 'beter', 'me-CHOR', 'Tu español es mejor que el mío.', 'Jouw Spaans is beter dan het mijne.', 'vergelijken'),
   ('peor', 'slechter', 'pe-OR', 'El tiempo es peor hoy.', 'Het weer is vandaag slechter.', 'vergelijken'),
   ('mayor', 'ouder / groter', 'ma-JOR', 'Mi hermano mayor vive en Bilbao.', 'Mijn oudere broer woont in Bilbao.', 'vergelijken'),
   ('bastante', 'genoeg / redelijk', 'bas-TAN-te', 'Es bastante caro.', 'Het is redelijk duur.', 'vergelijken'),
   ('demasiado', 'te veel / te', 'de-ma-SJA-do', 'Es demasiado tarde.', 'Het is te laat.', 'vergelijken'),
   ('tan ... como', 'even ... als', 'tan KO-mo', 'Es tan alto como su padre.', 'Hij is even lang als zijn vader.', 'vergelijken')]),
L(66, '🔗', 'Verbindingswoorden', 'Zinnen aan elkaar knopen.',
  'Samenhangende zinnen bouwen', 'Pero (maar), por eso (daarom), sin embargo (echter), mientras (terwijl), aunque (hoewel), además (bovendien). Ze staan meestal aan het begin van de bijzin.',
  [('pero', 'maar', 'PE-ro', 'Quiero ir, pero no puedo.', 'Ik wil gaan, maar ik kan niet.', 'verbinden'),
   ('por eso', 'daarom', 'por E-so', 'Llueve, por eso me quedo en casa.', 'Het regent, daarom blijf ik thuis.', 'verbinden'),
   ('en cambio', 'daarentegen', 'en KAM-bjo', 'A él le gusta el mar; en cambio, yo prefiero la montaña.', 'Hij houdt van zee; ik daarentegen geef de voorkeur aan de bergen.', 'verbinden'),
   ('mientras', 'terwijl', 'MJEN-tras', 'Cocino mientras escucho música.', 'Ik kook terwijl ik muziek luister.', 'verbinden'),
   ('por desgracia', 'helaas', 'por des-GRA-sja', 'Por desgracia, no hay entradas.', 'Helaas zijn er geen kaartjes.', 'verbinden'),
   ('solo', 'alleen, slechts', 'SO-lo', 'Solo tengo diez euros.', 'Ik heb maar tien euro.', 'verbinden'),
   ('además', 'bovendien', 'a-de-MAS', 'Es barato y, además, bueno.', 'Het is goedkoop en bovendien goed.', 'verbinden'),
   ('aunque', 'hoewel, ook al', 'AUN-ke', 'Salgo aunque llueva.', 'Ik ga naar buiten, ook al regent het.', 'verbinden')]),
L(67, '💼', 'Werk & kantoor', 'Praten over je werk.',
  'Zakelijke uitdrukkingen', 'Trabajo en / trabajo como (ik werk bij / als). Tengo una reunión a las diez. Con "usted" tegen klanten en de baas: ¿Podría enviarme el contrato?',
  [('el horario laboral', 'de werktijden', 'el o-RA-rjo la-bo-RAL', 'Mi horario laboral es de nueve a cinco.', 'Mijn werktijden zijn van negen tot vijf.', 'werk'),
   ('el compañero', 'collega', 'el kom-pa-NJE-ro', 'Mis compañeros son simpáticos.', "Mijn collega's zijn aardig.", 'werk'),
   ('la reunión', 'vergadering', 'la re-oe-NJON', 'La reunión es a las diez.', 'De vergadering is om tien uur.', 'werk'),
   ('el proyecto', 'project', 'el pro-JEK-to', 'Trabajamos en un proyecto nuevo.', 'We werken aan een nieuw project.', 'werk'),
   ('trabajar', 'werken', 'tra-ba-CHAR', 'Trabajo desde casa los viernes.', 'Op vrijdag werk ik thuis.', 'werk'),
   ('la nómina', 'de loonstrook', 'la NO-mi-na', 'Recibo la nómina a fin de mes.', 'Ik krijg mijn loonstrook aan het eind van de maand.', 'werk'),
   ('el contrato', 'contract', 'el kon-TRA-to', 'He firmado el contrato.', 'Ik heb het contract getekend.', 'werk'),
   ('la entrevista', 'sollicitatiegesprek', 'la en-tre-VIS-ta', 'Tengo una entrevista mañana.', 'Ik heb morgen een sollicitatiegesprek.', 'werk')]),
L(68, '🌟', 'Karaktereigenschappen', 'Iemands karakter beschrijven.',
  'Bijvoeglijke naamwoorden: geslacht en meervoud', 'Simpático/simpática/simpáticos. Op -e of medeklinker gelijk voor m/v: inteligente, amable. "Ser" voor karakter (es tímido), "estar" voor stemming (está nervioso).',
  [('amable', 'vriendelijk', 'a-MA-ble', 'La vecina es muy amable.', 'De buurvrouw is heel vriendelijk.', 'karakter'),
   ('serio', 'serieus', 'SE-rjo', 'Es una persona seria.', 'Het is een serieus persoon.', 'karakter'),
   ('inteligente', 'intelligent', 'in-te-li-CHEN-te', 'Mi hermana es muy inteligente.', 'Mijn zus is heel intelligent.', 'karakter'),
   ('tímido', 'verlegen', 'TIE-mi-do', 'De niño era tímido.', 'Als kind was ik verlegen.', 'karakter'),
   ('honesto', 'eerlijk', 'o-NES-to', 'Es honesto y trabajador.', 'Hij is eerlijk en hardwerkend.', 'karakter'),
   ('paciente', 'geduldig', 'pa-SJEN-te', 'Hay que ser paciente.', 'Je moet geduldig zijn.', 'karakter'),
   ('antipático', 'onaardig', 'an-ti-PA-ti-ko', 'No es antipático, solo tímido.', 'Hij is niet onaardig, alleen verlegen.', 'karakter'),
   ('simpático', 'aardig, sympathiek', 'sim-PA-ti-ko', 'Tus amigos son muy simpáticos.', 'Je vrienden zijn heel aardig.', 'karakter')]),
L(69, '🎭', 'Beschrijvingen', 'Indrukken en gevoelens over dingen.',
  'Uitroepen: ¡Qué + bijvoeglijk naamwoord!', '¡Qué bonito! ¡Qué interesante! ¡Qué raro! Met zelfstandig naamwoord: ¡Qué ciudad tan bonita! Let op de omgekeerde uitroeptekens.',
  [('increíble', 'ongelooflijk', 'in-kre-IE-ble', '¡Qué vista tan increíble!', 'Wat een ongelooflijk uitzicht!', 'beschrijvingen'),
   ('maravilloso', 'prachtig / wonderbaarlijk', 'ma-ra-vi-JO-so', 'Fue un viaje maravilloso.', 'Het was een prachtige reis.', 'beschrijvingen'),
   ('terrible', 'verschrikkelijk', 'te-RRIE-ble', 'El tráfico es terrible.', 'Het verkeer is verschrikkelijk.', 'beschrijvingen'),
   ('verdadero', 'waar, echt', 'ver-da-DE-ro', 'Es un verdadero amigo.', 'Hij is een echte vriend.', 'beschrijvingen'),
   ('fascinante', 'fascinerend', 'fas-si-NAN-te', 'La historia es fascinante.', 'De geschiedenis is fascinerend.', 'beschrijvingen'),
   ('la persona', 'de persoon', 'la per-SO-na', 'Es una persona interesante.', 'Het is een interessant persoon.', 'beschrijvingen'),
   ('complicado', 'gecompliceerd', 'kom-pli-KA-do', 'La situación es complicada.', 'De situatie is ingewikkeld.', 'beschrijvingen'),
   ('raro', 'vreemd, raar', 'RA-ro', '¡Qué raro!', 'Wat vreemd!', 'beschrijvingen')]),
L(70, '🧳', 'Reizen gevorderd', 'Praktische reiswoorden.',
  'Reizen: nuttige zinsconstructies', '¿A qué hora sale el próximo tren? ¿Cuánto tarda? Hay que hacer transbordo (overstappen). Necesito cambiar dinero.',
  [('la mochila', 'de rugzak', 'la mo-TSJIE-la', 'Viajo solo con una mochila.', 'Ik reis alleen met een rugzak.', 'reizen'),
   ('el trayecto', 'het traject / de rit', 'el tra-JEK-to', 'El trayecto dura tres horas.', 'De rit duurt drie uur.', 'reizen'),
   ('la ida', 'de heenreis', 'la IE-da', 'La ida es el sábado.', 'De heenreis is zaterdag.', 'reizen'),
   ('el itinerario', 'reisplan / route', 'el i-ti-ne-RA-rjo', 'El itinerario pasa por tres ciudades.', 'De route gaat langs drie steden.', 'reizen'),
   ('el seguro de viaje', 'reisverzekering', 'el se-GOE-ro de VJA-che', 'Tengo seguro de viaje.', 'Ik heb een reisverzekering.', 'reizen'),
   ('la aduana', 'douane', 'la a-DWA-na', 'Pasamos la aduana sin problemas.', 'We kwamen zonder problemen door de douane.', 'reizen'),
   ('el cambio', 'wisselkoers / wisselgeld', 'el KAM-bjo', '¿Cuál es el cambio hoy?', 'Wat is de wisselkoers vandaag?', 'reizen'),
   ('el plano', 'de plattegrond', 'el PLA-no', 'Necesito un plano del metro.', 'Ik heb een metrokaart nodig.', 'reizen')]),
L(71, '👨‍🍳', 'Koken gevorderd', 'Smaken en bereiding beschrijven.',
  'Smaken beschrijven', 'Está dulce / salado / picante / amargo. "Estar" voor hoe iets smaakt vandaag, "ser" voor hoe het altijd is: el limón es ácido.',
  [('la cucharada', 'de eetlepel', 'la koe-tsja-RA-da', 'Una cucharada de aceite.', 'Een eetlepel olie.', 'koken'),
   ('la patata', 'de aardappel', 'la pa-TA-ta', 'La tortilla lleva patatas.', 'In de tortilla zitten aardappels.', 'koken'),
   ('picante', 'pittig / scherp', 'pi-KAN-te', 'La salsa está muy picante.', 'De saus is heel pittig.', 'koken'),
   ('amargo', 'bitter', 'a-MAR-go', 'El café está amargo.', 'De koffie is bitter.', 'koken'),
   ('salado', 'zout / hartig', 'sa-LA-do', 'La sopa está demasiado salada.', 'De soep is te zout.', 'koken'),
   ('el sabor', 'smaak', 'el sa-BOR', 'Tiene un sabor especial.', 'Het heeft een bijzondere smaak.', 'koken'),
   ('cocer', 'koken / garen', 'ko-SER', 'Cuece la pasta diez minutos.', 'Kook de pasta tien minuten.', 'koken'),
   ('el aceite de oliva', 'olijfolie', 'el a-SEI-te de o-LIE-va', 'Un poco de aceite de oliva.', 'Een beetje olijfolie.', 'koken')]),
L(72, '📱', 'Technologie', 'Digitale woorden van elke dag.',
  'Technologische termen in het Spaans', 'Veel woorden zijn vertaald: la aplicación (app), la contraseña (wachtwoord), descargar (downloaden). "Wifi" en "internet" blijven gelijk, uitgesproken op zijn Spaans.',
  [('la aplicación', 'app / applicatie', 'la a-pli-ka-SJON', 'Descarga la aplicación.', 'Download de app.', 'technologie'),
   ('compartir', 'delen', 'kom-par-TIER', 'Comparto las fotos contigo.', "Ik deel de foto's met jou.", 'technologie'),
   ('la red', 'netwerk / internet', 'la red', 'No hay red aquí.', 'Er is hier geen netwerk.', 'technologie'),
   ('actualizar', 'updaten / bijwerken', 'ak-twa-li-SAR', 'Tengo que actualizar el móvil.', 'Ik moet mijn mobiel updaten.', 'technologie'),
   ('digital', 'digitaal', 'di-chi-TAL', 'Prefiero el billete digital.', 'Ik heb liever het digitale kaartje.', 'technologie'),
   ('la videollamada', 'videogesprek', 'la vi-de-o-ja-MA-da', 'Hacemos una videollamada el domingo.', 'We doen zondag een videogesprek.', 'technologie'),
   ('descargar', 'downloaden', 'des-kar-GAR', 'Descargo el mapa antes del viaje.', 'Ik download de kaart voor de reis.', 'technologie'),
   ('funcionar', 'werken, functioneren', 'foen-sjo-NAR', 'El wifi no funciona.', 'De wifi werkt niet.', 'technologie')]),
L(73, '🌿', 'Natuur & milieu', 'Over de natuur en het milieu praten.',
  'Onpersoonlijk "se"', '"Se" + werkwoord in de derde persoon voor "men": se recicla el vidrio (men recyclet glas), se puede ahorrar energía. Meervoud als het onderwerp meervoud is: se reciclan las botellas.',
  [('el medio ambiente', 'milieu', 'el ME-djo am-BJEN-te', 'Hay que proteger el medio ambiente.', 'We moeten het milieu beschermen.', 'milieu'),
   ('la contaminación', 'vervuiling', 'la kon-ta-mi-na-SJON', 'La contaminación es un problema.', 'Vervuiling is een probleem.', 'milieu'),
   ('la energía solar', 'zonne-energie', 'la e-ner-CHIE-a so-LAR', 'Usamos energía solar.', 'We gebruiken zonne-energie.', 'milieu'),
   ('el clima', 'klimaat', 'el KLIE-ma', 'El clima está cambiando.', 'Het klimaat verandert.', 'milieu'),
   ('el aire', 'de lucht', 'el AI-re', 'El aire de la montaña es limpio.', 'De berglucht is schoon.', 'milieu'),
   ('el ahorro', 'besparing', 'el a-O-rro', 'El ahorro de agua es importante.', 'Waterbesparing is belangrijk.', 'milieu'),
   ('la selva', 'het oerwoud', 'la SEL-va', 'La selva amazónica es enorme.', 'Het Amazone-oerwoud is enorm.', 'milieu'),
   ('reciclar', 'recyclen', 're-si-KLAR', 'Reciclamos el papel y el vidrio.', 'We recyclen papier en glas.', 'milieu')]),
L(74, '🧘', 'Gezondheid & welzijn', 'Adviezen voor een gezond leven.',
  'Advies geven: deber en hay que', 'Debes descansar (je moet rusten), hay que beber agua (men moet water drinken). "Deberías" is zachter: je zou moeten.',
  [('el bienestar', 'welzijn', 'el bjen-es-TAR', 'El bienestar es más que la salud.', 'Welzijn is meer dan gezondheid.', 'gezondheid'),
   ('la dieta equilibrada', 'uitgebalanceerd dieet', 'la DJE-ta e-ki-li-BRA-da', 'Sigo una dieta equilibrada.', 'Ik volg een uitgebalanceerd dieet.', 'gezondheid'),
   ('el estrés', 'stress', 'el es-TRES', 'Tengo mucho estrés en el trabajo.', 'Ik heb veel stress op het werk.', 'gezondheid'),
   ('meditar', 'mediteren', 'me-di-TAR', 'Medito diez minutos al día.', 'Ik mediteer tien minuten per dag.', 'gezondheid'),
   ('el equilibrio', 'evenwicht / balans', 'el e-ki-LIE-brjo', 'Busco el equilibrio entre trabajo y vida.', 'Ik zoek de balans tussen werk en leven.', 'gezondheid'),
   ('el cuerpo', 'het lichaam', 'el KWER-po', 'El cuerpo necesita descanso.', 'Het lichaam heeft rust nodig.', 'gezondheid'),
   ('el descanso', 'de rust', 'el des-KAN-so', 'El descanso es importante.', 'Rust is belangrijk.', 'gezondheid'),
   ('la actividad física', 'de lichamelijke activiteit', 'la ak-ti-vi-DAD FIE-si-ka', 'La actividad física mejora el ánimo.', 'Beweging verbetert de stemming.', 'gezondheid')]),
L(75, '❤️', 'Relaties & gevoelens', 'Vriendschap, liefde en ruzie.',
  'Bezig zijn met: estar + gerundio', 'Estoy pensando en ti (ik ben aan jou aan het denken). Gerundio: -ar → -ando, -er/-ir → -iendo. Onregelmatig: leyendo, durmiendo, diciendo.',
  [('la amistad', 'vriendschap', 'la a-mis-TAD', 'La amistad es para siempre.', 'Vriendschap is voor altijd.', 'relaties'),
   ('la confianza', 'vertrouwen', 'la kon-FJAN-sa', 'Tengo confianza en ti.', 'Ik heb vertrouwen in jou.', 'relaties'),
   ('la pareja', 'de partner / het stel', 'la pa-RE-cha', 'Mi pareja es de Chile.', 'Mijn partner komt uit Chili.', 'relaties'),
   ('discutir', 'ruziemaken', 'dis-koe-TIER', 'Discutimos por tonterías.', 'We maken ruzie om kleinigheden.', 'relaties'),
   ('perdonar', 'vergeven', 'per-do-NAR', 'Te perdono.', 'Ik vergeef je.', 'relaties'),
   ('querer', 'houden van, willen', 'ke-RER', 'Te quiero mucho.', 'Ik hou veel van je.', 'relaties'),
   ('orgulloso', 'trots', 'or-goe-JO-so', 'Estoy orgullosa de ti.', 'Ik ben trots op je.', 'relaties'),
   ('enamorarse', 'verliefd worden', 'e-na-mo-RAR-se', 'Se enamoró en Sevilla.', 'Ze werd verliefd in Sevilla.', 'relaties')]),
L(76, '⚽', 'Sport & competitie', 'Over wedstrijden en uitslagen praten.',
  'Sport bespreken', 'Ganar (winnen), perder (verliezen), empatar (gelijkspelen). ¿Cómo quedó el partido? — Dos a uno. Ser de + team: soy del Barça.',
  [('el árbitro', 'de scheidsrechter', 'el AR-bi-tro', 'El árbitro pitó penalti.', 'De scheidsrechter floot voor een strafschop.', 'sport'),
   ('el campeonato', 'kampioenschap', 'el kam-pe-o-NA-to', 'El campeonato empieza en agosto.', 'Het kampioenschap begint in augustus.', 'sport'),
   ('el aficionado', 'supporter / fan', 'el a-fi-sjo-NA-do', 'Los aficionados cantan.', 'De supporters zingen.', 'sport'),
   ('el entrenador', 'trainer / coach', 'el en-tre-na-DOR', 'El entrenador es argentino.', 'De trainer is Argentijns.', 'sport'),
   ('el empate', 'gelijkspel', 'el em-PA-te', 'El partido terminó en empate.', 'De wedstrijd eindigde in een gelijkspel.', 'sport'),
   ('el récord', 'record', 'el RE-kord', 'Ha batido el récord.', 'Ze heeft het record gebroken.', 'sport'),
   ('marcar', 'scoren', 'mar-KAR', 'Marcó dos goles.', 'Hij scoorde twee doelpunten.', 'sport'),
   ('la victoria', 'de overwinning', 'la vik-TO-rja', 'Celebramos la victoria.', 'We vieren de overwinning.', 'sport')]),
L(77, '🎵', 'Muziek', 'Muziek en optredens.',
  'Muziek bespreken', 'Me encanta esta canción. ¿Quién la canta? Tocar un instrumento (bespelen), cantar (zingen), la letra (de songtekst).',
  [('el estribillo', 'het refrein', 'el es-tri-BIE-jo', 'El estribillo es pegadizo.', 'Het refrein blijft hangen.', 'muziek'),
   ('el grupo', 'de band', 'el GROE-po', 'Mi grupo favorito es de Sevilla.', 'Mijn favoriete band komt uit Sevilla.', 'muziek'),
   ('el instrumento', 'het instrument', 'el ins-troe-MEN-to', '¿Tocas algún instrumento?', 'Bespeel je een instrument?', 'muziek'),
   ('la melodía', 'de melodie', 'la me-lo-DIE-a', 'La melodía es muy triste.', 'De melodie is heel droevig.', 'muziek'),
   ('la letra', 'songtekst', 'la LE-tra', 'No entiendo la letra.', 'Ik begrijp de tekst niet.', 'muziek'),
   ('el escenario', 'het podium', 'el es-se-NA-rjo', 'La banda sube al escenario.', 'De band gaat het podium op.', 'muziek'),
   ('la voz', 'de stem', 'la vos', 'Tiene una voz muy bonita.', 'Zij heeft een heel mooie stem.', 'muziek'),
   ('el aplauso', 'applaus', 'el a-PLAU-so', 'Hubo un gran aplauso.', 'Er was een groot applaus.', 'muziek')]),
L(78, '🤝', 'Zakelijk Spaans', 'Zakelijke woorden en formeel contact.',
  'Formeel vs. informeel in zakelijke context', 'Zakelijk gebruik je "usted": ¿Podría enviarme la factura? Estimado señor / Estimada señora in brieven, afsluiten met "Atentamente".',
  [('la empresa', 'bedrijf', 'la em-PRE-sa', 'Trabajo en una empresa española.', 'Ik werk bij een Spaans bedrijf.', 'zakelijk'),
   ('la factura', 'factuur', 'la fak-TOE-ra', 'Envíeme la factura, por favor.', 'Stuurt u mij de factuur, alstublieft.', 'zakelijk'),
   ('la oferta', 'aanbod / aanbieding', 'la o-FER-ta', 'Tenemos una oferta especial.', 'We hebben een speciale aanbieding.', 'zakelijk'),
   ('negociar', 'onderhandelen', 'ne-go-SJAR', 'Negociamos el precio.', 'We onderhandelen over de prijs.', 'zakelijk'),
   ('el acuerdo', 'akkoord / overeenkomst', 'el a-KWER-do', 'Hemos llegado a un acuerdo.', 'We hebben een akkoord bereikt.', 'zakelijk'),
   ('el presupuesto', 'budget / offerte', 'el pre-soe-PWES-to', '¿Me puede enviar un presupuesto?', 'Kunt u mij een offerte sturen?', 'zakelijk'),
   ('el objetivo', 'doel / doelstelling', 'el ob-che-TIE-vo', 'Nuestro objetivo es crecer.', 'Ons doel is groeien.', 'zakelijk'),
   ('el cliente', 'klant', 'el KLJEN-te', 'El cliente siempre tiene razón.', 'De klant heeft altijd gelijk.', 'zakelijk')]),
L(79, '🎨', 'Kunst & cultuur', 'Over kunst en erfgoed praten.',
  'Kunstwerken beschrijven', 'Famoso por (beroemd om), pintado por (geschilderd door), construido en (gebouwd in). Fue pintado por Velázquez en 1656.',
  [('la tradición', 'traditie', 'la tra-di-SJON', 'Es una tradición muy antigua.', 'Het is een heel oude traditie.', 'cultuur'),
   ('la cultura', 'cultuur', 'la koel-TOE-ra', 'La cultura española es muy rica.', 'De Spaanse cultuur is heel rijk.', 'cultuur'),
   ('la historia', 'geschiedenis', 'la is-TO-rja', 'Me interesa la historia de España.', 'De geschiedenis van Spanje interesseert me.', 'cultuur'),
   ('el patrimonio', 'erfgoed', 'el pa-tri-MO-njo', 'La Alhambra es patrimonio de la humanidad.', 'Het Alhambra is werelderfgoed.', 'cultuur'),
   ('la pasión', 'passie', 'la pa-SJON', 'El flamenco es pura pasión.', 'Flamenco is pure passie.', 'cultuur'),
   ('el arte', 'kunst', 'el AR-te', 'El arte moderno no me gusta.', 'Ik hou niet van moderne kunst.', 'cultuur'),
   ('el pintor', 'de schilder', 'el pin-TOR', 'Goya fue un pintor español.', 'Goya was een Spaanse schilder.', 'cultuur'),
   ('el cuadro', 'het schilderij', 'el KWA-dro', 'Este cuadro es de Picasso.', 'Dit schilderij is van Picasso.', 'cultuur')]),
L(80, '☀️', '¡Fiesta!', 'Halverwege A2: de Spaanse levensstijl.',
  'A2 halverwege: het goede leven', 'Je kent nu ruim 600 woorden. Deze uitdrukkingen horen bij het Spaanse leven: la siesta, la sobremesa (natafelen), ir de tapas.',
  [('la siesta', 'de siësta', 'la SJES-ta', 'Después de comer, siesta.', 'Na het eten, siësta.', 'uitdrukkingen'),
   ('la sobremesa', 'het natafelen', 'la so-bre-ME-sa', 'La sobremesa duró dos horas.', 'Het natafelen duurde twee uur.', 'uitdrukkingen'),
   ('el amor', 'de liefde', 'el a-MOR', 'El amor lo cambia todo.', 'De liefde verandert alles.', 'uitdrukkingen'),
   ('la vida', 'het leven', 'la VIE-da', 'La vida es bella.', 'Het leven is mooi.', 'uitdrukkingen'),
   ('el abrazo', 'knuffel / omhelzing', 'el a-BRA-so', 'Un abrazo fuerte.', 'Een dikke knuffel.', 'uitdrukkingen'),
   ('ir de tapas', 'tapas gaan eten', 'ier de TA-pas', 'El viernes vamos de tapas.', 'Vrijdag gaan we tapas eten.', 'uitdrukkingen'),
   ('¡nos vemos!', 'we zien elkaar!', 'nos VE-mos', '¡Nos vemos el lunes!', 'We zien elkaar maandag!', 'uitdrukkingen'),
   ('¡hasta pronto!', 'tot snel!', 'AS-ta PRON-to', '¡Hasta pronto, amigos!', 'Tot snel, vrienden!', 'uitdrukkingen')]),
L(81, '📰', 'Politiek & samenleving', 'Over nieuws en politiek praten.',
  'Meningen over de maatschappij', 'A mi parecer (naar mijn mening), estoy a favor de / en contra de (ik ben voor / tegen). Me parece bien / mal que + subjuntivo komt pas in B1.',
  [('la noticia', 'nieuws / bericht', 'la no-TIE-sja', '¿Has visto las noticias?', 'Heb je het nieuws gezien?', 'samenleving'),
   ('el gobierno', 'regering', 'el go-BJER-no', 'El gobierno ha aprobado la ley.', 'De regering heeft de wet goedgekeurd.', 'samenleving'),
   ('las elecciones', 'verkiezingen', 'las e-lek-SJO-nes', 'Las elecciones son en mayo.', 'De verkiezingen zijn in mei.', 'samenleving'),
   ('el partido político', 'politieke partij', 'el par-TIE-do po-LIE-ti-ko', '¿Qué partido político prefieres?', 'Welke politieke partij heb jij het liefst?', 'samenleving'),
   ('la ley', 'wet', 'la lei', 'Es la ley.', 'Het is de wet.', 'samenleving'),
   ('el debate', 'debat', 'el de-BA-te', 'El debate fue muy largo.', 'Het debat was heel lang.', 'samenleving'),
   ('votar', 'stemmen', 'vo-TAR', 'Voto por correo.', 'Ik stem per post.', 'samenleving'),
   ('el derecho', 'recht', 'el de-RE-tsjo', 'Todos tienen derecho a votar.', 'Iedereen heeft het recht om te stemmen.', 'samenleving')]),
L(82, '🌱', 'Het milieu', 'Duurzaamheid en klimaat.',
  'Noodzaak: hay que, es necesario + infinitief', 'Hay que reciclar (men moet recyclen). Es necesario reducir el plástico. "Tener que" is persoonlijk: tenemos que ahorrar agua.',
  [('el cambio climático', 'klimaatverandering', 'el KAM-bjo kli-MA-ti-ko', 'El cambio climático es real.', 'Klimaatverandering is echt.', 'milieu'),
   ('la energía renovable', 'hernieuwbare energie', 'la e-ner-CHIE-a re-no-VA-ble', 'España invierte en energía renovable.', 'Spanje investeert in hernieuwbare energie.', 'milieu'),
   ('la biodiversidad', 'biodiversiteit', 'la bjo-di-ver-si-DAD', 'La biodiversidad está en peligro.', 'De biodiversiteit is in gevaar.', 'milieu'),
   ('sostenible', 'duurzaam', 'sos-te-NIE-ble', 'Un turismo sostenible.', 'Duurzaam toerisme.', 'milieu'),
   ('las emisiones', 'uitstoot', 'las e-mi-SJO-nes', 'Hay que reducir las emisiones.', 'De uitstoot moet omlaag.', 'milieu'),
   ('el plástico', 'plastic', 'el PLAS-ti-ko', 'Evito el plástico.', 'Ik vermijd plastic.', 'milieu'),
   ('la basura', 'afval', 'la ba-SOE-ra', 'Separo la basura.', 'Ik scheid het afval.', 'milieu'),
   ('proteger', 'beschermen', 'pro-te-CHER', 'Hay que proteger los océanos.', 'We moeten de oceanen beschermen.', 'milieu')]),
L(83, '💰', 'Economie', 'Economische onderwerpen begrijpen.',
  'Onpersoonlijk "se" in het nieuws', 'Se dice que (men zegt dat), se espera que (verwacht wordt dat), se necesita (er is nodig). Handig om nieuwsberichten te begrijpen.',
  [('la economía', 'economie', 'la e-ko-no-MIE-a', 'La economía crece despacio.', 'De economie groeit langzaam.', 'economie'),
   ('el mercado laboral', 'de arbeidsmarkt', 'el mer-KA-do la-bo-RAL', 'El mercado laboral mejora.', 'De arbeidsmarkt verbetert.', 'economie'),
   ('la inflación', 'inflatie', 'la in-fla-SJON', 'La inflación sube los precios.', 'De inflatie doet de prijzen stijgen.', 'economie'),
   ('el paro', 'werkloosheid', 'el PA-ro', 'El paro ha bajado.', 'De werkloosheid is gedaald.', 'economie'),
   ('invertir', 'investeren', 'in-ver-TIER', 'Invierten en tecnología.', 'Ze investeren in technologie.', 'economie'),
   ('la crisis', 'crisis', 'la KRIE-sis', 'La crisis afectó a muchas familias.', 'De crisis raakte veel gezinnen.', 'economie'),
   ('los impuestos', 'belastingen', 'los im-PWES-tos', 'Los impuestos son altos.', 'De belastingen zijn hoog.', 'economie'),
   ('ahorrar', 'sparen / besparen', 'a-o-RRAR', 'Ahorro cien euros al mes.', 'Ik spaar honderd euro per maand.', 'economie')]),
L(84, '🏃', 'Gezondheid & welzijn 2', 'Praten over hoe je je voelt en wat je deed.',
  'Bezig zijn in het verleden: estaba + gerundio', 'Estaba corriendo cuando me llamaste (ik was aan het hardlopen toen je belde). Imperfecto van estar + gerundio.',
  [('la meditación', 'meditatie', 'la me-di-ta-SJON', 'La meditación me ayuda.', 'Meditatie helpt me.', 'gezondheid'),
   ('la prevención', 'preventie', 'la pre-ven-SJON', 'La prevención es mejor que la cura.', 'Voorkomen is beter dan genezen.', 'gezondheid'),
   ('alimentarse bien', 'goed eten', 'a-li-men-TAR-se bjen', 'Hay que alimentarse bien.', 'Je moet goed eten.', 'gezondheid'),
   ('la forma física', 'lichamelijke conditie', 'la FOR-ma FIE-si-ka', 'Está en buena forma física.', 'Hij is in goede conditie.', 'gezondheid'),
   ('relajarse', 'ontspannen', 're-la-CHAR-se', 'Me relajo con música.', 'Ik ontspan met muziek.', 'gezondheid'),
   ('la respiración', 'ademhaling', 'la res-pi-ra-SJON', 'Controla la respiración.', 'Beheers je ademhaling.', 'gezondheid'),
   ('el cansancio', 'de vermoeidheid', 'el kan-SAN-sjo', 'El cansancio se nota.', 'De vermoeidheid is merkbaar.', 'gezondheid'),
   ('sentirse', 'zich voelen', 'sen-TIER-se', 'Me siento mucho mejor.', 'Ik voel me veel beter.', 'gezondheid')]),
L(85, '📚', 'Kunst & literatuur', 'Over boeken en kunst praten.',
  'Kunst en literatuur beschrijven', 'Trata de (gaat over), está escrito por (is geschreven door), me hizo pensar (zette me aan het denken). El libro trata de una familia en Madrid.',
  [('la novela', 'roman', 'la no-VE-la', 'Leo una novela de Carlos Ruiz Zafón.', 'Ik lees een roman van Carlos Ruiz Zafón.', 'cultuur'),
   ('la poesía', 'poëzie', 'la po-e-SIE-a', 'Me gusta la poesía de Lorca.', 'Ik hou van de poëzie van Lorca.', 'cultuur'),
   ('el escritor', 'schrijver', 'el es-kri-TOR', 'Cervantes es el escritor más famoso.', 'Cervantes is de beroemdste schrijver.', 'cultuur'),
   ('la escultura', 'sculptuur', 'la es-koel-TOE-ra', 'La escultura es de bronce.', 'De sculptuur is van brons.', 'cultuur'),
   ('interpretar', 'interpreteren', 'in-ter-pre-TAR', 'Cada uno interpreta el cuadro.', 'Iedereen interpreteert het schilderij anders.', 'cultuur'),
   ('el personaje', 'personage', 'el per-so-NA-che', 'El personaje principal es una mujer.', 'Het hoofdpersonage is een vrouw.', 'cultuur'),
   ('la obra maestra', 'meesterwerk', 'la O-bra ma-ES-tra', 'El Quijote es una obra maestra.', 'Don Quichot is een meesterwerk.', 'cultuur'),
   ('la inspiración', 'inspiratie', 'la ins-pi-ra-SJON', 'Busco inspiración en la naturaleza.', 'Ik zoek inspiratie in de natuur.', 'cultuur')]),
L(86, '🔬', 'Wetenschap', 'Wetenschappelijke woorden.',
  'Antes de / después de + infinitief', 'Antes de comer (voor het eten), después de estudiar (na het studeren). Het werkwoord blijft in de infinitief.',
  [('la investigación', 'onderzoek', 'la in-ves-ti-ga-SJON', 'La investigación tardó años.', 'Het onderzoek duurde jaren.', 'wetenschap'),
   ('el experimento', 'experiment', 'el eks-pe-ri-MEN-to', 'El experimento funcionó.', 'Het experiment werkte.', 'wetenschap'),
   ('la teoría', 'theorie', 'la te-o-RIE-a', 'Es solo una teoría.', 'Het is maar een theorie.', 'wetenschap'),
   ('los datos', 'gegevens / data', 'los DA-tos', 'Los datos son claros.', 'De gegevens zijn duidelijk.', 'wetenschap'),
   ('descubrir', 'ontdekken', 'des-koe-BRIER', 'Han descubierto un planeta nuevo.', 'Ze hebben een nieuwe planeet ontdekt.', 'wetenschap'),
   ('analizar', 'analyseren', 'a-na-li-SAR', 'Analizamos los resultados.', 'We analyseren de resultaten.', 'wetenschap'),
   ('la innovación', 'innovatie', 'la i-no-va-SJON', 'La innovación crea empleo.', 'Innovatie creëert werk.', 'wetenschap'),
   ('el descubrimiento', 'ontdekking', 'el des-koe-bri-MJEN-to', 'Fue un gran descubrimiento.', 'Het was een grote ontdekking.', 'wetenschap')]),
L(87, '🤝', 'De samenleving', 'Samenleven en verschillen.',
  'Toegeving uitdrukken: aunque, sin embargo', 'Aunque es difícil, lo intento (hoewel het moeilijk is, probeer ik het). Sin embargo (echter) verbindt twee zinnen: Es caro; sin embargo, vale la pena.',
  [('la sociedad', 'samenleving', 'la so-sje-DAD', 'La sociedad cambia rápido.', 'De samenleving verandert snel.', 'samenleving'),
   ('la comunidad', 'gemeenschap', 'la ko-moe-ni-DAD', 'Vivimos en una comunidad pequeña.', 'We wonen in een kleine gemeenschap.', 'samenleving'),
   ('la diversidad', 'diversiteit', 'la di-ver-si-DAD', 'La diversidad es una riqueza.', 'Diversiteit is een rijkdom.', 'samenleving'),
   ('la integración', 'integratie', 'la in-te-gra-SJON', 'La integración lleva tiempo.', 'Integratie kost tijd.', 'samenleving'),
   ('la solidaridad', 'solidariteit', 'la so-li-da-ri-DAD', 'Hubo mucha solidaridad.', 'Er was veel solidariteit.', 'samenleving'),
   ('el voluntariado', 'vrijwilligerswerk', 'el vo-loen-ta-RJA-do', 'Hago voluntariado los sábados.', 'Ik doe vrijwilligerswerk op zaterdag.', 'samenleving'),
   ('el prejuicio', 'vooroordeel', 'el pre-CHWI-sjo', 'Hay que superar los prejuicios.', 'Vooroordelen moeten we overwinnen.', 'samenleving'),
   ('incluir', 'insluiten', 'in-KLWIER', 'Hay que incluir a todos.', 'Iedereen moet erbij horen.', 'samenleving')]),
L(88, '🎓', 'Onderwijs', 'Over studeren en school praten.',
  'Doorvertellen: dijo que, me preguntó si', 'Dijo que venía (hij zei dat hij kwam). Me preguntó si tenía tiempo (hij vroeg me of ik tijd had). De tijd schuift een stap terug.',
  [('la universidad', 'universiteit', 'la oe-ni-ver-si-DAD', 'Estudio en la Universidad de Granada.', 'Ik studeer aan de Universiteit van Granada.', 'onderwijs'),
   ('la beca', 'studiebeurs', 'la BE-ka', 'Ha conseguido una beca.', 'Zij heeft een studiebeurs gekregen.', 'onderwijs'),
   ('la carrera', 'studie / universitaire opleiding', 'la ka-RRE-ra', 'Estudia la carrera de Medicina.', 'Hij studeert geneeskunde.', 'onderwijs'),
   ('el profesor universitario', 'professor', 'el pro-fe-SOR oe-ni-ver-si-TA-rjo', 'Mi tío es profesor universitario.', 'Mijn oom is professor.', 'onderwijs'),
   ('aprobar', 'slagen voor', 'a-pro-BAR', 'He aprobado el examen.', 'Ik ben geslaagd voor het examen.', 'onderwijs'),
   ('suspender', 'zakken voor', 'soes-pen-DER', 'Suspendí matemáticas.', 'Ik zakte voor wiskunde.', 'onderwijs'),
   ('aprender', 'leren', 'a-pren-DER', 'Aprendo algo nuevo cada día.', 'Ik leer elke dag iets nieuws.', 'onderwijs'),
   ('la asignatura', 'vak (school)', 'la a-sig-na-TOE-ra', 'Mi asignatura favorita es historia.', 'Mijn favoriete vak is geschiedenis.', 'onderwijs')]),
L(89, '📱', 'Media & communicatie', 'Nieuws, sociale media en reclame.',
  'Tijdsbijzinnen: cuando, mientras, después de que', 'Cuando llego a casa, veo las noticias. Mientras como, leo el periódico. Bij toekomst volgt na "cuando" de subjuntivo (B1).',
  [('el periódico', 'krant', 'el pe-RJO-di-ko', 'Leo el periódico cada mañana.', 'Ik lees elke ochtend de krant.', 'media'),
   ('la televisión', 'televisie', 'la te-le-vi-SJON', 'Veo poco la televisión.', 'Ik kijk weinig televisie.', 'media'),
   ('las redes sociales', 'sociale media', 'las RE-des so-SJA-les', 'Paso mucho tiempo en las redes sociales.', 'Ik zit veel op sociale media.', 'media'),
   ('las noticias falsas', 'nepnieuws', 'las no-TIE-sjas FAL-sas', 'Cuidado con las noticias falsas.', 'Pas op voor nepnieuws.', 'media'),
   ('emitir', 'uitzenden', 'e-mi-TIER', 'Emiten el partido a las nueve.', 'Ze zenden de wedstrijd om negen uur uit.', 'media'),
   ('la publicidad', 'reclame', 'la poe-bli-si-DAD', 'Hay demasiada publicidad.', 'Er is te veel reclame.', 'media'),
   ('el influencer', 'influencer', 'el in-FLOE-en-ser', 'Es un influencer famoso.', 'Hij is een beroemde influencer.', 'media'),
   ('la comunicación', 'communicatie', 'la ko-moe-ni-ka-SJON', 'La comunicación es clave.', 'Communicatie is de sleutel.', 'media')]),
L(90, '🔮', 'Toekomst & dromen', 'Over plannen en dromen praten.',
  'Plannen: tengo la intención de, espero', 'Tengo la intención de viajar (ik ben van plan te reizen). Espero encontrar trabajo (ik hoop werk te vinden). Sueño con vivir en España.',
  [('el sueño', 'droom', 'el SWE-njo', 'Mi sueño es vivir en Barcelona.', 'Mijn droom is in Barcelona wonen.', 'toekomst'),
   ('el plan', 'project / plan', 'el plan', '¿Tienes planes para el verano?', 'Heb je plannen voor de zomer?', 'toekomst'),
   ('confiar en', 'vertrouwen op', 'kon-FJAR en', 'Confío en el futuro.', 'Ik vertrouw op de toekomst.', 'toekomst'),
   ('la esperanza', 'de hoop', 'la es-pe-RAN-sa', 'Nunca pierdo la esperanza.', 'Ik verlies nooit de hoop.', 'toekomst'),
   ('el mundo', 'de wereld', 'el MOEN-do', 'Quiero ver el mundo.', 'Ik wil de wereld zien.', 'toekomst'),
   ('la meta', 'doel', 'la ME-ta', 'Mi meta es hablar bien español.', 'Mijn doel is goed Spaans spreken.', 'toekomst'),
   ('el futuro', 'toekomst', 'el foe-TOE-ro', 'El futuro es incierto.', 'De toekomst is onzeker.', 'toekomst'),
   ('¡bien hecho!', 'goed gedaan!', 'bjen E-tsjo', '¡Bien hecho, sigue así!', 'Goed gedaan, ga zo door!', 'toekomst')]),
L(91, '⏮️', 'Pretérito indefinido', 'Vertellen wat er op een bepaald moment gebeurde.',
  'Pretérito indefinido: afgeronde acties', 'Ayer comí, la semana pasada fui. Regelmatig: -ar → -é, -aste, -ó, -amos, -asteis, -aron; -er/-ir → -í, -iste, -ió, -imos, -isteis, -ieron. Onregelmatig: fui (ser/ir), hice, tuve, estuve, dije.',
  [('anteayer', 'eergisteren', 'an-te-a-JER', 'Anteayer llegué a Madrid.', 'Eergisteren kwam ik in Madrid aan.', 'verleden'),
   ('la semana pasada', 'vorige week', 'la se-MA-na pa-SA-da', 'La semana pasada fui al cine.', 'Vorige week ging ik naar de bioscoop.', 'verleden'),
   ('el año pasado', 'vorig jaar', 'el A-njo pa-SA-do', 'El año pasado visité Sevilla.', 'Vorig jaar bezocht ik Sevilla.', 'verleden'),
   ('hace', 'geleden', 'A-se', 'Llegué hace dos días.', 'Ik kwam twee dagen geleden aan.', 'verleden'),
   ('fui', 'ik ging / ik was', 'fwi', 'Fui a Granada en marzo.', 'Ik ging in maart naar Granada.', 'verleden'),
   ('hice', 'ik deed / ik maakte', 'IE-se', 'Hice una tortilla.', 'Ik maakte een tortilla.', 'verleden'),
   ('tuve', 'ik had', 'TOE-ve', 'Tuve mucha suerte.', 'Ik had veel geluk.', 'verleden'),
   ('de repente', 'plotseling', 'de re-PEN-te', 'De repente empezó a llover.', 'Plotseling begon het te regenen.', 'verleden')]),
L(92, '🌅', 'Dagelijkse routine', 'Je dag beschrijven.',
  'Wederkerende werkwoorden in de routine', 'Me despierto, me levanto, me ducho, me visto, me acuesto. Klinkerwisseling: despertarse → me despierto, acostarse → me acuesto.',
  [('despertarse', 'wakker worden', 'des-per-TAR-se', 'Me despierto a las siete.', 'Ik word om zeven uur wakker.', 'routine'),
   ('levantarse', 'opstaan', 'le-van-TAR-se', 'Me levanto enseguida.', 'Ik sta meteen op.', 'routine'),
   ('ducharse', 'douchen', 'doe-TSJAR-se', 'Me ducho por la mañana.', "Ik douche 's ochtends.", 'routine'),
   ('desayunar', 'ontbijten', 'de-sa-joe-NAR', 'Desayuno tostadas con tomate.', 'Ik ontbijt met toast met tomaat.', 'routine'),
   ('ir al trabajo', 'naar het werk gaan', 'ier al tra-BA-cho', 'Voy al trabajo en metro.', 'Ik ga met de metro naar het werk.', 'routine'),
   ('el almuerzo', 'de lunch', 'el al-MWER-so', 'El almuerzo es a las dos.', 'De lunch is om twee uur.', 'routine'),
   ('volver', 'terugkeren', 'vol-VER', 'Vuelvo a casa a las seis.', 'Ik kom om zes uur thuis.', 'routine'),
   ('acostarse', 'naar bed gaan', 'a-kos-TAR-se', 'Me acuesto a las once.', 'Ik ga om elf uur naar bed.', 'routine')]),
L(93, '📅', 'Afspraken maken', 'Iets afspreken met iemand.',
  'Afspraken maken: uitdrukkingen', '¿Quedamos el sábado? (Zullen we zaterdag afspreken?) ¿Te apetece ir al cine? (Heb je zin om naar de bioscoop te gaan?) Vale, ¡hasta entonces!',
  [('quedar', 'afspreken', 'ke-DAR', '¿Quedamos a las ocho?', 'Zullen we om acht uur afspreken?', 'afspraken'),
   ('libre', 'vrij / beschikbaar', 'LIE-bre', '¿Estás libre el domingo?', 'Ben je zondag vrij?', 'afspraken'),
   ('¿te apetece?', 'heb je zin om?', 'te a-pe-TE-se', '¿Te apetece un café?', 'Heb je zin in een koffie?', 'afspraken'),
   ('lo siento', 'helaas / het spijt me', 'lo SJEN-to', 'Lo siento, no puedo.', 'Sorry, ik kan niet.', 'afspraken'),
   ('encontrarse', 'ontmoeten / elkaar treffen', 'en-kon-TRAR-se', 'Nos encontramos en la plaza.', 'We treffen elkaar op het plein.', 'afspraken'),
   ('el momento', 'het moment', 'el mo-MEN-to', 'Un momento, por favor.', 'Een ogenblik, alstublieft.', 'afspraken'),
   ('vale', 'oké', 'VA-le', 'Vale, nos vemos allí.', 'Oké, we zien elkaar daar.', 'afspraken'),
   ('cancelar', 'afzeggen', 'kan-se-LAR', 'Tengo que cancelar la cita.', 'Ik moet de afspraak afzeggen.', 'afspraken')]),
L(94, '🗓️', 'Plannen voor de toekomst', 'Toekomstplannen uitdrukken.',
  'Toekomst: futuro vs. ir a + infinitief', 'Voor concrete plannen "ir a": voy a estudiar. Voor voorspellingen en beloftes het futuro: estudiaré. Beide zijn correct in gesprekken.',
  [('pensar en', 'van plan zijn / denken aan', 'pen-SAR en', 'Pienso en cambiar de trabajo.', 'Ik denk erover om van baan te veranderen.', 'toekomst'),
   ('soñar con', 'dromen van', 'so-NJAR kon', 'Sueño con vivir en la costa.', 'Ik droom ervan aan de kust te wonen.', 'toekomst'),
   ('el año que viene', 'volgend jaar', 'el A-njo ke VJE-ne', 'El año que viene viajaré a México.', 'Volgend jaar reis ik naar Mexico.', 'toekomst'),
   ('en el futuro', 'in de toekomst', 'en el foe-TOE-ro', 'En el futuro quiero tener una casa.', 'In de toekomst wil ik een huis.', 'toekomst'),
   ('alcanzar', 'bereiken / halen', 'al-kan-SAR', 'Quiero alcanzar el nivel B1.', 'Ik wil niveau B1 halen.', 'toekomst'),
   ('decidir', 'beslissen', 'de-si-DIER', 'He decidido aprender español.', 'Ik heb besloten Spaans te leren.', 'toekomst'),
   ('conseguir', 'bereiken, krijgen', 'kon-se-GIER', 'Conseguiré un buen trabajo.', 'Ik zal een goede baan krijgen.', 'toekomst'),
   ('la oportunidad', 'de kans', 'la o-por-toe-ni-DAD', 'Es una gran oportunidad.', 'Het is een grote kans.', 'toekomst')]),
L(95, '🧺', 'Op de markt', 'Hoeveelheden vragen op de markt.',
  'Hoeveelheden en gewichten', 'Un kilo de, medio kilo de, cuarto kilo de, una docena de, un litro de. ¿Me pone un kilo de naranjas? — ¿Algo más? — Nada más, gracias.',
  [('la lista de la compra', 'de boodschappenlijst', 'la LIS-ta de la KOM-pra', 'He hecho la lista de la compra.', 'Ik heb een boodschappenlijst gemaakt.', 'winkelen'),
   ('de temporada', 'seizoensgebonden', 'de tem-po-RA-da', 'Compro fruta de temporada.', 'Ik koop fruit van het seizoen.', 'winkelen'),
   ('el vendedor', 'de verkoper', 'el ven-de-DOR', 'El vendedor es muy simpático.', 'De verkoper is heel aardig.', 'winkelen'),
   ('pesar', 'wegen', 'pe-SAR', '¿Me lo pesa, por favor?', 'Kunt u het even wegen?', 'winkelen'),
   ('la vuelta', 'het wisselgeld', 'la VWEL-ta', 'Quédese con la vuelta.', 'Houd het wisselgeld maar.', 'winkelen'),
   ('ecológico', 'biologisch', 'e-ko-LO-chi-ko', 'Estas verduras son ecológicas.', 'Deze groenten zijn biologisch.', 'winkelen'),
   ('medio kilo', 'een halve kilo', 'ME-djo KIE-lo', 'Medio kilo de fresas.', 'Een halve kilo aardbeien.', 'winkelen'),
   ('¿algo más?', 'nog iets?', 'AL-go mas', '¿Algo más? — No, nada más.', 'Nog iets? — Nee, dat is alles.', 'winkelen')]),
L(96, '👨‍🍳', 'Koken & recepten', 'Een recept volgen.',
  'De gebiedende wijs in recepten', 'Corta (snijd), mezcla (meng), añade (voeg toe), cuece (kook). Tú-vorm = derde persoon presente. Onregelmatig: pon (poner), haz (hacer).',
  [('cortar', 'snijden', 'kor-TAR', 'Corta la cebolla.', 'Snijd de ui.', 'koken'),
   ('mezclar', 'mengen / roeren', 'mes-KLAR', 'Mezcla bien los huevos.', 'Meng de eieren goed.', 'koken'),
   ('añadir', 'toevoegen', 'a-nja-DIER', 'Añade sal y pimienta.', 'Voeg zout en peper toe.', 'koken'),
   ('freír', 'bakken / frituren', 'fre-IER', 'Fríe las patatas.', 'Bak de aardappels.', 'koken'),
   ('la sartén', 'de koekenpan', 'la sar-TEN', 'Calienta la sartén.', 'Verwarm de koekenpan.', 'koken'),
   ('el horno', 'de oven', 'el OR-no', 'Hornea treinta minutos en el horno.', 'Bak dertig minuten in de oven.', 'koken'),
   ('probar', 'proeven', 'pro-BAR', 'Prueba la salsa.', 'Proef de saus.', 'koken'),
   ('el ingrediente', 'het ingrediënt', 'el in-gre-DJEN-te', 'Solo tiene cuatro ingredientes.', 'Het heeft maar vier ingrediënten.', 'koken')]),
L(97, '🎬', 'Bioscoop & uitgaan', 'Over films en uitgaan praten.',
  'Meningen over films', 'Me gustó mucho (ik vond het heel leuk), me encantó (ik vond het geweldig), me aburrió (het verveelde me). ¿De qué trata? (Waar gaat het over?)',
  [('la película', 'de film', 'la pe-LIE-koe-la', 'La película dura dos horas.', 'De film duurt twee uur.', 'uitgaan'),
   ('la entrada', 'ticket', 'la en-TRA-da', 'Dos entradas, por favor.', 'Twee kaartjes, alstublieft.', 'uitgaan'),
   ('la trama', 'het verhaal / de plot', 'la TRA-ma', 'La trama es complicada.', 'De plot is ingewikkeld.', 'uitgaan'),
   ('actuar', 'acteren / spelen', 'ak-TWAR', 'El actor actúa muy bien.', 'De acteur speelt heel goed.', 'uitgaan'),
   ('la sesión', 'de voorstelling', 'la se-SJON', 'La sesión de las diez está llena.', 'De voorstelling van tien uur is vol.', 'uitgaan'),
   ('me gustó', 'ik vond het leuk', 'me goes-TO', 'Me gustó mucho el final.', 'Ik vond het einde heel goed.', 'uitgaan'),
   ('emocionante', 'aangrijpend / spannend', 'e-mo-sjo-NAN-te', 'Fue una película emocionante.', 'Het was een spannende film.', 'uitgaan'),
   ('aburrido', 'saai', 'a-boe-RRIE-do', 'La segunda parte es aburrida.', 'Het tweede deel is saai.', 'uitgaan')]),
L(98, '👫', 'Vrienden & sociale plannen', 'Uitnodigen en reageren.',
  'Uitnodigen en reageren', '¿Quieres venir? (Wil je komen?) ¿Vienes con nosotros? Ja: ¡Claro! ¡Con mucho gusto! Nee: Lo siento, no puedo. Otro día, ¿vale?',
  [('conocer', 'kennen, leren kennen', 'ko-no-SER', 'Conozco a Marta desde hace años.', 'Ik ken Marta al jaren.', 'vrienden'),
   ('salir juntos', 'samen uitgaan', 'sa-LIER CHOEN-tos', 'Salimos juntos los viernes.', 'We gaan vrijdag samen uit.', 'vrienden'),
   ('invitar', 'uitnodigen', 'in-vi-TAR', 'Te invito a cenar.', 'Ik nodig je uit om te eten.', 'vrienden'),
   ('la compañía', 'het gezelschap', 'la kom-pa-NJIE-a', 'Me gusta tu compañía.', 'Ik hou van je gezelschap.', 'vrienden'),
   ('charlar', 'een praatje maken, kletsen', 'tsjar-LAR', 'Charlamos hasta muy tarde.', 'We kletsten tot heel laat.', 'vrienden'),
   ('el amigo', 'de vriend', 'el a-MIE-go', 'Es mi mejor amigo.', 'Hij is mijn beste vriend.', 'vrienden'),
   ('divertirse', 'zich amuseren / plezier hebben', 'di-ver-TIER-se', 'Nos divertimos mucho.', 'We hebben veel plezier gehad.', 'vrienden'),
   ('¡claro!', 'natuurlijk!', 'KLA-ro', '¿Vienes? — ¡Claro!', 'Kom je? — Natuurlijk!', 'vrienden')]),
L(99, '🏠', 'Huis zoeken & huren', 'Een woning huren.',
  'Woningen beschrijven', 'Un piso de dos habitaciones, amueblado, con terraza. ¿Cuánto es el alquiler? ¿Los gastos están incluidos? Se alquila (te huur).',
  [('el piso', 'het appartement', 'el PIE-so', 'Busco un piso en el centro.', 'Ik zoek een appartement in het centrum.', 'wonen'),
   ('el alquiler', 'de huur / de huurprijs', 'el al-ki-LER', 'El alquiler es de ochocientos euros.', 'De huur is achthonderd euro.', 'wonen'),
   ('amueblado', 'gemeubileerd', 'a-mwe-BLA-do', 'El piso está amueblado.', 'Het appartement is gemeubileerd.', 'wonen'),
   ('los gastos', 'de kosten / bijkomende kosten', 'los GAS-tos', 'Los gastos no están incluidos.', 'De bijkomende kosten zijn niet inbegrepen.', 'wonen'),
   ('el contrato de alquiler', 'het huurcontract', 'el kon-TRA-to de al-ki-LER', 'Firmamos el contrato de alquiler.', 'We tekenen het huurcontract.', 'wonen'),
   ('el propietario', 'de eigenaar / verhuurder', 'el pro-pje-TA-rjo', 'El propietario vive arriba.', 'De eigenaar woont boven.', 'wonen'),
   ('la fianza', 'de borg', 'la FJAN-sa', 'La fianza es de un mes.', 'De borg is één maand huur.', 'wonen'),
   ('mudarse', 'verhuizen', 'moe-DAR-se', 'Nos mudamos en septiembre.', 'We verhuizen in september.', 'wonen')]),
L(100, '🏆', '🎉 100 lessen!', 'Honderd lessen: goed bezig!',
  'Trots zijn: complimenten geven en ontvangen', '¡Enhorabuena! ¡Qué bien hablas! Antwoorden: Gracias, todavía estoy aprendiendo. Estar orgulloso de (trots zijn op).',
  [('el logro', 'de prestatie', 'el LO-gro', 'Es un gran logro.', 'Het is een grote prestatie.', 'motivatie'),
   ('el progreso', 'de vooruitgang', 'el pro-GRE-so', 'Tu progreso es enorme.', 'Je vooruitgang is enorm.', 'motivatie'),
   ('mejorar', 'verbeteren', 'me-cho-RAR', 'Cada día mejoro un poco.', 'Elke dag word ik een beetje beter.', 'motivatie'),
   ('esforzarse', 'zich inzetten', 'es-for-SAR-se', 'Te has esforzado mucho.', 'Je hebt je flink ingezet.', 'motivatie'),
   ('la constancia', 'de volharding', 'la kons-TAN-sja', 'La constancia da resultados.', 'Volharding geeft resultaat.', 'motivatie'),
   ('estar orgulloso de', 'trots zijn op', 'es-TAR or-goe-JO-so de', 'Estoy orgulloso de mi progreso.', 'Ik ben trots op mijn vooruitgang.', 'motivatie'),
   ('seguir', 'doorgaan / verdergaan', 'se-GIER', 'Sigue así.', 'Ga zo door.', 'motivatie'),
   ('fantástico', 'fantastisch', 'fan-TAS-ti-ko', '¡Fantástico, lo has conseguido!', 'Fantastisch, je hebt het gehaald!', 'motivatie')]),
L(101, '🏦', 'Bij de bank', 'Bankzaken regelen.',
  'Bankzaken in Spanje', 'Quiero abrir una cuenta (een rekening openen). Sacar dinero (geld opnemen), ingresar (storten), hacer una transferencia (overboeken). Het pinapparaat heet "el cajero".',
  [('la cuenta corriente', 'de betaalrekening', 'la KWEN-ta ko-RRJEN-te', 'Quiero abrir una cuenta corriente.', 'Ik wil een betaalrekening openen.', 'bank'),
   ('sacar dinero', 'geld opnemen', 'sa-KAR di-NE-ro', 'Saco dinero del cajero.', 'Ik neem geld op bij de automaat.', 'bank'),
   ('ingresar', 'storten', 'in-gre-SAR', 'Ingreso el dinero mañana.', 'Ik stort het geld morgen.', 'bank'),
   ('la transferencia', 'de overboeking', 'la trans-fe-REN-sja', 'He hecho una transferencia.', 'Ik heb een overboeking gedaan.', 'bank'),
   ('el cajero automático', 'de geldautomaat', 'el ka-CHE-ro au-to-MA-ti-ko', '¿Dónde hay un cajero automático?', 'Waar is een geldautomaat?', 'bank'),
   ('la tarjeta de crédito', 'de creditcard', 'la tar-CHE-ta de KRE-di-to', 'Pago con tarjeta de crédito.', 'Ik betaal met creditcard.', 'bank'),
   ('los intereses', 'de rente', 'los in-te-RE-ses', 'Los intereses son bajos.', 'De rente is laag.', 'bank'),
   ('el dinero', 'het geld', 'el di-NE-ro', 'No tengo dinero en efectivo.', 'Ik heb geen contant geld.', 'bank')]),
L(102, '🎉', 'Feestjes & gelegenheden', 'Feestvieren en gelukwensen.',
  'Wensen en gelukwensen', '¡Felicidades! (gefeliciteerd), ¡Feliz cumpleaños!, ¡Enhorabuena! (bij een prestatie), ¡Que lo pases bien! (veel plezier), ¡Salud! (proost).',
  [('¡felicidades!', 'gefeliciteerd!', 'fe-li-si-DA-des', '¡Felicidades por tu cumpleaños!', 'Gefeliciteerd met je verjaardag!', 'feest'),
   ('celebrar', 'vieren', 'se-le-BRAR', 'Celebramos el cumpleaños de Ana.', 'We vieren de verjaardag van Ana.', 'feest'),
   ('el regalo', 'het cadeau', 'el re-GA-lo', 'Gracias por el regalo.', 'Bedankt voor het cadeau.', 'feest'),
   ('brindar', 'toasten / klinken', 'brin-DAR', 'Brindamos por los novios.', 'We toasten op het bruidspaar.', 'feest'),
   ('la boda', 'de bruiloft', 'la BO-da', 'La boda es en junio.', 'De bruiloft is in juni.', 'feest'),
   ('la ceremonia', 'de ceremonie', 'la se-re-MO-nja', 'La ceremonia fue preciosa.', 'De ceremonie was prachtig.', 'feest'),
   ('organizar', 'organiseren', 'or-ga-ni-SAR', 'Organizo una fiesta sorpresa.', 'Ik organiseer een verrassingsfeest.', 'feest'),
   ('¡salud!', 'proost!', 'sa-LOED', '¡Salud, y feliz año!', 'Proost, en gelukkig nieuwjaar!', 'feest')]),
L(103, '😤', 'Klachten & problemen', 'Een klacht indienen.',
  'Een klacht uiten: beleefd maar duidelijk', 'Perdone, tengo un problema con... (Pardon, ik heb een probleem met...). Quisiera una solución. ¿Puedo hablar con el responsable?',
  [('quejarse', 'klagen', 'ke-CHAR-se', 'Me quejo del servicio.', 'Ik klaag over de service.', 'klachten'),
   ('no funciona', 'het werkt niet', 'no foen-SJO-na', 'El aire acondicionado no funciona.', 'De airconditioning werkt niet.', 'klachten'),
   ('la avería', 'de storing / het defect', 'la a-ve-RIE-a', 'Hay una avería en el ascensor.', 'Er is een storing in de lift.', 'klachten'),
   ('pedir un reembolso', 'om terugbetaling vragen', 'pe-DIER oen re-em-BOL-so', 'Quiero pedir un reembolso.', 'Ik wil om terugbetaling vragen.', 'klachten'),
   ('el responsable', 'de verantwoordelijke / de manager', 'el res-pon-SA-ble', '¿Puedo hablar con el responsable?', 'Kan ik de verantwoordelijke spreken?', 'klachten'),
   ('el problema', 'het probleem', 'el pro-BLE-ma', 'Tengo un problema con la habitación.', 'Ik heb een probleem met de kamer.', 'klachten'),
   ('solucionar', 'oplossen', 'so-loe-sjo-NAR', 'Lo solucionamos enseguida.', 'We lossen het meteen op.', 'klachten'),
   ('la garantía', 'de garantie', 'la ga-ran-TIE-a', 'Todavía está en garantía.', 'Het zit nog in de garantie.', 'klachten')]),
L(104, '👤', 'Beschrijven van mensen', 'Het uiterlijk van mensen beschrijven.',
  'Bijvoeglijke naamwoorden voor uiterlijk', 'Tiene el pelo rubio / moreno / largo. Lleva gafas (draagt een bril). Es alto y delgado. "Ser" voor uiterlijk, "llevar" voor wat iemand draagt.',
  [('el pelo', 'het haar', 'el PE-lo', 'Tiene el pelo largo y moreno.', 'Ze heeft lang, donker haar.', 'mensen'),
   ('la barba', 'de baard', 'la BAR-ba', 'Mi padre lleva barba.', 'Mijn vader heeft een baard.', 'mensen'),
   ('rubio', 'blond', 'ROE-bjo', 'Mi hermana es rubia.', 'Mijn zus is blond.', 'mensen'),
   ('moreno', 'donkerharig / getint', 'mo-RE-no', 'Es moreno con ojos verdes.', 'Hij is donkerharig met groene ogen.', 'mensen'),
   ('delgado', 'slank', 'del-GA-do', 'Es alta y delgada.', 'Ze is lang en slank.', 'mensen'),
   ('parecerse a', 'lijken op', 'pa-re-SER-se a', 'Se parece a su madre.', 'Ze lijkt op haar moeder.', 'mensen'),
   ('llevar', 'dragen (kleding, bril)', 'je-VAR', 'Lleva gafas y una gorra.', 'Hij draagt een bril en een pet.', 'mensen'),
   ('joven', 'jong', 'CHO-ven', 'Es un hombre joven.', 'Het is een jonge man.', 'mensen')]),
L(105, '✈️', 'Reizen plannen', 'Een reis voorbereiden.',
  'Plannen: tengo pensado, pienso', 'Tengo pensado ir a Perú (ik ben van plan naar Peru te gaan). Pienso quedarme una semana. Voy a reservar el hotel hoy.',
  [('el viaje organizado', 'de georganiseerde reis', 'el VJA-che or-ga-ni-SA-do', 'Prefiero un viaje organizado.', 'Ik heb liever een georganiseerde reis.', 'reizen'),
   ('la guía de viaje', 'de reisgids', 'la GIE-a de VJA-che', 'Compré una guía de viaje.', 'Ik heb een reisgids gekocht.', 'reizen'),
   ('el visado', 'het visum', 'el vi-SA-do', 'No necesito visado.', 'Ik heb geen visum nodig.', 'reizen'),
   ('el destino', 'de bestemming', 'el des-TIE-no', 'Nuestro destino es Lima.', 'Onze bestemming is Lima.', 'reizen'),
   ('la estancia', 'het verblijf', 'la es-TAN-sja', 'La estancia dura diez días.', 'Het verblijf duurt tien dagen.', 'reizen'),
   ('el alojamiento', 'de accommodatie', 'el a-lo-cha-MJEN-to', 'El alojamiento está incluido.', 'De accommodatie is inbegrepen.', 'reizen'),
   ('la escala', 'de tussenstop', 'la es-KA-la', 'Hacemos escala en Madrid.', 'We maken een tussenstop in Madrid.', 'reizen'),
   ('tengo pensado', 'ik ben van plan', 'TEN-go pen-SA-do', 'Tengo pensado visitar Cusco.', 'Ik ben van plan Cusco te bezoeken.', 'reizen')]),
L(106, '🚇', 'Vervoer & mobiliteit', 'Openbaar vervoer en de auto.',
  'Vervoer: kaartjes en routebeschrijving', '¿Dónde compro el billete? Hay que hacer transbordo en Sol (overstappen). ¿Cuánto tarda? Con retraso / a tiempo.',
  [('hacer transbordo', 'overstappen', 'a-SER trans-BOR-do', 'Hay que hacer transbordo en Sol.', 'Je moet overstappen bij Sol.', 'vervoer'),
   ('el abono', 'het abonnement', 'el a-BO-no', 'Tengo un abono mensual.', 'Ik heb een maandabonnement.', 'vervoer'),
   ('a tiempo', 'op tijd', 'a TJEM-po', 'El tren llegó a tiempo.', 'De trein kwam op tijd aan.', 'vervoer'),
   ('alquilar', 'huren', 'al-ki-LAR', 'Alquilamos un coche.', 'We huren een auto.', 'vervoer'),
   ('el accidente', 'het ongeluk', 'el ak-si-DEN-te', 'Hubo un accidente en la autopista.', 'Er was een ongeluk op de snelweg.', 'vervoer'),
   ('el atasco', 'de file', 'el a-TAS-ko', 'Hay un atasco enorme.', 'Er staat een enorme file.', 'vervoer'),
   ('la gasolina', 'de benzine', 'la ga-so-LIE-na', 'La gasolina está cara.', 'Benzine is duur.', 'vervoer'),
   ('aparcar', 'parkeren', 'a-par-KAR', 'Es difícil aparcar en el centro.', 'Parkeren in het centrum is lastig.', 'vervoer')]),
L(107, '😔', 'Spijt & wensen', 'Spijt en wensen uitdrukken.',
  'Spijt uitdrukken: tendría que haber, ojalá', 'Tendría que haber estudiado más (ik had meer moeten studeren). ¡Ojalá! (hopelijk / was het maar zo). Me arrepiento de (ik heb spijt van).',
  [('¡qué pena!', 'wat jammer!', 'ke PE-na', '¡Qué pena que no puedas venir!', 'Wat jammer dat je niet kunt komen!', 'gevoelens'),
   ('lo siento mucho', 'het spijt me erg', 'lo SJEN-to MOE-tsjo', 'Lo siento mucho, fue mi culpa.', 'Het spijt me erg, het was mijn schuld.', 'gevoelens'),
   ('me arrepiento', 'ik heb spijt', 'me a-rre-PJEN-to', 'Me arrepiento de no haber ido.', 'Ik heb er spijt van dat ik niet ben gegaan.', 'gevoelens'),
   ('olvidar', 'vergeten', 'ol-vi-DAR', 'Olvidé tu cumpleaños.', 'Ik ben je verjaardag vergeten.', 'gevoelens'),
   ('ojalá', 'hopelijk / was het maar zo', 'o-cha-LA', 'Ojalá haga sol mañana.', 'Hopelijk schijnt morgen de zon.', 'gevoelens'),
   ('equivocarse', 'een fout maken', 'e-ki-vo-KAR-se', 'Me equivoqué de tren.', 'Ik nam de verkeerde trein.', 'gevoelens'),
   ('la culpa', 'de schuld', 'la KOEL-pa', 'No es culpa tuya.', 'Het is niet jouw schuld.', 'gevoelens'),
   ('tendría que', 'ik had moeten', 'ten-DRIE-a ke', 'Tendría que haber llamado.', 'Ik had moeten bellen.', 'gevoelens')]),
L(108, '🍝', 'Culinaire tradities', 'De Spaanse keuken per regio.',
  'Regionale verschillen in Spanje', 'Elke regio heeft eigen gerechten: paella (Valencia), pulpo (Galicia), gazpacho (Andalusië), pintxos (Baskenland). "Es típico de" = het is typisch voor.',
  [('la cocina regional', 'de regionale keuken', 'la ko-SIE-na re-chjo-NAL', 'La cocina regional es muy variada.', 'De regionale keuken is heel gevarieerd.', 'eten'),
   ('el plato típico', 'het typische gerecht', 'el PLA-to TIE-pi-ko', 'El gazpacho es un plato típico andaluz.', 'Gazpacho is een typisch Andalusisch gerecht.', 'eten'),
   ('los ingredientes', 'de ingrediënten', 'los in-gre-DJEN-tes', 'Los ingredientes son frescos.', 'De ingrediënten zijn vers.', 'eten'),
   ('el aperitivo', 'het aperitief', 'el a-pe-ri-TIE-vo', 'Tomamos el aperitivo a la una.', 'We nemen om één uur het aperitief.', 'eten'),
   ('el marisco', 'zeevruchten', 'el ma-RIS-ko', 'En Galicia el marisco es excelente.', 'In Galicië zijn de zeevruchten uitstekend.', 'eten'),
   ('el pincho', 'pincho (hapje op brood)', 'el PIN-tsjo', 'En Bilbao comemos pinchos.', 'In Bilbao eten we pinchos.', 'eten'),
   ('a base de', 'op basis van', 'a BA-se de', 'Es una sopa a base de tomate.', 'Het is een soep op basis van tomaat.', 'eten'),
   ('el vino de la casa', 'de huiswijn', 'el VIE-no de la KA-sa', 'Una copa de vino de la casa.', 'Een glas huiswijn.', 'eten')]),
L(109, '🥗', 'Gezondheid & leefstijl', 'Gezonde gewoontes.',
  'Frequentie uitdrukken', 'Siempre, casi siempre, a menudo, a veces, casi nunca, nunca. Dos veces por semana (twee keer per week), todos los días (elke dag).',
  [('la alimentación', 'de voeding', 'la a-li-men-ta-SJON', 'Una alimentación sana es básica.', 'Gezonde voeding is de basis.', 'gezondheid'),
   ('hacer ejercicio', 'bewegen / sporten', 'a-SER e-cher-SIE-sjo', 'Hago ejercicio tres veces por semana.', 'Ik sport drie keer per week.', 'gezondheid'),
   ('evitar', 'vermijden', 'e-vi-TAR', 'Evito el azúcar.', 'Ik vermijd suiker.', 'gezondheid'),
   ('a veces', 'soms', 'a VE-ses', 'A veces como fuera.', 'Soms eet ik buiten de deur.', 'gezondheid'),
   ('casi nunca', 'bijna nooit', 'KA-si NOEN-ka', 'Casi nunca bebo alcohol.', 'Ik drink bijna nooit alcohol.', 'gezondheid'),
   ('dormir bien', 'goed slapen', 'dor-MIER bjen', 'Es importante dormir bien.', 'Het is belangrijk om goed te slapen.', 'gezondheid'),
   ('el hábito', 'de gewoonte', 'el A-bi-to', 'Es un hábito sano.', 'Het is een gezonde gewoonte.', 'gezondheid'),
   ('todos los días', 'elke dag', 'TO-dos los DIE-as', 'Camino todos los días.', 'Ik wandel elke dag.', 'gezondheid')]),
L(110, '⛰️', 'Sport & outdoor', 'Buitensport en wedstrijden.',
  'Jugar vs. hacer vs. practicar', 'Jugar al fútbol / al tenis (balsporten). Hacer senderismo / yoga. Practicar deporte (sport beoefenen). Montar en bici (fietsen).',
  [('el senderismo', 'het wandelen (in de natuur)', 'el sen-de-RIS-mo', 'Hacemos senderismo en los Pirineos.', 'We wandelen in de Pyreneeën.', 'sport'),
   ('entrenar', 'trainen', 'en-tre-NAR', 'Entreno por las tardes.', "Ik train 's middags.", 'sport'),
   ('la competición', 'de competitie / wedstrijd', 'la kom-pe-ti-SJON', 'La competición es en mayo.', 'De wedstrijd is in mei.', 'sport'),
   ('animar', 'aanmoedigen / supporteren', 'a-ni-MAR', 'Animamos al equipo.', 'We moedigen het team aan.', 'sport'),
   ('montar en bici', 'fietsen', 'mon-TAR en BIE-si', 'Monto en bici los domingos.', 'Ik fiets op zondag.', 'sport'),
   ('escalar', 'klimmen', 'es-ka-LAR', 'Me gusta escalar.', 'Ik hou van klimmen.', 'sport'),
   ('el podio', 'het podium', 'el PO-djo', 'Subió al podio.', 'Ze stond op het podium.', 'sport'),
   ('la medalla', 'de medaille', 'la me-DA-ja', 'Ganó la medalla de oro.', 'Hij won de gouden medaille.', 'sport')]),
L(111, '👗', 'Winkelen & mode', 'Kleding passen en kopen.',
  'Passen en maten in Spanje', '¿Puedo probármelo? (Mag ik het passen?) Me queda bien / mal (het staat me goed / slecht). Me queda pequeño / grande. ¿Lo tiene en otra talla?',
  [('el escaparate', 'de etalage', 'el es-ka-pa-RA-te', 'Lo vi en el escaparate.', 'Ik zag het in de etalage.', 'winkelen'),
   ('quedar bien', 'goed staan / passen', 'ke-DAR bjen', 'Este vestido te queda muy bien.', 'Deze jurk staat je heel goed.', 'winkelen'),
   ('estrecho', 'te krap / te nauw', 'es-TRE-tsjo', 'Los zapatos me quedan estrechos.', 'De schoenen zitten te krap.', 'winkelen'),
   ('ancho', 'wijd', 'AN-tsjo', 'La camisa es demasiado ancha.', 'Het overhemd is te wijd.', 'winkelen'),
   ('la marca', 'het merk', 'la MAR-ka', 'No me importa la marca.', 'Het merk maakt me niet uit.', 'winkelen'),
   ('devolver', 'terugbrengen / ruilen', 'de-vol-VER', '¿Puedo devolverlo?', 'Kan ik het terugbrengen?', 'winkelen'),
   ('el ticket', 'de kassabon', 'el TIE-ket', 'Guarda el ticket.', 'Bewaar de kassabon.', 'winkelen'),
   ('la moda', 'de mode', 'la MO-da', 'Me interesa la moda.', 'Mode interesseert me.', 'winkelen')]),
L(112, '💻', 'Technologie & internet', 'Online communiceren.',
  'Technologische woordenschat', 'Subir una foto (uploaden), bajar / descargar (downloaden), la nube (de cloud), el enlace (de link). Muchos términos ingleses se usan también: el wifi, el email.',
  [('subir', 'uploaden', 'soe-BIER', 'Subo las fotos a la nube.', "Ik upload de foto's naar de cloud.", 'technologie'),
   ('la copia de seguridad', 'de back-up', 'la KO-pja de se-goe-ri-DAD', 'Hago una copia de seguridad.', 'Ik maak een back-up.', 'technologie'),
   ('el enlace', 'de link', 'el en-LA-se', 'Te mando el enlace.', 'Ik stuur je de link.', 'technologie'),
   ('el mensaje', 'het bericht', 'el men-SA-che', 'No he leído tu mensaje.', 'Ik heb je bericht niet gelezen.', 'technologie'),
   ('la notificación', 'de melding', 'la no-ti-fi-ka-SJON', 'Recibo demasiadas notificaciones.', 'Ik krijg te veel meldingen.', 'technologie'),
   ('el correo electrónico', 'de e-mail', 'el ko-RRE-o e-lek-TRO-ni-ko', 'Te escribo un correo electrónico.', 'Ik stuur je een e-mail.', 'technologie'),
   ('la pantalla', 'het scherm', 'la pan-TA-ja', 'La pantalla está rota.', 'Het scherm is kapot.', 'technologie'),
   ('el archivo', 'het bestand', 'el ar-TSJIE-vo', 'Adjunto el archivo.', 'Ik voeg het bestand bij.', 'technologie')]),
L(113, '🌦️', 'Het weer & de natuur', 'Weer en landschap in detail.',
  'Weersomstandigheden: gevorderde uitdrukkingen', 'Hace un calor sofocante (het is benauwd heet). Está nublado. Hay tormenta. Ha caído una helada. El tiempo está loco (het weer is gek).',
  [('la ola de calor', 'de hittegolf', 'la O-la de ka-LOR', 'Llega una ola de calor.', 'Er komt een hittegolf aan.', 'weer'),
   ('el granizo', 'de hagel', 'el gra-NIE-so', 'El granizo dañó los coches.', 'De hagel beschadigde de auto\'s.', 'weer'),
   ('sofocante', 'benauwd / drukkend', 'so-fo-KAN-te', 'Hace un calor sofocante.', 'Het is benauwd heet.', 'weer'),
   ('la sequía', 'de droogte', 'la se-KIE-a', 'La sequía afecta a los agricultores.', 'De droogte treft de boeren.', 'weer'),
   ('la tierra', 'de aarde, de grond', 'la TJE-rra', 'La tierra está seca.', 'De grond is droog.', 'weer'),
   ('el amanecer', 'de zonsopgang', 'el a-ma-ne-SER', 'Salimos al amanecer.', 'We vertrekken bij zonsopgang.', 'weer'),
   ('el valle', 'de vallei', 'el VA-je', 'El valle es muy verde.', 'De vallei is heel groen.', 'weer'),
   ('la humedad', 'de vochtigheid', 'la oe-me-DAD', 'La humedad es alta en la costa.', 'De vochtigheid is hoog aan de kust.', 'weer')]),
L(114, '💼', 'Werk & loopbaan', 'Over je loopbaan praten.',
  'Werkervaring beschrijven: he trabajado como', 'He trabajado como camarero (ik heb als ober gewerkt). Trabajé tres años en Madrid (afgerond: indefinido). Tengo experiencia en ventas.',
  [('la entrevista de trabajo', 'het sollicitatiegesprek', 'la en-tre-VIS-ta de tra-BA-cho', 'La entrevista de trabajo fue bien.', 'Het sollicitatiegesprek ging goed.', 'werk'),
   ('el currículum', 'het cv', 'el koe-RRIE-koe-loem', 'Envío mi currículum hoy.', 'Ik stuur mijn cv vandaag.', 'werk'),
   ('contratar', 'aannemen / in dienst nemen', 'kon-tra-TAR', 'La empresa contrata a diez personas.', 'Het bedrijf neemt tien mensen aan.', 'werk'),
   ('dimitir', 'ontslag nemen', 'di-mi-TIER', 'Ha dimitido esta semana.', 'Hij heeft deze week ontslag genomen.', 'werk'),
   ('el ascenso', 'de promotie / bevordering', 'el as-SEN-so', 'Me han dado un ascenso.', 'Ik heb promotie gekregen.', 'werk'),
   ('la experiencia', 'de ervaring', 'la eks-pe-RJEN-sja', 'Tengo experiencia en ventas.', 'Ik heb ervaring in de verkoop.', 'werk'),
   ('teletrabajar', 'thuiswerken', 'te-le-tra-ba-CHAR', 'Teletrabajo dos días por semana.', 'Ik werk twee dagen per week thuis.', 'werk'),
   ('el jefe', 'de baas', 'el CHE-fe', 'Mi jefa es muy exigente.', 'Mijn baas is heel veeleisend.', 'werk')]),
L(115, '🎨', 'Kunst & musea', 'Musea bezoeken.',
  'Musea en kunstwerken bespreken', '¿A qué hora abre el museo? La entrada es gratis los domingos. Fue pintado en el siglo XVII. Me impresionó (het maakte indruk op me).',
  [('el retrato', 'het portret', 'el re-TRA-to', 'Es un retrato de la reina.', 'Het is een portret van de koningin.', 'cultuur'),
   ('la exposición', 'de tentoonstelling', 'la eks-po-si-SJON', 'Hay una exposición de Dalí.', 'Er is een tentoonstelling van Dalí.', 'cultuur'),
   ('la obra', 'het werk (kunst)', 'la O-bra', 'Es su obra más famosa.', 'Het is zijn beroemdste werk.', 'cultuur'),
   ('el siglo', 'de eeuw', 'el SIE-glo', 'Fue pintado en el siglo XVII.', 'Het is in de zeventiende eeuw geschilderd.', 'cultuur'),
   ('la sala', 'de zaal', 'la SA-la', 'La sala principal está cerrada.', 'De hoofdzaal is gesloten.', 'cultuur'),
   ('la entrada gratuita', 'gratis toegang', 'la en-TRA-da gra-TWI-ta', 'Los domingos la entrada es gratuita.', 'Op zondag is de toegang gratis.', 'cultuur'),
   ('impresionar', 'indruk maken', 'im-pre-sjo-NAR', 'El Guernica me impresionó.', 'Guernica maakte indruk op me.', 'cultuur'),
   ('la visita guiada', 'de rondleiding', 'la vi-SIE-ta gi-A-da', 'Hacemos una visita guiada.', 'We doen een rondleiding.', 'cultuur')]),
L(116, '🎭', 'Spaanse tradities', 'Feestdagen en tradities in Spanje.',
  'Feestdagen en tradities uitleggen', 'Se celebra en (het wordt gevierd in), es tradición (het is traditie). Nochevieja: twaalf druiven om middernacht. Semana Santa: processies. Reyes Magos: cadeaus op 6 januari.',
  [('la Nochevieja', 'oudejaarsavond', 'la no-tsje-VJE-cha', 'En Nochevieja comemos doce uvas.', 'Op oudejaarsavond eten we twaalf druiven.', 'tradities'),
   ('los Reyes Magos', 'Driekoningen', 'los RE-jes MA-gos', 'Los Reyes Magos traen los regalos.', 'De Drie Koningen brengen de cadeaus.', 'tradities'),
   ('la Semana Santa', 'de Goede Week', 'la se-MA-na SAN-ta', 'En Semana Santa hay procesiones.', 'In de Goede Week zijn er processies.', 'tradities'),
   ('la feria', 'de kermis / het volksfeest', 'la FE-rja', 'La Feria de Abril es en Sevilla.', 'De Feria de Abril is in Sevilla.', 'tradities'),
   ('las uvas', 'de druiven', 'las OE-vas', 'Doce uvas a medianoche.', 'Twaalf druiven om middernacht.', 'tradities'),
   ('la corrida', 'het stierengevecht', 'la ko-RRIE-da', 'La corrida es polémica.', 'Het stierengevecht is omstreden.', 'tradities'),
   ('el villancico', 'het kerstlied', 'el vi-jan-SIE-ko', 'Cantamos villancicos en Navidad.', 'We zingen kerstliederen met Kerst.', 'tradities'),
   ('la plaza mayor', 'het hoofdplein', 'la PLA-sa ma-JOR', 'La fiesta es en la plaza mayor.', 'Het feest is op het hoofdplein.', 'tradities')]),
L(117, '📚', 'Onderwijs & leren', 'Over leren en examens.',
  'Het Spaanse schoolsysteem', 'Primaria, la ESO (secundaria), el bachillerato, la universidad. Matricularse (zich inschrijven), hacer un examen, sacar buena nota (een goed cijfer halen).',
  [('matricularse', 'zich inschrijven', 'ma-tri-koe-LAR-se', 'Me he matriculado en un curso.', 'Ik heb me ingeschreven voor een cursus.', 'onderwijs'),
   ('el título', 'het diploma', 'el TIE-toe-lo', 'Tiene el título de enfermera.', 'Ze heeft het diploma verpleegkunde.', 'onderwijs'),
   ('hacer un examen', 'een examen afleggen', 'a-SER oen ek-SA-men', 'Hago un examen el lunes.', 'Ik leg maandag een examen af.', 'onderwijs'),
   ('la nota', 'het cijfer', 'la NO-ta', 'Saqué buena nota.', 'Ik haalde een goed cijfer.', 'onderwijs'),
   ('practicar', 'oefenen', 'prak-ti-KAR', 'Practico español cada día.', 'Ik oefen elke dag Spaans.', 'onderwijs'),
   ('la lengua materna', 'de moedertaal', 'la LEN-gwa ma-TER-na', 'Mi lengua materna es el neerlandés.', 'Mijn moedertaal is Nederlands.', 'onderwijs'),
   ('el bachillerato', 'de bovenbouw (16–18)', 'el ba-tsji-je-RA-to', 'Mi hijo hace el bachillerato.', 'Mijn zoon zit in de bovenbouw.', 'onderwijs'),
   ('la prueba', 'de test', 'la PRWE-ba', 'La prueba es oral.', 'De test is mondeling.', 'onderwijs')]),
L(118, '📰', 'Media & nieuws', 'Nieuws volgen en bespreken.',
  'Nieuws bespreken', '¿Has oído la noticia? Según el periódico (volgens de krant). Me parece increíble que... Seguir a alguien (volgen) en redes sociales.',
  [('el telediario', 'het journaal', 'el te-le-DJA-rjo', 'Veo el telediario a las nueve.', 'Ik kijk het journaal om negen uur.', 'media'),
   ('el titular', 'de krantenkop', 'el ti-toe-LAR', 'Leo solo los titulares.', 'Ik lees alleen de koppen.', 'media'),
   ('según', 'volgens', 'se-GOEN', 'Según el periódico, lloverá.', 'Volgens de krant gaat het regenen.', 'media'),
   ('la portada', 'de voorpagina', 'la por-TA-da', 'La noticia está en portada.', 'Het nieuws staat op de voorpagina.', 'media'),
   ('seguir a', 'volgen (sociale media)', 'se-GIER a', 'Sigo a varios cocineros.', 'Ik volg verschillende koks.', 'media'),
   ('comentar', 'reageren / commentaar geven', 'ko-men-TAR', 'Mucha gente comentó la noticia.', 'Veel mensen reageerden op het nieuws.', 'media'),
   ('la crónica', 'het verslag (journalistiek)', 'la KRO-ni-ka', 'Leí la crónica del partido.', 'Ik las het verslag van de wedstrijd.', 'media'),
   ('el reportaje', 'de reportage', 'el re-por-TA-che', 'Un reportaje sobre el clima.', 'Een reportage over het klimaat.', 'media')]),
L(119, '🌿', 'Duurzaamheid & milieu', 'Duurzaam leven in de praktijk.',
  'Milieu: actueel woordgebruik', 'Reciclar, reutilizar, reducir (de drie R\'s). La huella de carbono (de koolstofvoetafdruk). Ir en bici en vez de en coche.',
  [('la recogida selectiva', 'het gescheiden afval inzamelen', 'la re-ko-CHIE-da se-lek-TIE-va', 'La recogida selectiva es obligatoria.', 'Gescheiden inzamelen is verplicht.', 'milieu'),
   ('ahorrar energía', 'energie besparen', 'a-o-RRAR e-ner-CHIE-a', 'Apago las luces para ahorrar energía.', 'Ik doe de lichten uit om energie te besparen.', 'milieu'),
   ('reducir', 'verminderen', 're-doe-SIER', 'Hay que reducir el consumo.', 'Het verbruik moet omlaag.', 'milieu'),
   ('la bolsa reutilizable', 'de herbruikbare tas', 'la BOL-sa re-oe-ti-li-SA-ble', 'Llevo mi bolsa reutilizable.', 'Ik neem mijn herbruikbare tas mee.', 'milieu'),
   ('la huella de carbono', 'de koolstofvoetafdruk', 'la WE-ja de kar-BO-no', 'Quiero reducir mi huella de carbono.', 'Ik wil mijn koolstofvoetafdruk verkleinen.', 'milieu'),
   ('el compost', 'het compost', 'el kom-POST', 'Hago compost en el jardín.', 'Ik maak compost in de tuin.', 'milieu'),
   ('reutilizar', 'hergebruiken', 're-oe-ti-li-SAR', 'Reutilizo los frascos de cristal.', 'Ik hergebruik de glazen potten.', 'milieu'),
   ('la movilidad sostenible', 'de duurzame mobiliteit', 'la mo-vi-li-DAD sos-te-NIE-ble', 'La ciudad apuesta por la movilidad sostenible.', 'De stad zet in op duurzame mobiliteit.', 'milieu')]),
L(120, '🎓', '🎓 A2 afgerond!', 'Gefeliciteerd: A2 compleet!',
  'Gefeliciteerd: A2 compleet!', 'Je kent nu bijna 1000 Spaanse woorden en de belangrijkste verleden en toekomende tijden. Volgende stap: B1, met de subjuntivo en langere teksten. ¡Enhorabuena!',
  [('el nombre', 'de naam', 'el NOM-bre', '¿Cómo se escribe tu nombre?', 'Hoe schrijf je je naam?', 'taal'),
   ('la pronunciación', 'de uitspraak', 'la pro-noen-sja-SJON', 'Tu pronunciación es muy buena.', 'Je uitspraak is heel goed.', 'taal'),
   ('la gramática', 'de grammatica', 'la gra-MA-ti-ka', 'La gramática ya no me da miedo.', 'De grammatica maakt me niet meer bang.', 'taal'),
   ('el vocabulario', 'de woordenschat', 'el vo-ka-boe-LA-rjo', 'Mi vocabulario ha crecido.', 'Mijn woordenschat is gegroeid.', 'taal'),
   ('la palabra', 'het woord', 'la pa-LA-bra', 'Aprendo diez palabras al día.', 'Ik leer tien woorden per dag.', 'taal'),
   ('comprender', 'begrijpen', 'kom-pren-DER', 'Ya comprendo las noticias.', 'Ik begrijp het nieuws al.', 'taal'),
   ('expresarse', 'zich uitdrukken', 'eks-pre-SAR-se', 'Me expreso mejor cada día.', 'Ik druk me elke dag beter uit.', 'taal'),
   ('el siguiente paso', 'de volgende stap', 'el si-GJEN-te PA-so', 'El siguiente paso es el B1.', 'De volgende stap is B1.', 'taal')]),
]

# ── Validatie + schrijven ────────────────────────────────────────────────────
from collections import Counter
assert [l['id'] for l in LESSONS] == list(range(61, 121)), 'les-IDs'
vocab = json.load(open(OUT / 'vocabulary.json', encoding='utf-8'))
curriculum = json.load(open(OUT / 'curriculum.json', encoding='utf-8'))
vocab = [w for w in vocab if w['level'] != 'A2']; curriculum = [l for l in curriculum if l['level'] != 'A2']
ART = re.compile(r"^(?:(?:el|la|los|las|un|una|unos|unas)\s+)", re.I)
norm = lambda s: ART.sub('', s.lower()).strip()
existing = {norm(w['it']) for w in vocab}
seen = Counter(); n = max(int(w['id'][1:]) for w in vocab) + 1
new_vocab, new_curr = [], []
for l in LESSONS:
    assert len(l['words']) == 8, f"les {l['id']}: {len(l['words'])} woorden"
    ids = []
    for es, nl, ph, ex, exNl, cat in l['words']:
        k = norm(es); seen[k] += 1
        assert k not in existing, f"les {l['id']}: '{es}' bestaat al in A1"
        wid = f'e{n:03d}'; n += 1
        new_vocab.append({'id': wid, 'it': es, 'nl': nl, 'ph': ph, 'ex': ex, 'exNl': exNl, 'lesson': l['id'], 'level': 'A2', 'cat': cat})
        ids.append(wid)
    new_curr.append({'id': l['id'], 'title': l['title'], 'emoji': l['emoji'], 'level': 'A2', 'description': l['description'], 'grammar': l['grammar'], 'words': ids})
dups = [k for k, c in seen.items() if c > 1]
assert not dups, f'dubbel binnen A2: {dups}'
vocab += new_vocab; curriculum += new_curr
json.dump(vocab, open(OUT / 'vocabulary.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'vocabulary.json', 'a').write('\n')
json.dump(curriculum, open(OUT / 'curriculum.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2); open(OUT / 'curriculum.json', 'a').write('\n')
print(f'Spaans A2: {len(new_curr)} lessen, {len(new_vocab)} woorden → totaal {len(curriculum)} lessen, {len(vocab)} woorden')
